import {
  MULTIPLAYER_DEFAULT_QUESTION_LIMIT,
  MULTIPLAYER_MAX_PLAYERS,
  MULTIPLAYER_MAX_QUESTION_LIMIT,
  MULTIPLAYER_MIN_QUESTION_LIMIT,
} from '../../config/quizLimits';

export const MIN_QUESTION_LIMIT = MULTIPLAYER_MIN_QUESTION_LIMIT;
export const MAX_QUESTION_LIMIT = MULTIPLAYER_MAX_QUESTION_LIMIT;
export const MAX_PLAYERS = MULTIPLAYER_MAX_PLAYERS;
export const DEFAULT_QUESTION_LIMIT = MULTIPLAYER_DEFAULT_QUESTION_LIMIT;
