import { StyleSheet } from 'react-native';
import { colors, fonts } from '../../styles/theme';

const styles = StyleSheet.create({
  loadingContainer: {
    flex: 1,
    backgroundColor: colors.background,
    alignItems: 'center',
    justifyContent: 'center',
  },
  initializationErrorCard: {
    width: '86%',
    maxWidth: 420,
    padding: 24,
    borderRadius: 22,
    backgroundColor: 'rgba(17, 20, 44, 0.96)',
    borderWidth: 1,
    borderColor: colors.borderStrong,
    alignItems: 'center',
    shadowColor: colors.accentPurple,
    shadowOpacity: 0.32,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 8 },
    elevation: 8,
  },
  initializationErrorTitle: {
    color: colors.textPrimary,
    fontFamily: fonts.bold,
    fontSize: 20,
    textAlign: 'center',
  },
  initializationErrorText: {
    color: colors.textSecondary,
    fontFamily: fonts.regular,
    fontSize: 14,
    lineHeight: 20,
    textAlign: 'center',
    marginTop: 8,
    marginBottom: 20,
  },
  initializationRetryButton: {
    width: '100%',
    minHeight: 48,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.accentCyan,
  },
  initializationRetryButtonText: {
    color: '#04171D',
    fontFamily: fonts.bold,
    fontSize: 15,
  },
  initializationSignOutButton: {
    minHeight: 44,
    paddingHorizontal: 20,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 8,
  },
  initializationSignOutButtonText: {
    color: colors.textSecondary,
    fontFamily: fonts.medium,
    fontSize: 14,
  },
  tabBar: {
    backgroundColor: 'rgba(12, 10, 34, 0.97)',
    borderTopColor: 'rgba(34, 211, 238, 0.36)',
    borderTopWidth: 1,
    height: 72,
    paddingTop: 5,
    paddingBottom: 7,
    shadowColor: colors.accentPurple,
    shadowOpacity: 0.32,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: -5 },
    elevation: 16,
  },
  tabBarLabel: {
    fontFamily: fonts.medium,
    fontSize: 11,
    letterSpacing: 0.4,
  },
  tabBarItem: {
    paddingVertical: 1,
  },
  tabBarBadge: {
    minWidth: 18,
    height: 18,
    borderRadius: 9,
    backgroundColor: '#ef4444',
    color: '#ffffff',
    fontFamily: fonts.bold,
    fontSize: 10,
    lineHeight: 14,
    textAlignVertical: 'center',
  },
  tabBarDotBadge: {
    minWidth: 10,
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: '#22c55e',
    top: 4,
  },
});

export default styles;
