import { StyleSheet } from 'react-native';
import { colors, fonts, radii } from '../../styles/theme';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 32,
  },
  backgroundGlowTop: {
    position: 'absolute',
    width: 320,
    height: 320,
    borderRadius: 160,
    backgroundColor: colors.accent,
    opacity: 0.16,
    top: -160,
    right: -80,
  },
  backgroundGlowBottom: {
    position: 'absolute',
    width: 260,
    height: 260,
    borderRadius: 130,
    backgroundColor: colors.accentPink,
    opacity: 0.12,
    bottom: -140,
    left: -80,
  },
  panel: {
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderWidth: 1,
    borderRadius: radii.xl,
    paddingHorizontal: 20,
    paddingVertical: 28,
    shadowColor: '#05050A',
    shadowOpacity: 0.6,
    shadowRadius: 30,
    shadowOffset: { width: 0, height: 20 },
    elevation: 10,
    width: '100%',
    maxWidth: 420,
    alignSelf: 'center',
  },
  brand: {
    fontSize: 32,
    fontFamily: fonts.bold,
    textAlign: 'center',
    marginBottom: 32,
    color: colors.textPrimary,
    letterSpacing: 1.2,
  },
  inputGroup: {
    marginBottom: 16,
  },
  inputGroupLarge: {
    marginBottom: 24,
  },
  label: {
    color: colors.textSecondary,
    marginBottom: 6,
    fontFamily: fonts.medium,
  },
  input: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radii.md,
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: 16,
    color: colors.textPrimary,
    backgroundColor: colors.surfaceAlt,
    fontFamily: fonts.regular,
  },
  passwordHint: {
    color: colors.textMuted,
    marginTop: 6,
    fontSize: 13,
    lineHeight: 18,
  },
  rememberRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 16,
  },
  rememberBox: {
    width: 20,
    height: 20,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: colors.borderStrong,
    backgroundColor: colors.surfaceAlt,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 10,
  },
  rememberBoxChecked: {
    backgroundColor: colors.accent,
    borderColor: colors.accent,
  },
  rememberLabel: {
    color: colors.textSecondary,
    fontSize: 14,
    fontFamily: fonts.medium,
  },
  message: {
    color: '#FFB1B9',
    marginBottom: 16,
    textAlign: 'center',
    fontFamily: fonts.medium,
  },
  primaryButton: {
    backgroundColor: colors.accent,
    paddingVertical: 14,
    borderRadius: radii.md,
    alignItems: 'center',
    marginBottom: 12,
    shadowColor: colors.accent,
    shadowOpacity: 0.5,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 12 },
    elevation: 10,
  },
  primaryButtonDisabled: {
    backgroundColor: '#316A8F',
    opacity: 0.6,
  },
  primaryButtonText: {
    color: '#081019',
    fontSize: 18,
    fontFamily: fonts.bold,
    letterSpacing: 0.2,
  },
  toggleText: {
    color: '#9EDCFF',
    textAlign: 'center',
    fontSize: 15,
    marginBottom: 10,
    fontFamily: fonts.medium,
  },
  socialGroup: {
    marginTop: 24,
    flexDirection: 'row',
    justifyContent: 'center',
  },
  guestButton: {
    marginTop: 12,
    paddingVertical: 12,
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surfaceAlt,
    alignItems: 'center',
  },
  guestButtonDisabled: {
    opacity: 0.6,
  },
  guestButtonText: {
    color: colors.textSecondary,
    fontSize: 16,
    fontFamily: fonts.medium,
  },
  socialButton: {
    width: 52,
    height: 52,
    borderRadius: radii.md,
    alignItems: 'center',
    justifyContent: 'center',
    marginHorizontal: 6,
  },
  googleButton: {
    backgroundColor: '#DB4437',
  },
  discordButton: {
    backgroundColor: '#5865F2',
  },
});

export default styles;
