import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#030712',
    paddingHorizontal: 20,
    paddingTop: 60,
    paddingBottom: 40,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 32,
  },
  title: {
    color: '#F8FAFC',
    fontSize: 32,
    fontWeight: '800',
    letterSpacing: 1,
  },
  quickActions: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  leaderboardButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: 'rgba(96, 165, 250, 0.12)',
    borderWidth: 1,
    borderColor: 'rgba(96, 165, 250, 0.35)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  leaderboardDotLarge: {
    width: 14,
    height: 14,
    borderRadius: 4,
    backgroundColor: '#60A5FA',
  },
  leaderboardDotMedium: {
    position: 'absolute',
    bottom: 10,
    width: 10,
    height: 10,
    borderRadius: 3,
    backgroundColor: '#93C5FD',
  },
  leaderboardDotSmall: {
    position: 'absolute',
    bottom: 4,
    width: 6,
    height: 6,
    borderRadius: 2,
    backgroundColor: '#BFDBFE',
  },
  settingsButton: {
    width: 44,
    height: 44,
    borderRadius: 12,
    backgroundColor: 'rgba(148, 163, 184, 0.18)',
    borderWidth: 1,
    borderColor: 'rgba(148, 163, 184, 0.35)',
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: 16,
  },
  settingsOuter: {
    width: 20,
    height: 20,
    borderRadius: 10,
    borderWidth: 2,
    borderColor: '#E2E8F0',
    alignItems: 'center',
    justifyContent: 'center',
  },
  settingsNeedle: {
    width: 2,
    height: 10,
    backgroundColor: '#E2E8F0',
    borderRadius: 1,
  },
  settingsPivot: {
    position: 'absolute',
    top: 3,
    width: 2,
    height: 2,
    backgroundColor: '#E2E8F0',
    borderRadius: 1,
  },
  arenaCard: {
    backgroundColor: '#111827',
    borderRadius: 24,
    paddingVertical: 28,
    paddingHorizontal: 24,
    marginBottom: 28,
    borderWidth: 1,
    borderColor: 'rgba(59, 130, 246, 0.25)',
  },
  arenaLabel: {
    color: '#60A5FA',
    fontSize: 14,
    letterSpacing: 2,
    fontWeight: '600',
    textTransform: 'uppercase',
    marginBottom: 12,
  },
  arenaTitle: {
    color: '#F8FAFC',
    fontSize: 24,
    fontWeight: '700',
    marginBottom: 10,
  },
  arenaDescription: {
    color: '#CBD5F5',
    fontSize: 15,
    lineHeight: 22,
  },
  sectionLabel: {
    color: '#94A3B8',
    fontSize: 14,
    marginBottom: 12,
  },
  difficultyList: {\n  marginBottom: 0,\n  rowGap: 14,\n  gap: 14,\n},,
  difficultyCard: {
    backgroundColor: '#0F172A',
    borderRadius: 18,
    paddingVertical: 16,
    paddingHorizontal: 18,
    borderWidth: 1,
    borderColor: 'rgba(148, 163, 184, 0.25)',
    marginBottom: 14,
  },
  difficultyCardLast: {
    marginBottom: 0,
  },
  difficultyCardActive: {
    shadowOpacity: 0.45,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 8 },
    elevation: 6,
  },
  difficultyCardInactive: {
    shadowOpacity: 0,
    shadowRadius: 0,
    shadowOffset: { width: 0, height: 0 },
    elevation: 0,
  },
  difficultyRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  difficultyTitle: {
    color: '#F8FAFC',
    fontSize: 20,
    fontWeight: '700',
  },
  difficultyDescription: {
    color: '#94A3B8',
    fontSize: 13,
    marginTop: 4,
  },
  streakBadge: {
    width: 60,
    height: 60,
    borderRadius: 24,
    borderWidth: 2,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 10,
    paddingHorizontal: 6,
  },
  streakValue: {
    fontWeight: '800',
    fontSize: 18,
  },
  streakLabel: {
    fontSize: 14,
    fontWeight: '700',
    marginTop: 2,
  },
  flexSpacer: {
    flex: 1,
  },
  startButton: {
    backgroundColor: '#2563EB',
    paddingVertical: 18,
    borderRadius: 16,
    alignItems: 'center',
    shadowColor: '#2563EB',
    shadowOpacity: 0.45,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 8 },
    elevation: 8,
    marginBottom: 14,
  },
  startButtonText: {
    color: '#0F172A',
    fontSize: 18,
    fontWeight: '800',
    letterSpacing: 0.5,
  },
  signOutButton: {
    alignSelf: 'center',
  },
  signOutText: {
    color: '#64748B',
    fontSize: 14,
  },
});

export default styles;

