import { StyleSheet } from 'react-native';
import { colors, fonts, radii } from '../../styles/theme';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  backgroundGlowTop: {
    display: 'none',
    position: 'absolute',
    width: 320,
    height: 320,
    borderRadius: 160,
    backgroundColor: colors.accent,
    opacity: 0.18,
    top: -160,
    right: -80,
  },
  backgroundGlowBottom: {
    display: 'none',
    position: 'absolute',
    width: 280,
    height: 280,
    borderRadius: 140,
    backgroundColor: colors.accentWarm,
    opacity: 0.12,
    bottom: -120,
    left: -60,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 6,
  },
  profileQuickAccess: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
    minWidth: 0,
    marginRight: 14,
    paddingVertical: 6,
    paddingHorizontal: 8,
    borderRadius: radii.lg,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: 'transparent',
    shadowColor: '#000000',
    shadowOpacity: 0.12,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 6 },
    elevation: 3,
    position: 'relative',
    overflow: 'visible',
  },
  profileQuickAccessGradient: {
    ...StyleSheet.absoluteFillObject,
    borderRadius: radii.lg,
  },
  profileQuickAccessClaimReady: {
    borderWidth: 2,
    borderColor: '#22C55E',
    shadowColor: '#22C55E',
    shadowOpacity: 0.32,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 6 },
    elevation: 6,
  },
  profileQuickAccessClaimBadge: {
    position: 'absolute',
    top: -8,
    right: -8,
    width: 24,
    height: 24,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#22C55E',
    borderWidth: 2,
    borderColor: '#0F172A',
    shadowColor: '#22C55E',
    shadowOpacity: 0.4,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
    elevation: 8,
  },
  profileQuickAccessPressed: {
    opacity: 0.85,
  },
  profileAvatarFrame: {
    width: 42,
    height: 42,
    borderRadius: 21,
    borderWidth: 1,
    borderColor: colors.borderStrong,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 10,
    overflow: 'visible',
    position: 'relative',
  },
  profileAvatarCircle: {
    width: 34,
    height: 34,
    borderRadius: 17,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(148, 163, 184, 0.2)',
  },
  profileAvatarImage: {
    width: 34,
    height: 34,
    borderRadius: 17,
  },
  profileAvatarInitials: {
    color: colors.textPrimary,
    fontFamily: fonts.bold,
    fontSize: 12,
    letterSpacing: 0.6,
  },
  profileProgressBlock: {
    flex: 1,
    minWidth: 0,
  },
  profileLevelText: {
    color: colors.textPrimary,
    fontFamily: fonts.bold,
    fontSize: 12,
    letterSpacing: 0.3,
  },
  profileProgressTrack: {
    marginTop: 6,
    height: 6,
    borderRadius: radii.pill,
    backgroundColor: colors.border,
    overflow: 'hidden',
  },
  profileProgressFill: {
    height: '100%',
    borderRadius: radii.pill,
    backgroundColor: colors.accent,
  },
  quickActions: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  coinBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 10,
    height: 44,
    borderRadius: radii.pill,
    backgroundColor: 'rgba(255, 216, 77, 0.16)',
    borderWidth: 1,
    borderColor: 'rgba(255, 214, 117, 0.45)',
  },
  coinBadgeText: {
    color: colors.highlight,
    fontFamily: fonts.bold,
    fontSize: 13,
    marginLeft: 6,
  },
  coinEmoji: {
    fontSize: 16,
  },
  energyTopBadge: {
    position: 'relative',
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 10,
    height: 44,
    borderRadius: radii.pill,
    backgroundColor: 'transparent',
    borderWidth: 1,
    borderColor: 'rgba(165, 107, 255, 0.55)',
    marginLeft: 10,
    overflow: 'visible',
  },
  energyTopBadgeGradient: {
    ...StyleSheet.absoluteFillObject,
    borderRadius: radii.pill,
  },
  energyTopBadgePressed: {
    opacity: 0.82,
  },
  energyTopBadgeGlow: {
    position: 'absolute',
    top: -5,
    bottom: -5,
    left: -5,
    right: -5,
    borderRadius: radii.pill,
    backgroundColor: 'rgba(255, 214, 117, 0.2)',
    borderWidth: 1,
    borderColor: 'rgba(255, 214, 117, 0.45)',
  },
  energyTopBadgeText: {
    color: '#C9A8FF',
    fontFamily: fonts.bold,
    fontSize: 13,
    marginLeft: 6,
  },
  energyTopEmoji: {
    fontSize: 16,
  },
  energyTopBurst: {
    position: 'absolute',
    top: -16,
    right: -4,
    color: colors.highlight,
    fontFamily: fonts.bold,
    fontSize: 13,
    textShadowColor: 'rgba(7, 7, 11, 0.55)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 6,
  },
  homeScroll: {
    flex: 1,
  },
  scrollContent: {
    flexGrow: 1,
    justifyContent: 'flex-start',
    paddingHorizontal: 18,
    paddingTop: 14,
    paddingBottom: 12,
    rowGap: 10,
  },
  scrollContentCompact: {
    paddingTop: 6,
    rowGap: 7,
  },
  scrollContentTight: {
    paddingTop: 4,
    rowGap: 5,
  },
  section: {
    rowGap: 6,
  },
  sectionTitle: {
    color: colors.textPrimary,
    fontSize: 13,
    fontFamily: fonts.bold,
    letterSpacing: 0.3,
  },
  offlineBanner: {
    backgroundColor: colors.surfaceAlt,
    borderRadius: radii.lg,
    borderWidth: 1,
    borderColor: colors.border,
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  offlineHeader: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  offlineDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: colors.danger,
    marginRight: 8,
  },
  offlineTitle: {
    color: colors.textPrimary,
    fontFamily: fonts.bold,
    fontSize: 14,
    letterSpacing: 0.5,
    textTransform: 'uppercase',
  },
  offlineText: {
    color: colors.textSecondary,
    marginTop: 5,
    fontSize: 12,
    lineHeight: 16,
  },
  offlineButton: {
    alignSelf: 'flex-start',
    marginTop: 8,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: radii.pill,
    borderWidth: 1,
    borderColor: 'rgba(87, 199, 255, 0.45)',
    backgroundColor: 'rgba(87, 199, 255, 0.16)',
  },
  offlineButtonDisabled: {
    opacity: 0.6,
  },
  offlineButtonText: {
    color: '#CBEAFF',
    fontFamily: fonts.medium,
    fontSize: 12,
    letterSpacing: 0.4,
  },
  streakCard: {
    backgroundColor: colors.surface,
    borderRadius: radii.lg,
    borderWidth: 1,
    borderColor: colors.border,
    paddingHorizontal: 14,
    paddingVertical: 9,
    shadowColor: colors.accentWarm,
    shadowOpacity: 0.18,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 10 },
    elevation: 4,
    overflow: 'hidden',
  },
  streakCardGradient: {
    position: 'absolute',
    top: -28,
    right: -28,
    bottom: -28,
    left: -28,
  },
  streakHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  streakCopy: {
    flex: 1,
    paddingRight: 12,
  },
  streakTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
    columnGap: 8,
    rowGap: 4,
  },
  streakTitle: {
    color: colors.textPrimary,
    fontSize: 16,
    fontFamily: fonts.bold,
    flexShrink: 1,
  },
  streakSubtitle: {
    color: colors.textSecondary,
    fontSize: 12,
    fontFamily: fonts.medium,
    marginTop: 3,
  },
  streakIconWrap: {
    width: 30,
    height: 30,
    borderRadius: 15,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'transparent',
    borderWidth: 0,
    borderColor: 'transparent',
  },
  streakIconImage: {
    width: 40,
    height: 40,
    resizeMode: 'contain',
  },
  streakShieldButton: {
    flexDirection: 'row',
    alignItems: 'center',
    columnGap: 5,
    paddingHorizontal: 7,
    paddingVertical: 3,
    borderRadius: 10,
    backgroundColor: colors.surfaceAlt,
    borderWidth: 1,
    borderColor: colors.border,
  },
  streakShieldButtonActive: {
    backgroundColor: colors.accentWarm,
    borderColor: 'rgba(255, 178, 92, 0.65)',
  },
  streakShieldButtonDisabled: {
    opacity: 0.5,
  },
  streakShieldButtonText: {
    color: colors.textMuted,
    fontSize: 11,
    fontFamily: fonts.bold,
  },
  streakShieldButtonTextActive: {
    color: '#0A0A12',
  },
  streakProgressTrack: {
    height: 6,
    borderRadius: 3,
    backgroundColor: colors.surfaceHigh,
    marginTop: 6,
    overflow: 'hidden',
  },
  streakProgressFill: {
    height: '100%',
    borderRadius: 3,
    backgroundColor: colors.accentWarm,
  },
  streakProgressText: {
    color: colors.textMuted,
    fontSize: 10,
    fontFamily: fonts.medium,
    marginTop: 3,
  },
  featuredCard: {
    backgroundColor: colors.surfaceAlt,
    borderRadius: radii.lg,
    borderWidth: 1,
    borderColor: colors.borderStrong,
    padding: 16,
    paddingRight: 118,
    minHeight: 136,
    overflow: 'hidden',
    shadowColor: colors.accent,
    shadowOpacity: 0.25,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 10 },
    elevation: 5,
  },
  featuredCardGradient: {
    position: 'absolute',
    top: -32,
    right: -32,
    bottom: -32,
    left: -32,
  },
  featuredCardPressed: {
    transform: [{ scale: 0.98 }],
  },
  featuredCardDisabled: {
    opacity: 0.6,
  },
  featuredCardTop: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
  },
  featuredCardCopy: {
    flex: 1,
    paddingRight: 12,
  },
  featuredCardTitle: {
    color: colors.textPrimary,
    fontSize: 18,
    fontFamily: fonts.bold,
  },
  featuredCardRewardRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 6,
  },
  featuredCardRewardText: {
    color: colors.textSecondary,
    fontSize: 14,
    fontFamily: fonts.medium,
  },
  featuredCardRewardIcon: {
    fontSize: 15,
    marginLeft: 6,
  },
  featuredCardBottom: {
    marginTop: 14,
  },
  featuredCardButton: {
    alignSelf: 'flex-start',
    paddingHorizontal: 18,
    paddingVertical: 10,
    borderRadius: radii.pill,
    backgroundColor: colors.highlight,
    flexDirection: 'row',
    alignItems: 'center',
    columnGap: 8,
    borderWidth: 1,
    borderColor: 'rgba(255, 245, 179, 0.72)',
    shadowColor: colors.accentWarm,
    shadowOpacity: 0.36,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 6 },
    elevation: 5,
  },
  featuredCardButtonDisabled: {
    opacity: 0.5,
  },
  featuredCardButtonText: {
    color: '#211500',
    fontFamily: fonts.bold,
    fontSize: 14,
    letterSpacing: 0.3,
  },
  featuredCardArt: {
    position: 'absolute',
    right: -12,
    bottom: -12,
    width: 124,
    height: 124,
    opacity: 0.9,
  },
  featuredCardAnimation: {
    width: 124,
    height: 124,
  },
  categoriesSection: {
    flexGrow: 0,
    flexShrink: 0,
    justifyContent: 'flex-start',
  },
  categoriesSectionCompact: {
    rowGap: 5,
  },
  categoriesSectionTight: {
    rowGap: 4,
  },
  categoryRail: {
    flexGrow: 0,
    flexShrink: 0,
    height: 108,
    marginHorizontal: -18,
  },
  categoryRailContent: {
    alignItems: 'stretch',
  },
  categoryFooterAction: {
    marginTop: 4,
    paddingTop: 4,
  },
  categoryCard: {
    width: 100,
    minWidth: 94,
    minHeight: 102,
    height: 102,
    backgroundColor: colors.surface,
    borderRadius: radii.lg,
    borderWidth: 1,
    borderColor: colors.border,
    paddingVertical: 10,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: colors.accentPurple,
    shadowOpacity: 0.24,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 8 },
    elevation: 4,
    overflow: 'hidden',
  },
  categoryCardGradient: {
    position: 'absolute',
    top: -22,
    right: -22,
    bottom: -22,
    left: -22,
  },
  categoryCardPressed: {
    transform: [{ scale: 0.98 }],
  },
  categoryCardDisabled: {
    opacity: 0.5,
  },
  categoryIconWrap: {
    width: 38,
    height: 38,
    borderRadius: 19,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: colors.borderStrong,
    marginBottom: 8,
    backgroundColor: colors.surfaceHigh,
  },
  categoryEmoji: {
    width: 38,
    color: colors.textPrimary,
    fontSize: 20,
    lineHeight: 24,
    textAlign: 'center',
    letterSpacing: 0,
  },
  categoryLabel: {
    color: colors.textPrimary,
    fontFamily: fonts.medium,
    fontSize: 12,
    textAlign: 'center',
    paddingHorizontal: 6,
  },
  lobbyJoinCard: {
    maxWidth: 390,
  },
  lobbyJoinCardPressable: {
    paddingVertical: 23,
    paddingHorizontal: 20,
  },
  lobbyJoinCardTitle: {
    fontSize: 22,
  },
  lobbyRejoinCard: {
    shadowOpacity: 0.5,
  },
  lobbyRejoinCardPressable: {
    borderRadius: radii.xl,
    backgroundColor: 'transparent',
  },
  lobbyRejoinCardTitle: {
    color: '#0A0A12',
  },
  modeCard: {
    width: '100%',
    maxWidth: 360,
    borderRadius: radii.xl,
    borderWidth: 2,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    shadowOpacity: 0.4,
    shadowRadius: 20,
    shadowOffset: { width: 0, height: 12 },
    elevation: 8,
    overflow: 'hidden',
  },
  modeCardPressable: {
    paddingVertical: 14,
    paddingHorizontal: 18,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: radii.xl,
    overflow: 'hidden',
    position: 'relative',
  },
  modeCardGradient: {
    position: 'absolute',
    top: -48,
    right: -48,
    bottom: -48,
    left: -48,
  },
  modeCardDisabled: {
    opacity: 0.5,
  },
  modeCardTitle: {
    fontSize: 17,
    fontFamily: fonts.bold,
    letterSpacing: 0.5,
  },
  modeCardTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    columnGap: 10,
  },
  modeCardIconWrap: {
    width: 38,
    height: 38,
    borderRadius: 19,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.16)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.22)',
  },
  modeCardTitleMeta: {
    marginLeft: 10,
  },
  modeCardSubtitle: {
    color: colors.textSecondary,
    marginTop: 6,
    fontSize: 12,
    letterSpacing: 0.3,
    fontFamily: fonts.regular,
  },
  energyMessage: {
    color: '#FFB1B9',
    textAlign: 'center',
    marginTop: 6,
    fontFamily: fonts.medium,
  },
  boostButtonDisabled: {
    opacity: 0.6,
  },
  boostButtonCoin: {
    minHeight: 74,
    paddingHorizontal: 20,
    paddingVertical: 16,
    borderRadius: 22,
    borderWidth: 0,
    borderColor: '#F5C84C',
    backgroundColor: '#F5C84C',
    alignItems: 'stretch',
    justifyContent: 'center',
    width: '100%',
    shadowColor: 'rgba(245, 200, 76, 0.5)',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.24,
    shadowRadius: 24,
    elevation: 6,
  },
  boostActionContent: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  boostActionEmoji: {
    width: 42,
    textAlign: 'center',
    fontSize: 26,
    lineHeight: 30,
    marginRight: 14,
  },
  boostActionEmojiCoin: {
    color: '#5A3A00',
  },
  boostActionEmojiEnergy: {
    color: '#EAF8FF',
  },
  boostActionCopy: {
    flex: 1,
    minWidth: 0,
  },
  boostButtonCoinTitle: {
    color: '#2C1B00',
    fontFamily: fonts.bold,
    fontSize: 19,
    letterSpacing: 0.2,
    lineHeight: 23,
  },
  boostButtonCoinSubtitle: {
    color: 'rgba(44, 27, 0, 0.82)',
    fontFamily: fonts.medium,
    fontSize: 13,
    letterSpacing: 0.3,
    lineHeight: 17,
    marginTop: 4,
  },
  boostOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(3, 7, 18, 0.78)',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 18,
    paddingVertical: 24,
    zIndex: 80,
  },
  boostGlowTop: {
    position: 'absolute',
    top: 74,
    right: -96,
    width: 250,
    height: 250,
    borderRadius: 125,
    backgroundColor: 'rgba(56, 189, 248, 0.18)',
  },
  boostGlowBottom: {
    position: 'absolute',
    bottom: 82,
    left: -88,
    width: 230,
    height: 230,
    borderRadius: 115,
    backgroundColor: 'rgba(245, 200, 76, 0.16)',
  },
  boostCard: {
    width: '100%',
    maxWidth: 430,
    maxHeight: '92%',
    alignSelf: 'center',
    borderRadius: 34,
    borderWidth: 1,
    borderColor: 'rgba(148, 163, 184, 0.18)',
    backgroundColor: 'rgba(8, 13, 24, 0.98)',
    paddingTop: 18,
    paddingHorizontal: 18,
    paddingBottom: 18,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 24 },
    shadowOpacity: 0.36,
    shadowRadius: 34,
    elevation: 18,
  },
  boostHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 4,
  },
  boostBackButton: {
    width: 48,
    height: 48,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.12)',
    backgroundColor: 'rgba(15, 23, 42, 0.88)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  boostHeaderCoinBadge: {
    height: 46,
    paddingHorizontal: 14,
    backgroundColor: 'rgba(255, 214, 117, 0.14)',
    borderColor: 'rgba(255, 214, 117, 0.34)',
  },
  boostHero: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingTop: 8,
  },
  boostContentStack: {
    width: '100%',
    maxWidth: 430,
    alignSelf: 'center',
  },
  boostHeroPanel: {
    width: '100%',
    paddingHorizontal: 18,
    paddingTop: 16,
    paddingBottom: 16,
    borderRadius: 26,
    borderWidth: 1,
    borderColor: 'rgba(125, 211, 252, 0.18)',
    backgroundColor: 'rgba(15, 23, 42, 0.82)',
    alignItems: 'stretch',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 16 },
    shadowOpacity: 0.18,
    shadowRadius: 24,
    elevation: 8,
  },
  boostTitleBlock: {
    width: '100%',
    alignItems: 'center',
    marginBottom: 12,
  },
  boostTitle: {
    color: colors.textPrimary,
    fontSize: 31,
    lineHeight: 37,
    fontFamily: fonts.bold,
    textAlign: 'center',
    letterSpacing: 0.3,
    maxWidth: 280,
  },
  boostValueAura: {
    alignSelf: 'center',
    padding: 8,
    borderRadius: 26,
    backgroundColor: 'rgba(125, 211, 252, 0.06)',
  },
  boostValueRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
    paddingHorizontal: 22,
    paddingVertical: 10,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.1)',
    backgroundColor: 'rgba(255, 255, 255, 0.055)',
  },
  boostValueNumber: {
    color: colors.textPrimary,
    fontSize: 58,
    lineHeight: 62,
    fontFamily: fonts.bold,
  },
  boostValueIcon: {
    marginLeft: 10,
    color: colors.accentWarm,
    fontSize: 32,
    lineHeight: 36,
    fontFamily: fonts.bold,
  },
  boostMessage: {
    color: '#FFB1B9',
    fontSize: 14,
    lineHeight: 20,
    marginTop: 12,
    textAlign: 'center',
    fontFamily: fonts.medium,
    maxWidth: 320,
    alignSelf: 'center',
  },
  boostTimerPill: {
    width: '100%',
    marginTop: 14,
    paddingHorizontal: 16,
    paddingVertical: 13,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: 'rgba(101, 196, 255, 0.48)',
    backgroundColor: 'rgba(58, 109, 152, 0.22)',
    alignItems: 'center',
    shadowColor: 'rgba(68, 163, 255, 0.45)',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.16,
    shadowRadius: 18,
    elevation: 4,
  },
  boostTimerLabel: {
    color: '#A9D8F5',
    fontSize: 11,
    letterSpacing: 1.1,
    textTransform: 'uppercase',
    fontFamily: fonts.medium,
    textAlign: 'center',
  },
  boostTimerValue: {
    marginTop: 7,
    color: '#F2FBFF',
    fontSize: 25,
    lineHeight: 29,
    letterSpacing: 1.5,
    fontFamily: fonts.bold,
  },
  boostActions: {
    rowGap: 12,
    paddingTop: 14,
  },
  boostButtonGhost: {
    minHeight: 72,
    paddingHorizontal: 20,
    paddingVertical: 16,
    borderRadius: 22,
    borderWidth: 0,
    borderColor: '#2E8AD9',
    alignItems: 'stretch',
    justifyContent: 'center',
    width: '100%',
    backgroundColor: '#2E8AD9',
  },
  boostButtonEnergyTitle: {
    color: '#F6FBFF',
    fontSize: 19,
    lineHeight: 23,
    fontFamily: fonts.bold,
    letterSpacing: 0.2,
  },
  boostButtonEnergySubtitle: {
    color: 'rgba(236, 248, 255, 0.86)',
    fontSize: 13,
    lineHeight: 17,
    fontFamily: fonts.medium,
    letterSpacing: 0.25,
    marginTop: 4,
  },
});

export function getModeCardContainerStyle(accent, glow, glowColors) {
  return StyleSheet.compose(styles.modeCard, {
    shadowColor: accent,
    shadowOffset: { width: 0, height: 24 },
    borderColor: glow.interpolate({
      inputRange: [0, 1],
      outputRange: [glowColors.inactive, glowColors.active],
    }),
    shadowOpacity: glow.interpolate({
      inputRange: [0, 1],
      outputRange: [0.45, 0.85],
    }),
    shadowRadius: glow.interpolate({
      inputRange: [0, 1],
      outputRange: [34, 64],
    }),
    transform: [
      {
        scale: glow.interpolate({
          inputRange: [0, 1],
          outputRange: [1, 1.04],
        }),
      },
    ],
  });
}

export function getModeCardTitleStyle(accent) {
  return StyleSheet.compose(styles.modeCardTitle, { color: accent });
}

export default styles;
