import { StyleSheet } from 'react-native';
import { colors, fonts, radii } from '../../styles/theme';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  backgroundGlowTop: {
    display: 'none',
    position: 'absolute',
    width: 320,
    height: 320,
    borderRadius: 160,
    backgroundColor: colors.accent,
    opacity: 0.18,
    top: -160,
    right: -80,
  },
  backgroundGlowBottom: {
    display: 'none',
    position: 'absolute',
    width: 280,
    height: 280,
    borderRadius: 140,
    backgroundColor: colors.accentWarm,
    opacity: 0.12,
    bottom: -120,
    left: -60,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
  },
  profileQuickAccess: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
    minWidth: 0,
    marginRight: 14,
    paddingVertical: 6,
    paddingHorizontal: 8,
    borderRadius: radii.lg,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    shadowColor: '#000000',
    shadowOpacity: 0.12,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 6 },
    elevation: 3,
    position: 'relative',
    overflow: 'visible',
  },
  profileQuickAccessClaimReady: {
    borderWidth: 2,
    borderColor: '#22C55E',
    shadowColor: '#22C55E',
    shadowOpacity: 0.32,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 6 },
    elevation: 6,
  },
  profileQuickAccessClaimBadge: {
    position: 'absolute',
    top: -8,
    right: -8,
    width: 24,
    height: 24,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#22C55E',
    borderWidth: 2,
    borderColor: '#0F172A',
    shadowColor: '#22C55E',
    shadowOpacity: 0.4,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
    elevation: 8,
  },
  profileQuickAccessPressed: {
    opacity: 0.85,
  },
  profileAvatarFrame: {
    width: 42,
    height: 42,
    borderRadius: 21,
    borderWidth: 1,
    borderColor: colors.borderStrong,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 10,
    overflow: 'visible',
    position: 'relative',
  },
  profileAvatarCircle: {
    width: 34,
    height: 34,
    borderRadius: 17,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(148, 163, 184, 0.2)',
  },
  profileAvatarImage: {
    width: 34,
    height: 34,
    borderRadius: 17,
  },
  profileAvatarFrameImage: {
    position: 'absolute',
    top: -7,
    left: -7,
    width: 56,
    height: 56,
  },
  profileAvatarInitials: {
    color: colors.textPrimary,
    fontFamily: fonts.bold,
    fontSize: 12,
    letterSpacing: 0.6,
  },
  profileProgressBlock: {
    flex: 1,
    minWidth: 0,
  },
  profileLevelText: {
    color: colors.textPrimary,
    fontFamily: fonts.bold,
    fontSize: 12,
    letterSpacing: 0.3,
  },
  profileProgressTrack: {
    marginTop: 6,
    height: 6,
    borderRadius: radii.pill,
    backgroundColor: colors.border,
    overflow: 'hidden',
  },
  profileProgressFill: {
    height: '100%',
    borderRadius: radii.pill,
    backgroundColor: colors.accent,
  },
  quickActions: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  coinBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 10,
    height: 44,
    borderRadius: radii.pill,
    backgroundColor: 'rgba(255, 214, 117, 0.16)',
    borderWidth: 1,
    borderColor: 'rgba(255, 214, 117, 0.45)',
  },
  coinBadgeText: {
    color: colors.highlight,
    fontFamily: fonts.bold,
    fontSize: 13,
    marginLeft: 6,
  },
  coinEmoji: {
    fontSize: 16,
  },
  energyTopBadge: {
    position: 'relative',
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 10,
    height: 44,
    borderRadius: radii.pill,
    backgroundColor: 'rgba(165, 107, 255, 0.18)',
    borderWidth: 1,
    borderColor: 'rgba(165, 107, 255, 0.55)',
    marginLeft: 10,
    overflow: 'visible',
  },
  energyTopBadgePressed: {
    opacity: 0.82,
  },
  energyTopBadgeGlow: {
    position: 'absolute',
    top: -5,
    bottom: -5,
    left: -5,
    right: -5,
    borderRadius: radii.pill,
    backgroundColor: 'rgba(255, 214, 117, 0.2)',
    borderWidth: 1,
    borderColor: 'rgba(255, 214, 117, 0.45)',
  },
  energyTopBadgeText: {
    color: '#C9A8FF',
    fontFamily: fonts.bold,
    fontSize: 13,
    marginLeft: 6,
  },
  energyTopEmoji: {
    fontSize: 16,
  },
  energyTopBurst: {
    position: 'absolute',
    top: -16,
    right: -4,
    color: colors.highlight,
    fontFamily: fonts.bold,
    fontSize: 13,
    textShadowColor: 'rgba(7, 7, 11, 0.55)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 6,
  },
  scrollContent: {
    paddingHorizontal: 24,
    paddingTop: 40,
    paddingBottom: 24,
    rowGap: 20,
  },
  section: {
    rowGap: 12,
  },
  sectionTitle: {
    color: colors.textPrimary,
    fontSize: 16,
    fontFamily: fonts.bold,
    letterSpacing: 0.3,
  },
  activeLobbyBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.borderStrong,
    borderRadius: radii.lg,
    paddingVertical: 12,
    paddingHorizontal: 16,
    shadowColor: colors.accent,
    shadowOpacity: 0.25,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 10 },
    elevation: 5,
  },
  activeLobbyTitle: {
    color: colors.textPrimary,
    fontSize: 18,
    fontFamily: fonts.bold,
    letterSpacing: 0.5,
  },
  activeLobbyCode: {
    color: colors.textMuted,
    fontFamily: fonts.medium,
    fontSize: 14,
    letterSpacing: 1.2,
  },
  offlineBanner: {
    backgroundColor: colors.surfaceAlt,
    borderRadius: radii.lg,
    borderWidth: 1,
    borderColor: colors.border,
    paddingHorizontal: 16,
    paddingVertical: 14,
  },
  offlineHeader: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  offlineDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: colors.danger,
    marginRight: 8,
  },
  offlineTitle: {
    color: colors.textPrimary,
    fontFamily: fonts.bold,
    fontSize: 14,
    letterSpacing: 0.5,
    textTransform: 'uppercase',
  },
  offlineText: {
    color: colors.textSecondary,
    marginTop: 8,
    fontSize: 13,
    lineHeight: 18,
  },
  offlineButton: {
    alignSelf: 'flex-start',
    marginTop: 12,
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: radii.pill,
    borderWidth: 1,
    borderColor: 'rgba(87, 199, 255, 0.45)',
    backgroundColor: 'rgba(87, 199, 255, 0.16)',
  },
  offlineButtonDisabled: {
    opacity: 0.6,
  },
  offlineButtonText: {
    color: '#CBEAFF',
    fontFamily: fonts.medium,
    fontSize: 12,
    letterSpacing: 0.4,
  },
  streakCard: {
    backgroundColor: colors.surface,
    borderRadius: radii.lg,
    borderWidth: 1,
    borderColor: colors.border,
    paddingHorizontal: 16,
    paddingVertical: 13,
    shadowColor: colors.accentWarm,
    shadowOpacity: 0.18,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 10 },
    elevation: 4,
  },
  streakHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  streakCopy: {
    flex: 1,
    paddingRight: 12,
  },
  streakTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
    columnGap: 10,
    rowGap: 6,
  },
  streakTitle: {
    color: colors.textPrimary,
    fontSize: 18,
    fontFamily: fonts.bold,
    flexShrink: 1,
  },
  streakSubtitle: {
    color: colors.textSecondary,
    fontSize: 12,
    fontFamily: fonts.medium,
    marginTop: 4,
  },
  streakIconWrap: {
    width: 32,
    height: 32,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'transparent',
    borderWidth: 0,
    borderColor: 'transparent',
  },
  streakIconImage: {
    width: 44,
    height: 44,
    resizeMode: 'contain',
  },
  streakShieldButton: {
    flexDirection: 'row',
    alignItems: 'center',
    columnGap: 6,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 10,
    backgroundColor: colors.surfaceAlt,
    borderWidth: 1,
    borderColor: colors.border,
  },
  streakShieldButtonActive: {
    backgroundColor: colors.accentWarm,
    borderColor: 'rgba(255, 178, 92, 0.65)',
  },
  streakShieldButtonDisabled: {
    opacity: 0.5,
  },
  streakShieldButtonText: {
    color: colors.textMuted,
    fontSize: 11,
    fontFamily: fonts.bold,
  },
  streakShieldButtonTextActive: {
    color: '#0A0A12',
  },
  streakProgressTrack: {
    height: 8,
    borderRadius: 4,
    backgroundColor: colors.surfaceHigh,
    marginTop: 11,
    overflow: 'hidden',
  },
  streakProgressFill: {
    height: '100%',
    borderRadius: 4,
    backgroundColor: colors.accentWarm,
  },
  streakProgressText: {
    color: colors.textMuted,
    fontSize: 11,
    fontFamily: fonts.medium,
    marginTop: 5,
  },
  featuredCard: {
    backgroundColor: colors.surfaceAlt,
    borderRadius: radii.lg,
    borderWidth: 1,
    borderColor: colors.borderStrong,
    padding: 16,
    paddingRight: 120,
    minHeight: 140,
    overflow: 'hidden',
    shadowColor: colors.accent,
    shadowOpacity: 0.25,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 10 },
    elevation: 5,
  },
  featuredCardPressed: {
    transform: [{ scale: 0.98 }],
  },
  featuredCardDisabled: {
    opacity: 0.6,
  },
  featuredCardTop: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
  },
  featuredCardCopy: {
    flex: 1,
    paddingRight: 12,
  },
  featuredCardTitle: {
    color: colors.textPrimary,
    fontSize: 18,
    fontFamily: fonts.bold,
  },
  featuredCardSubtitle: {
    color: colors.textSecondary,
    fontSize: 12,
    fontFamily: fonts.regular,
    marginTop: 4,
  },
  featuredCardSubtitleInline: {
    color: colors.textSecondary,
    fontSize: 12,
    fontFamily: fonts.regular,
  },
  featuredCardRewardRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 6,
  },
  featuredCardRewardText: {
    color: colors.textSecondary,
    fontSize: 13,
    fontFamily: fonts.medium,
  },
  featuredCardRewardIcon: {
    fontSize: 14,
    marginLeft: 6,
  },
  featuredCardBadge: {
    alignSelf: 'flex-start',
  },
  featuredCardBottom: {
    marginTop: 14,
  },
  featuredCardButton: {
    alignSelf: 'flex-start',
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: radii.pill,
    backgroundColor: colors.accent,
  },
  featuredCardButtonDisabled: {
    opacity: 0.5,
  },
  featuredCardButtonText: {
    color: colors.background,
    fontFamily: fonts.bold,
    fontSize: 12,
    letterSpacing: 0.3,
  },
  featuredCardArt: {
    position: 'absolute',
    right: -12,
    bottom: -18,
    width: 120,
    height: 120,
    opacity: 0.9,
  },
  featuredCardAnimation: {
    width: 120,
    height: 120,
  },
  categoryGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    rowGap: 12,
  },
  categoryFooterAction: {
    marginTop: 18,
  },
  categoryCard: {
    width: '48%',
    minWidth: 128,
    minHeight: 112,
    backgroundColor: colors.surface,
    borderRadius: radii.lg,
    borderWidth: 1,
    borderColor: colors.border,
    paddingVertical: 16,
    alignItems: 'center',
    shadowColor: '#05050A',
    shadowOpacity: 0.45,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 10 },
    elevation: 4,
  },
  categoryCardPressed: {
    transform: [{ scale: 0.98 }],
  },
  categoryCardDisabled: {
    opacity: 0.5,
  },
  categoryIconWrap: {
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: colors.borderStrong,
    marginBottom: 10,
    backgroundColor: colors.surfaceHigh,
  },
  categoryEmoji: {
    width: 42,
    color: colors.textPrimary,
    fontSize: 21,
    lineHeight: 26,
    textAlign: 'center',
    letterSpacing: 0,
  },
  categoryLabel: {
    color: colors.textPrimary,
    fontFamily: fonts.medium,
    fontSize: 13,
    textAlign: 'center',
    paddingHorizontal: 6,
  },
  modeSection: {
    flex: 1,
    justifyContent: 'flex-start',
    alignItems: 'center',
    rowGap: 18,
    marginTop: 36,
  },
  modeCard: {
    width: '100%',
    maxWidth: 360,
    borderRadius: radii.xl,
    borderWidth: 2,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    shadowOpacity: 0.4,
    shadowRadius: 20,
    shadowOffset: { width: 0, height: 12 },
    elevation: 8,
  },
  modeCardPressable: {
    paddingVertical: 26,
    paddingHorizontal: 24,
    alignItems: 'center',
  },
  modeCardDisabled: {
    opacity: 0.5,
  },
  modeCardTitle: {
    fontSize: 20,
    fontFamily: fonts.bold,
    letterSpacing: 0.5,
  },
  modeCardTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  modeCardTitleMeta: {
    marginLeft: 10,
  },
  modeCardSubtitle: {
    color: colors.textSecondary,
    marginTop: 6,
    fontSize: 12,
    letterSpacing: 0.3,
    fontFamily: fonts.regular,
  },
  flexSpacer: {
    flex: 1,
  },
  energyMessage: {
    color: '#FFB1B9',
    textAlign: 'center',
    marginTop: 10,
    fontFamily: fonts.medium,
  },
  boostButtonDisabled: {
    opacity: 0.6,
  },
  boostButtonCoin: {
    minHeight: 78,
    paddingHorizontal: 22,
    paddingVertical: 18,
    borderRadius: 24,
    borderWidth: 0,
    borderColor: '#F5C84C',
    backgroundColor: '#F5C84C',
    alignItems: 'stretch',
    justifyContent: 'center',
    width: '100%',
    shadowColor: 'rgba(245, 200, 76, 0.5)',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.24,
    shadowRadius: 24,
    elevation: 6,
  },
  boostActionContent: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  boostActionEmoji: {
    width: 42,
    textAlign: 'center',
    fontSize: 26,
    lineHeight: 30,
    marginRight: 14,
  },
  boostActionEmojiCoin: {
    color: '#5A3A00',
  },
  boostActionEmojiEnergy: {
    color: '#EAF8FF',
  },
  boostActionCopy: {
    flex: 1,
    minWidth: 0,
  },
  boostButtonCoinTitle: {
    color: '#2C1B00',
    fontFamily: fonts.bold,
    fontSize: 19,
    letterSpacing: 0.2,
    lineHeight: 23,
  },
  boostButtonCoinSubtitle: {
    color: 'rgba(44, 27, 0, 0.82)',
    fontFamily: fonts.medium,
    fontSize: 13,
    letterSpacing: 0.3,
    lineHeight: 17,
    marginTop: 4,
  },
  boostOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(6, 8, 14, 0.97)',
    alignItems: 'stretch',
    zIndex: 80,
  },
  boostGlowTop: {
    position: 'absolute',
    top: -120,
    right: -90,
    width: 260,
    height: 260,
    borderRadius: 130,
    backgroundColor: 'rgba(101, 196, 255, 0.18)',
  },
  boostGlowBottom: {
    position: 'absolute',
    bottom: -120,
    left: -70,
    width: 240,
    height: 240,
    borderRadius: 120,
    backgroundColor: 'rgba(255, 214, 117, 0.14)',
  },
  boostCard: {
    flex: 1,
    width: '100%',
    backgroundColor: '#080B12',
    paddingTop: 36,
    paddingHorizontal: 24,
    paddingBottom: 24,
  },
  boostHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 6,
  },
  boostBackButton: {
    width: 52,
    height: 52,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.1)',
    backgroundColor: 'rgba(18, 24, 35, 0.9)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  boostHeaderCoinBadge: {
    height: 48,
    paddingHorizontal: 14,
    backgroundColor: 'rgba(255, 214, 117, 0.14)',
    borderColor: 'rgba(255, 214, 117, 0.34)',
  },
  boostCoinsBadge: {
    minWidth: 110,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: radii.lg,
    borderWidth: 1,
    borderColor: 'rgba(255, 214, 117, 0.42)',
    backgroundColor: 'rgba(255, 214, 117, 0.12)',
    alignItems: 'flex-end',
  },
  boostCoinsLabel: {
    color: colors.textMuted,
    fontSize: 11,
    letterSpacing: 1,
    textTransform: 'uppercase',
    fontFamily: fonts.medium,
  },
  boostCoinsValue: {
    color: colors.highlight,
    fontSize: 20,
    fontFamily: fonts.bold,
  },
  boostHero: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingBottom: 10,
  },
  boostContentStack: {
    width: '100%',
    maxWidth: 430,
    alignSelf: 'center',
  },
  boostHeroPanel: {
    width: '100%',
    paddingHorizontal: 22,
    paddingTop: 18,
    paddingBottom: 18,
    borderRadius: 28,
    borderWidth: 1,
    borderColor: 'rgba(128, 176, 255, 0.16)',
    backgroundColor: 'rgba(14, 19, 29, 0.96)',
    alignItems: 'stretch',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 18 },
    shadowOpacity: 0.22,
    shadowRadius: 28,
    elevation: 10,
  },
  boostTitleBlock: {
    width: '100%',
    alignItems: 'center',
    marginBottom: 14,
  },
  boostTitle: {
    color: colors.textPrimary,
    fontSize: 34,
    lineHeight: 40,
    fontFamily: fonts.bold,
    textAlign: 'center',
    letterSpacing: 0.3,
    maxWidth: 280,
  },
  boostValueAura: {
    alignSelf: 'center',
    padding: 10,
    borderRadius: 28,
    backgroundColor: 'rgba(255, 255, 255, 0.02)',
  },
  boostValueRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
    paddingHorizontal: 22,
    paddingVertical: 12,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.08)',
    backgroundColor: 'rgba(255, 255, 255, 0.045)',
  },
  boostValueNumber: {
    color: colors.textPrimary,
    fontSize: 62,
    lineHeight: 66,
    fontFamily: fonts.bold,
  },
  boostValueIcon: {
    marginLeft: 10,
    color: colors.accentWarm,
    fontSize: 32,
    lineHeight: 36,
    fontFamily: fonts.bold,
  },
  boostMessage: {
    color: '#FFB1B9',
    fontSize: 14,
    lineHeight: 20,
    marginTop: 12,
    textAlign: 'center',
    fontFamily: fonts.medium,
    maxWidth: 320,
    alignSelf: 'center',
  },
  boostTimerPill: {
    width: '100%',
    marginTop: 16,
    paddingHorizontal: 18,
    paddingVertical: 14,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: 'rgba(101, 196, 255, 0.48)',
    backgroundColor: 'rgba(58, 109, 152, 0.22)',
    alignItems: 'center',
    shadowColor: 'rgba(68, 163, 255, 0.45)',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.16,
    shadowRadius: 18,
    elevation: 4,
  },
  boostTimerLabel: {
    color: '#A9D8F5',
    fontSize: 11,
    letterSpacing: 1.1,
    textTransform: 'uppercase',
    fontFamily: fonts.medium,
    textAlign: 'center',
  },
  boostTimerValue: {
    marginTop: 7,
    color: '#F2FBFF',
    fontSize: 27,
    lineHeight: 30,
    letterSpacing: 1.5,
    fontFamily: fonts.bold,
  },
  boostActions: {
    rowGap: 12,
    paddingTop: 16,
  },
  boostButtonGhost: {
    minHeight: 72,
    paddingHorizontal: 22,
    paddingVertical: 18,
    borderRadius: 24,
    borderWidth: 0,
    borderColor: '#2E8AD9',
    alignItems: 'stretch',
    justifyContent: 'center',
    width: '100%',
    backgroundColor: '#2E8AD9',
  },
  boostButtonEnergyTitle: {
    color: '#F6FBFF',
    fontSize: 19,
    lineHeight: 23,
    fontFamily: fonts.bold,
    letterSpacing: 0.2,
  },
  boostButtonEnergySubtitle: {
    color: 'rgba(236, 248, 255, 0.86)',
    fontSize: 13,
    lineHeight: 17,
    fontFamily: fonts.medium,
    letterSpacing: 0.25,
    marginTop: 4,
  },
});

export function getModeCardContainerStyle(accent, glow, glowColors) {
  return StyleSheet.compose(styles.modeCard, {
    shadowColor: accent,
    shadowOffset: { width: 0, height: 24 },
    borderColor: glow.interpolate({
      inputRange: [0, 1],
      outputRange: [glowColors.inactive, glowColors.active],
    }),
    shadowOpacity: glow.interpolate({
      inputRange: [0, 1],
      outputRange: [0.45, 0.85],
    }),
    shadowRadius: glow.interpolate({
      inputRange: [0, 1],
      outputRange: [34, 64],
    }),
    transform: [
      {
        scale: glow.interpolate({
          inputRange: [0, 1],
          outputRange: [1, 1.04],
        }),
      },
    ],
  });
}

export function getModeCardTitleStyle(accent) {
  return StyleSheet.compose(styles.modeCardTitle, { color: accent });
}

export default styles;
