import { StyleSheet } from 'react-native';
import { colors, fonts, radii } from '../../styles/theme';

const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: colors.background,
  },
  backgroundGlowTop: {
    display: 'none',
    position: 'absolute',
    width: 280,
    height: 280,
    borderRadius: 140,
    backgroundColor: colors.accent,
    opacity: 0.14,
    top: -140,
    right: -100,
  },
  backgroundGlowBottom: {
    display: 'none',
    position: 'absolute',
    width: 240,
    height: 240,
    borderRadius: 120,
    backgroundColor: colors.accentWarm,
    opacity: 0.1,
    bottom: -120,
    left: -80,
  },
  header: {
    paddingTop: 60,
    paddingHorizontal: 24,
    paddingBottom: 24,
    backgroundColor: colors.surface,
    borderBottomWidth: 1,
    borderColor: colors.border,
  },
  headerRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  headerTitle: {
    fontSize: 30,
    fontFamily: fonts.bold,
    color: colors.textPrimary,
  },
  headerTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
    paddingRight: 12,
  },
  headerTitleIcon: {
    marginLeft: 8,
  },
  closeButton: {
    width: 34,
    height: 34,
    marginRight: __DEV__ ? 144 : 0,
    borderRadius: 17,
    borderWidth: 1,
    borderColor: 'rgba(255, 93, 110, 0.78)',
    backgroundColor: 'rgba(255, 93, 110, 0.12)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  closeButtonText: {
    color: '#FF6B7C',
    fontFamily: fonts.bold,
    fontSize: 22,
    lineHeight: 24,
  },
  headerSubtitle: {
    color: colors.textSecondary,
    marginTop: 6,
    fontFamily: fonts.regular,
  },
  stateContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 24,
    backgroundColor: colors.background,
  },
  stateMessage: {
    marginTop: 12,
    color: colors.textMuted,
    fontFamily: fonts.regular,
  },
  errorMessage: {
    fontSize: 16,
    color: '#FFB1B9',
    textAlign: 'center',
    marginBottom: 16,
    fontFamily: fonts.medium,
  },
  retryButton: {
    backgroundColor: colors.accent,
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: radii.md,
  },
  retryButtonText: {
    color: '#081019',
    fontFamily: fonts.bold,
  },
  list: {
    flex: 1,
    backgroundColor: colors.background,
  },
  listContent: {
    paddingTop: 20,
    paddingHorizontal: 20,
    paddingBottom: 0,
  },
  emptyState: {
    padding: 24,
    alignItems: 'center',
    backgroundColor: colors.surfaceAlt,
    borderRadius: radii.lg,
  },
  emptyText: {
    fontSize: 16,
    color: colors.textSecondary,
    fontFamily: fonts.regular,
  },
  entry: {
    borderRadius: radii.lg,
    borderWidth: 1,
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 18,
    paddingHorizontal: 18,
    marginBottom: 14,
  },
  entryRank: {
    width: 46,
    fontSize: 18,
    fontFamily: fonts.bold,
  },
  entryAvatar: {
    width: 42,
    height: 42,
    borderRadius: 21,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.surfaceAlt,
    borderWidth: 1,
    borderColor: 'rgba(148, 163, 184, 0.4)',
    marginRight: 12,
    overflow: 'hidden',
  },
  entryAvatarImage: {
    width: '100%',
    height: '100%',
  },
  entryAvatarText: {
    fontSize: 14,
    fontFamily: fonts.bold,
    color: colors.textSecondary,
  },
  entryMeta: {
    flex: 1,
    marginRight: 14,
  },
  entryName: {
    fontSize: 16,
    fontFamily: fonts.medium,
    color: colors.textPrimary,
  },
  entryTitle: {
    fontSize: 12,
    color: colors.textMuted,
    marginTop: 4,
    fontFamily: fonts.regular,
  },
  entryScoreWrap: {
    alignItems: 'flex-end',
  },
  entryScore: {
    fontSize: 16,
    fontFamily: fonts.bold,
    color: colors.highlight,
  },
  entryScoreLabel: {
    fontSize: 11,
    color: colors.textMuted,
    marginTop: 4,
    fontFamily: fonts.regular,
  },
});

export default styles;
