import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#050910',
    paddingHorizontal: 20,
    paddingTop: 40,
    paddingBottom: 24,
  },
  scrollContent: {
    paddingBottom: 36,
    gap: 16,
  },
  createHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 24,
  },
  createTitle: {
    color: '#F8FAFC',
    fontSize: 28,
    fontWeight: '800',
  },
  createContent: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  createSubtitle: {
    fontSize: 18,
    color: '#CBD5F5',
    marginBottom: 18,
  },
  createDifficultyColumn: {
    width: '100%',
  },
  createDifficultyCard: {
    paddingVertical: 18,
    paddingHorizontal: 16,
    borderRadius: 18,
    borderWidth: 2,
    backgroundColor: 'rgba(15, 23, 42, 0.8)',
  },
  createDifficultySpacing: {
    marginBottom: 14,
  },
  createDifficultyLabel: {
    fontSize: 18,
    fontWeight: '800',
    marginBottom: 6,
  },
  createDifficultyPoints: {
    color: '#94A3B8',
    fontSize: 13,
  },
  createQuestionBlock: {
    width: '100%',
    marginTop: 18,
  },
  createQuestionLabel: {
    color: '#CBD5F5',
    fontWeight: '600',
    marginBottom: 10,
  },
  createSeparator: {
    width: '100%',
    borderTopWidth: 1,
    borderColor: 'rgba(148, 163, 184, 0.35)',
    marginTop: 26,
    paddingTop: 26,
    alignItems: 'center',
  },
  createPlayButton: {
    marginTop: 6,
    paddingVertical: 14,
    paddingHorizontal: 76,
    borderRadius: 18,
    borderWidth: 1,
    backgroundColor: '#22C55E',
    borderColor: '#22C55E',
    shadowOpacity: 0.45,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 12 },
    elevation: 12,
  },
  createPlayButtonText: {
    color: '#0B1120',
    fontWeight: '900',
    fontSize: 20,
    letterSpacing: 0.2,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 24,
  },
  title: {
    color: '#F472B6',
    fontSize: 26,
    fontWeight: '800',
    marginTop: 4,
  },
  subtitle: {
    color: '#F472B6',
    fontSize: 14,
    letterSpacing: 1.4,
    textTransform: 'uppercase',
    fontWeight: '700',
  },
  headerActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  headerStreak: {
    height: 3,
    borderRadius: 999,
    backgroundColor: '#F472B6',
    marginHorizontal: -20,
    marginBottom: 18,
    shadowColor: '#F472B6',
    shadowOpacity: 0.35,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 4,
  },
  homeButton: {
    paddingHorizontal: 12,
    paddingVertical: 9,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(244, 114, 182, 0.4)',
    backgroundColor: 'rgba(15, 23, 42, 0.95)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  closeButton: {
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(244, 63, 94, 0.45)',
    backgroundColor: 'rgba(31, 41, 55, 0.95)',
    alignItems: 'center',
  },
  closeButtonText: {
    color: '#FCA5A5',
    fontWeight: '700',
    fontSize: 18,
  },
  loadingBox: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(15, 23, 42, 0.75)',
    borderRadius: 14,
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderWidth: 1,
    borderColor: 'rgba(59, 130, 246, 0.35)',
    marginBottom: 16,
  },
  loadingText: {
    marginLeft: 12,
    color: '#E2E8F0',
  },
  errorBox: {
    backgroundColor: 'rgba(239, 68, 68, 0.15)',
    borderRadius: 16,
    padding: 16,
    borderWidth: 1,
    borderColor: 'rgba(239, 68, 68, 0.4)',
    marginBottom: 16,
  },
  errorTitle: {
    color: '#FCA5A5',
    fontWeight: '700',
    fontSize: 16,
    marginBottom: 6,
  },
  errorMessage: {
    color: '#F8FAFC',
    fontSize: 14,
  },
  configCard: {
    backgroundColor: '#0F172A',
    borderRadius: 20,
    padding: 20,
    borderWidth: 1,
    borderColor: 'rgba(59, 130, 246, 0.35)',
    marginBottom: 24,
  },
  configTitle: {
    color: '#F8FAFC',
    fontSize: 18,
    fontWeight: '700',
  },
  configSection: {
    marginBottom: 18,
  },
  configLabel: {
    color: '#CBD5F5',
    fontWeight: '600',
    marginBottom: 10,
  },
  difficultyChips: {
    flexDirection: 'row',
    columnGap: 10,
  },
  difficultyChip: {
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(148, 163, 184, 0.3)',
    backgroundColor: 'rgba(15, 23, 42, 0.85)',
  },
  difficultyChipActive: {
    borderColor: 'rgba(59, 130, 246, 0.65)',
    backgroundColor: 'rgba(59, 130, 246, 0.18)',
  },
  difficultyChipText: {
    color: '#E2E8F0',
    fontWeight: '700',
  },
  difficultyChipTextActive: {
    color: '#BFDBFE',
  },
  questionStepper: {
    flexDirection: 'row',
    alignItems: 'center',
    columnGap: 12,
  },
  stepperButton: {
    width: 40,
    height: 40,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(59, 130, 246, 0.25)',
    borderWidth: 1,
    borderColor: 'rgba(59, 130, 246, 0.45)',
  },
  stepperButtonDisabled: {
    backgroundColor: 'rgba(15, 23, 42, 0.7)',
    borderColor: 'rgba(148, 163, 184, 0.3)',
  },
  stepperButtonText: {
    color: '#F8FAFC',
    fontSize: 18,
    fontWeight: '700',
  },
  stepperValue: {
    color: '#F8FAFC',
    fontSize: 18,
    fontWeight: '800',
    minWidth: 36,
    textAlign: 'center',
  },
  startAction: {
    marginTop: 6,
    backgroundColor: '#22C55E',
    borderRadius: 16,
    paddingVertical: 16,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#22C55E',
    shadowOpacity: 0.35,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 8 },
    elevation: 8,
  },
  startActionText: {
    color: '#052E16',
    fontSize: 16,
    fontWeight: '800',
  },
  lobbyCard: {
    backgroundColor: '#0B1020',
    borderRadius: 20,
    padding: 20,
    marginBottom: 20,
  },
  lobbyTitle: {
    color: '#F8FAFC',
    fontSize: 20,
    fontWeight: '800',
    letterSpacing: 0.5,
    marginBottom: 10,
  },
  lobbySettingsButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: 'rgba(147, 197, 253, 0.45)',
    backgroundColor: 'rgba(59, 130, 246, 0.18)',
  },
  lobbyConfig: {
    marginTop: 16,
    paddingTop: 16,
    borderTopWidth: 1,
    borderTopColor: 'rgba(96, 165, 250, 0.25)',
    rowGap: 12,
  },
  lobbyConfigTitle: {
    color: '#F8FAFC',
    fontSize: 16,
    fontWeight: '700',
  },
  lobbyConfigAction: {
    alignSelf: 'flex-start',
    backgroundColor: '#38BDF8',
    borderRadius: 14,
    paddingVertical: 10,
    paddingHorizontal: 18,
  },
  lobbyConfigActionText: {
    color: '#021527',
    fontSize: 15,
    fontWeight: '800',
  },
  codeBadge: {
    alignSelf: 'flex-start',
    backgroundColor: 'rgba(15, 23, 42, 0.6)',
    borderRadius: 14,
    paddingVertical: 10,
    paddingHorizontal: 18,
    borderWidth: 1,
    borderColor: 'rgba(52, 211, 153, 0.25)',
    marginBottom: 20,
    minWidth: 150,
    alignItems: 'center',
  },
  codeBadgeText: {
    color: '#F8FAFC',
    fontSize: 20,
    fontWeight: '800',
    letterSpacing: 1.6,
  },
  codeBadgeSuccess: {
    backgroundColor: 'rgba(34, 197, 94, 0.25)',
    borderColor: 'rgba(34, 197, 94, 0.65)',
  },
  codeActionsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginTop: 20,
    paddingTop: 16,
    borderTopWidth: 1,
    borderTopColor: 'rgba(96, 165, 250, 0.2)',
  },
  codeHint: {
    color: '#94A3B8',
    marginTop: 4,
    fontSize: 12,
  },
  codeHintSuccess: {
    color: '#34D399',
    marginTop: 4,
    fontSize: 12,
  },
 shareButton: {
   flexDirection: 'row',
   alignItems: 'center',
   paddingVertical: 10,
   paddingHorizontal: 14,
   borderRadius: 12,
   borderWidth: 1,
    borderColor: 'rgba(236, 72, 153, 0.4)',
    backgroundColor: 'rgba(236, 72, 153, 0.12)',
 },
  shareButtonText: {
    display: 'none',
  },
  shareIconAnim: {
    width: 32,
    height: 32,
  },
  participantsHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  participantGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    columnGap: 12,
    rowGap: 12,
  },
  participantSlot: {
    alignItems: 'center',
    gap: 6,
    width: '30%',
  },
  participantsTitle: {
    color: '#BFDBFE',
    fontSize: 14,
    fontWeight: '700',
    letterSpacing: 0.6,
    textTransform: 'uppercase',
  },
  participantsCount: {
    color: '#E2E8F0',
    fontWeight: '600',
  },
  participantList: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
    marginBottom: 16,
    justifyContent: 'flex-start',
  },
  participantAvatarCard: {
    alignItems: 'center',
    gap: 6,
  },
  participantAvatarCardSelected: {
    opacity: 0.95,
  },
  participantAvatar: {
    width: 64,
    height: 64,
    borderRadius: 999,
    backgroundColor: 'rgba(96, 165, 250, 0.16)',
    borderWidth: 1,
    borderColor: 'rgba(96, 165, 250, 0.45)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  participantAvatarKick: {
    borderColor: 'rgba(248, 113, 113, 0.8)',
    backgroundColor: 'rgba(248, 113, 113, 0.18)',
  },
  hostBadge: {
    position: 'absolute',
    top: -8,
    right: -8,
    width: 28,
    height: 28,
  },
  participantAvatarGhost: {
    backgroundColor: 'rgba(148, 163, 184, 0.14)',
    borderColor: 'rgba(148, 163, 184, 0.35)',
  },
  participantAvatarText: {
    color: '#F8FAFC',
    fontSize: 18,
    fontWeight: '800',
  },
  participantAvatarImage: {
    width: '100%',
    height: '100%',
    borderRadius: 999,
  },
  participantName: {
    color: '#F8FAFC',
    fontSize: 14,
    fontWeight: '600',
    textAlign: 'center',
  },
  participantPlaceholder: {
    color: '#94A3B8',
  },
  kickButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    columnGap: 6,
    paddingVertical: 6,
    paddingHorizontal: 10,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: 'rgba(248, 113, 113, 0.75)',
    backgroundColor: 'rgba(248, 113, 113, 0.12)',
  },
  kickButtonText: {
    color: '#FCA5A5',
    fontSize: 11,
    fontWeight: '700',
  },
  kickButtonDisabled: {
    opacity: 0.6,
  },
  startRow: {
    marginTop: 6,
    marginBottom: 8,
    flexDirection: 'row',
    alignItems: 'center',
    columnGap: 10,
  },
  startButton: {
    alignSelf: 'flex-start',
    minWidth: 180,
  },
  startHint: {
    color: '#94A3B8',
    fontSize: 13,
  },
  refreshWaitingButton: {
    paddingVertical: 10,
    paddingHorizontal: 16,
    alignSelf: 'flex-start',
    borderRadius: 12,
    backgroundColor: 'rgba(59, 130, 246, 0.2)',
  },
  refreshWaitingText: {
    color: '#BFDBFE',
    fontWeight: '700',
  },
  createInfoBox: {
    backgroundColor: 'rgba(96, 165, 250, 0.12)',
    borderRadius: 18,
    paddingVertical: 18,
    paddingHorizontal: 20,
    borderWidth: 1,
    borderColor: 'rgba(96, 165, 250, 0.35)',
    marginTop: 20,
  },
  createInfoTitle: {
    color: '#BFDBFE',
    fontSize: 16,
    fontWeight: '700',
    marginBottom: 6,
  },
  createInfoText: {
    color: '#94A3B8',
    fontSize: 13,
    lineHeight: 20,
  },
  actionsRow: {
    flexDirection: 'row',
    justifyContent: 'center',
    marginBottom: 20,
  },
  primaryAction: {
    alignSelf: 'center',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#22C55E',
    borderRadius: 16,
    paddingVertical: 18,
    paddingHorizontal: 18,
    minWidth: 170,
    maxWidth: 200,
    shadowColor: '#22C55E',
    shadowOpacity: 0.35,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 8 },
    elevation: 8,
  },
  primaryActionText: {
    color: '#02190F',
    fontSize: 18,
    fontWeight: '900',
  },
  actionDisabled: {
    opacity: 0.65,
  },
  joinSection: {
    marginBottom: 20,
  },
  joinLabel: {
    color: '#94A3B8',
    marginBottom: 8,
    fontWeight: '600',
  },
  joinRow: {
    flexDirection: 'row',
    columnGap: 12,
  },
  joinInput: {
    flex: 1,
    backgroundColor: '#0F172A',
    borderRadius: 14,
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderWidth: 1,
    borderColor: 'rgba(148, 163, 184, 0.35)',
    color: '#F8FAFC',
    fontSize: 16,
    fontWeight: '700',
    letterSpacing: 1.4,
  },
  joinButton: {
    width: 80,
    backgroundColor: '#38BDF8',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 14,
  },
  joinButtonText: {
    color: '#021527',
    fontSize: 16,
    fontWeight: '800',
  },
  listHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  listTitle: {
    color: '#F8FAFC',
    fontSize: 18,
    fontWeight: '700',
  },
  listRefresh: {
    color: '#60A5FA',
    fontWeight: '600',
  },
  loadingList: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 28,
    backgroundColor: 'rgba(15, 23, 42, 0.75)',
    borderRadius: 18,
    borderWidth: 1,
    borderColor: 'rgba(59, 130, 246, 0.25)',
  },
  loadingListText: {
    marginTop: 10,
    color: '#E2E8F0',
  },
  listContent: {
    rowGap: 14,
    paddingBottom: 12,
  },
  listEmpty: {
    flexGrow: 1,
    justifyContent: 'center',
    paddingVertical: 40,
  },
  matchCard: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#0F172A',
    borderRadius: 16,
    paddingVertical: 16,
    paddingHorizontal: 18,
    borderWidth: 1,
    borderColor: 'rgba(148, 163, 184, 0.25)',
  },
  matchInfo: {
    flex: 1,
    marginRight: 12,
  },
  matchCode: {
    color: '#F8FAFC',
    fontSize: 18,
    fontWeight: '800',
    letterSpacing: 1,
  },
  matchMeta: {
    color: '#94A3B8',
    marginTop: 4,
    fontSize: 13,
  },
  matchHost: {
    color: '#CBD5F5',
    marginTop: 6,
    fontSize: 13,
  },
  matchAction: {
    backgroundColor: 'rgba(56, 189, 248, 0.18)',
    borderRadius: 12,
    paddingVertical: 8,
    paddingHorizontal: 12,
  },
  matchActionText: {
    color: '#38BDF8',
    fontWeight: '700',
  },
  emptyState: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 48,
    paddingHorizontal: 16,
  },
  emptyTitle: {
    color: '#E2E8F0',
    fontSize: 18,
    fontWeight: '700',
    marginBottom: 8,
  },
  emptyIcon: {
    width: 120,
    height: 120,
    marginTop: 6,
  },
  emptySubtitle: {
    color: '#94A3B8',
    textAlign: 'center',
    lineHeight: 20,
  },
  onlineFriendsSection: {
    marginTop: 18,
    padding: 16,
    backgroundColor: 'rgba(15, 23, 42, 0.9)',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: 'rgba(96, 165, 250, 0.35)',
    rowGap: 10,
  },
  onlineFriendsTitle: {
    color: '#E0F2FE',
    fontSize: 16,
    fontWeight: '800',
  },
  onlineFriendsSubtitle: {
    color: '#94A3B8',
    fontSize: 13,
  },
  loadingInline: {
    flexDirection: 'row',
    alignItems: 'center',
    columnGap: 10,
  },
  loadingInlineText: {
    color: '#E2E8F0',
  },
  onlineFriendList: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  onlineFriendCard: {
    backgroundColor: 'rgba(37, 99, 235, 0.1)',
    borderColor: 'rgba(37, 99, 235, 0.45)',
    borderWidth: 1,
    borderRadius: 14,
    paddingHorizontal: 14,
    paddingVertical: 10,
    minWidth: 120,
  },
  onlineFriendName: {
    color: '#E2E8F0',
    fontWeight: '700',
    fontSize: 14,
  },
  onlineFriendCode: {
    color: '#93C5FD',
    fontSize: 12,
    letterSpacing: 0.5,
    marginTop: 4,
  },
  onlineFriendHint: {
    color: '#60A5FA',
    fontSize: 12,
    marginTop: 4,
  },
  onlineFriendEmpty: {
    color: '#94A3B8',
    fontSize: 13,
  },
  modalOverlay: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: 'rgba(2, 6, 23, 0.85)',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 24,
  },
  modalBackdrop: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    left: 0,
    right: 0,
  },
  modalCard: {
    width: '100%',
    maxWidth: 340,
    backgroundColor: '#0F172A',
    borderRadius: 20,
    padding: 24,
    borderWidth: 1,
    borderColor: 'rgba(148, 163, 184, 0.25)',
    rowGap: 16,
  },
  settingsModalCard: {
    maxWidth: 360,
  },
  modalTitle: {
    color: '#F8FAFC',
    fontSize: 20,
    fontWeight: '700',
  },
  settingsModalTitle: {
    color: '#F8FAFC',
    fontSize: 20,
    fontWeight: '700',
  },
  settingsModalSection: {
    rowGap: 10,
  },
  settingsModalLabel: {
    color: '#E2E8F0',
    fontSize: 14,
    fontWeight: '700',
  },
  settingsApplyButton: {
    borderRadius: 16,
    paddingVertical: 14,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    backgroundColor: 'rgba(15, 23, 42, 0.85)',
    overflow: 'hidden',
  },
  settingsApplyFill: {
    position: 'absolute',
    left: 0,
    top: 0,
    bottom: 0,
    borderRadius: 16,
    opacity: 0.35,
  },
  settingsApplyText: {
    color: '#E2E8F0',
    fontWeight: '800',
    letterSpacing: 0.3,
  },
  modalActions: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    columnGap: 12,
  },
  modalButton: {
    flex: 1,
    borderRadius: 14,
    paddingVertical: 12,
    alignItems: 'center',
    borderWidth: 1,
  },
  modalButtonContinue: {
    backgroundColor: 'rgba(34, 197, 94, 0.25)',
    borderColor: 'rgba(34, 197, 94, 0.55)',
  },
  modalButtonContinueText: {
    color: '#BBF7D0',
    fontWeight: '700',
  },
  modalButtonExit: {
    backgroundColor: 'rgba(239, 68, 68, 0.25)',
    borderColor: 'rgba(239, 68, 68, 0.6)',
    width: 60,
    alignItems: 'center',
    justifyContent: 'center',
  },
  modalButtonExitText: {
    color: '#FCA5A5',
    fontWeight: '800',
    fontSize: 16,
  },
});

export default styles;
