import { StyleSheet } from 'react-native';
import { colors, fonts, radii } from '../../styles/theme';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
    paddingHorizontal: 24,
    paddingTop: 40,
    paddingBottom: 24,
  },
  backgroundGlowTop: {
    display: 'none',
    position: 'absolute',
    width: 280,
    height: 280,
    borderRadius: 140,
    backgroundColor: colors.accentPink,
    opacity: 0.14,
    top: -120,
    right: -120,
  },
  backgroundGlowBottom: {
    display: 'none',
    position: 'absolute',
    width: 240,
    height: 240,
    borderRadius: 120,
    backgroundColor: colors.accent,
    opacity: 0.12,
    bottom: -120,
    left: -80,
  },
  scrollContent: {
    paddingBottom: 36,
    gap: 16,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 24,
  },
  title: {
    color: colors.accentPink,
    fontSize: 26,
    fontFamily: fonts.bold,
    marginTop: 4,
  },
  subtitle: {
    color: colors.accentPink,
    fontSize: 14,
    letterSpacing: 1.4,
    textTransform: 'uppercase',
    fontFamily: fonts.medium,
  },
  headerActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  headerStreak: {
    height: 3,
    borderRadius: radii.pill,
    backgroundColor: colors.accentPink,
    marginHorizontal: -20,
    marginBottom: 18,
    shadowColor: colors.accentPink,
    shadowOpacity: 0.35,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 4,
  },
  homeButton: {
    paddingHorizontal: 12,
    paddingVertical: 9,
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: 'rgba(255, 127, 168, 0.4)',
    backgroundColor: colors.surfaceAlt,
    alignItems: 'center',
    justifyContent: 'center',
  },
  closeButton: {
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: 'rgba(255, 93, 110, 0.55)',
    backgroundColor: colors.surfaceAlt,
    alignItems: 'center',
  },
  closeButtonText: {
    color: '#FFB1B9',
    fontFamily: fonts.bold,
    fontSize: 18,
  },
  loadingBox: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.surfaceAlt,
    borderRadius: radii.md,
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderWidth: 1,
    borderColor: colors.border,
    marginBottom: 16,
  },
  loadingText: {
    marginLeft: 12,
    color: colors.textSecondary,
    fontFamily: fonts.regular,
  },
  errorBox: {
    backgroundColor: 'rgba(255, 93, 110, 0.15)',
    borderRadius: radii.lg,
    padding: 16,
    borderWidth: 1,
    borderColor: 'rgba(255, 93, 110, 0.45)',
    marginBottom: 16,
  },
  errorTitle: {
    color: '#FFB1B9',
    fontFamily: fonts.bold,
    fontSize: 16,
    marginBottom: 6,
  },
  errorMessage: {
    color: colors.textPrimary,
    fontSize: 14,
    fontFamily: fonts.regular,
  },
  difficultyChips: {
    flexDirection: 'row',
    columnGap: 10,
  },
  difficultyChip: {
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surfaceAlt,
  },
  difficultyChipActive: {
    borderColor: 'rgba(87, 199, 255, 0.65)',
    backgroundColor: 'rgba(87, 199, 255, 0.18)',
  },
  difficultyChipText: {
    color: colors.textSecondary,
    fontFamily: fonts.medium,
  },
  difficultyChipTextActive: {
    color: '#CBEAFF',
  },
  questionStepper: {
    flexDirection: 'row',
    alignItems: 'center',
    columnGap: 12,
  },
  stepperButton: {
    width: 40,
    height: 40,
    borderRadius: radii.md,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(87, 199, 255, 0.2)',
    borderWidth: 1,
    borderColor: 'rgba(87, 199, 255, 0.45)',
  },
  stepperButtonDisabled: {
    backgroundColor: colors.surfaceAlt,
    borderColor: colors.border,
  },
  stepperButtonText: {
    color: colors.textPrimary,
    fontSize: 18,
    fontFamily: fonts.bold,
  },
  stepperValue: {
    color: colors.textPrimary,
    fontSize: 18,
    fontFamily: fonts.bold,
    minWidth: 36,
    textAlign: 'center',
  },
  lobbyCard: {
    backgroundColor: colors.surface,
    borderRadius: radii.lg,
    padding: 20,
    marginBottom: 20,
  },
  lobbyTitle: {
    color: colors.textPrimary,
    fontSize: 20,
    fontFamily: fonts.bold,
    letterSpacing: 0.5,
    marginBottom: 10,
  },
  lobbySettingsButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: 'rgba(87, 199, 255, 0.45)',
    backgroundColor: 'rgba(87, 199, 255, 0.18)',
  },
  lobbyConfig: {
    marginTop: 16,
    paddingTop: 16,
    borderTopWidth: 1,
    borderTopColor: colors.border,
    rowGap: 12,
  },
  lobbyConfigTitle: {
    color: colors.textPrimary,
    fontSize: 16,
    fontFamily: fonts.medium,
  },
  lobbyConfigAction: {
    alignSelf: 'flex-start',
    backgroundColor: colors.accent,
    borderRadius: radii.md,
    paddingVertical: 10,
    paddingHorizontal: 18,
  },
  lobbyConfigActionText: {
    color: '#081019',
    fontSize: 15,
    fontFamily: fonts.bold,
  },
  codeBadge: {
    alignSelf: 'flex-start',
    backgroundColor: colors.surfaceAlt,
    borderRadius: radii.md,
    paddingVertical: 10,
    paddingHorizontal: 18,
    borderWidth: 1,
    borderColor: 'rgba(57, 229, 138, 0.35)',
    marginBottom: 20,
    minWidth: 150,
    alignItems: 'center',
  },
  codeBadgeText: {
    color: colors.textPrimary,
    fontSize: 20,
    fontFamily: fonts.bold,
    letterSpacing: 1.6,
  },
  codeBadgeSuccess: {
    backgroundColor: 'rgba(57, 229, 138, 0.25)',
    borderColor: 'rgba(57, 229, 138, 0.65)',
  },
  codeActionsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginTop: 20,
    paddingTop: 16,
    borderTopWidth: 1,
    borderTopColor: colors.border,
  },
  codeHint: {
    color: colors.textMuted,
    marginTop: 4,
    fontSize: 12,
    fontFamily: fonts.regular,
  },
  codeHintSuccess: {
    color: colors.success,
    marginTop: 4,
    fontSize: 12,
    fontFamily: fonts.medium,
  },
  shareButton: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 10,
    paddingHorizontal: 14,
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: 'rgba(255, 127, 168, 0.4)',
    backgroundColor: 'rgba(255, 127, 168, 0.12)',
  },
  shareButtonText: {
    display: 'none',
  },
  shareIconAnim: {
    width: 32,
    height: 32,
  },
  participantsHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  participantGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    columnGap: 12,
    rowGap: 12,
  },
  participantSlot: {
    alignItems: 'center',
    gap: 6,
    width: '30%',
  },
  participantsTitle: {
    color: '#CBEAFF',
    fontSize: 14,
    fontFamily: fonts.medium,
    letterSpacing: 0.6,
    textTransform: 'uppercase',
  },
  participantsCount: {
    color: colors.textSecondary,
    fontFamily: fonts.medium,
  },
  participantList: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
    marginBottom: 16,
    justifyContent: 'flex-start',
  },
  participantAvatarCard: {
    alignItems: 'center',
    gap: 6,
  },
  participantAvatarCardSelected: {
    opacity: 0.95,
  },
  participantAvatar: {
    width: 64,
    height: 64,
    borderRadius: 999,
    backgroundColor: 'rgba(87, 199, 255, 0.16)',
    borderWidth: 1,
    borderColor: 'rgba(87, 199, 255, 0.45)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  participantAvatarKick: {
    borderColor: 'rgba(255, 93, 110, 0.8)',
    backgroundColor: 'rgba(255, 93, 110, 0.18)',
  },
  hostBadge: {
    position: 'absolute',
    top: -8,
    right: -8,
    width: 28,
    height: 28,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#57C7FF',
    borderWidth: 1,
    borderColor: 'rgba(11, 18, 32, 0.8)',
  },
  participantAvatarGhost: {
    backgroundColor: 'rgba(255, 255, 255, 0.08)',
    borderColor: colors.border,
  },
  participantAvatarPending: {
    backgroundColor: 'rgba(148, 163, 184, 0.18)',
    borderColor: 'rgba(148, 163, 184, 0.5)',
  },
  participantAvatarText: {
    color: colors.textPrimary,
    fontSize: 18,
    fontFamily: fonts.bold,
  },
  participantAvatarImage: {
    width: '100%',
    height: '100%',
    borderRadius: 999,
  },
  participantName: {
    color: colors.textPrimary,
    fontSize: 14,
    fontFamily: fonts.medium,
    textAlign: 'center',
  },
  participantPlaceholder: {
    color: colors.textMuted,
  },
  participantPending: {
    color: colors.textMuted,
  },
  participantPendingLabel: {
    color: colors.textMuted,
    fontSize: 11,
    fontFamily: fonts.regular,
    textAlign: 'center',
  },
  kickButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    columnGap: 6,
    paddingVertical: 6,
    paddingHorizontal: 10,
    borderRadius: radii.sm,
    borderWidth: 1,
    borderColor: 'rgba(255, 93, 110, 0.75)',
    backgroundColor: 'rgba(255, 93, 110, 0.12)',
  },
  kickButtonText: {
    color: '#FFB1B9',
    fontSize: 11,
    fontFamily: fonts.bold,
  },
  kickButtonDisabled: {
    opacity: 0.6,
  },
  startRow: {
    marginTop: 6,
    marginBottom: 8,
    flexDirection: 'row',
    alignItems: 'center',
    columnGap: 10,
  },
  startButton: {
    alignSelf: 'flex-start',
    minWidth: 180,
    borderWidth: 2,
    borderColor: 'rgba(57, 229, 138, 0.7)',
  },
  startButtonText: {
    textTransform: 'uppercase',
    letterSpacing: 2,
    textShadowColor: 'rgba(16, 185, 129, 0.35)',
    textShadowRadius: 6,
    textShadowOffset: { width: 0, height: 2 },
  },
  startHint: {
    color: colors.textMuted,
    fontSize: 13,
    fontFamily: fonts.regular,
  },
  refreshWaitingButton: {
    paddingVertical: 10,
    paddingHorizontal: 16,
    alignSelf: 'flex-start',
    borderRadius: radii.md,
    backgroundColor: 'rgba(87, 199, 255, 0.16)',
  },
  refreshWaitingText: {
    color: '#CBEAFF',
    fontFamily: fonts.bold,
  },
  createInfoBox: {
    backgroundColor: 'rgba(87, 199, 255, 0.12)',
    borderRadius: radii.lg,
    paddingVertical: 18,
    paddingHorizontal: 20,
    borderWidth: 1,
    borderColor: 'rgba(87, 199, 255, 0.35)',
    marginTop: 20,
  },
  createInfoTitle: {
    color: '#CBEAFF',
    fontSize: 16,
    fontFamily: fonts.bold,
    marginBottom: 6,
  },
  createInfoText: {
    color: colors.textMuted,
    fontSize: 13,
    lineHeight: 20,
    fontFamily: fonts.regular,
  },
  actionsRow: {
    flexDirection: 'row',
    justifyContent: 'center',
    marginTop: 20,
    marginBottom: 12,
  },
  primaryAction: {
    alignSelf: 'center',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.success,
    borderRadius: radii.md,
    paddingVertical: 18,
    paddingHorizontal: 18,
    minWidth: 170,
    maxWidth: 200,
    shadowColor: colors.success,
    shadowOpacity: 0.35,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 8 },
    elevation: 8,
  },
  primaryActionText: {
    color: '#07120F',
    fontSize: 18,
    fontFamily: fonts.bold,
  },
  actionDisabled: {
    opacity: 0.65,
  },
  joinSection: {
    marginBottom: 20,
  },
  joinLabel: {
    color: colors.textMuted,
    marginBottom: 8,
    fontFamily: fonts.medium,
  },
  joinRow: {
    flexDirection: 'row',
    columnGap: 12,
  },
  joinInput: {
    flex: 1,
    backgroundColor: colors.surface,
    borderRadius: radii.md,
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderWidth: 1,
    borderColor: colors.borderStrong,
    color: colors.textPrimary,
    fontSize: 16,
    fontFamily: fonts.medium,
    letterSpacing: 1.4,
  },
  joinButton: {
    width: 80,
    backgroundColor: colors.accent,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: radii.md,
  },
  joinButtonText: {
    color: '#081019',
    fontSize: 16,
    fontFamily: fonts.bold,
  },
  listHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  listTitle: {
    color: colors.textPrimary,
    fontSize: 18,
    fontFamily: fonts.bold,
  },
  listRefresh: {
    color: colors.accent,
    fontFamily: fonts.medium,
  },
  loadingList: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 28,
    backgroundColor: colors.surfaceAlt,
    borderRadius: radii.lg,
    borderWidth: 1,
    borderColor: colors.border,
  },
  loadingListText: {
    marginTop: 10,
    color: colors.textSecondary,
    fontFamily: fonts.regular,
  },
  listContent: {
    rowGap: 14,
    paddingBottom: 12,
  },
  listEmpty: {
    flexGrow: 1,
    justifyContent: 'center',
    paddingVertical: 40,
  },
  matchCard: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: colors.surface,
    borderRadius: radii.md,
    paddingVertical: 16,
    paddingHorizontal: 18,
    borderWidth: 1,
    borderColor: colors.border,
  },
  matchInfo: {
    flex: 1,
    marginRight: 12,
  },
  matchCode: {
    color: colors.textPrimary,
    fontSize: 18,
    fontFamily: fonts.bold,
    letterSpacing: 1,
  },
  matchMeta: {
    color: colors.textMuted,
    marginTop: 4,
    fontSize: 13,
    fontFamily: fonts.regular,
  },
  matchHost: {
    color: colors.textSecondary,
    marginTop: 6,
    fontSize: 13,
    fontFamily: fonts.regular,
  },
  matchAction: {
    backgroundColor: 'rgba(87, 199, 255, 0.18)',
    borderRadius: radii.md,
    paddingVertical: 8,
    paddingHorizontal: 12,
  },
  matchActionText: {
    color: colors.accent,
    fontFamily: fonts.bold,
  },
  emptyState: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 48,
    paddingHorizontal: 16,
  },
  emptyTitle: {
    color: colors.textSecondary,
    fontSize: 18,
    fontFamily: fonts.bold,
    marginBottom: 8,
  },
  emptyIcon: {
    width: 120,
    height: 120,
    marginTop: 6,
  },
  emptySubtitle: {
    color: colors.textMuted,
    textAlign: 'center',
    lineHeight: 20,
    fontFamily: fonts.regular,
  },
  onlineFriendsSection: {
    marginTop: 18,
    padding: 16,
    backgroundColor: colors.surfaceAlt,
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.border,
    rowGap: 10,
  },
  onlineFriendsTitle: {
    color: '#DFF3FF',
    fontSize: 16,
    fontFamily: fonts.bold,
  },
  onlineFriendsSubtitle: {
    color: colors.textMuted,
    fontSize: 13,
    fontFamily: fonts.regular,
  },
  loadingInline: {
    flexDirection: 'row',
    alignItems: 'center',
    columnGap: 10,
  },
  loadingInlineText: {
    color: colors.textSecondary,
    fontFamily: fonts.regular,
  },
  onlineFriendList: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  onlineFriendCard: {
    backgroundColor: 'rgba(87, 199, 255, 0.12)',
    borderColor: 'rgba(87, 199, 255, 0.45)',
    borderWidth: 1,
    borderRadius: radii.md,
    paddingHorizontal: 14,
    paddingVertical: 10,
    minWidth: 120,
  },
  onlineFriendName: {
    color: colors.textPrimary,
    fontFamily: fonts.medium,
    fontSize: 14,
  },
  onlineFriendTitle: {
    color: colors.highlight,
    fontSize: 12,
    fontFamily: fonts.medium,
    marginTop: 4,
  },
  onlineFriendCode: {
    color: '#9EDCFF',
    fontSize: 12,
    letterSpacing: 0.5,
    marginTop: 4,
    fontFamily: fonts.regular,
  },
  onlineFriendHint: {
    color: colors.accent,
    fontSize: 12,
    marginTop: 4,
    fontFamily: fonts.regular,
  },
  onlineFriendEmpty: {
    color: colors.textMuted,
    fontSize: 13,
    fontFamily: fonts.regular,
  },
  modalOverlay: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: 'rgba(7, 7, 11, 0.85)',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 24,
  },
  modalBackdrop: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    left: 0,
    right: 0,
  },
  modalCard: {
    width: '100%',
    maxWidth: 340,
    backgroundColor: colors.surface,
    borderRadius: radii.lg,
    padding: 24,
    borderWidth: 1,
    borderColor: colors.border,
    rowGap: 16,
  },
  settingsModalCard: {
    maxWidth: 360,
  },
  modalTitle: {
    color: colors.textPrimary,
    fontSize: 20,
    fontFamily: fonts.bold,
  },
  settingsModalTitle: {
    color: colors.textPrimary,
    fontSize: 20,
    fontFamily: fonts.bold,
  },
  settingsModalSection: {
    rowGap: 10,
  },
  settingsModalLabel: {
    color: colors.textSecondary,
    fontSize: 14,
    fontFamily: fonts.medium,
  },
  settingsApplyButton: {
    borderRadius: radii.md,
    paddingVertical: 14,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    backgroundColor: colors.surfaceAlt,
    overflow: 'hidden',
  },
  settingsApplyFill: {
    position: 'absolute',
    left: 0,
    top: 0,
    bottom: 0,
    borderRadius: radii.md,
    opacity: 0.35,
  },
  settingsApplyText: {
    color: colors.textSecondary,
    fontFamily: fonts.bold,
    letterSpacing: 0.3,
  },
  modalActions: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    columnGap: 12,
  },
  modalButton: {
    flex: 1,
    borderRadius: radii.md,
    paddingVertical: 12,
    alignItems: 'center',
    borderWidth: 1,
  },
  modalButtonContinue: {
    backgroundColor: 'rgba(57, 229, 138, 0.2)',
    borderColor: 'rgba(57, 229, 138, 0.5)',
  },
  modalButtonContinueText: {
    color: '#B6F5D4',
    fontFamily: fonts.bold,
  },
  modalButtonExit: {
    backgroundColor: 'rgba(255, 93, 110, 0.22)',
    borderColor: 'rgba(255, 93, 110, 0.6)',
    width: 60,
    alignItems: 'center',
    justifyContent: 'center',
  },
  modalButtonExitText: {
    color: '#FFB1B9',
    fontFamily: fonts.bold,
    fontSize: 16,
  },
});

export default styles;
