import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#0B1120',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 24,
    paddingVertical: 32,
  },
  backgroundGlowLarge: {
    position: 'absolute',
    width: 320,
    height: 320,
    borderRadius: 160,
    opacity: 0.2,
    top: -60,
  },
  backgroundGlowSmall: {
    position: 'absolute',
    width: 260,
    height: 260,
    borderRadius: 130,
    backgroundColor: '#2563EB',
    opacity: 0.18,
    bottom: -80,
    right: -40,
  },
  sparkle: {
    position: 'absolute',
  },
  sparkleHorizontal: {
    position: 'absolute',
    left: 0,
    right: 0,
  },
  sparkleVertical: {
    position: 'absolute',
    top: 0,
    bottom: 0,
  },
  card: {
    width: '100%',
    maxWidth: 420,
    borderRadius: 28,
    paddingVertical: 28,
    paddingHorizontal: 24,
    backgroundColor: 'rgba(15, 23, 42, 0.85)',
    borderWidth: 1,
    borderColor: 'rgba(148, 163, 184, 0.18)',
    alignItems: 'center',
  },
  badgePill: {
    paddingVertical: 10,
    paddingHorizontal: 24,
    borderRadius: 999,
    marginBottom: 18,
  },
  badgePillText: {
    color: '#0F172A',
    fontSize: 14,
    fontWeight: '700',
    letterSpacing: 1,
    textTransform: 'uppercase',
  },
  heading: {
    fontSize: 32,
    fontWeight: '800',
    color: '#F8FAFF',
    textAlign: 'center',
    marginBottom: 8,
  },
  subtitle: {
    fontSize: 16,
    color: '#CBD5F5',
    textAlign: 'center',
    marginBottom: 24,
  },
  statsSection: {
    width: '100%',
    borderRadius: 20,
    paddingVertical: 20,
    paddingHorizontal: 18,
    backgroundColor: 'rgba(30, 64, 175, 0.25)',
    borderWidth: 1,
    borderColor: 'rgba(59, 130, 246, 0.4)',
  },
  statsRow: {
    flexDirection: 'row',
    justifyContent: 'center',
    marginBottom: 14,
  },
  statPill: {
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 20,
    backgroundColor: 'rgba(148, 163, 184, 0.12)',
    marginHorizontal: 6,
    alignItems: 'center',
  },
  statPillLabel: {
    color: '#CBD5F5',
    fontSize: 12,
  },
  statPillValue: {
    color: '#FFFFFF',
    fontWeight: '600',
    marginTop: 2,
  },
  progressBar: {
    height: 12,
    borderRadius: 6,
    backgroundColor: 'rgba(148, 163, 184, 0.2)',
    overflow: 'hidden',
  },
  progressFill: {
    height: '100%',
    borderRadius: 6,
  },
  primaryButton: {
    marginTop: 28,
    width: '100%',
    paddingVertical: 16,
    borderRadius: 16,
    alignItems: 'center',
    shadowOpacity: 0.45,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 6 },
    elevation: 6,
  },
  primaryButtonText: {
    color: '#0F172A',
    fontSize: 18,
    fontWeight: '700',
  },
  secondaryButton: {
    width: '100%',
    paddingVertical: 14,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: 'rgba(148, 163, 184, 0.35)',
    alignItems: 'center',
    marginTop: 14,
  },
  secondaryButtonText: {
    color: '#E0E7FF',
    fontSize: 16,
    fontWeight: '600',
  },
  tertiaryButton: {
    marginTop: 16,
  },
  tertiaryButtonText: {
    color: '#94A3B8',
    fontSize: 14,
  },
  spotlight: {
    position: 'absolute',
    width: '70%',
    height: 120,
    top: 90,
    borderRadius: 60,
    backgroundColor: 'rgba(250, 204, 21, 0.16)',
    transform: [{ rotate: '-5deg' }],
  },
});

export default styles;
