import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#030712',
    paddingHorizontal: 20,
    paddingTop: 60,
    paddingBottom: 40,
  },
  scrollContent: {
    paddingBottom: 100,
    flexGrow: 1,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 32,
  },
  headerTitle: {
    color: '#F8FAFC',
    fontSize: 30,
    fontWeight: '800',
    letterSpacing: 1,
  },
  headerCloseButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: 'rgba(148, 163, 184, 0.35)',
    backgroundColor: 'rgba(15, 23, 42, 0.9)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerCloseText: {
    color: '#E0E7FF',
    fontWeight: '700',
    fontSize: 18,
  },
  tabRow: {
    flexDirection: 'row',
    backgroundColor: 'rgba(15, 23, 42, 0.75)',
    borderRadius: 14,
    padding: 4,
    borderWidth: 1,
    borderColor: 'rgba(148, 163, 184, 0.25)',
    marginBottom: 20,
  },
  tabButton: {
    flex: 1,
    paddingVertical: 12,
    borderRadius: 10,
    alignItems: 'center',
  },
  tabButtonActive: {
    backgroundColor: 'rgba(59, 130, 246, 0.15)',
    borderColor: 'rgba(59, 130, 246, 0.5)',
    borderWidth: 1,
  },
  tabButtonText: {
    color: '#94A3B8',
    fontWeight: '700',
    letterSpacing: 0.4,
  },
  tabButtonTextActive: {
    color: '#F8FAFC',
  },
  card: {
    backgroundColor: '#0F172A',
    borderRadius: 20,
    paddingVertical: 22,
    paddingHorizontal: 20,
    borderWidth: 1,
    marginBottom: 24,
  },
  audioCard: {
    borderColor: 'rgba(96, 165, 250, 0.35)',
  },
  squadCard: {
    borderColor: 'rgba(14, 165, 233, 0.35)',
  },
  profileCard: {
    borderColor: 'rgba(226, 232, 240, 0.18)',
  },
  cardLabel: {
    color: '#60A5FA',
    fontSize: 14,
    letterSpacing: 1.5,
    marginBottom: 0,
    textTransform: 'uppercase',
    fontWeight: '600',
  },
  cardTitle: {
    color: '#F8FAFC',
    fontSize: 18,
    fontWeight: '700',
  },
  rowBetween: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  fieldGroup: {
    marginBottom: 16,
  },
  input: {
    backgroundColor: '#111827',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(148, 163, 184, 0.25)',
    paddingHorizontal: 14,
    paddingVertical: 12,
    color: '#E2E8F0',
    fontSize: 14,
  },
  actionButton: {
    marginTop: 12,
    paddingVertical: 12,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
    paddingHorizontal: 16,
  },
  successButton: {
    backgroundColor: '#22C55E',
  },
  successButtonText: {
    color: '#0F172A',
    fontWeight: '700',
  },
  primaryButton: {
    backgroundColor: '#2563EB',
  },
  primaryButtonText: {
    color: '#F8FAFC',
    fontWeight: '600',
  },
  warningButton: {
    backgroundColor: '#F59E0B',
  },
  warningButtonText: {
    color: '#0F172A',
    fontWeight: '700',
  },
  dangerButton: {
    backgroundColor: '#F87171',
    borderWidth: 1,
    borderColor: '#F87171',
    elevation: 0,
    shadowOpacity: 0,
  },
  dangerButtonText: {
    color: '#F8FAFC',
    fontWeight: '800',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  dangerButtonDisabled: {
    backgroundColor: '#7F1D1D',
    borderWidth: 1,
    borderColor: '#7F1D1D',
    elevation: 0,
    shadowOpacity: 0,
  },
  disabledButton: {
    backgroundColor: '#1E3A8A',
  },
  warningButtonDisabled: {
    backgroundColor: '#0F172A',
  },
  friendHeroRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 18,
  },
  friendToggleRow: {
    marginBottom: 12,
    paddingBottom: 8,
    borderBottomWidth: 1,
    borderColor: 'rgba(148, 163, 184, 0.18)',
  },
  friendHeroEmoji: {
    fontSize: 36,
    marginRight: 14,
  },
  friendHeroTextGroup: {
    flex: 1,
  },
  friendHeroTitle: {
    color: '#F8FAFC',
    fontSize: 22,
    fontWeight: '800',
  },
  friendHeroSubtitle: {
    color: '#CBD5F5',
    fontSize: 14,
    marginTop: 4,
  },
  friendCodeCard: {
    marginBottom: 20,
    paddingVertical: 18,
    paddingHorizontal: 20,
    borderRadius: 20,
    backgroundColor: 'rgba(59, 130, 246, 0.12)',
    borderWidth: 1,
    borderColor: 'rgba(59, 130, 246, 0.45)',
  },
  friendCodeLabel: {
    color: '#93C5FD',
    fontSize: 12,
    letterSpacing: 1.2,
    textTransform: 'uppercase',
    marginBottom: 6,
  },
  friendCodeValue: {
    color: '#F8FAFC',
    fontSize: 28,
    fontWeight: '800',
    letterSpacing: 4,
  },
  friendCodeValueWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    columnGap: 10,
  },
  friendCodeCopy: {
    marginTop: 4,
    color: '#93C5FD',
    fontSize: 18,
    fontWeight: '800',
  },
  friendCodeCaption: {
    color: '#E2E8F0',
    fontSize: 13,
    marginTop: 6,
    opacity: 0.85,
  },
  friendInputLabel: {
    color: '#E5E7EB',
    fontSize: 15,
    fontWeight: '600',
    marginBottom: 8,
  },
  friendList: {
    backgroundColor: 'rgba(15, 23, 42, 0.95)',
    borderRadius: 18,
    paddingVertical: 18,
    paddingHorizontal: 18,
    borderWidth: 1,
    borderColor: 'rgba(148, 163, 184, 0.25)',
    maxHeight: 240,
  },
  friendListHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  friendListTitle: {
    color: '#F8FAFC',
    fontSize: 16,
    fontWeight: '700',
  },
  friendListCount: {
    color: '#94A3B8',
    fontSize: 13,
  },
  friendLoading: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 24,
  },
  friendLoadingText: {
    color: '#94A3B8',
    marginTop: 8,
  },
  friendEmptyText: {
    color: '#94A3B8',
    textAlign: 'center',
    fontSize: 14,
    paddingVertical: 12,
  },
  friendRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderColor: 'rgba(148, 163, 184, 0.12)',
  },
  friendCodeText: {
    color: '#E2E8F0',
    fontSize: 16,
    fontWeight: '700',
    letterSpacing: 2,
  },
  friendStatusText: {
    color: '#A5B4FC',
    fontSize: 12,
    fontWeight: '700',
    marginTop: 2,
  },
  friendRemoveButton: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: 'rgba(239, 68, 68, 0.35)',
  },
  friendRemoveText: {
    color: '#FCA5A5',
    fontSize: 12,
  },
  banner: {
    paddingVertical: 12,
    paddingHorizontal: 16,
    backgroundColor: 'rgba(59, 130, 246, 0.16)',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: 'rgba(59, 130, 246, 0.35)',
    marginBottom: 24,
  },
  bannerText: {
    color: '#BFDBFE',
    fontSize: 13,
  },
  inlineLink: {
    alignSelf: 'center',
    marginTop: 12,
    marginBottom: 4,
  },
  inlineLinkText: {
    color: '#BFDBFE',
    fontSize: 13,
    textDecorationLine: 'underline',
  },
  helperText: {
    marginTop: 6,
    color: '#94A3B8',
    fontSize: 12,
  },
  profileRow: {
    flexDirection: 'row',
    columnGap: 14,
    marginTop: 12,
    marginBottom: 12,
  },
  avatarFrame: {
    width: 72,
    height: 72,
    borderRadius: 16,
    borderWidth: 2,
    borderColor: 'rgba(59, 130, 246, 0.55)',
    shadowColor: '#3B82F6',
    shadowOpacity: 0.35,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 6 },
    overflow: 'hidden',
  },
  avatarCircle: {
    flex: 1,
    borderRadius: 14,
    backgroundColor: 'rgba(59, 130, 246, 0.12)',
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  avatarImage: {
    width: '100%',
    height: '100%',
    borderRadius: 14,
  },
  avatarText: {
    color: '#F8FAFC',
    fontSize: 22,
    fontWeight: '800',
  },
  profileInfo: {
    flex: 1,
  },
  profileName: {
    color: '#F8FAFC',
    fontSize: 18,
    fontWeight: '800',
  },
  profileEmail: {
    color: '#94A3B8',
    fontSize: 13,
    marginTop: 2,
  },
  levelBadge: {
    marginTop: 8,
    alignSelf: 'flex-start',
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 12,
    backgroundColor: 'transparent',
    borderWidth: 0,
  },
  levelBadgeText: {
    color: '#FFEAD1',
    fontWeight: '700',
    fontSize: 12,
    letterSpacing: 0.6,
  },
  profileStatsRow: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 8,
    marginBottom: 4,
  },
  profileStatCard: {
    flex: 1,
    backgroundColor: '#0B1220',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(148, 163, 184, 0.35)',
    paddingVertical: 10,
    paddingHorizontal: 12,
  },
  profileStatLabel: {
    color: '#94A3B8',
    fontSize: 12,
    fontWeight: '700',
    letterSpacing: 0.3,
  },
  profileStatValue: {
    color: '#F8FAFC',
    fontSize: 18,
    fontWeight: '800',
    marginTop: 4,
    letterSpacing: 0.2,
  },
  achievementRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 10,
  },
  achievementText: {
    color: '#94A3B8',
    fontSize: 12,
    fontWeight: '600',
  },
  flameBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 12,
    backgroundColor: 'rgba(249, 115, 22, 0.15)',
    borderWidth: 1,
    borderColor: 'rgba(249, 115, 22, 0.4)',
    columnGap: 6,
  },
  flameEmoji: {
    fontSize: 16,
  },
  flameText: {
    color: '#FDBA74',
    fontWeight: '800',
    fontSize: 13,
    letterSpacing: 0.5,
  },
  avatarGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
    marginTop: 12,
  },
  avatarTile: {
    width: '30%',
    minWidth: 96,
    borderRadius: 14,
    overflow: 'hidden',
    backgroundColor: '#0B1220',
    borderWidth: 1,
    borderColor: 'rgba(148, 163, 184, 0.35)',
  },
  avatarTileSelected: {
    borderColor: 'rgba(59, 130, 246, 0.8)',
    shadowColor: '#3B82F6',
    shadowOpacity: 0.35,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
  },
  avatarTileLocked: {
    opacity: 0.45,
  },
  avatarTileImage: {
    width: '100%',
    height: 84,
  },
  avatarTileLockBanner: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: 'rgba(15, 23, 42, 0.9)',
    paddingVertical: 6,
    alignItems: 'center',
  },
  avatarTileLevel: {
    color: '#FFFFFF',
    fontSize: 13,
    fontWeight: '800',
    letterSpacing: 0.4,
  },
  avatarToggle: {
    marginTop: 8,
    alignSelf: 'flex-start',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: 'rgba(59, 130, 246, 0.45)',
    backgroundColor: 'rgba(59, 130, 246, 0.12)',
  },
  avatarToggleText: {
    color: '#BFDBFE',
    fontWeight: '700',
  },
  resetContainer: {
    marginBottom: 8,
    padding: 16,
    borderRadius: 16,
    backgroundColor: 'rgba(15, 23, 42, 0.85)',
    borderWidth: 1,
    borderColor: 'rgba(59, 130, 246, 0.3)',
  },
  bottomActions: {
    marginTop: 24,
    marginBottom: 0,
    gap: 6,
  },
  fixedFooter: {
    paddingTop: 8,
    paddingBottom: 16,
    gap: 8,
  },
});

export default styles;
