import { StyleSheet } from 'react-native';
import { colors, fonts, radii } from '../../styles/theme';

const styles = StyleSheet.create({
  screenRoot: {
    flex: 1,
    backgroundColor: colors.background,
  },
  container: {
    flex: 1,
    backgroundColor: colors.background,
    paddingHorizontal: 24,
    paddingTop: 42,
    paddingBottom: 0,
  },
  containerProfileTop: {
    paddingTop: 0,
  },
  backgroundGlowTop: {
    display: 'none',
    position: 'absolute',
    width: 280,
    height: 280,
    borderRadius: 140,
    backgroundColor: colors.accent,
    opacity: 0.14,
    top: -140,
    right: -100,
  },
  backgroundGlowBottom: {
    display: 'none',
    position: 'absolute',
    width: 240,
    height: 240,
    borderRadius: 120,
    backgroundColor: colors.accentWarm,
    opacity: 0.1,
    bottom: -120,
    left: -80,
  },
  scrollContent: {
    paddingBottom: 0,
    flexGrow: 1,
  },
  scrollContentProfile: {
    paddingTop: 18,
  },
  settingsFooterSpacer: {
    flexGrow: 1,
    flexBasis: 220,
    minHeight: 220,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 32,
  },
  headerProfile: {
    marginBottom: 20,
  },
  headerSide: {
    width: 94,
    minHeight: 42,
    flexDirection: 'row',
    alignItems: 'center',
    flexShrink: 0,
  },
  headerSideLeft: {
    justifyContent: 'flex-start',
  },
  headerSideRight: {
    justifyContent: 'flex-end',
    gap: 10,
  },
  headerTitle: {
    flex: 1,
    minWidth: 0,
    flexShrink: 1,
    color: colors.textPrimary,
    fontSize: 30,
    fontFamily: fonts.bold,
    letterSpacing: 1,
    paddingRight: 12,
  },
  headerTitleCentered: {
    textAlign: 'center',
    paddingHorizontal: 12,
    paddingRight: 12,
  },
  headerActionButton: {
    width: 42,
    height: 42,
    borderRadius: radii.md,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  headerBackButton: {
    borderColor: colors.borderStrong,
    backgroundColor: colors.surfaceAlt,
  },
  headerLeadingButton: {
    borderColor: colors.borderStrong,
    backgroundColor: colors.surfaceAlt,
  },
  headerTrailingButton: {
    borderColor: colors.borderStrong,
    backgroundColor: colors.surfaceAlt,
  },
  headerCloseButton: {
    marginRight: __DEV__ ? 144 : 0,
    borderColor: 'rgba(255, 93, 110, 0.78)',
    backgroundColor: 'rgba(255, 93, 110, 0.12)',
  },
  headerCloseText: {
    color: '#FF6B7C',
    fontFamily: fonts.bold,
    fontSize: 22,
    lineHeight: 24,
  },
  tabRow: {
    flexDirection: 'row',
    backgroundColor: colors.surfaceAlt,
    borderRadius: radii.md,
    padding: 4,
    borderWidth: 1,
    borderColor: colors.border,
    marginBottom: 20,
  },
  tabButton: {
    flex: 1,
    paddingVertical: 12,
    borderRadius: radii.sm,
    alignItems: 'center',
  },
  tabButtonActive: {
    backgroundColor: 'rgba(87, 199, 255, 0.16)',
    borderColor: 'rgba(87, 199, 255, 0.5)',
    borderWidth: 1,
  },
  tabButtonText: {
    color: colors.textMuted,
    fontFamily: fonts.medium,
    letterSpacing: 0.4,
  },
  tabButtonTextActive: {
    color: colors.textPrimary,
  },
  card: {
    backgroundColor: colors.surface,
    borderRadius: radii.lg,
    paddingVertical: 22,
    paddingHorizontal: 20,
    borderWidth: 1,
    marginBottom: 24,
  },
  settingsCard: {
    borderColor: 'rgba(87, 199, 255, 0.35)',
  },
  squadCard: {
    borderColor: 'rgba(87, 199, 255, 0.35)',
  },
  profileCard: {
    borderColor: colors.border,
  },
  cardLabel: {
    color: colors.accent,
    fontSize: 14,
    letterSpacing: 1.5,
    marginBottom: 0,
    textTransform: 'uppercase',
    fontFamily: fonts.medium,
  },
  claimOverlayContainer: {
    ...StyleSheet.absoluteFillObject,
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 80,
    elevation: 12,
  },
  claimOverlayBackdrop: {
    ...StyleSheet.absoluteFillObject,
  },
  claimOverlayBlur: {
    ...StyleSheet.absoluteFillObject,
  },
  claimOverlayDimmer: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(2, 6, 23, 0.52)',
  },
  claimCenterCard: {
    width: '88%',
    maxWidth: 390,
    borderRadius: radii.xl,
    backgroundColor: 'rgba(17, 25, 40, 0.92)',
    borderWidth: 1,
    borderColor: 'rgba(255, 127, 168, 0.42)',
    paddingHorizontal: 22,
    paddingVertical: 24,
    shadowColor: '#FF7FA8',
    shadowOpacity: 0.34,
    shadowRadius: 30,
    shadowOffset: {
      width: 0,
      height: 14,
    },
    overflow: 'hidden',
  },
  claimCenterHero: {
    marginTop: 0,
    width: '100%',
    alignItems: 'flex-start',
  },
  claimCenterHeroRow: {
    marginTop: 6,
    width: '100%',
    flexDirection: 'row',
    alignItems: 'flex-end',
    justifyContent: 'space-between',
    columnGap: 12,
  },
  claimCenterCoinsValue: {
    flexShrink: 1,
    color: colors.accentPink,
    fontFamily: fonts.bold,
    fontSize: 42,
    letterSpacing: 0.8,
  },
  claimCenterCoinsGain: {
    marginTop: 4,
    color: '#FFD7E4',
    fontFamily: fonts.bold,
    fontSize: 16,
    letterSpacing: 0.35,
  },
  claimCenterMiniLevelBadge: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: radii.pill,
    borderWidth: 1,
    borderColor: 'rgba(255, 127, 168, 0.38)',
    backgroundColor: 'rgba(255, 127, 168, 0.12)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  claimCenterMiniLevelLabel: {
    color: colors.textSecondary,
    fontFamily: fonts.medium,
    fontSize: 10,
    textTransform: 'uppercase',
    letterSpacing: 0.85,
  },
  claimCenterMiniLevelValue: {
    marginTop: 1,
    color: '#FFD0DF',
    fontFamily: fonts.bold,
    fontSize: 18,
    letterSpacing: 0.3,
  },
  claimCenterProgressWrap: {
    width: '100%',
    marginTop: 18,
  },
  claimCenterProgressTrack: {
    width: '100%',
    borderRadius: radii.pill,
    backgroundColor: 'rgba(16, 23, 37, 0.95)',
    borderWidth: 1,
    borderColor: 'rgba(255, 127, 168, 0.26)',
    overflow: 'hidden',
  },
  claimCenterProgressFill: {
    height: '100%',
    borderRadius: radii.pill,
    backgroundColor: colors.accentPink,
    shadowColor: colors.accentPink,
    shadowOpacity: 0.62,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 0 },
  },
  rowBetween: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  rowBetweenSpaced: {
    marginTop: 14,
  },
  fieldGroup: {
    marginBottom: 16,
  },
  input: {
    backgroundColor: colors.surfaceAlt,
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.border,
    paddingHorizontal: 14,
    paddingVertical: 12,
    color: colors.textPrimary,
    fontSize: 14,
    fontFamily: fonts.regular,
  },
  actionButton: {
    marginTop: 12,
    paddingVertical: 12,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
    paddingHorizontal: 16,
  },
  successButton: {
    backgroundColor: colors.success,
  },
  successButtonText: {
    color: '#07120F',
    fontFamily: fonts.bold,
  },
  friendRequestSentButton: {
    backgroundColor: '#22C55E',
  },
  friendRequestSentButtonText: {
    color: '#052E16',
    fontFamily: fonts.bold,
  },
  primaryButton: {
    backgroundColor: colors.accent,
  },
  primaryButtonText: {
    color: '#081019',
    fontFamily: fonts.bold,
  },
  warningButton: {
    backgroundColor: colors.accentWarm,
  },
  warningButtonText: {
    color: '#0A0A12',
    fontFamily: fonts.bold,
  },
  dangerButton: {
    backgroundColor: colors.danger,
    borderWidth: 1,
    borderColor: colors.danger,
    elevation: 0,
    shadowOpacity: 0,
  },
  dangerButtonText: {
    color: colors.textPrimary,
    fontFamily: fonts.bold,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  dangerButtonDisabled: {
    backgroundColor: '#7A1D2B',
    borderWidth: 1,
    borderColor: '#7A1D2B',
    elevation: 0,
    shadowOpacity: 0,
  },
  disabledButton: {
    backgroundColor: '#2B4B63',
  },
  warningButtonDisabled: {
    backgroundColor: colors.surfaceAlt,
  },
  friendHeroSubtitle: {
    color: colors.textSecondary,
    fontSize: 14,
    marginTop: 4,
    fontFamily: fonts.regular,
  },
  friendCodeCard: {
    marginBottom: 16,
    paddingVertical: 12,
    paddingHorizontal: 14,
    borderRadius: radii.md,
    backgroundColor: 'rgba(87, 199, 255, 0.12)',
    borderWidth: 1,
    borderColor: 'rgba(87, 199, 255, 0.45)',
  },
  friendCodeValue: {
    color: colors.textPrimary,
    fontSize: 22,
    fontFamily: fonts.bold,
    letterSpacing: 2,
  },
  friendCodeValueWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    columnGap: 10,
  },
  friendCodeCopy: {
    marginTop: 4,
    color: '#9EDCFF',
    fontSize: 14,
    fontFamily: fonts.bold,
  },
  friendCodeCopyIcon: {
    marginTop: 4,
  },
  subtleFriendCodeButton: {
    alignSelf: 'flex-start',
    flexDirection: 'row',
    alignItems: 'center',
    columnGap: 6,
    paddingVertical: 2,
  },
  subtleFriendCodeText: {
    color: colors.textMuted,
    fontSize: 11,
    fontFamily: fonts.medium,
    letterSpacing: 0.5,
    opacity: 0.74,
  },
  subtleFriendCodeTextCopied: {
    color: '#9EDCFF',
    opacity: 0.92,
  },
  subtleFriendCodeIcon: {
    opacity: 0.86,
  },
  friendInputLabel: {
    color: colors.textSecondary,
    fontSize: 15,
    fontFamily: fonts.medium,
    marginBottom: 8,
  },
  friendList: {
    backgroundColor: colors.surfaceAlt,
    borderRadius: radii.lg,
    paddingVertical: 18,
    paddingHorizontal: 18,
    borderWidth: 1,
    borderColor: colors.border,
  },
  friendListDivider: {
    height: 1,
    backgroundColor: colors.border,
    marginTop: 20,
    marginBottom: 22,
  },
  friendListHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 12,
    columnGap: 12,
  },
  friendListHeaderText: {
    flex: 1,
  },
  friendListTitle: {
    color: colors.textPrimary,
    fontSize: 16,
    fontFamily: fonts.bold,
  },
  friendListCount: {
    color: colors.textMuted,
    fontSize: 13,
    fontFamily: fonts.regular,
  },
  friendListInlineCode: {
    marginTop: 4,
  },
  friendAddButton: {
    width: 34,
    height: 34,
    borderRadius: 17,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
  },
  friendLoading: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 24,
  },
  friendLoadingText: {
    color: colors.textMuted,
    marginTop: 8,
    fontFamily: fonts.regular,
  },
  friendEmptyText: {
    color: colors.textMuted,
    textAlign: 'center',
    fontSize: 14,
    paddingVertical: 12,
    fontFamily: fonts.regular,
  },
  friendRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderColor: colors.border,
  },
  friendMainPressable: {
    flex: 1,
    marginRight: 12,
    paddingVertical: 2,
  },
  friendIdentityRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  friendAvatar: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.08)',
    borderWidth: 1,
    borderColor: colors.border,
    marginRight: 10,
    overflow: 'hidden',
  },
  friendAvatarImage: {
    width: '100%',
    height: '100%',
    borderRadius: 20,
  },
  friendAvatarText: {
    color: colors.textPrimary,
    fontFamily: fonts.bold,
    fontSize: 12,
  },
  friendIdentityMeta: {
    flex: 1,
    minWidth: 0,
  },
  friendHeadlineRow: {
    flexDirection: 'row',
    alignItems: 'center',
    minWidth: 0,
    columnGap: 8,
  },
  friendRowLast: {
    borderBottomWidth: 0,
  },
  friendCodeText: {
    color: colors.textPrimary,
    fontSize: 16,
    fontFamily: fonts.bold,
    letterSpacing: 0.2,
    flex: 1,
    minWidth: 0,
  },
  friendTitleText: {
    color: colors.highlight,
    fontSize: 12,
    fontFamily: fonts.medium,
    marginTop: 2,
  },
  friendStatusDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    marginRight: 6,
  },
  friendOnlineIndicator: {
    marginRight: 0,
    flexShrink: 0,
  },
  friendStatusDotOnline: {
    backgroundColor: colors.success,
  },
  friendRequestsSection: {
    rowGap: 10,
  },
  friendRequestsTitle: {
    color: colors.textPrimary,
    fontSize: 15,
    fontFamily: fonts.bold,
  },
  friendRequestRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderColor: colors.border,
  },
  friendRequestInfo: {
    flex: 1,
    minWidth: 0,
    marginRight: 6,
  },
  friendRequestActions: {
    flexDirection: 'row',
    alignItems: 'center',
    columnGap: 6,
    flexShrink: 0,
  },
  friendRequestActionButton: {
    width: 32,
    height: 32,
    alignItems: 'center',
    justifyContent: 'center',
  },
  friendRequestDeclineButton: {
    borderRadius: 16,
    borderWidth: 1,
    borderColor: 'rgba(255, 93, 110, 0.45)',
    backgroundColor: 'rgba(255, 93, 110, 0.14)',
  },
  friendRequestAcceptButton: {
    borderRadius: 16,
    borderWidth: 1,
    borderColor: 'rgba(34, 197, 94, 0.45)',
    backgroundColor: 'rgba(34, 197, 94, 0.18)',
  },
  friendRequestAcceptButtonDisabled: {
    opacity: 0.65,
  },
  friendAddOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 20,
    justifyContent: 'flex-end',
  },
  friendAddBackdrop: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: 'rgba(8, 12, 20, 0.7)',
  },
  friendAddCard: {
    backgroundColor: colors.surface,
    borderTopLeftRadius: radii.lg,
    borderTopRightRadius: radii.lg,
    borderWidth: 1,
    borderColor: colors.border,
    paddingHorizontal: 20,
    paddingTop: 18,
    paddingBottom: 24,
  },
  friendAddHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 10,
  },
  friendAddTitle: {
    color: colors.textPrimary,
    fontSize: 18,
    fontFamily: fonts.bold,
  },
  friendAddClose: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.surfaceAlt,
    borderWidth: 1,
    borderColor: colors.border,
  },
  friendRemoveConfirmOverlay: {
    ...StyleSheet.absoluteFillObject,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 24,
    zIndex: 40,
    elevation: 12,
  },
  friendRemoveConfirmBackdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(4, 8, 18, 0.76)',
  },
  friendRemoveConfirmCard: {
    width: '100%',
    maxWidth: 360,
    borderRadius: radii.xl,
    backgroundColor: 'rgba(17, 25, 40, 0.96)',
    borderWidth: 1,
    borderColor: 'rgba(255, 127, 168, 0.34)',
    paddingHorizontal: 22,
    paddingVertical: 22,
    shadowColor: '#000',
    shadowOpacity: 0.36,
    shadowRadius: 24,
    shadowOffset: { width: 0, height: 12 },
    overflow: 'hidden',
    rowGap: 16,
  },
  friendRemoveConfirmMessage: {
    color: colors.textPrimary,
    fontSize: 16,
    lineHeight: 24,
    fontFamily: fonts.medium,
  },
  friendRemoveConfirmActions: {
    flexDirection: 'row',
    columnGap: 12,
    marginTop: 2,
  },
  friendRemoveConfirmButton: {
    flex: 1,
    minHeight: 48,
    borderRadius: radii.md,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 14,
  },
  friendRemoveConfirmCancelButton: {
    backgroundColor: colors.surfaceAlt,
    borderColor: colors.borderStrong,
  },
  friendRemoveConfirmDangerButton: {
    backgroundColor: 'rgba(255, 93, 110, 0.18)',
    borderColor: 'rgba(255, 93, 110, 0.52)',
  },
  friendRemoveConfirmCancelText: {
    color: colors.textPrimary,
    fontSize: 14,
    fontFamily: fonts.bold,
  },
  friendRemoveConfirmDangerText: {
    color: '#FFD3DA',
    fontSize: 14,
    fontFamily: fonts.bold,
  },
  friendRemoveConfirmButtonDisabled: {
    opacity: 0.7,
  },
  banner: {
    paddingVertical: 12,
    paddingHorizontal: 16,
    backgroundColor: 'rgba(87, 199, 255, 0.16)',
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: 'rgba(87, 199, 255, 0.35)',
    marginBottom: 24,
  },
  bannerText: {
    color: '#CBEAFF',
    fontSize: 13,
    fontFamily: fonts.medium,
  },
  helperText: {
    marginTop: 6,
    color: colors.textMuted,
    fontSize: 12,
    fontFamily: fonts.regular,
  },
  profileRow: {
    flexDirection: 'row',
    columnGap: 14,
    marginTop: 12,
    marginBottom: 12,
  },
  profileRowNoTitle: {
    marginTop: 0,
  },
  avatarFrame: {
    width: 84,
    height: 84,
    borderRadius: radii.md,
    borderWidth: 2,
    borderColor: 'rgba(87, 199, 255, 0.6)',
    shadowColor: colors.accent,
    shadowOpacity: 0.35,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 6 },
    overflow: 'visible',
    position: 'relative',
  },
  avatarCircle: {
    flex: 1,
    borderRadius: radii.md,
    backgroundColor: 'rgba(87, 199, 255, 0.12)',
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  avatarImage: {
    width: '100%',
    height: '100%',
    borderRadius: radii.md,
  },
  avatarText: {
    color: colors.textPrimary,
    fontSize: 22,
    fontFamily: fonts.bold,
  },
  profileInfo: {
    flex: 1,
  },
  profileName: {
    color: colors.textPrimary,
    fontSize: 18,
    fontFamily: fonts.bold,
  },
  profileTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    columnGap: 8,
    marginTop: 8,
  },
  profileTitleLabel: {
    color: colors.textMuted,
    fontSize: 11,
    fontFamily: fonts.medium,
    letterSpacing: 0.6,
    textTransform: 'uppercase',
  },
  profileTitleValue: {
    color: colors.highlight,
    fontSize: 13,
    fontFamily: fonts.bold,
  },
  profileTitleHint: {
    color: colors.textMuted,
    fontSize: 11,
    marginTop: 4,
    fontFamily: fonts.regular,
  },
  profileXpText: {
    color: colors.textSecondary,
    fontSize: 12,
    fontFamily: fonts.medium,
    marginTop: 4,
  },
  profileFriendCodeInline: {
    marginTop: 8,
  },
  profileLevelProgressBlock: {
    marginTop: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: 'rgba(87, 199, 255, 0.32)',
    backgroundColor: 'rgba(9, 26, 44, 0.48)',
  },
  profileLevelProgressHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  profileLevelProgressLabel: {
    color: '#BFEAFF',
    fontSize: 11,
    fontFamily: fonts.medium,
    letterSpacing: 0.7,
    textTransform: 'uppercase',
  },
  profileLevelProgressPercent: {
    color: colors.textPrimary,
    fontSize: 13,
    fontFamily: fonts.bold,
  },
  profileLevelProgressTrack: {
    marginTop: 8,
    height: 14,
    borderRadius: radii.pill,
    backgroundColor: 'rgba(15, 23, 42, 0.92)',
    borderWidth: 1,
    borderColor: 'rgba(148, 163, 184, 0.3)',
    overflow: 'hidden',
  },
  profileLevelProgressFill: {
    height: '100%',
    borderRadius: radii.pill,
    backgroundColor: '#57C7FF',
    shadowColor: '#57C7FF',
    shadowOpacity: 0.48,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 0 },
  },
  profileLevelProgressMetaRow: {
    marginTop: 8,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    columnGap: 8,
  },
  profileLevelProgressMeta: {
    color: colors.textSecondary,
    fontSize: 11,
    fontFamily: fonts.medium,
    flexShrink: 1,
  },
  levelBadge: {
    marginTop: 8,
    alignSelf: 'flex-start',
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: radii.md,
    backgroundColor: 'transparent',
    borderWidth: 0,
  },
  levelBadgeText: {
    color: '#FFEAD1',
    fontFamily: fonts.bold,
    fontSize: 12,
    letterSpacing: 0.6,
  },
  profileStatsRow: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 8,
    marginBottom: 4,
  },
  profileStatCard: {
    flex: 1,
    backgroundColor: colors.surfaceAlt,
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.border,
    paddingVertical: 10,
    paddingHorizontal: 12,
  },
  profileStatLabel: {
    color: colors.textMuted,
    fontSize: 12,
    fontFamily: fonts.medium,
    letterSpacing: 0.3,
  },
  profileStatValue: {
    color: colors.textPrimary,
    fontSize: 18,
    fontFamily: fonts.bold,
    marginTop: 4,
    letterSpacing: 0.2,
  },
  profileInventory: {
    marginTop: 12,
  },
  profileInventoryTitle: {
    color: colors.textPrimary,
    fontSize: 14,
    fontFamily: fonts.bold,
    marginBottom: 8,
  },
  profileInventoryRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  profileInventoryItem: {
    flexDirection: 'row',
    alignItems: 'center',
    columnGap: 10,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: radii.md,
    backgroundColor: colors.surfaceAlt,
    borderWidth: 1,
    borderColor: colors.border,
    flexGrow: 1,
    minWidth: 142,
  },
  profileInventoryIconWrap: {
    width: 28,
    height: 28,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
  },
  profileInventoryText: {
    flex: 1,
  },
  profileInventoryLabel: {
    color: colors.textSecondary,
    fontSize: 12,
    fontFamily: fonts.medium,
  },
  profileInventoryValue: {
    color: colors.textPrimary,
    fontSize: 12,
    fontFamily: fonts.bold,
    marginTop: 2,
  },
  profileInventoryValueActive: {
    color: colors.accent,
  },
  profileAchievements: {
    marginTop: 16,
  },
  profileAchievementList: {
    gap: 10,
    marginTop: 8,
  },
  profileAchievementCard: {
    backgroundColor: colors.surfaceAlt,
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.border,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  profileAchievementCardActive: {
    borderColor: 'rgba(34, 197, 94, 0.6)',
    backgroundColor: 'rgba(34, 197, 94, 0.12)',
  },
  profileAchievementCardClaimed: {
    opacity: 0.58,
  },
  profileAchievementCardLocked: {
    opacity: 0.72,
  },
  profileAchievementHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  profileAchievementTitle: {
    color: colors.textPrimary,
    fontSize: 14,
    fontFamily: fonts.bold,
  },
  profileAchievementStatus: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: radii.pill,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
  },
  profileAchievementStatusActive: {
    borderColor: 'rgba(34, 197, 94, 0.7)',
    backgroundColor: 'rgba(34, 197, 94, 0.2)',
  },
  profileAchievementStatusClaimed: {
    borderColor: 'rgba(100, 116, 139, 0.78)',
    backgroundColor: 'rgba(71, 85, 105, 0.22)',
  },
  profileAchievementStatusClaimedMuted: {
    borderColor: 'rgba(100, 116, 139, 0.92)',
    backgroundColor: 'rgba(51, 65, 85, 0.3)',
  },
  profileAchievementStatusText: {
    color: colors.textSecondary,
    fontSize: 11,
    fontFamily: fonts.bold,
  },
  profileAchievementStatusTextClaimed: {
    color: 'rgba(203, 213, 225, 0.72)',
  },
  profileAchievementStatusDisabled: {
    opacity: 0.52,
  },
  profileAchievementStatusPressed: {
    opacity: 0.82,
  },
  profileAchievementHint: {
    color: colors.textMuted,
    fontSize: 12,
    fontFamily: fonts.regular,
    marginTop: 6,
  },
  profileAchievementMeta: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 8,
    gap: 8,
  },
  profileAchievementProgress: {
    color: colors.textPrimary,
    fontSize: 12,
    fontFamily: fonts.bold,
    minWidth: 56,
  },
  profileAchievementReward: {
    color: colors.accentWarm,
    fontSize: 12,
    fontFamily: fonts.medium,
    flex: 1,
    textAlign: 'right',
    flexShrink: 1,
  },
  profileAchievementRewardCoin: {
    color: colors.highlight,
    fontFamily: fonts.bold,
  },
  helpContainer: {
    paddingBottom: 18,
  },
  helpScrollContent: {
    paddingBottom: 24,
    gap: 16,
  },
  helpOptionButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  helpOptionButtonLast: {
    borderBottomWidth: 0,
  },
  helpOptionContent: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  helpOptionIconWrap: {
    width: 34,
    height: 34,
    borderRadius: 17,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(87, 199, 255, 0.16)',
    borderWidth: 1,
    borderColor: 'rgba(87, 199, 255, 0.35)',
  },
  helpOptionIconWrapDanger: {
    backgroundColor: 'rgba(239, 68, 68, 0.14)',
    borderColor: 'rgba(239, 68, 68, 0.34)',
  },
  helpOptionLabel: {
    color: colors.textPrimary,
    fontSize: 15,
    fontFamily: fonts.bold,
  },
  helpOptionLabelDanger: {
    color: '#FFD5DB',
  },
  helpResetBlock: {
    paddingTop: 4,
    paddingBottom: 16,
  },
  avatarGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
    marginTop: 12,
  },
  avatarTile: {
    width: '30%',
    minWidth: 96,
    borderRadius: radii.md,
    overflow: 'hidden',
    backgroundColor: colors.surfaceAlt,
    borderWidth: 1,
    borderColor: 'rgba(148, 163, 184, 0.45)',
  },
  avatarTileCustom: {
    borderStyle: 'solid',
    borderColor: 'rgba(148, 163, 184, 0.45)',
    backgroundColor: 'rgba(15, 23, 42, 0.38)',
  },
  avatarTileSelected: {
    borderColor: '#22C55E',
    shadowColor: '#22C55E',
    shadowOpacity: 0.45,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 4,
  },
  avatarTileLocked: {
    opacity: 0.45,
  },
  avatarTileImage: {
    width: '100%',
    height: 84,
  },
  avatarTileIconWrap: {
    width: '100%',
    height: 84,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(87, 199, 255, 0.08)',
  },
  avatarTilePlaceholder: {
    height: 84,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
  },
  avatarTilePlaceholderText: {
    fontSize: 12,
    fontFamily: fonts.medium,
    color: '#BFDBFE',
    textTransform: 'uppercase',
    letterSpacing: 0.8,
  },
  avatarTileLockBanner: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: 'rgba(11, 11, 18, 0.9)',
    paddingVertical: 6,
    alignItems: 'center',
  },
  avatarTileLevel: {
    color: colors.textPrimary,
    fontSize: 13,
    fontFamily: fonts.bold,
    letterSpacing: 0.4,
  },
  footerStack: {
    marginTop: 0,
    paddingTop: 8,
    paddingBottom: 16,
  },
  footerPrimary: {
    marginTop: 0,
  },
});

export default styles;
