import { StyleSheet } from 'react-native';
import { colors, fonts, radii } from '../../styles/theme';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
    paddingHorizontal: 20,
    paddingTop: 60,
    paddingBottom: 40,
  },
  backgroundGlowTop: {
    position: 'absolute',
    width: 280,
    height: 280,
    borderRadius: 140,
    backgroundColor: colors.accent,
    opacity: 0.14,
    top: -140,
    right: -100,
  },
  backgroundGlowBottom: {
    position: 'absolute',
    width: 240,
    height: 240,
    borderRadius: 120,
    backgroundColor: colors.accentWarm,
    opacity: 0.1,
    bottom: -120,
    left: -80,
  },
  scrollContent: {
    paddingBottom: 100,
    flexGrow: 1,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 32,
  },
  headerTitle: {
    color: colors.textPrimary,
    fontSize: 30,
    fontFamily: fonts.bold,
    letterSpacing: 1,
  },
  headerCloseButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surfaceAlt,
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerCloseText: {
    color: colors.textSecondary,
    fontFamily: fonts.bold,
    fontSize: 18,
  },
  tabRow: {
    flexDirection: 'row',
    backgroundColor: colors.surfaceAlt,
    borderRadius: radii.md,
    padding: 4,
    borderWidth: 1,
    borderColor: colors.border,
    marginBottom: 20,
  },
  tabButton: {
    flex: 1,
    paddingVertical: 12,
    borderRadius: radii.sm,
    alignItems: 'center',
  },
  tabButtonActive: {
    backgroundColor: 'rgba(87, 199, 255, 0.16)',
    borderColor: 'rgba(87, 199, 255, 0.5)',
    borderWidth: 1,
  },
  tabButtonText: {
    color: colors.textMuted,
    fontFamily: fonts.medium,
    letterSpacing: 0.4,
  },
  tabButtonTextActive: {
    color: colors.textPrimary,
  },
  card: {
    backgroundColor: colors.surface,
    borderRadius: radii.lg,
    paddingVertical: 22,
    paddingHorizontal: 20,
    borderWidth: 1,
    marginBottom: 24,
  },
  audioCard: {
    borderColor: 'rgba(87, 199, 255, 0.35)',
  },
  squadCard: {
    borderColor: 'rgba(87, 199, 255, 0.35)',
  },
  profileCard: {
    borderColor: colors.border,
  },
  cardLabel: {
    color: colors.accent,
    fontSize: 14,
    letterSpacing: 1.5,
    marginBottom: 0,
    textTransform: 'uppercase',
    fontFamily: fonts.medium,
  },
  cardTitle: {
    color: colors.textPrimary,
    fontSize: 18,
    fontFamily: fonts.bold,
  },
  rowBetween: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  fieldGroup: {
    marginBottom: 16,
  },
  input: {
    backgroundColor: colors.surfaceAlt,
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.border,
    paddingHorizontal: 14,
    paddingVertical: 12,
    color: colors.textPrimary,
    fontSize: 14,
    fontFamily: fonts.regular,
  },
  actionButton: {
    marginTop: 12,
    paddingVertical: 12,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
    paddingHorizontal: 16,
  },
  successButton: {
    backgroundColor: colors.success,
  },
  successButtonText: {
    color: '#07120F',
    fontFamily: fonts.bold,
  },
  primaryButton: {
    backgroundColor: colors.accent,
  },
  primaryButtonText: {
    color: '#081019',
    fontFamily: fonts.bold,
  },
  warningButton: {
    backgroundColor: colors.accentWarm,
  },
  warningButtonText: {
    color: '#0A0A12',
    fontFamily: fonts.bold,
  },
  dangerButton: {
    backgroundColor: colors.danger,
    borderWidth: 1,
    borderColor: colors.danger,
    elevation: 0,
    shadowOpacity: 0,
  },
  dangerButtonText: {
    color: colors.textPrimary,
    fontFamily: fonts.bold,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  dangerButtonDisabled: {
    backgroundColor: '#7A1D2B',
    borderWidth: 1,
    borderColor: '#7A1D2B',
    elevation: 0,
    shadowOpacity: 0,
  },
  disabledButton: {
    backgroundColor: '#2B4B63',
  },
  warningButtonDisabled: {
    backgroundColor: colors.surfaceAlt,
  },
  friendHeroRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 18,
  },
  friendToggleRow: {
    marginBottom: 12,
    paddingBottom: 8,
    borderBottomWidth: 1,
    borderColor: colors.border,
  },
  friendHeroEmoji: {
    fontSize: 36,
    marginRight: 14,
  },
  friendHeroTextGroup: {
    flex: 1,
  },
  friendHeroTitle: {
    color: colors.textPrimary,
    fontSize: 22,
    fontFamily: fonts.bold,
  },
  friendHeroSubtitle: {
    color: colors.textSecondary,
    fontSize: 14,
    marginTop: 4,
    fontFamily: fonts.regular,
  },
  friendCodeCard: {
    marginBottom: 16,
    paddingVertical: 12,
    paddingHorizontal: 14,
    borderRadius: radii.md,
    backgroundColor: 'rgba(87, 199, 255, 0.12)',
    borderWidth: 1,
    borderColor: 'rgba(87, 199, 255, 0.45)',
  },
  friendCodeLabel: {
    color: '#9EDCFF',
    fontSize: 11,
    letterSpacing: 1.1,
    textTransform: 'uppercase',
    marginBottom: 4,
    fontFamily: fonts.medium,
  },
  friendCodeValue: {
    color: colors.textPrimary,
    fontSize: 22,
    fontFamily: fonts.bold,
    letterSpacing: 2,
  },
  friendCodeValueWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    columnGap: 10,
  },
  friendCodeCopy: {
    marginTop: 4,
    color: '#9EDCFF',
    fontSize: 14,
    fontFamily: fonts.bold,
  },
  friendCodeCopyIcon: {
    marginTop: 4,
  },
  friendCodeCaption: {
    color: colors.textSecondary,
    fontSize: 13,
    marginTop: 6,
    opacity: 0.85,
    fontFamily: fonts.regular,
  },
  friendInputLabel: {
    color: colors.textSecondary,
    fontSize: 15,
    fontFamily: fonts.medium,
    marginBottom: 8,
  },
  friendList: {
    backgroundColor: colors.surfaceAlt,
    borderRadius: radii.lg,
    paddingVertical: 18,
    paddingHorizontal: 18,
    borderWidth: 1,
    borderColor: colors.border,
    maxHeight: 240,
  },
  friendListDivider: {
    height: 1,
    backgroundColor: colors.border,
    marginTop: 20,
    marginBottom: 22,
  },
  friendListHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  friendListTitle: {
    color: colors.textPrimary,
    fontSize: 16,
    fontFamily: fonts.bold,
  },
  friendListCount: {
    color: colors.textMuted,
    fontSize: 13,
    fontFamily: fonts.regular,
  },
  friendLoading: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 24,
  },
  friendLoadingText: {
    color: colors.textMuted,
    marginTop: 8,
    fontFamily: fonts.regular,
  },
  friendEmptyText: {
    color: colors.textMuted,
    textAlign: 'center',
    fontSize: 14,
    paddingVertical: 12,
    fontFamily: fonts.regular,
  },
  friendRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderColor: colors.border,
  },
  friendRowLast: {
    borderBottomWidth: 0,
  },
  friendCodeText: {
    color: colors.textPrimary,
    fontSize: 16,
    fontFamily: fonts.bold,
    letterSpacing: 2,
  },
  friendTitleText: {
    color: colors.highlight,
    fontSize: 12,
    fontFamily: fonts.medium,
    marginTop: 2,
  },
  friendStatusRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 4,
  },
  friendStatusDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    marginRight: 6,
  },
  friendStatusDotOnline: {
    backgroundColor: colors.success,
  },
  friendStatusDotOffline: {
    backgroundColor: colors.textMuted,
  },
  friendStatusDotLobby: {
    backgroundColor: colors.accent,
  },
  friendStatusText: {
    color: colors.accentPink,
    fontSize: 12,
    fontFamily: fonts.medium,
  },
  friendStatusTextOnline: {
    color: '#9BF2C4',
  },
  friendStatusTextOffline: {
    color: colors.textMuted,
  },
  friendStatusTextLobby: {
    color: '#9EDCFF',
  },
  friendRemoveButton: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: radii.sm,
    borderWidth: 1,
    borderColor: 'rgba(255, 93, 110, 0.4)',
  },
  friendRemoveText: {
    color: '#FFB1B9',
    fontSize: 12,
    fontFamily: fonts.medium,
  },
  banner: {
    paddingVertical: 12,
    paddingHorizontal: 16,
    backgroundColor: 'rgba(87, 199, 255, 0.16)',
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: 'rgba(87, 199, 255, 0.35)',
    marginBottom: 24,
  },
  bannerText: {
    color: '#CBEAFF',
    fontSize: 13,
    fontFamily: fonts.medium,
  },
  inlineLink: {
    alignSelf: 'center',
    marginTop: 12,
    marginBottom: 4,
  },
  inlineLinkText: {
    color: '#9EDCFF',
    fontSize: 13,
    textDecorationLine: 'underline',
    fontFamily: fonts.medium,
  },
  legalRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
    columnGap: 8,
    marginTop: 6,
  },
  legalLink: {
    paddingHorizontal: 6,
    paddingVertical: 4,
  },
  legalLinkText: {
    color: '#9EDCFF',
    fontSize: 12,
    fontFamily: fonts.medium,
  },
  legalDivider: {
    color: colors.textMuted,
    fontSize: 12,
  },
  legalLinkDisabled: {
    opacity: 0.4,
  },
  helperText: {
    marginTop: 6,
    color: colors.textMuted,
    fontSize: 12,
    fontFamily: fonts.regular,
  },
  profileRow: {
    flexDirection: 'row',
    columnGap: 14,
    marginTop: 12,
    marginBottom: 12,
  },
  avatarFrame: {
    width: 72,
    height: 72,
    borderRadius: radii.md,
    borderWidth: 2,
    borderColor: 'rgba(87, 199, 255, 0.6)',
    shadowColor: colors.accent,
    shadowOpacity: 0.35,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 6 },
    overflow: 'hidden',
  },
  avatarCircle: {
    flex: 1,
    borderRadius: radii.md,
    backgroundColor: 'rgba(87, 199, 255, 0.12)',
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  avatarImage: {
    width: '100%',
    height: '100%',
    borderRadius: radii.md,
  },
  avatarText: {
    color: colors.textPrimary,
    fontSize: 22,
    fontFamily: fonts.bold,
  },
  profileInfo: {
    flex: 1,
  },
  profileName: {
    color: colors.textPrimary,
    fontSize: 18,
    fontFamily: fonts.bold,
  },
  profileTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    columnGap: 8,
    marginTop: 8,
  },
  profileTitleLabel: {
    color: colors.textMuted,
    fontSize: 11,
    fontFamily: fonts.medium,
    letterSpacing: 0.6,
    textTransform: 'uppercase',
  },
  profileTitleValue: {
    color: colors.highlight,
    fontSize: 13,
    fontFamily: fonts.bold,
  },
  profileTitleHint: {
    color: colors.textMuted,
    fontSize: 11,
    marginTop: 4,
    fontFamily: fonts.regular,
  },
  profileXpText: {
    color: colors.textSecondary,
    fontSize: 12,
    fontFamily: fonts.medium,
    marginTop: 4,
  },
  profileEmail: {
    color: colors.textMuted,
    fontSize: 13,
    marginTop: 2,
    fontFamily: fonts.regular,
  },
  levelBadge: {
    marginTop: 8,
    alignSelf: 'flex-start',
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: radii.md,
    backgroundColor: 'transparent',
    borderWidth: 0,
  },
  levelBadgeText: {
    color: '#FFEAD1',
    fontFamily: fonts.bold,
    fontSize: 12,
    letterSpacing: 0.6,
  },
  profileStatsRow: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 8,
    marginBottom: 4,
  },
  profileStatCard: {
    flex: 1,
    backgroundColor: colors.surfaceAlt,
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.border,
    paddingVertical: 10,
    paddingHorizontal: 12,
  },
  profileStatLabel: {
    color: colors.textMuted,
    fontSize: 12,
    fontFamily: fonts.medium,
    letterSpacing: 0.3,
  },
  profileStatValue: {
    color: colors.textPrimary,
    fontSize: 18,
    fontFamily: fonts.bold,
    marginTop: 4,
    letterSpacing: 0.2,
  },
  achievementRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 10,
  },
  achievementPill: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: radii.pill,
    backgroundColor: 'rgba(87, 199, 255, 0.12)',
    borderWidth: 1,
    borderColor: 'rgba(87, 199, 255, 0.35)',
  },
  achievementText: {
    color: colors.textMuted,
    fontSize: 12,
    fontFamily: fonts.medium,
  },
  flameBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: radii.md,
    backgroundColor: 'rgba(255, 178, 92, 0.18)',
    borderWidth: 1,
    borderColor: 'rgba(255, 178, 92, 0.4)',
    columnGap: 6,
  },
  flameEmoji: {
    fontSize: 16,
  },
  flameText: {
    color: '#FFD0A1',
    fontFamily: fonts.bold,
    fontSize: 13,
    letterSpacing: 0.5,
  },
  avatarGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
    marginTop: 12,
  },
  avatarTile: {
    width: '30%',
    minWidth: 96,
    borderRadius: radii.md,
    overflow: 'hidden',
    backgroundColor: colors.surfaceAlt,
    borderWidth: 1,
    borderColor: colors.border,
  },
  avatarTileSelected: {
    borderColor: 'rgba(87, 199, 255, 0.8)',
    shadowColor: colors.accent,
    shadowOpacity: 0.35,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
  },
  avatarTileLocked: {
    opacity: 0.45,
  },
  avatarTileImage: {
    width: '100%',
    height: 84,
  },
  avatarTileLockBanner: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: 'rgba(11, 11, 18, 0.9)',
    paddingVertical: 6,
    alignItems: 'center',
  },
  avatarTileLevel: {
    color: colors.textPrimary,
    fontSize: 13,
    fontFamily: fonts.bold,
    letterSpacing: 0.4,
  },
  avatarToggle: {
    marginTop: 8,
    alignSelf: 'flex-start',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: radii.sm,
    borderWidth: 1,
    borderColor: 'rgba(87, 199, 255, 0.45)',
    backgroundColor: 'rgba(87, 199, 255, 0.12)',
  },
  avatarToggleText: {
    color: '#CBEAFF',
    fontFamily: fonts.bold,
  },
  resetContainer: {
    marginBottom: 8,
    padding: 16,
    borderRadius: radii.lg,
    backgroundColor: colors.surfaceAlt,
    borderWidth: 1,
    borderColor: colors.border,
  },
  bottomActions: {
    marginTop: 24,
    marginBottom: 0,
    gap: 6,
  },
  fixedFooter: {
    paddingTop: 8,
    paddingBottom: 16,
    gap: 8,
  },
});

export default styles;
