import { StyleSheet } from 'react-native';
import { colors, fonts, radii } from '../../styles/theme';

export const styles = StyleSheet.create({
  overlay: {
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 22,
    zIndex: 40,
  },
  backdrop: {
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    backgroundColor: 'rgba(5, 8, 14, 0.72)',
  },
  card: {
    width: '100%',
    maxWidth: 420,
    backgroundColor: colors.surface,
    borderRadius: radii.lg,
    borderWidth: 1,
    borderColor: colors.borderStrong,
    paddingHorizontal: 18,
    paddingVertical: 16,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingTop: 4,
  },
  headerLeading: {
    flexDirection: 'row',
    alignItems: 'center',
    columnGap: 10,
  },
  headerIconButton: {
    width: 30,
    height: 30,
    borderRadius: 15,
    borderWidth: 1,
    borderColor: 'rgba(87, 199, 255, 0.55)',
    backgroundColor: 'rgba(87, 199, 255, 0.12)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerTitle: {
    color: colors.textPrimary,
    fontSize: 18,
    fontFamily: fonts.bold,
  },
  headerActions: {
    flexDirection: 'row',
    alignItems: 'center',
    columnGap: 10,
  },
  profileRow: {
    marginTop: 14,
    flexDirection: 'row',
    columnGap: 12,
  },
  avatarFrame: {
    width: 72,
    height: 72,
    borderRadius: radii.md,
    borderWidth: 2,
    borderColor: 'rgba(87, 199, 255, 0.6)',
    shadowColor: colors.accent,
    shadowOpacity: 0.35,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 6 },
    overflow: 'visible',
    position: 'relative',
  },
  avatarCircle: {
    flex: 1,
    borderRadius: radii.md,
    backgroundColor: 'rgba(87, 199, 255, 0.12)',
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  avatarImage: {
    width: '100%',
    height: '100%',
    borderRadius: radii.md,
  },
  avatarText: {
    color: colors.textPrimary,
    fontSize: 22,
    fontFamily: fonts.bold,
  },
  profileNameRow: {
    flexDirection: 'row',
    alignItems: 'center',
    columnGap: 8,
  },
  profileNameOnlineDotWrap: {
    width: 18,
    height: 18,
    borderRadius: 9,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(34, 197, 94, 0.28)',
    borderWidth: 1,
    borderColor: 'rgba(34, 197, 94, 0.65)',
    shadowColor: '#22C55E',
    shadowOpacity: 0.95,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 0 },
    elevation: 6,
  },
  profileNameOnlineDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: '#22C55E',
  },
  profileInfo: {
    flex: 1,
  },
  profileName: {
    color: colors.textPrimary,
    fontSize: 18,
    fontFamily: fonts.bold,
  },
  profileSubtitle: {
    color: colors.textMuted,
    fontSize: 13,
    fontFamily: fonts.regular,
    marginTop: 2,
  },
  levelBadge: {
    marginTop: 8,
    alignSelf: 'flex-start',
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: radii.md,
    backgroundColor: 'rgba(255, 179, 71, 0.16)',
    borderWidth: 1,
    borderColor: 'rgba(255, 179, 71, 0.4)',
  },
  levelBadgeText: {
    color: '#FFEAD1',
    fontFamily: fonts.bold,
    fontSize: 12,
    letterSpacing: 0.6,
  },
  profileTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    columnGap: 8,
    marginTop: 8,
  },
  profileTitleLabel: {
    color: colors.textMuted,
    fontSize: 11,
    fontFamily: fonts.medium,
    letterSpacing: 0.6,
    textTransform: 'uppercase',
  },
  profileTitleValue: {
    color: colors.highlight,
    fontSize: 13,
    fontFamily: fonts.bold,
    flexShrink: 1,
  },
  profileStatsRow: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 14,
  },
  profileStatCard: {
    flex: 1,
    backgroundColor: colors.surfaceAlt,
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.border,
    paddingVertical: 10,
    paddingHorizontal: 12,
  },
  profileStatLabel: {
    color: colors.textMuted,
    fontSize: 12,
    fontFamily: fonts.medium,
    letterSpacing: 0.3,
  },
  profileStatValue: {
    color: colors.textPrimary,
    fontSize: 18,
    fontFamily: fonts.bold,
    marginTop: 4,
    letterSpacing: 0.2,
  },
  bioWrap: {
    marginTop: 12,
    backgroundColor: colors.surfaceAlt,
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.border,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  bioText: {
    color: colors.textSecondary,
    fontSize: 13,
    fontFamily: fonts.regular,
    lineHeight: 18,
  },
  actionStack: {
    marginTop: 14,
    rowGap: 10,
  },
  secondaryActionRow: {
    flexDirection: 'row',
    gap: 10,
  },
  secondaryActionButton: {
    flex: 1,
    minHeight: 44,
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.borderStrong,
    backgroundColor: colors.surfaceAlt,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 10,
  },
  secondaryActionText: {
    color: colors.textSecondary,
    fontSize: 13,
    fontFamily: fonts.bold,
    textAlign: 'center',
  },
  secondaryActionDangerButton: {
    borderColor: 'rgba(248, 113, 113, 0.5)',
    backgroundColor: 'rgba(248, 113, 113, 0.12)',
  },
  secondaryActionDangerText: {
    color: '#FFD1D1',
    fontSize: 13,
    fontFamily: fonts.bold,
    textAlign: 'center',
  },
  secondaryActionNeutralButton: {
    borderColor: 'rgba(96, 165, 250, 0.45)',
    backgroundColor: 'rgba(96, 165, 250, 0.12)',
  },
  secondaryActionNeutralText: {
    color: '#D8ECFF',
  },
  footerActionButton: {
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: 'rgba(248, 113, 113, 0.55)',
    backgroundColor: 'rgba(248, 113, 113, 0.16)',
    paddingVertical: 11,
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 44,
  },
  footerActionButtonDisabled: {
    opacity: 0.65,
  },
  footerActionText: {
    color: '#FFD1D1',
    fontSize: 15,
    fontFamily: fonts.bold,
    letterSpacing: 0.2,
  },
});
