export const SOLO_QUESTION_LIMIT = 6;
export const QUICK_PLAY_QUESTION_LIMIT = SOLO_QUESTION_LIMIT;
export const CATEGORY_QUESTION_LIMIT = SOLO_QUESTION_LIMIT;
export const MULTIPLAYER_DEFAULT_QUESTION_LIMIT = SOLO_QUESTION_LIMIT;
export const MULTIPLAYER_MIN_QUESTION_LIMIT = 3;
export const MULTIPLAYER_MAX_QUESTION_LIMIT = 20;
export const MULTIPLAYER_MAX_PLAYERS = 5;
