insert into public.questions (
  question,
  correct_answer,
  options,
  category,
  difficulty,
  slug
)
values
  ('Wie heisst der Knochen des Oberarms?', 'Humerus', '["Humerus","Radius","Ulna","Femur"]'::jsonb, 'Anatomie', 'leicht', 'anatomie-leicht-01'),
  ('Wie viele Kammern hat das menschliche Herz?', 'Vier', '["Zwei","Drei","Vier","Fuenf"]'::jsonb, 'Anatomie', 'leicht', 'anatomie-leicht-02'),
  ('Welcher Muskel ist der groesste im menschlichen Koerper?', 'M. gluteus maximus', '["M. gluteus maximus","M. biceps brachii","M. deltoideus","M. rectus abdominis"]'::jsonb, 'Anatomie', 'leicht', 'anatomie-leicht-03'),
  ('Welches Organ liegt im linken Oberbauch?', 'Milz', '["Milz","Leber","Appendix","Gallenblase"]'::jsonb, 'Anatomie', 'leicht', 'anatomie-leicht-04'),
  ('Wie heisst der Knochen der Kniescheibe?', 'Patella', '["Patella","Tibia","Fibula","Talus"]'::jsonb, 'Anatomie', 'leicht', 'anatomie-leicht-05'),
  ('Welcher Nerv innerviert den Musculus biceps brachii motorisch?', 'N. musculocutaneus', '["N. musculocutaneus","N. radialis","N. medianus","N. ulnaris"]'::jsonb, 'Anatomie', 'mittel', 'anatomie-mittel-01'),
  ('Welche Struktur trennt rechten und linken Vorhof?', 'Vorhofseptum', '["Vorhofseptum","Ventrikelseptum","Aortenklappe","Trikuspidalklappe"]'::jsonb, 'Anatomie', 'mittel', 'anatomie-mittel-02'),
  ('Welche Arterie versorgt den vorderen Hirnkreislauf hauptsaechlich?', 'A. carotis interna', '["A. carotis interna","A. vertebralis","A. basilaris","A. subclavia"]'::jsonb, 'Anatomie', 'mittel', 'anatomie-mittel-03'),
  ('Wie viele Lungenlappen hat die rechte Lunge?', 'Drei', '["Zwei","Drei","Vier","Fuenf"]'::jsonb, 'Anatomie', 'mittel', 'anatomie-mittel-04'),
  ('Wo liegt das Foramen magnum?', 'Os occipitale', '["Os occipitale","Os frontale","Os temporale","Os sphenoidale"]'::jsonb, 'Anatomie', 'mittel', 'anatomie-mittel-05'),
  ('Welche Struktur verlaesst die Fossa cranii media durch das Foramen ovale?', 'N. mandibularis (V3)', '["N. mandibularis (V3)","N. oculomotorius (III)","N. facialis (VII)","N. abducens (VI)"]'::jsonb, 'Anatomie', 'schwer', 'anatomie-schwer-01'),
  ('Welcher Muskel gehoert zur Rotatorenmanschette?', 'M. supraspinatus', '["M. supraspinatus","M. pectoralis major","M. latissimus dorsi","M. serratus anterior"]'::jsonb, 'Anatomie', 'schwer', 'anatomie-schwer-02'),
  ('Welcher Ast der A. iliaca interna versorgt die Harnblase?', 'A. vesicalis superior', '["A. vesicalis superior","A. obturatoria","A. glutea superior","A. pudenda interna"]'::jsonb, 'Anatomie', 'schwer', 'anatomie-schwer-03'),
  ('Welcher Wirbel besitzt einen Dens?', 'Axis (C2)', '["Axis (C2)","Atlas (C1)","C3","C7"]'::jsonb, 'Anatomie', 'schwer', 'anatomie-schwer-04'),
  ('Welche Schicht der Darmwand liegt direkt unter der Mukosa?', 'Submukosa', '["Submukosa","Muskularis propria","Serosa","Adventitia"]'::jsonb, 'Anatomie', 'schwer', 'anatomie-schwer-05'),
  ('Welches Hormon steigert den Blutzuckerspiegel?', 'Glukagon', '["Glukagon","Insulin","Aldosteron","Oxytocin"]'::jsonb, 'Physiologie', 'leicht', 'physiologie-leicht-01'),
  ('Wie viel Prozent Sauerstoff enthaelt die Einatemluft ungefaehr?', '21 %', '["21 %","16 %","10 %","40 %"]'::jsonb, 'Physiologie', 'leicht', 'physiologie-leicht-02'),
  ('Welche Ionen sind hauptsaechlich fuer das Ruhemembranpotential verantwortlich?', 'Kalium', '["Kalium","Natrium","Calcium","Chlorid"]'::jsonb, 'Physiologie', 'leicht', 'physiologie-leicht-03'),
  ('Wie heisst der Herzschrittmacher im rechten Vorhof?', 'Sinusknoten', '["Sinusknoten","AV-Knoten","Purkinje-Fasern","His-Buendel"]'::jsonb, 'Physiologie', 'leicht', 'physiologie-leicht-04'),
  ('Welches System reguliert den Kurzzeit-Blutdruck?', 'Barorezeptoren', '["Barorezeptoren","Chemorezeptoren","Hypothalamus","Nebennierenrinde"]'::jsonb, 'Physiologie', 'leicht', 'physiologie-leicht-05'),
  ('Welcher Transportmechanismus nutzt ATP direkt?', 'Primaer aktiver Transport', '["Primaer aktiver Transport","Erleichterte Diffusion","Osmose","Filtration"]'::jsonb, 'Physiologie', 'mittel', 'physiologie-mittel-01'),
  ('Welche Saeure wird von Belegzellen im Magen gebildet?', 'Salzsaeure', '["Salzsaeure","Milchsaeure","Kohlensaeure","Essigsaeure"]'::jsonb, 'Physiologie', 'mittel', 'physiologie-mittel-02'),
  ('Wie lange leben Erythrozyten ungefaehr?', '120 Tage', '["30 Tage","60 Tage","120 Tage","300 Tage"]'::jsonb, 'Physiologie', 'mittel', 'physiologie-mittel-03'),
  ('Welche Struktur ist der Ort des Gasaustauschs in der Lunge?', 'Alveolen', '["Alveolen","Bronchien","Pleura","Trachea"]'::jsonb, 'Physiologie', 'mittel', 'physiologie-mittel-04'),
  ('Welches Hormon foerdert die Wasserresorption in der Niere?', 'ADH (Vasopressin)', '["ADH (Vasopressin)","Aldosteron","ANP","Cortisol"]'::jsonb, 'Physiologie', 'mittel', 'physiologie-mittel-05'),
  ('Welche Stromart verursacht die Phase-0-Depolarisation im Sinusknoten?', 'Calcium-Einstrom (L-Typ)', '["Calcium-Einstrom (L-Typ)","Natrium-Einstrom (schnell)","Kalium-Ausstrom","Chlorid-Einstrom"]'::jsonb, 'Physiologie', 'schwer', 'physiologie-schwer-01'),
  ('Welcher Teil des Nephrons ist fuer die Gegenstrommultiplikation entscheidend?', 'Henle-Schleife', '["Henle-Schleife","Bowman-Kapsel","Proximaler Tubulus","Sammelrohr"]'::jsonb, 'Physiologie', 'schwer', 'physiologie-schwer-02'),
  ('Welcher Faktor verschiebt die O2-Bindungskurve nach rechts?', 'pH-Abfall (Bohr-Effekt)', '["pH-Abfall (Bohr-Effekt)","pH-Anstieg","Temperaturabfall","CO2-Abfall"]'::jsonb, 'Physiologie', 'schwer', 'physiologie-schwer-03'),
  ('Wann findet die isovolumetrische Kontraktion statt?', 'Direkt nach AV-Klappenschluss', '["Direkt nach AV-Klappenschluss","Waerend der Auswurfphase","Waerend der Ventrikelfuellung","Nach Oeffnung der AV-Klappen"]'::jsonb, 'Physiologie', 'schwer', 'physiologie-schwer-04'),
  ('Welche Zellen produzieren Surfactant in der Lunge?', 'Pneumozyten Typ II', '["Pneumozyten Typ II","Pneumozyten Typ I","Alveolarmakrophagen","Endothelzellen"]'::jsonb, 'Physiologie', 'schwer', 'physiologie-schwer-05'),
  ('Wie nennt man eine gutartige Geschwulst des Fettgewebes?', 'Lipom', '["Lipom","Sarkom","Melanom","Lymphom"]'::jsonb, 'Pathologie', 'leicht', 'pathologie-leicht-01'),
  ('Welche Entzuendung betrifft den Blinddarm?', 'Appendizitis', '["Appendizitis","Cholezystitis","Pankreatitis","Gastritis"]'::jsonb, 'Pathologie', 'leicht', 'pathologie-leicht-02'),
  ('Was bezeichnet man als Fieber?', 'Koerpertemperatur ueber 38 C', '["Koerpertemperatur ueber 38 C","Koerpertemperatur unter 36 C","Koerpertemperatur 37 C","Koerpertemperatur unter 35 C"]'::jsonb, 'Pathologie', 'leicht', 'pathologie-leicht-03'),
  ('Wie nennt man Gewebsuntergang durch Durchblutungsstoerung?', 'Infarkt', '["Infarkt","Hyperplasie","Dysplasie","Metaplasie"]'::jsonb, 'Pathologie', 'leicht', 'pathologie-leicht-04'),
  ('Welche Blutungsform zeigt punktfoermige Hauteinblutungen?', 'Petechien', '["Petechien","Haematome","Ulcera","Varizen"]'::jsonb, 'Pathologie', 'leicht', 'pathologie-leicht-05'),
  ('Welcher Tumormarker ist typisch erhoeht beim Prostatakarzinom?', 'PSA', '["PSA","AFP","CEA","CA-125"]'::jsonb, 'Pathologie', 'mittel', 'pathologie-mittel-01'),
  ('Welche Nekroseform ist typisch beim Myokardinfarkt?', 'Koagulationsnekrose', '["Koagulationsnekrose","Kolliquationsnekrose","Fettgewebsnekrose","Fibrinoidnekrose"]'::jsonb, 'Pathologie', 'mittel', 'pathologie-mittel-02'),
  ('Was beschreibt eine Metaplasie?', 'Reversible Umwandlung eines Zelltyps in einen anderen', '["Reversible Umwandlung eines Zelltyps in einen anderen","Vermehrung der Zellzahl","Zellgroessenzunahme","Ungeordnete Zellproliferation"]'::jsonb, 'Pathologie', 'mittel', 'pathologie-mittel-03'),
  ('Welche Autoimmunthyreoiditis ist haeufig?', 'Hashimoto-Thyreoiditis', '["Hashimoto-Thyreoiditis","Basedow","Riedel-Struma","Kretinismus"]'::jsonb, 'Pathologie', 'mittel', 'pathologie-mittel-04'),
  ('Welche Zellen spielen bei der Typ-I-Allergie die Hauptrolle?', 'Mastzellen', '["Mastzellen","Neutrophile","Erythrozyten","Thrombozyten"]'::jsonb, 'Pathologie', 'mittel', 'pathologie-mittel-05'),
  ('Welche Translokation ist typisch fuer die CML?', 't(9;22) BCR-ABL', '["t(9;22) BCR-ABL","t(8;14)","t(15;17)","t(14;18)"]'::jsonb, 'Pathologie', 'schwer', 'pathologie-schwer-01'),
  ('Welche Amyloidose ist typisch beim multiplen Myelom?', 'AL-Amyloid', '["AL-Amyloid","AA-Amyloid","ATTR","Abeta"]'::jsonb, 'Pathologie', 'schwer', 'pathologie-schwer-02'),
  ('Welche Virusinfektion ist mit Zervixkarzinom assoziiert?', 'HPV 16/18', '["HPV 16/18","EBV","CMV","HSV-1"]'::jsonb, 'Pathologie', 'schwer', 'pathologie-schwer-03'),
  ('Welcher Autoantikoerper ist typisch beim Goodpasture-Syndrom?', 'Anti-GBM', '["Anti-GBM","ANA","c-ANCA","Rheumafaktor"]'::jsonb, 'Pathologie', 'schwer', 'pathologie-schwer-04'),
  ('Welche Tumorsuppressor-Genmutation ist typisch beim Retinoblastom?', 'RB1', '["RB1","p53","APC","BRCA1"]'::jsonb, 'Pathologie', 'schwer', 'pathologie-schwer-05'),
  ('Welches Analgetikum ist ein NSAID?', 'Ibuprofen', '["Ibuprofen","Paracetamol","Morphin","Amitriptylin"]'::jsonb, 'Pharmakologie', 'leicht', 'pharmakologie-leicht-01'),
  ('Welcher Wirkstoff ist ein Beta-Blocker?', 'Metoprolol', '["Metoprolol","Amlodipin","Losartan","Furosemid"]'::jsonb, 'Pharmakologie', 'leicht', 'pharmakologie-leicht-02'),
  ('Welche Substanz ist ein Penicillin-Antibiotikum?', 'Amoxicillin', '["Amoxicillin","Azithromycin","Doxycyclin","Ciprofloxacin"]'::jsonb, 'Pharmakologie', 'leicht', 'pharmakologie-leicht-03'),
  ('Welches Medikament ist ein Protonenpumpenhemmer?', 'Omeprazol', '["Omeprazol","Ranitidin","Metoclopramid","Sucralfat"]'::jsonb, 'Pharmakologie', 'leicht', 'pharmakologie-leicht-04'),
  ('Welche Substanz ist ein Opioid?', 'Morphin', '["Morphin","Diclofenac","Ibuprofen","Paracetamol"]'::jsonb, 'Pharmakologie', 'leicht', 'pharmakologie-leicht-05'),
  ('Welcher Wirkstoff hemmt die HMG-CoA-Reduktase?', 'Atorvastatin', '["Atorvastatin","Ezetimib","Fenofibrat","Niacin"]'::jsonb, 'Pharmakologie', 'mittel', 'pharmakologie-mittel-01'),
  ('Welches Diuretikum wirkt am aufsteigenden Ast der Henle-Schleife?', 'Furosemid', '["Furosemid","Hydrochlorothiazid","Spironolacton","Acetazolamid"]'::jsonb, 'Pharmakologie', 'mittel', 'pharmakologie-mittel-02'),
  ('Welche typische Nebenwirkung von ACE-Hemmern ist korrekt?', 'Trockener Husten', '["Trockener Husten","Hypoglykaemie","Bradykardie","Hyperthyreose"]'::jsonb, 'Pharmakologie', 'mittel', 'pharmakologie-mittel-03'),
  ('Welcher Wirkstoff ist ein direkter Faktor-Xa-Hemmer?', 'Rivaroxaban', '["Rivaroxaban","Warfarin","Heparin","Dabigatran"]'::jsonb, 'Pharmakologie', 'mittel', 'pharmakologie-mittel-04'),
  ('Welcher Wirkstoff ist ein SSRI?', 'Sertralin', '["Sertralin","Amitriptylin","Venlafaxin","Haloperidol"]'::jsonb, 'Pharmakologie', 'mittel', 'pharmakologie-mittel-05'),
  ('Welches Antidot wird bei Paracetamol-Intoxikation gegeben?', 'N-Acetylcystein', '["N-Acetylcystein","Flumazenil","Naloxon","Atropin"]'::jsonb, 'Pharmakologie', 'schwer', 'pharmakologie-schwer-01'),
  ('Welcher Wirkstoff ist ein nicht-depolarisierendes Muskelrelaxans?', 'Rocuronium', '["Rocuronium","Succinylcholin","Neostigmin","Midazolam"]'::jsonb, 'Pharmakologie', 'schwer', 'pharmakologie-schwer-02'),
  ('Welches Antiarrhythmikum gehoert zu Klasse III?', 'Amiodaron', '["Amiodaron","Lidocain","Verapamil","Propranolol"]'::jsonb, 'Pharmakologie', 'schwer', 'pharmakologie-schwer-03'),
  ('Welche Substanz ist ein monoklonaler Anti-TNF-Antikoerper?', 'Infliximab', '["Infliximab","Rituximab","Trastuzumab","Bevacizumab"]'::jsonb, 'Pharmakologie', 'schwer', 'pharmakologie-schwer-04'),
  ('Welcher Wirkmechanismus trifft auf Heparin zu?', 'Aktivierung von Antithrombin III', '["Aktivierung von Antithrombin III","Vitamin-K-Antagonismus","Direkte Thrombinhemmung","Hemmung der Thrombozytenaggregation"]'::jsonb, 'Pharmakologie', 'schwer', 'pharmakologie-schwer-05'),
  ('Welches Bakterium ist grampositiv?', 'Staphylococcus aureus', '["Staphylococcus aureus","Escherichia coli","Pseudomonas aeruginosa","Neisseria meningitidis"]'::jsonb, 'Mikrobiologie', 'leicht', 'mikrobiologie-leicht-01'),
  ('Welche Struktur nutzen Bakterien zur Bewegung?', 'Flagellen', '["Flagellen","Pili","Kapsel","Ribosomen"]'::jsonb, 'Mikrobiologie', 'leicht', 'mikrobiologie-leicht-02'),
  ('Wie nennt man Viren mit RNA als Erbmaterial?', 'RNA-Viren', '["RNA-Viren","DNA-Viren","Prionen","Pilze"]'::jsonb, 'Mikrobiologie', 'leicht', 'mikrobiologie-leicht-03'),
  ('Welche Pilzinfektion betrifft haeufig die Haut?', 'Tinea', '["Tinea","Malaria","Lepra","Zoster"]'::jsonb, 'Mikrobiologie', 'leicht', 'mikrobiologie-leicht-04'),
  ('Welcher Erreger verursacht Masern?', 'Masernvirus', '["Masernvirus","Varizella-Zoster-Virus","Influenzavirus","Adenovirus"]'::jsonb, 'Mikrobiologie', 'leicht', 'mikrobiologie-leicht-05'),
  ('Welcher Erreger verursacht typischerweise Harnwegsinfekte?', 'Escherichia coli', '["Escherichia coli","Streptococcus pyogenes","Mycoplasma pneumoniae","Treponema pallidum"]'::jsonb, 'Mikrobiologie', 'mittel', 'mikrobiologie-mittel-01'),
  ('Welches Bakterium verursacht Tetanus?', 'Clostridium tetani', '["Clostridium tetani","Corynebacterium diphtheriae","Borrelia burgdorferi","Campylobacter jejuni"]'::jsonb, 'Mikrobiologie', 'mittel', 'mikrobiologie-mittel-02'),
  ('Welche Viren sind typisch fuer Gastroenteritis bei Kindern?', 'Rotavirus', '["Rotavirus","EBV","HSV-1","Parvovirus B19"]'::jsonb, 'Mikrobiologie', 'mittel', 'mikrobiologie-mittel-03'),
  ('Welche Eigenschaft hat Mycobacterium tuberculosis?', 'Saeurefest', '["Saeurefest","Sporenbildend","Gramnegativ","Kapselbildend"]'::jsonb, 'Mikrobiologie', 'mittel', 'mikrobiologie-mittel-04'),
  ('Welcher Erreger verursacht eine atypische Pneumonie?', 'Mycoplasma pneumoniae', '["Mycoplasma pneumoniae","Streptococcus pneumoniae","Haemophilus influenzae","Moraxella catarrhalis"]'::jsonb, 'Mikrobiologie', 'mittel', 'mikrobiologie-mittel-05'),
  ('Welcher Erreger verursacht Lyme-Borreliose?', 'Borrelia burgdorferi', '["Borrelia burgdorferi","Treponema pallidum","Leptospira interrogans","Rickettsia rickettsii"]'::jsonb, 'Mikrobiologie', 'schwer', 'mikrobiologie-schwer-01'),
  ('Welches Gen vermittelt Methicillinresistenz bei MRSA?', 'mecA', '["mecA","vanA","blaCTX-M","gyrA"]'::jsonb, 'Mikrobiologie', 'schwer', 'mikrobiologie-schwer-02'),
  ('Welches Virus besitzt eine Reverse Transkriptase?', 'HIV', '["HIV","Adenovirus","HPV","Parvovirus B19"]'::jsonb, 'Mikrobiologie', 'schwer', 'mikrobiologie-schwer-03'),
  ('Welcher Erreger verursacht Legionella-Pneumonie?', 'Legionella pneumophila', '["Legionella pneumophila","Chlamydia trachomatis","Bordetella pertussis","Coxiella burnetii"]'::jsonb, 'Mikrobiologie', 'schwer', 'mikrobiologie-schwer-04'),
  ('Welche Bakterien besitzen keine Zellwand?', 'Mycoplasmen', '["Mycoplasmen","Staphylokokken","Streptokokken","Listerien"]'::jsonb, 'Mikrobiologie', 'schwer', 'mikrobiologie-schwer-05');
