-- Expand several still-thin online category pools with another precise bilingual pack.

with question_rows (
  slug,
  category,
  question_de,
  correct_de,
  options_de,
  explanation_de,
  question_en,
  correct_en,
  options_en,
  explanation_en
) as (
  values
    (
      'online-breit-biochemie-01',
      'Biochemie',
      'Welches Enzym wandelt Homocystein zu Cystathionin um?',
      'Cystathionin-beta-Synthase',
      '["Cystathionin-beta-Synthase","Methioninsynthase","Phenylalaninhydroxylase","Arginase"]'::jsonb,
      'Die Cystathionin-beta-Synthase katalysiert im Transsulfurierungsweg die Umwandlung von Homocystein und Serin zu Cystathionin.',
      'Which enzyme converts homocysteine to cystathionine?',
      'Cystathionine beta-synthase',
      '["Cystathionine beta-synthase","Methionine synthase","Phenylalanine hydroxylase","Arginase"]'::jsonb,
      'Cystathionine beta-synthase catalyzes the transsulfuration step converting homocysteine and serine into cystathionine.'
    ),
    (
      'online-breit-biochemie-02',
      'Biochemie',
      'Welcher Enzymdefekt ist fuer die klassische Phenylketonurie typisch?',
      'Phenylalaninhydroxylase-Mangel',
      '["Phenylalaninhydroxylase-Mangel","Tyrosinase-Mangel","Homogentisat-1,2-Dioxygenase-Mangel","Dihydropteridin-Reduktase-Mangel"]'::jsonb,
      'Die klassische Phenylketonurie beruht typischerweise auf einem Mangel der Phenylalaninhydroxylase. Dadurch steigt Phenylalanin pathologisch an.',
      'Which enzyme defect is typical of classic phenylketonuria?',
      'Phenylalanine hydroxylase deficiency',
      '["Phenylalanine hydroxylase deficiency","Tyrosinase deficiency","Homogentisate 1,2-dioxygenase deficiency","Dihydropteridine reductase deficiency"]'::jsonb,
      'Classic phenylketonuria is typically caused by deficiency of phenylalanine hydroxylase. This leads to pathologic elevation of phenylalanine.'
    ),
    (
      'online-breit-biochemie-03',
      'Biochemie',
      'Welches Apolipoprotein aktiviert die Lipoproteinlipase direkt?',
      'ApoC-II',
      '["ApoC-II","ApoA-I","ApoB-100","ApoE"]'::jsonb,
      'ApoC-II ist der notwendige Aktivator der Lipoproteinlipase. Ohne ApoC-II werden triglyceridreiche Lipoproteine unzureichend abgebaut.',
      'Which apolipoprotein directly activates lipoprotein lipase?',
      'ApoC-II',
      '["ApoC-II","ApoA-I","ApoB-100","ApoE"]'::jsonb,
      'ApoC-II is the required activator of lipoprotein lipase. Without ApoC-II, triglyceride-rich lipoproteins are not adequately cleared.'
    ),
    (
      'online-breit-biochemie-04',
      'Biochemie',
      'Welches Enzym katalysiert den geschwindigkeitsbestimmenden Schritt der Cholesterinsynthese?',
      'HMG-CoA-Reduktase',
      '["HMG-CoA-Reduktase","HMG-CoA-Synthase","Acetyl-CoA-Carboxylase","Squalenoxidase"]'::jsonb,
      'Die HMG-CoA-Reduktase reduziert HMG-CoA zu Mevalonat und ist das zentrale Schrittmacherenzym der Cholesterinsynthese.',
      'Which enzyme catalyzes the rate-limiting step of cholesterol synthesis?',
      'HMG-CoA reductase',
      '["HMG-CoA reductase","HMG-CoA synthase","Acetyl-CoA carboxylase","Squalene oxidase"]'::jsonb,
      'HMG-CoA reductase reduces HMG-CoA to mevalonate and is the key rate-limiting enzyme in cholesterol synthesis.'
    ),
    (
      'online-breit-biochemie-05',
      'Biochemie',
      'Welcher Cofaktor des Pyruvatdehydrogenase-Komplexes ist ein Vitamin-B1-Derivat?',
      'Thiaminpyrophosphat',
      '["Thiaminpyrophosphat","Biotin","Tetrahydrofolat","Cobalamin"]'::jsonb,
      'Thiaminpyrophosphat ist die aktive Form von Vitamin B1 und ein essenzieller Cofaktor des Pyruvatdehydrogenase-Komplexes.',
      'Which cofactor of the pyruvate dehydrogenase complex is derived from vitamin B1?',
      'Thiamine pyrophosphate',
      '["Thiamine pyrophosphate","Biotin","Tetrahydrofolate","Cobalamin"]'::jsonb,
      'Thiamine pyrophosphate is the active form of vitamin B1 and an essential cofactor of the pyruvate dehydrogenase complex.'
    ),
    (
      'online-breit-biochemie-06',
      'Biochemie',
      'Welches Transportsystem schleust langkettige Fettsaeuren in die Mitochondrienmatrix?',
      'Carnitin-Shuttle',
      '["Carnitin-Shuttle","Malat-Aspartat-Shuttle","Glycerol-3-Phosphat-Shuttle","Ornithin-Shuttle"]'::jsonb,
      'Langkettige Fettsaeuren benoetigen fuer den Transport in die Mitochondrienmatrix das Carnitin-Shuttle mit CPT-I und CPT-II.',
      'Which transport system shuttles long-chain fatty acids into the mitochondrial matrix?',
      'Carnitine shuttle',
      '["Carnitine shuttle","Malate-aspartate shuttle","Glycerol-3-phosphate shuttle","Ornithine shuttle"]'::jsonb,
      'Long-chain fatty acids require the carnitine shuttle, including CPT-I and CPT-II, to enter the mitochondrial matrix.'
    ),
    (
      'online-breit-biochemie-07',
      'Biochemie',
      'Welcher Enzymdefekt verursacht die klassische Galaktosaemie?',
      'Galaktose-1-phosphat-Uridyltransferase-Mangel',
      '["Galaktose-1-phosphat-Uridyltransferase-Mangel","Galaktokinase-Mangel","Laktase-Mangel","Aldolase-B-Mangel"]'::jsonb,
      'Die klassische Galaktosaemie entsteht durch einen Mangel der Galaktose-1-phosphat-Uridyltransferase. Dadurch akkumulieren toxische Galaktosemetabolite.',
      'Which enzyme defect causes classic galactosemia?',
      'Galactose-1-phosphate uridyltransferase deficiency',
      '["Galactose-1-phosphate uridyltransferase deficiency","Galactokinase deficiency","Lactase deficiency","Aldolase B deficiency"]'::jsonb,
      'Classic galactosemia is caused by deficiency of galactose-1-phosphate uridyltransferase. Toxic galactose metabolites accumulate as a result.'
    ),
    (
      'online-breit-biochemie-08',
      'Biochemie',
      'Welches Folat-Derivat spendet direkt Ein-Kohlenstoff-Gruppen fuer die Purinsynthese?',
      'N10-Formyl-THF',
      '["N10-Formyl-THF","N5-Methyl-THF","Biopterin","Pyridoxalphosphat"]'::jsonb,
      'N10-Formyl-THF liefert die Formylgruppen fuer zwei Schritte der de-novo-Purinsynthese. Deshalb ist Folatmangel auch fuer die Nukleotidbildung relevant.',
      'Which folate derivative directly donates one-carbon units for purine synthesis?',
      'N10-formyl-THF',
      '["N10-formyl-THF","N5-methyl-THF","Biopterin","Pyridoxal phosphate"]'::jsonb,
      'N10-formyl-THF donates formyl groups in two steps of de novo purine synthesis. That is why folate deficiency affects nucleotide production.'
    ),
    (
      'online-breit-biochemie-09',
      'Biochemie',
      'Welcher Metabolit aktiviert die Phosphofructokinase-1 in der Leber besonders stark?',
      'Fructose-2,6-Bisphosphat',
      '["Fructose-2,6-Bisphosphat","Citrat","ATP","Acetyl-CoA"]'::jsonb,
      'Fructose-2,6-Bisphosphat ist ein starker allosterischer Aktivator der hepatischen Phosphofructokinase-1 und foerdert damit die Glykolyse.',
      'Which metabolite strongly activates phosphofructokinase-1 in the liver?',
      'Fructose-2,6-bisphosphate',
      '["Fructose-2,6-bisphosphate","Citrate","ATP","Acetyl-CoA"]'::jsonb,
      'Fructose-2,6-bisphosphate is a potent allosteric activator of hepatic phosphofructokinase-1 and therefore promotes glycolysis.'
    ),
    (
      'online-breit-biochemie-10',
      'Biochemie',
      'Welches Enzym reduziert Ribonukleotide zu Desoxyribonukleotiden?',
      'Ribonukleotid-Reduktase',
      '["Ribonukleotid-Reduktase","DNA-Polymerase","Thymidylat-Synthase","Primase"]'::jsonb,
      'Die Ribonukleotid-Reduktase erzeugt aus Ribonukleotiden die Desoxyribonukleotide, die fuer die DNA-Synthese benoetigt werden.',
      'Which enzyme reduces ribonucleotides to deoxyribonucleotides?',
      'Ribonucleotide reductase',
      '["Ribonucleotide reductase","DNA polymerase","Thymidylate synthase","Primase"]'::jsonb,
      'Ribonucleotide reductase generates the deoxyribonucleotides required for DNA synthesis from ribonucleotides.'
    ),
    (
      'online-breit-genetik-01',
      'Genetik',
      'Welche Repeat-Expansion ist fuer die myotone Dystrophie Typ 1 typisch?',
      'CTG',
      '["CTG","CGG","CAG","GAA"]'::jsonb,
      'Die myotone Dystrophie Typ 1 wird durch eine CTG-Repeat-Expansion im DMPK-Gen verursacht.',
      'Which repeat expansion is typical of myotonic dystrophy type 1?',
      'CTG',
      '["CTG","CGG","CAG","GAA"]'::jsonb,
      'Myotonic dystrophy type 1 is caused by a CTG repeat expansion in the DMPK gene.'
    ),
    (
      'online-breit-genetik-02',
      'Genetik',
      'Welche Repeat-Expansion ist fuer die Friedreich-Ataxie klassisch?',
      'GAA',
      '["GAA","CTG","CGG","CAG"]'::jsonb,
      'Die Friedreich-Ataxie beruht klassisch auf einer GAA-Repeat-Expansion im FXN-Gen.',
      'Which repeat expansion is classically associated with Friedreich ataxia?',
      'GAA',
      '["GAA","CTG","CGG","CAG"]'::jsonb,
      'Friedreich ataxia is classically caused by a GAA repeat expansion in the FXN gene.'
    ),
    (
      'online-breit-genetik-03',
      'Genetik',
      'Welches Gen ist bei zystischer Fibrose klassisch mutiert?',
      'CFTR',
      '["CFTR","FBN1","HBB","DMD"]'::jsonb,
      'Die zystische Fibrose wird durch Mutationen im CFTR-Gen verursacht, das fuer einen Chloridkanal kodiert.',
      'Which gene is classically mutated in cystic fibrosis?',
      'CFTR',
      '["CFTR","FBN1","HBB","DMD"]'::jsonb,
      'Cystic fibrosis is caused by mutations in the CFTR gene, which encodes a chloride channel.'
    ),
    (
      'online-breit-genetik-04',
      'Genetik',
      'Welcher Erbgang ist fuer das Marfan-Syndrom typisch?',
      'Autosomal-dominant',
      '["Autosomal-dominant","Autosomal-rezessiv","X-chromosomal-rezessiv","Mitochondrial"]'::jsonb,
      'Das Marfan-Syndrom wird klassisch autosomal-dominant vererbt, meist durch Mutationen in FBN1.',
      'Which inheritance pattern is typical of Marfan syndrome?',
      'Autosomal dominant',
      '["Autosomal dominant","Autosomal recessive","X-linked recessive","Mitochondrial"]'::jsonb,
      'Marfan syndrome is classically inherited in an autosomal dominant pattern, usually due to mutations in FBN1.'
    ),
    (
      'online-breit-genetik-05',
      'Genetik',
      'Welche Erkrankung beruht klassisch auf einer Mutation des beta-Globin-Gens HBB?',
      'Sichelzellkrankheit',
      '["Sichelzellkrankheit","Mukoviszidose","Huntington-Krankheit","Neurofibromatose Typ 1"]'::jsonb,
      'Die Sichelzellkrankheit entsteht durch eine Punktmutation im beta-Globin-Gen HBB, die zu HbS fuehrt.',
      'Which disease is classically caused by a mutation in the beta-globin gene HBB?',
      'Sickle cell disease',
      '["Sickle cell disease","Cystic fibrosis","Huntington disease","Neurofibromatosis type 1"]'::jsonb,
      'Sickle cell disease is caused by a point mutation in the beta-globin gene HBB, producing hemoglobin S.'
    ),
    (
      'online-breit-genetik-06',
      'Genetik',
      'Welche Deletion des Locus 15q11-q13 verursacht klassisch das Prader-Willi-Syndrom?',
      'Paternale Deletion',
      '["Paternale Deletion","Maternal deletion","Mitochondriale Mutation","Trisomie 18"]'::jsonb,
      'Das Prader-Willi-Syndrom entsteht klassisch durch den Verlust der vaeterlichen Genexpression im Bereich 15q11-q13, meist durch paternale Deletion.',
      'Which deletion at locus 15q11-q13 classically causes Prader-Willi syndrome?',
      'Paternal deletion',
      '["Paternal deletion","Maternal deletion","Mitochondrial mutation","Trisomy 18"]'::jsonb,
      'Prader-Willi syndrome classically results from loss of paternal gene expression at 15q11-q13, most often due to a paternal deletion.'
    ),
    (
      'online-breit-genetik-07',
      'Genetik',
      'Welche Deletion desselben Locus 15q11-q13 verursacht klassisch das Angelman-Syndrom?',
      'Maternal deletion',
      '["Maternal deletion","Paternale Deletion","Y-chromosomale Deletion","Triploidie"]'::jsonb,
      'Das Angelman-Syndrom entsteht klassisch durch den Verlust der muetterlichen Genexpression im Bereich 15q11-q13, meist durch maternale Deletion.',
      'Which deletion at the same locus 15q11-q13 classically causes Angelman syndrome?',
      'Maternal deletion',
      '["Maternal deletion","Paternal deletion","Y-chromosome deletion","Triploidy"]'::jsonb,
      'Angelman syndrome classically results from loss of maternal gene expression at 15q11-q13, most often due to a maternal deletion.'
    ),
    (
      'online-breit-genetik-08',
      'Genetik',
      'Welches Tumorsuppressorgen ist beim Li-Fraumeni-Syndrom typischerweise mutiert?',
      'TP53',
      '["TP53","APC","RB1","VHL"]'::jsonb,
      'Das Li-Fraumeni-Syndrom ist klassisch mit Keimbahnmutationen in TP53 assoziiert.',
      'Which tumor suppressor gene is typically mutated in Li-Fraumeni syndrome?',
      'TP53',
      '["TP53","APC","RB1","VHL"]'::jsonb,
      'Li-Fraumeni syndrome is classically associated with germline mutations in TP53.'
    ),
    (
      'online-breit-genetik-09',
      'Genetik',
      'Welcher DNA-Reparaturweg ist beim Xeroderma pigmentosum defekt?',
      'Nukleotidexzisionsreparatur',
      '["Nukleotidexzisionsreparatur","Mismatch-Reparatur","Basenexzisionsreparatur","Nicht-homologes End-Joining"]'::jsonb,
      'Beim Xeroderma pigmentosum ist die Nukleotidexzisionsreparatur gestoert. Dadurch werden UV-induzierte DNA-Schaeden unzureichend repariert.',
      'Which DNA repair pathway is defective in xeroderma pigmentosum?',
      'Nucleotide excision repair',
      '["Nucleotide excision repair","Mismatch repair","Base excision repair","Non-homologous end joining"]'::jsonb,
      'In xeroderma pigmentosum, nucleotide excision repair is defective. UV-induced DNA damage is therefore not repaired adequately.'
    ),
    (
      'online-breit-genetik-10',
      'Genetik',
      'Welches Gen ist beim Neurofibromatose-Typ-1-Syndrom typischerweise mutiert?',
      'NF1',
      '["NF1","NF2","RET","WT1"]'::jsonb,
      'Das Neurofibromatose-Typ-1-Syndrom beruht typischerweise auf Mutationen im NF1-Gen auf Chromosom 17.',
      'Which gene is typically mutated in neurofibromatosis type 1?',
      'NF1',
      '["NF1","NF2","RET","WT1"]'::jsonb,
      'Neurofibromatosis type 1 is typically caused by mutations in the NF1 gene on chromosome 17.'
    )
    ,
    (
      'online-breit-radiologie-01',
      'Radiologie',
      'Welche Bildgebung ist beim haemodynamisch stabilen Erwachsenen mit Verdacht auf Lungenembolie typischerweise Mittel der Wahl?',
      'CT-Pulmonalisangiographie',
      '["CT-Pulmonalisangiographie","Thoraxsonographie","Natives Thorax-CT","MRT des Thorax ohne Kontrastmittel"]'::jsonb,
      'Bei haemodynamisch stabilen Erwachsenen ist die CT-Pulmonalisangiographie die Standardbildgebung zum Nachweis einer Lungenembolie.',
      'Which imaging study is typically the modality of choice in a hemodynamically stable adult with suspected pulmonary embolism?',
      'CT pulmonary angiography',
      '["CT pulmonary angiography","Thoracic ultrasound","Non-contrast chest CT","Chest MRI without contrast"]'::jsonb,
      'In hemodynamically stable adults, CT pulmonary angiography is the standard imaging study used to diagnose pulmonary embolism.'
    ),
    (
      'online-breit-radiologie-02',
      'Radiologie',
      'Welche Form hat ein epidurales Haematom im nativen CT klassisch?',
      'Bikonvexe hyperdense Raumforderung',
      '["Bikonvexe hyperdense Raumforderung","Sichelfoermige extraaxiale Blutung","Ringfoermig kontrastaufnehmende Laesion","Diffus hypodense Marklagerlaesion"]'::jsonb,
      'Ein epidurales Haematom erscheint im nativen CT klassisch linsenfoermig beziehungsweise bikonvex.',
      'What shape does an epidural hematoma classically have on non-contrast CT?',
      'Biconvex hyperdense collection',
      '["Biconvex hyperdense collection","Crescent-shaped extra-axial hemorrhage","Ring-enhancing lesion","Diffuse hypodense white matter lesion"]'::jsonb,
      'On non-contrast CT, an epidural hematoma classically appears lens-shaped or biconvex.'
    ),
    (
      'online-breit-radiologie-03',
      'Radiologie',
      'Welche Form hat ein subdurales Haematom im nativen CT klassisch?',
      'Sichelfoermige extraaxiale Blutung',
      '["Sichelfoermige extraaxiale Blutung","Bikonvexe hyperdense Raumforderung","Rundliche intraventrikulaere Blutung","Diffus verkalkte Massenlaesion"]'::jsonb,
      'Ein subdurales Haematom zeigt sich im nativen CT typischerweise sichelfoermig entlang der Hirnkonvexitaet.',
      'What shape does a subdural hematoma classically have on non-contrast CT?',
      'Crescent-shaped extra-axial hemorrhage',
      '["Crescent-shaped extra-axial hemorrhage","Biconvex hyperdense collection","Rounded intraventricular hemorrhage","Diffuse calcified mass lesion"]'::jsonb,
      'On non-contrast CT, a subdural hematoma typically appears crescent-shaped along the cerebral convexity.'
    ),
    (
      'online-breit-radiologie-04',
      'Radiologie',
      'Welche MRT-Sequenz unterdrueckt freies Liquorsignal und macht periventrikulaere Herde besser sichtbar?',
      'FLAIR',
      '["FLAIR","T1 ohne Kontrast","Gradientenecho","TOF-Angiographie"]'::jsonb,
      'Die FLAIR-Sequenz unterdrueckt freies Liquorsignal. Dadurch werden periventrikulaere Laesionen, etwa bei Demyelinisierung, besser sichtbar.',
      'Which MRI sequence suppresses free cerebrospinal fluid signal and makes periventricular lesions more visible?',
      'FLAIR',
      '["FLAIR","T1 without contrast","Gradient echo","TOF angiography"]'::jsonb,
      'FLAIR suppresses free cerebrospinal fluid signal. This makes periventricular lesions, such as demyelinating plaques, more conspicuous.'
    ),
    (
      'online-breit-radiologie-05',
      'Radiologie',
      'Welche MRT-Sequenz ist am empfindlichsten fuer akute Diffusionsstoerungen beim ischaemischen Schlaganfall?',
      'DWI',
      '["DWI","T1 ohne Kontrast","STIR","MRCP"]'::jsonb,
      'Die Diffusionsbildgebung DWI zeigt akute zytotoxische Oedeme frueh und ist daher besonders sensitiv fuer den frischen ischaemischen Schlaganfall.',
      'Which MRI sequence is most sensitive for acute diffusion abnormalities in ischemic stroke?',
      'DWI',
      '["DWI","T1 without contrast","STIR","MRCP"]'::jsonb,
      'Diffusion-weighted imaging detects acute cytotoxic edema early and is therefore highly sensitive for acute ischemic stroke.'
    ),
    (
      'online-breit-radiologie-06',
      'Radiologie',
      'Welche Bildgebung ist beim Erwachsenen fuer den Nachweis eines Uretersteins am sensitivsten?',
      'Natives CT von Abdomen und Becken',
      '["Natives CT von Abdomen und Becken","Abdomensonographie","MRT des Abdomens","Intravenoeses Urogramm"]'::jsonb,
      'Beim Erwachsenen ist das native CT von Abdomen und Becken die sensitivste Untersuchung zum Nachweis eines Harnleitersteins.',
      'Which imaging study is most sensitive for detecting a ureteral stone in an adult?',
      'Non-contrast CT of the abdomen and pelvis',
      '["Non-contrast CT of the abdomen and pelvis","Abdominal ultrasound","Abdominal MRI","Intravenous urogram"]'::jsonb,
      'In adults, non-contrast CT of the abdomen and pelvis is the most sensitive test for detecting a ureteral stone.'
    ),
    (
      'online-breit-radiologie-07',
      'Radiologie',
      'Welche Bildgebung ist bei Kindern mit Verdacht auf Appendizitis typischerweise die Erstwahl?',
      'Sonographie',
      '["Sonographie","CT mit Kontrastmittel","PET-CT","Mammographie"]'::jsonb,
      'Bei Kindern wird wegen der fehlenden Strahlenbelastung typischerweise zuerst die Sonographie zur Abklaerung einer Appendizitis eingesetzt.',
      'Which imaging study is typically the first choice in children with suspected appendicitis?',
      'Ultrasound',
      '["Ultrasound","Contrast-enhanced CT","PET-CT","Mammography"]'::jsonb,
      'In children, ultrasound is typically used first for suspected appendicitis because it avoids ionizing radiation.'
    ),
    (
      'online-breit-radiologie-08',
      'Radiologie',
      'Welcher Roentgenbefund im Stehen spricht klassisch fuer eine Hohlorganperforation?',
      'Freie Luft subdiafragmal',
      '["Freie Luft subdiafragmal","Diffuse Pleuraerguesse","Mediastinale Verkalkungen","Beidseitige Hilusadenopathie"]'::jsonb,
      'Freie Luft unter dem Zwerchfell in einer stehenden Aufnahme ist ein klassischer Hinweis auf eine Hohlorganperforation.',
      'Which upright radiographic finding classically suggests perforation of a hollow viscus?',
      'Subdiaphragmatic free air',
      '["Subdiaphragmatic free air","Diffuse pleural effusions","Mediastinal calcifications","Bilateral hilar lymphadenopathy"]'::jsonb,
      'Free air beneath the diaphragm on an upright radiograph is a classic sign of perforation of a hollow viscus.'
    ),
    (
      'online-breit-radiologie-09',
      'Radiologie',
      'Welche MR-basierte Untersuchung stellt die Gallenwege nichtinvasiv ohne ionisierende Strahlung dar?',
      'MRCP',
      '["MRCP","ERCP","DSA","DEXA"]'::jsonb,
      'Die MRCP nutzt MRT-Technik zur nichtinvasiven Darstellung der Gallen- und Pankreasgaenge ohne ionisierende Strahlung.',
      'Which MR-based study visualizes the biliary tree noninvasively without ionizing radiation?',
      'MRCP',
      '["MRCP","ERCP","DSA","DEXA"]'::jsonb,
      'MRCP uses MRI technology to visualize the biliary and pancreatic ducts noninvasively without ionizing radiation.'
    ),
    (
      'online-breit-radiologie-10',
      'Radiologie',
      'Welche Bildgebung detektiert Mikroverkalkungen der Brust am besten?',
      'Mammographie',
      '["Mammographie","Brust-MRT ohne Kontrast","Thorax-CT","Brustsonographie"]'::jsonb,
      'Mikroverkalkungen werden am besten in der Mammographie erkannt. Genau deshalb ist sie fuer die Brustkrebsfrueherkennung so wichtig.',
      'Which imaging modality best detects breast microcalcifications?',
      'Mammography',
      '["Mammography","Breast MRI without contrast","Chest CT","Breast ultrasound"]'::jsonb,
      'Microcalcifications are best detected on mammography, which is why it is so important in breast cancer screening.'
    ),
    (
      'online-breit-chirurgie-01',
      'Chirurgie',
      'Welche Struktur wird bei einer Koniotomie inzidiert?',
      'Membrana cricothyroidea',
      '["Membrana cricothyroidea","Ligamentum vocale","Cartilago cricoidea","Epiglottis"]'::jsonb,
      'Bei der Koniotomie wird die Membrana cricothyroidea zwischen Schild- und Ringknorpel eroefnet, um einen Notfallatemweg zu schaffen.',
      'Which structure is incised during a cricothyrotomy?',
      'Cricothyroid membrane',
      '["Cricothyroid membrane","Vocal ligament","Cricoid cartilage","Epiglottis"]'::jsonb,
      'In cricothyrotomy, the cricothyroid membrane between the thyroid and cricoid cartilages is opened to establish an emergency airway.'
    ),
    (
      'online-breit-chirurgie-02',
      'Chirurgie',
      'Welche Leistenhernie hat das hoechste Strangulationsrisiko?',
      'Schenkelhernie',
      '["Schenkelhernie","Direkte Leistenhernie","Indirekte Leistenhernie","Narbenhernie"]'::jsonb,
      'Die Schenkelhernie hat wegen ihres engen Bruchkanals ein besonders hohes Risiko fuer Inkarzeration und Strangulation.',
      'Which groin hernia carries the highest risk of strangulation?',
      'Femoral hernia',
      '["Femoral hernia","Direct inguinal hernia","Indirect inguinal hernia","Incisional hernia"]'::jsonb,
      'Because of its narrow canal, a femoral hernia carries a particularly high risk of incarceration and strangulation.'
    ),
    (
      'online-breit-chirurgie-03',
      'Chirurgie',
      'Welche Massnahme ist die definitive Akuttherapie eines Spannungspneumothorax?',
      'Thoraxdrainage',
      '["Thoraxdrainage","Sauerstoffbrille allein","Antibiotikagabe","Bronchoskopie"]'::jsonb,
      'Die definitive Akuttherapie des Spannungspneumothorax ist die Entlastung ueber eine Thoraxdrainage. Eine Nadelentlastung ist nur die initiale Ueberbrueckung.',
      'What is the definitive acute treatment for tension pneumothorax?',
      'Chest tube thoracostomy',
      '["Chest tube thoracostomy","Nasal oxygen alone","Antibiotic therapy","Bronchoscopy"]'::jsonb,
      'The definitive acute treatment of tension pneumothorax is decompression with a chest tube. Needle decompression is only an initial bridge.'
    ),
    (
      'online-breit-chirurgie-04',
      'Chirurgie',
      'Welche Arterie wird bei einem posterioren Duodenalulkus klassisch arrodiert und kann massiv bluten?',
      'Arteria gastroduodenalis',
      '["Arteria gastroduodenalis","Arteria lienalis","Arteria mesenterica superior","Arteria hepatica communis"]'::jsonb,
      'Posterior gelegene Duodenalulzera koennen die Arteria gastroduodenalis arrodierten und schwere obere GI-Blutungen ausloesen.',
      'Which artery is classically eroded by a posterior duodenal ulcer and can cause massive bleeding?',
      'Gastroduodenal artery',
      '["Gastroduodenal artery","Splenic artery","Superior mesenteric artery","Common hepatic artery"]'::jsonb,
      'Posterior duodenal ulcers can erode the gastroduodenal artery and cause severe upper gastrointestinal bleeding.'
    ),
    (
      'online-breit-chirurgie-05',
      'Chirurgie',
      'Welche Arterie ist bei einem Ulkus an der kleinen Magenkurvatur klassisch gefaehrdet?',
      'Arteria gastrica sinistra',
      '["Arteria gastrica sinistra","Arteria lienalis","Arteria gastroduodenalis","Arteria mesenterica inferior"]'::jsonb,
      'Ulkera an der kleinen Magenkurvatur koennen in die Arteria gastrica sinistra einbrechen und dadurch bluten.',
      'Which artery is classically endangered by an ulcer on the lesser curvature of the stomach?',
      'Left gastric artery',
      '["Left gastric artery","Splenic artery","Gastroduodenal artery","Inferior mesenteric artery"]'::jsonb,
      'Ulcers on the lesser curvature of the stomach can erode into the left gastric artery and cause bleeding.'
    ),
    (
      'online-breit-chirurgie-06',
      'Chirurgie',
      'Welche Operation ist die Standardtherapie bei symptomatischer Cholezystolithiasis mit rezidivierender Gallenkolik?',
      'Laparoskopische Cholezystektomie',
      '["Laparoskopische Cholezystektomie","Hemikolektomie rechts","Nissen-Fundoplikatio","Hartmann-Operation"]'::jsonb,
      'Bei symptomatischen Gallensteinen mit wiederholter Gallenkolik ist die laparoskopische Cholezystektomie die Standardtherapie.',
      'Which operation is the standard treatment for symptomatic cholelithiasis with recurrent biliary colic?',
      'Laparoscopic cholecystectomy',
      '["Laparoscopic cholecystectomy","Right hemicolectomy","Nissen fundoplication","Hartmann procedure"]'::jsonb,
      'For symptomatic gallstones with recurrent biliary colic, laparoscopic cholecystectomy is the standard treatment.'
    ),
    (
      'online-breit-chirurgie-07',
      'Chirurgie',
      'Welche Resektion charakterisiert den Whipple-Eingriff im Kern?',
      'Resektion von Pankreaskopf und Duodenum',
      '["Resektion von Pankreaskopf und Duodenum","Resektion des linken Leberlappens","Totale Gastrektomie","Totale Kolektomie"]'::jsonb,
      'Der Whipple-Eingriff ist die klassische partielle Duodenopankreatektomie mit Entfernung von Pankreaskopf und Duodenum.',
      'Which resection fundamentally characterizes the Whipple procedure?',
      'Resection of the pancreatic head and duodenum',
      '["Resection of the pancreatic head and duodenum","Resection of the left hepatic lobe","Total gastrectomy","Total colectomy"]'::jsonb,
      'The Whipple procedure is the classic pancreaticoduodenectomy with removal of the pancreatic head and duodenum.'
    ),
    (
      'online-breit-chirurgie-08',
      'Chirurgie',
      'Welche Regel wird zur schnellen Abschaetzung der verbrannten Koerperoberflaeche beim Erwachsenen verwendet?',
      'Neunerregel',
      '["Neunerregel","APGAR-Score","Glasgow-Coma-Scale","MELD-Score"]'::jsonb,
      'Zur schnellen Schaetzung der verbrannten Koerperoberflaeche beim Erwachsenen wird klassisch die Neunerregel verwendet.',
      'Which rule is used for rapid estimation of burned body surface area in adults?',
      'Rule of nines',
      '["Rule of nines","APGAR score","Glasgow Coma Scale","MELD score"]'::jsonb,
      'The rule of nines is classically used for rapid estimation of burned body surface area in adults.'
    ),
    (
      'online-breit-chirurgie-09',
      'Chirurgie',
      'Welches Syndrom ist die klassische Indikation zur notfallmaessigen Fasziotomie?',
      'Kompartmentsyndrom',
      '["Kompartmentsyndrom","ARDS","Kurzdarmsyndrom","Dumping-Syndrom"]'::jsonb,
      'Das akute Kompartmentsyndrom bedroht die Gewebedurchblutung und ist eine klassische Indikation zur sofortigen Fasziotomie.',
      'Which syndrome is the classic indication for emergency fasciotomy?',
      'Compartment syndrome',
      '["Compartment syndrome","ARDS","Short bowel syndrome","Dumping syndrome"]'::jsonb,
      'Acute compartment syndrome threatens tissue perfusion and is a classic indication for immediate fasciotomy.'
    ),
    (
      'online-breit-chirurgie-10',
      'Chirurgie',
      'Welche Inzision ist fuer die offene Appendektomie klassisch?',
      'McBurney-Inzision',
      '["McBurney-Inzision","Kocher-Inzision","Pfannenstiel-Inzision","Chevron-Inzision"]'::jsonb,
      'Die offene Appendektomie erfolgt klassisch ueber eine McBurney-Inzision im rechten Unterbauch.',
      'Which incision is classically used for open appendectomy?',
      'McBurney incision',
      '["McBurney incision","Kocher incision","Pfannenstiel incision","Chevron incision"]'::jsonb,
      'Open appendectomy is classically performed through a McBurney incision in the right lower quadrant.'
    )
    ,
    (
      'online-breit-mikrobiologie-01',
      'Mikrobiologie',
      'Welcher Erreger verursacht klassisch die Diphtherie?',
      'Corynebacterium diphtheriae',
      '["Corynebacterium diphtheriae","Corynebacterium jeikeium","Listeria monocytogenes","Bacillus anthracis"]'::jsonb,
      'Die klassische Diphtherie wird durch Corynebacterium diphtheriae verursacht, dessen Toxin Pseudomembranen und systemische Komplikationen ausloesen kann.',
      'Which pathogen classically causes diphtheria?',
      'Corynebacterium diphtheriae',
      '["Corynebacterium diphtheriae","Corynebacterium jeikeium","Listeria monocytogenes","Bacillus anthracis"]'::jsonb,
      'Classic diphtheria is caused by Corynebacterium diphtheriae, whose toxin can produce pseudomembranes and systemic complications.'
    ),
    (
      'online-breit-mikrobiologie-02',
      'Mikrobiologie',
      'Welcher Erreger verursacht eine atypische Pneumonie und besitzt keine Zellwand?',
      'Mycoplasma pneumoniae',
      '["Mycoplasma pneumoniae","Streptococcus pneumoniae","Legionella pneumophila","Klebsiella pneumoniae"]'::jsonb,
      'Mycoplasma pneumoniae besitzt keine Zellwand und ist ein klassischer Erreger der atypischen Pneumonie.',
      'Which pathogen causes atypical pneumonia and lacks a cell wall?',
      'Mycoplasma pneumoniae',
      '["Mycoplasma pneumoniae","Streptococcus pneumoniae","Legionella pneumophila","Klebsiella pneumoniae"]'::jsonb,
      'Mycoplasma pneumoniae lacks a cell wall and is a classic cause of atypical pneumonia.'
    ),
    (
      'online-breit-mikrobiologie-03',
      'Mikrobiologie',
      'Welcher Erreger ist klassisch fuer Gasbrand mit Myonekrose verantwortlich?',
      'Clostridium perfringens',
      '["Clostridium perfringens","Clostridioides difficile","Clostridium tetani","Bacteroides fragilis"]'::jsonb,
      'Clostridium perfringens produziert ein Alpha-Toxin und ist der klassische Erreger des Gasbrandes mit Myonekrose.',
      'Which pathogen is classically responsible for gas gangrene with myonecrosis?',
      'Clostridium perfringens',
      '["Clostridium perfringens","Clostridioides difficile","Clostridium tetani","Bacteroides fragilis"]'::jsonb,
      'Clostridium perfringens produces alpha toxin and is the classic cause of gas gangrene with myonecrosis.'
    ),
    (
      'online-breit-mikrobiologie-04',
      'Mikrobiologie',
      'Welcher Erreger verursacht die Katzenkratzkrankheit?',
      'Bartonella henselae',
      '["Bartonella henselae","Pasteurella multocida","Borrelia burgdorferi","Toxoplasma gondii"]'::jsonb,
      'Die Katzenkratzkrankheit wird klassisch durch Bartonella henselae verursacht.',
      'Which pathogen causes cat scratch disease?',
      'Bartonella henselae',
      '["Bartonella henselae","Pasteurella multocida","Borrelia burgdorferi","Toxoplasma gondii"]'::jsonb,
      'Cat scratch disease is classically caused by Bartonella henselae.'
    ),
    (
      'online-breit-mikrobiologie-05',
      'Mikrobiologie',
      'Welches Virus verursacht klassisch die infektioese Mononukleose?',
      'Epstein-Barr-Virus',
      '["Epstein-Barr-Virus","Cytomegalievirus","Parvovirus B19","Adenovirus"]'::jsonb,
      'Das Epstein-Barr-Virus ist der klassische Ausloeser der infektioesen Mononukleose.',
      'Which virus classically causes infectious mononucleosis?',
      'Epstein-Barr virus',
      '["Epstein-Barr virus","Cytomegalovirus","Parvovirus B19","Adenovirus"]'::jsonb,
      'Epstein-Barr virus is the classic cause of infectious mononucleosis.'
    ),
    (
      'online-breit-mikrobiologie-06',
      'Mikrobiologie',
      'Welches Virus kann bei Patienten mit chronischer Haemolyse eine aplastische Krise ausloesen?',
      'Parvovirus B19',
      '["Parvovirus B19","Respiratory-Syncytial-Virus","Mumpsvirus","Rotavirus"]'::jsonb,
      'Parvovirus B19 infiziert erythroide Vorlaeuferzellen und kann bei chronischer Haemolyse eine aplastische Krise ausloesen.',
      'Which virus can trigger an aplastic crisis in patients with chronic hemolysis?',
      'Parvovirus B19',
      '["Parvovirus B19","Respiratory syncytial virus","Mumps virus","Rotavirus"]'::jsonb,
      'Parvovirus B19 infects erythroid precursor cells and can trigger aplastic crisis in patients with chronic hemolysis.'
    ),
    (
      'online-breit-mikrobiologie-07',
      'Mikrobiologie',
      'Welche Plasmodium-Art ist am ehesten mit zerebraler Malaria assoziiert?',
      'Plasmodium falciparum',
      '["Plasmodium falciparum","Plasmodium vivax","Plasmodium ovale","Plasmodium malariae"]'::jsonb,
      'Die zerebrale Malaria ist klassisch mit Plasmodium falciparum assoziiert, der schwersten Form der Malaria tropica.',
      'Which Plasmodium species is most strongly associated with cerebral malaria?',
      'Plasmodium falciparum',
      '["Plasmodium falciparum","Plasmodium vivax","Plasmodium ovale","Plasmodium malariae"]'::jsonb,
      'Cerebral malaria is classically associated with Plasmodium falciparum, the most severe form of malaria.'
    ),
    (
      'online-breit-mikrobiologie-08',
      'Mikrobiologie',
      'Welcher Pilz verursacht bei AIDS-Patienten klassisch eine Meningitis nach Inhalation aus Taubenkot?',
      'Cryptococcus neoformans',
      '["Cryptococcus neoformans","Candida albicans","Aspergillus fumigatus","Sporothrix schenckii"]'::jsonb,
      'Cryptococcus neoformans ist ein bekapselter Hefepilz, der besonders bei AIDS-Patienten eine Meningitis verursachen kann.',
      'Which fungus classically causes meningitis in patients with AIDS after inhalation from pigeon droppings?',
      'Cryptococcus neoformans',
      '["Cryptococcus neoformans","Candida albicans","Aspergillus fumigatus","Sporothrix schenckii"]'::jsonb,
      'Cryptococcus neoformans is an encapsulated yeast that can cause meningitis, especially in patients with AIDS.'
    ),
    (
      'online-breit-mikrobiologie-09',
      'Mikrobiologie',
      'Welcher dimorphe Pilz ist mit Fledermauskot in Ohio- und Mississippi-Tal assoziiert?',
      'Histoplasma capsulatum',
      '["Histoplasma capsulatum","Blastomyces dermatitidis","Coccidioides immitis","Candida glabrata"]'::jsonb,
      'Histoplasma capsulatum ist ein dimorpher Pilz, der klassisch mit Fledermaus- und Vogelkot in den betroffenen US-Regionen assoziiert ist.',
      'Which dimorphic fungus is associated with bat droppings in the Ohio and Mississippi River valleys?',
      'Histoplasma capsulatum',
      '["Histoplasma capsulatum","Blastomyces dermatitidis","Coccidioides immitis","Candida glabrata"]'::jsonb,
      'Histoplasma capsulatum is a dimorphic fungus classically associated with bat and bird droppings in those U.S. regions.'
    ),
    (
      'online-breit-mikrobiologie-10',
      'Mikrobiologie',
      'Welcher Parasit wird mit dem Klebestreifentest perianal nachgewiesen?',
      'Enterobius vermicularis',
      '["Enterobius vermicularis","Ascaris lumbricoides","Taenia saginata","Trichinella spiralis"]'::jsonb,
      'Der perianale Klebestreifentest dient klassisch dem Nachweis von Enterobius vermicularis.',
      'Which parasite is detected by the perianal tape test?',
      'Enterobius vermicularis',
      '["Enterobius vermicularis","Ascaris lumbricoides","Taenia saginata","Trichinella spiralis"]'::jsonb,
      'The perianal tape test is classically used to detect Enterobius vermicularis.'
    ),
    (
      'online-breit-pathologie-01',
      'Pathologie',
      'Welche Nekroseform ist fuer einen ischaemischen Hirninfarkt typisch?',
      'Kolliquationsnekrose',
      '["Kolliquationsnekrose","Verkaesende Nekrose","Koagulationsnekrose","Fibrinoide Nekrose"]'::jsonb,
      'Im Gehirn fuehrt ein ischaemischer Infarkt typischerweise zu einer Kolliquationsnekrose und nicht zu einer Koagulationsnekrose.',
      'Which type of necrosis is typical of an ischemic cerebral infarction?',
      'Liquefactive necrosis',
      '["Liquefactive necrosis","Caseous necrosis","Coagulative necrosis","Fibrinoid necrosis"]'::jsonb,
      'In the brain, ischemic infarction typically results in liquefactive necrosis rather than coagulative necrosis.'
    ),
    (
      'online-breit-pathologie-02',
      'Pathologie',
      'Welche Nekroseform ist fuer die Tuberkulose klassisch?',
      'Verkaesende Nekrose',
      '["Verkaesende Nekrose","Kolliquationsnekrose","Fettgewebsnekrose","Fibrinoide Nekrose"]'::jsonb,
      'Granulome bei Tuberkulose zeigen klassisch eine verkaesende Nekrose im Zentrum.',
      'Which type of necrosis is classically associated with tuberculosis?',
      'Caseous necrosis',
      '["Caseous necrosis","Liquefactive necrosis","Fat necrosis","Fibrinoid necrosis"]'::jsonb,
      'Tuberculous granulomas classically show central caseous necrosis.'
    ),
    (
      'online-breit-pathologie-03',
      'Pathologie',
      'Welcher ultrastrukturelle Befund ist typisch fuer die Minimal-Change-Nephropathie?',
      'Verschmelzung der Podozytenfussfortsaetze',
      '["Verschmelzung der Podozytenfussfortsaetze","Subepitheliale Spikes","Mesangiale Amyloidplaques","Lineare IgG-Baender"]'::jsonb,
      'Die Minimal-Change-Nephropathie zeigt im Elektronenmikroskop typisch eine diffuse Verschmelzung der Podozytenfussfortsaetze.',
      'Which ultrastructural finding is typical of minimal change disease?',
      'Effacement of podocyte foot processes',
      '["Effacement of podocyte foot processes","Subepithelial spikes","Mesangial amyloid plaques","Linear IgG bands"]'::jsonb,
      'Minimal change disease characteristically shows diffuse effacement of podocyte foot processes on electron microscopy.'
    ),
    (
      'online-breit-pathologie-04',
      'Pathologie',
      'Welcher Ablagerungstyp ist fuer die membranoese Nephropathie charakteristisch?',
      'Subepitheliale Immunkomplexablagerungen',
      '["Subepitheliale Immunkomplexablagerungen","Subendotheliale Immunkomplexablagerungen","Intratubulaere Kalziumzylinder","Mesangiale Eisenablagerungen"]'::jsonb,
      'Die membranoese Nephropathie ist durch subepitheliale Immunkomplexablagerungen entlang der glomerulaeren Basalmembran charakterisiert.',
      'Which type of deposit is characteristic of membranous nephropathy?',
      'Subepithelial immune complex deposits',
      '["Subepithelial immune complex deposits","Subendothelial immune complex deposits","Intratubular calcium casts","Mesangial iron deposits"]'::jsonb,
      'Membranous nephropathy is characterized by subepithelial immune complex deposits along the glomerular basement membrane.'
    ),
    (
      'online-breit-pathologie-05',
      'Pathologie',
      'Welche Zelle ist der klassische Diagnosehinweis fuer das klassische Hodgkin-Lymphom?',
      'Reed-Sternberg-Zelle',
      '["Reed-Sternberg-Zelle","Auerstaebchenzelle","Plasmazelle","Mastzelle"]'::jsonb,
      'Die Reed-Sternberg-Zelle ist der klassische morphologische Diagnosehinweis fuer das klassische Hodgkin-Lymphom.',
      'Which cell is the classic diagnostic clue for classical Hodgkin lymphoma?',
      'Reed-Sternberg cell',
      '["Reed-Sternberg cell","Auer rod cell","Plasma cell","Mast cell"]'::jsonb,
      'The Reed-Sternberg cell is the classic morphologic diagnostic clue for classical Hodgkin lymphoma.'
    ),
    (
      'online-breit-pathologie-06',
      'Pathologie',
      'Welcher histologische Koerper ist typisch fuer den Dottersacktumor?',
      'Schiller-Duval-Koerper',
      '["Schiller-Duval-Koerper","Aschoff-Koerper","Psammomkoerper","Mallory-Denk-Koerper"]'::jsonb,
      'Der Dottersacktumor zeigt klassisch Schiller-Duval-Koerper und oft ein erhoehtes AFP.',
      'Which histologic body is typical of a yolk sac tumor?',
      'Schiller-Duval body',
      '["Schiller-Duval body","Aschoff body","Psammoma body","Mallory-Denk body"]'::jsonb,
      'Yolk sac tumors classically show Schiller-Duval bodies and often have elevated AFP.'
    ),
    (
      'online-breit-pathologie-07',
      'Pathologie',
      'Welcher histologische Befund ist typisch fuer das Schwannom?',
      'Verocay-Koerper',
      '["Verocay-Koerper","Russell-Koerper","Councilman-Koerper","Negri-Koerper"]'::jsonb,
      'Schwannome zeigen klassisch Antoni-A-Areale mit Verocay-Koerpern.',
      'Which histologic finding is typical of schwannoma?',
      'Verocay bodies',
      '["Verocay bodies","Russell bodies","Councilman bodies","Negri bodies"]'::jsonb,
      'Schwannomas classically show Antoni A areas with Verocay bodies.'
    ),
    (
      'online-breit-pathologie-08',
      'Pathologie',
      'Welche Granulomform ist fuer die Sarkoidose klassisch?',
      'Nicht verkaesende Granulome',
      '["Nicht verkaesende Granulome","Verkaesende Granulome","Eitrige Granulome","Hyaline Granulome"]'::jsonb,
      'Die Sarkoidose ist klassisch durch nicht verkaesende Granulome charakterisiert.',
      'Which type of granuloma is classically seen in sarcoidosis?',
      'Noncaseating granulomas',
      '["Noncaseating granulomas","Caseating granulomas","Suppurative granulomas","Hyaline granulomas"]'::jsonb,
      'Sarcoidosis is classically characterized by noncaseating granulomas.'
    ),
    (
      'online-breit-pathologie-09',
      'Pathologie',
      'Welche hepatische Veraenderung mit Mallory-Denk-Koerperchen passt typisch zur alkoholischen Hepatitis?',
      'Ballonierung der Hepatozyten',
      '["Ballonierung der Hepatozyten","Vermehrte Kupffer-Zellen ohne Zellschaden","Ausgedehnte Eisenspeicherung ohne Entzuendung","Mukoid degenerierte Gallengaenge"]'::jsonb,
      'Die alkoholische Hepatitis zeigt typischerweise ballonierte Hepatozyten zusammen mit Mallory-Denk-Koerperchen und neutrophiler Entzuendung.',
      'Which hepatic change associated with Mallory-Denk bodies is typical of alcoholic hepatitis?',
      'Ballooning degeneration of hepatocytes',
      '["Ballooning degeneration of hepatocytes","Increased Kupffer cells without cell injury","Extensive iron storage without inflammation","Mucinous degeneration of bile ducts"]'::jsonb,
      'Alcoholic hepatitis typically shows ballooned hepatocytes together with Mallory-Denk bodies and neutrophilic inflammation.'
    ),
    (
      'online-breit-pathologie-10',
      'Pathologie',
      'Welches Amyloidprotein lagert sich in den Plaques des Morbus Alzheimer ab?',
      'Amyloid-beta',
      '["Amyloid-beta","Serumamyloid A","Transthyretin","Beta-2-Mikroglobulin"]'::jsonb,
      'Die neuritischen Plaques des Morbus Alzheimer enthalten vor allem Amyloid-beta-Peptid.',
      'Which amyloid protein is deposited in the plaques of Alzheimer disease?',
      'Amyloid-beta',
      '["Amyloid-beta","Serum amyloid A","Transthyretin","Beta-2 microglobulin"]'::jsonb,
      'Neuritic plaques in Alzheimer disease are composed primarily of amyloid-beta peptide.'
    )
),
upsert_questions as (
  insert into public.questions (
    slug,
    category,
    question,
    correct_answer,
    options,
    explanation
  )
  select
    slug,
    category,
    question_de,
    correct_de,
    options_de,
    explanation_de
  from question_rows
  on conflict (slug) do update
    set category = excluded.category,
        question = excluded.question,
        correct_answer = excluded.correct_answer,
        options = excluded.options,
        explanation = excluded.explanation,
        updated_at = now()
  returning id, slug
)
insert into public.question_translations (
  question_id,
  language,
  question,
  options,
  correct_answer,
  explanation
)
select
  upsert_questions.id,
  'en',
  question_rows.question_en,
  question_rows.options_en,
  question_rows.correct_en,
  question_rows.explanation_en
from upsert_questions
join question_rows
  on question_rows.slug = upsert_questions.slug
on conflict (question_id, language) do update
  set question = excluded.question,
      options = excluded.options,
      correct_answer = excluded.correct_answer,
      explanation = excluded.explanation,
      updated_at = now();
