-- Expand more mid-sized online category pools with another precise bilingual pack.

with question_rows (
  slug,
  category,
  question_de,
  correct_de,
  options_de,
  explanation_de,
  question_en,
  correct_en,
  options_en,
  explanation_en
) as (
  values
    (
      'online-plus-immunologie-01',
      'Immunologie',
      'Welches Immunglobulin passiert unter physiologischen Bedingungen die Plazenta?',
      'IgG',
      '["IgG","IgA","IgM","IgE"]'::jsonb,
      'IgG ist das einzige Immunglobulin, das unter physiologischen Bedingungen aktiv ueber den FcRn-Rezeptor die Plazenta passiert.',
      'Which immunoglobulin crosses the placenta under physiologic conditions?',
      'IgG',
      '["IgG","IgA","IgM","IgE"]'::jsonb,
      'IgG is the only immunoglobulin that actively crosses the placenta under physiologic conditions via the FcRn receptor.'
    ),
    (
      'online-plus-immunologie-02',
      'Immunologie',
      'Welche HLA-Klasse praesentiert endogene Peptide an CD8-positive T-Zellen?',
      'HLA-Klasse I',
      '["HLA-Klasse I","HLA-Klasse II","CD1","Fc-gamma-Rezeptor"]'::jsonb,
      'HLA-Klasse-I-Molekuele praesentieren intrazellulaer entstandene Peptide an CD8-positive zytotoxische T-Zellen.',
      'Which HLA class presents endogenous peptides to CD8-positive T cells?',
      'HLA class I',
      '["HLA class I","HLA class II","CD1","Fc gamma receptor"]'::jsonb,
      'HLA class I molecules present intracellularly derived peptides to CD8-positive cytotoxic T cells.'
    ),
    (
      'online-plus-immunologie-03',
      'Immunologie',
      'Welche Komplementkomponente startet den Membranangriffskomplex direkt?',
      'C5b',
      '["C5b","C3b","C1q","Properdin"]'::jsonb,
      'Nach Spaltung von C5 bindet C5b nacheinander C6 bis C9 und startet damit direkt die Bildung des Membranangriffskomplexes.',
      'Which complement component directly initiates the membrane attack complex?',
      'C5b',
      '["C5b","C3b","C1q","Properdin"]'::jsonb,
      'After C5 is cleaved, C5b sequentially binds C6 through C9 and directly initiates membrane attack complex formation.'
    ),
    (
      'online-plus-immunologie-04',
      'Immunologie',
      'Welches Zytokin ist der zentrale Aktivator und Wachstumsfaktor eosinophiler Granulozyten?',
      'IL-5',
      '["IL-5","IL-2","IL-8","TNF-alpha"]'::jsonb,
      'IL-5 foerdert Differenzierung, Aktivierung und Ueberleben eosinophiler Granulozyten und ist daher zentral bei parasitaeren Infektionen und Allergien.',
      'Which cytokine is the key activator and growth factor for eosinophils?',
      'IL-5',
      '["IL-5","IL-2","IL-8","TNF-alpha"]'::jsonb,
      'IL-5 promotes eosinophil differentiation, activation, and survival and is therefore central in parasitic infection and allergy.'
    ),
    (
      'online-plus-immunologie-05',
      'Immunologie',
      'Welcher hochaffine Rezeptor bindet IgE auf Mastzellen?',
      'Fc-epsilon-RI',
      '["Fc-epsilon-RI","Fc-gamma-RII","CR1","TCR"]'::jsonb,
      'Der hochaffine IgE-Rezeptor Fc-epsilon-RI sitzt auf Mastzellen und Basophilen und vermittelt die Sofortreaktion nach Allergenvernetzung.',
      'Which high-affinity receptor binds IgE on mast cells?',
      'Fc epsilon RI',
      '["Fc epsilon RI","Fc gamma RII","CR1","TCR"]'::jsonb,
      'The high-affinity IgE receptor Fc epsilon RI is expressed on mast cells and basophils and mediates the immediate allergic response after allergen cross-linking.'
    ),
    (
      'online-plus-immunologie-06',
      'Immunologie',
      'Welcher primaire Immundefekt ist klassisch mit fehlendem Thymusschatten im Thoraxbild assoziiert?',
      'DiGeorge-Syndrom',
      '["DiGeorge-Syndrom","Bruton-Agammaglobulinaemie","Chediak-Higashi-Syndrom","Wiskott-Aldrich-Syndrom"]'::jsonb,
      'Beim DiGeorge-Syndrom fuehrt eine gestoerte Entwicklung der dritten und vierten Schlundtasche zu einer thymischen Hypoplasie mit fehlendem Thymusschatten.',
      'Which primary immunodeficiency is classically associated with an absent thymic shadow on chest imaging?',
      'DiGeorge syndrome',
      '["DiGeorge syndrome","Bruton agammaglobulinemia","Chediak-Higashi syndrome","Wiskott-Aldrich syndrome"]'::jsonb,
      'In DiGeorge syndrome, abnormal development of the third and fourth pharyngeal pouches causes thymic hypoplasia and an absent thymic shadow.'
    ),
    (
      'online-plus-immunologie-07',
      'Immunologie',
      'Gegen welche Struktur richten sich die Autoantikoeper beim Goodpasture-Syndrom?',
      'Alpha-3-Kette des Typ-IV-Kollagens',
      '["Alpha-3-Kette des Typ-IV-Kollagens","Desmoglein 3","Acetylcholinrezeptor","Mitochondriale Pyruvatdehydrogenase"]'::jsonb,
      'Beim Goodpasture-Syndrom richten sich Autoantikoeper gegen die Alpha-3-Kette des Typ-IV-Kollagens in der glomerulaeren und alveolaeren Basalmembran.',
      'Against which structure are the autoantibodies directed in Goodpasture syndrome?',
      'Alpha-3 chain of type IV collagen',
      '["Alpha-3 chain of type IV collagen","Desmoglein 3","Acetylcholine receptor","Mitochondrial pyruvate dehydrogenase"]'::jsonb,
      'In Goodpasture syndrome, autoantibodies target the alpha-3 chain of type IV collagen in glomerular and alveolar basement membranes.'
    ),
    (
      'online-plus-immunologie-08',
      'Immunologie',
      'Der Mangel welcher Komplementfaktoren praedisponiert klassisch fuer invasive Neisserieninfektionen?',
      'C5 bis C9',
      '["C5 bis C9","C1-Inhibitor","C3","Faktor B"]'::jsonb,
      'Defekte der terminalen Komplementkaskade von C5 bis C9 stoeren die Bildung des Membranangriffskomplexes und beguenstigen Neisserieninfektionen.',
      'Deficiency of which complement factors classically predisposes to invasive Neisseria infections?',
      'C5 through C9',
      '["C5 through C9","C1 inhibitor","C3","Factor B"]'::jsonb,
      'Defects of the terminal complement cascade from C5 through C9 impair membrane attack complex formation and predispose to Neisseria infection.'
    ),
    (
      'online-plus-immunologie-09',
      'Immunologie',
      'Welches Zytokin treibt die Differenzierung naiver T-Helferzellen in Richtung Th1 besonders an?',
      'IL-12',
      '["IL-12","IL-4","IL-10","TGF-beta"]'::jsonb,
      'IL-12 aus antigenpraesentierenden Zellen foerdert die Th1-Differenzierung und damit eine zellulaere Immunantwort mit IFN-gamma-Produktion.',
      'Which cytokine strongly drives differentiation of naive helper T cells toward the Th1 lineage?',
      'IL-12',
      '["IL-12","IL-4","IL-10","TGF-beta"]'::jsonb,
      'IL-12 released by antigen-presenting cells promotes Th1 differentiation and therefore a cellular immune response with IFN-gamma production.'
    ),
    (
      'online-plus-immunologie-10',
      'Immunologie',
      'Welchem Hypersensitivitaetstyp entspricht die Serumkrankheit?',
      'Typ III',
      '["Typ III","Typ I","Typ II","Typ IV"]'::jsonb,
      'Die Serumkrankheit ist eine Immunkomplexerkrankung und gehoert daher zum Hypersensitivitaetstyp III.',
      'Serum sickness belongs to which hypersensitivity type?',
      'Type III',
      '["Type III","Type I","Type II","Type IV"]'::jsonb,
      'Serum sickness is an immune complex disease and therefore belongs to type III hypersensitivity.'
    ),
    (
      'online-plus-immunologie-11',
      'Immunologie',
      'Der Defekt welchen Molekuels auf T-Zellen verursacht das X-chromosomale Hyper-IgM-Syndrom klassisch?',
      'CD40L',
      '["CD40L","CD3","CD28","CTLA-4"]'::jsonb,
      'Beim X-chromosomalen Hyper-IgM-Syndrom fehlt funktionelles CD40L auf T-Helferzellen, sodass der Isotypwechsel der B-Zellen ausbleibt.',
      'Defect of which molecule on T cells classically causes X-linked hyper-IgM syndrome?',
      'CD40L',
      '["CD40L","CD3","CD28","CTLA-4"]'::jsonb,
      'In X-linked hyper-IgM syndrome, functional CD40L is absent on helper T cells, so B-cell class switching fails.'
    ),
    (
      'online-plus-immunologie-12',
      'Immunologie',
      'Welches Zytokin foerdert den Isotypwechsel zu IgE am staerksten?',
      'IL-4',
      '["IL-4","IL-1","IL-12","IFN-gamma"]'::jsonb,
      'IL-4 aus Th2-Zellen foerdert die Klassenwechselrekombination zu IgE und ist zentral fuer allergische Sofortreaktionen.',
      'Which cytokine most strongly promotes class switching to IgE?',
      'IL-4',
      '["IL-4","IL-1","IL-12","IFN-gamma"]'::jsonb,
      'IL-4 from Th2 cells promotes class-switch recombination to IgE and is central to immediate allergic reactions.'
    ),
    (
      'online-plus-pharmakologie-01',
      'Pharmakologie',
      'Welches Antidot ist Standard bei einer Paracetamol-Ueberdosierung?',
      'N-Acetylcystein',
      '["N-Acetylcystein","Naloxon","Atropin","Protamin"]'::jsonb,
      'N-Acetylcystein regeneriert Glutathion und entgiftet dadurch den toxischen Paracetamol-Metaboliten NAPQI.',
      'Which antidote is standard for acetaminophen overdose?',
      'N-acetylcysteine',
      '["N-acetylcysteine","Naloxone","Atropine","Protamine"]'::jsonb,
      'N-acetylcysteine regenerates glutathione and thereby detoxifies the toxic acetaminophen metabolite NAPQI.'
    ),
    (
      'online-plus-pharmakologie-02',
      'Pharmakologie',
      'Welches Schleifendiuretikum hemmt den Na-K-2Cl-Kotransporter im dicken aufsteigenden Teil der Henle-Schleife?',
      'Furosemid',
      '["Furosemid","Hydrochlorothiazid","Spironolacton","Acetazolamid"]'::jsonb,
      'Furosemid blockiert den Na-K-2Cl-Kotransporter im dicken aufsteigenden Schenkel und wirkt dadurch als Schleifendiuretikum.',
      'Which loop diuretic inhibits the Na-K-2Cl cotransporter in the thick ascending limb of Henle?',
      'Furosemide',
      '["Furosemide","Hydrochlorothiazide","Spironolactone","Acetazolamide"]'::jsonb,
      'Furosemide blocks the Na-K-2Cl cotransporter in the thick ascending limb and therefore acts as a loop diuretic.'
    ),
    (
      'online-plus-pharmakologie-03',
      'Pharmakologie',
      'Durch welchen Mechanismus wirkt unfraktioniertes Heparin antikoagulatorisch hauptsaechlich?',
      'Aktivierung von Antithrombin III',
      '["Aktivierung von Antithrombin III","Direkte Hemmung von Vitamin-K-Epoxid-Reduktase","Aktivierung von Plasmin","Blockade von GPIIb/IIIa"]'::jsonb,
      'Unfraktioniertes Heparin bindet Antithrombin III und beschleunigt so vor allem die Inaktivierung von Thrombin und Faktor Xa.',
      'By which mechanism does unfractionated heparin mainly exert its anticoagulant effect?',
      'Activation of antithrombin III',
      '["Activation of antithrombin III","Direct inhibition of vitamin K epoxide reductase","Activation of plasmin","Blockade of GPIIb/IIIa"]'::jsonb,
      'Unfractionated heparin binds antithrombin III and thereby accelerates inactivation of thrombin and factor Xa.'
    ),
    (
      'online-plus-pharmakologie-04',
      'Pharmakologie',
      'Welche Klasse der Vaughan-Williams-Einteilung blockiert Kaliumkanaele und verlaengert dadurch die Repolarisation?',
      'Klasse III',
      '["Klasse III","Klasse I","Klasse II","Klasse IV"]'::jsonb,
      'Klasse-III-Antiarrhythmika wie Amiodaron blockieren vor allem Kaliumkanaele und verlaengern das Aktionspotenzial.',
      'Which Vaughan Williams class blocks potassium channels and thereby prolongs repolarization?',
      'Class III',
      '["Class III","Class I","Class II","Class IV"]'::jsonb,
      'Class III antiarrhythmics such as amiodarone mainly block potassium channels and prolong the action potential.'
    ),
    (
      'online-plus-pharmakologie-05',
      'Pharmakologie',
      'Welches Antibiotikum ist klassisch mit dem Red-Man-Syndrom assoziiert?',
      'Vancomycin',
      '["Vancomycin","Gentamicin","Doxycyclin","Linezolid"]'::jsonb,
      'Das Red-Man-Syndrom ist eine histaminvermittelte Infusionsreaktion, die klassisch bei zu schneller Vancomycin-Gabe auftritt.',
      'Which antibiotic is classically associated with red man syndrome?',
      'Vancomycin',
      '["Vancomycin","Gentamicin","Doxycycline","Linezolid"]'::jsonb,
      'Red man syndrome is a histamine-mediated infusion reaction that classically occurs when vancomycin is given too rapidly.'
    ),
    (
      'online-plus-pharmakologie-06',
      'Pharmakologie',
      'Welches Opioid ist ein partieller Mu-Agonist und kann bei Abhaengigen einen Entzug ausloesen?',
      'Buprenorphin',
      '["Buprenorphin","Morphin","Fentanyl","Methadon"]'::jsonb,
      'Buprenorphin ist ein partieller Mu-Agonist mit hoher Rezeptoraffinitaet und kann dadurch volle Agonisten vom Rezeptor verdraengen.',
      'Which opioid is a partial mu agonist and can precipitate withdrawal in dependent patients?',
      'Buprenorphine',
      '["Buprenorphine","Morphine","Fentanyl","Methadone"]'::jsonb,
      'Buprenorphine is a partial mu agonist with high receptor affinity and can therefore displace full agonists from the receptor.'
    ),
    (
      'online-plus-pharmakologie-07',
      'Pharmakologie',
      'Welches Antiemetikum wirkt als Dopamin-D2-Antagonist und wird auch prokinetisch bei Gastroparese eingesetzt?',
      'Metoclopramid',
      '["Metoclopramid","Ondansetron","Aprepitant","Dimenhydrinat"]'::jsonb,
      'Metoclopramid blockiert D2-Rezeptoren und steigert die gastrointestinale Motilitaet, weshalb es auch bei Gastroparese eingesetzt wird.',
      'Which antiemetic acts as a dopamine D2 antagonist and is also used as a prokinetic drug in gastroparesis?',
      'Metoclopramide',
      '["Metoclopramide","Ondansetron","Aprepitant","Dimenhydrinate"]'::jsonb,
      'Metoclopramide blocks D2 receptors and increases gastrointestinal motility, which is why it is also used in gastroparesis.'
    ),
    (
      'online-plus-pharmakologie-08',
      'Pharmakologie',
      'Welcher PDE-5-Hemmer hat die laengste Wirkdauer?',
      'Tadalafil',
      '["Tadalafil","Sildenafil","Vardenafil","Avanafil"]'::jsonb,
      'Tadalafil hat von den gaengigen PDE-5-Hemmern die laengste Halbwertszeit und damit die laengste Wirkdauer.',
      'Which PDE-5 inhibitor has the longest duration of action?',
      'Tadalafil',
      '["Tadalafil","Sildenafil","Vardenafil","Avanafil"]'::jsonb,
      'Among commonly used PDE-5 inhibitors, tadalafil has the longest half-life and therefore the longest duration of action.'
    ),
    (
      'online-plus-pharmakologie-09',
      'Pharmakologie',
      'Welches Medikament beendet eine AV-Knoten-Reentry-Tachykardie typischerweise durch kurzzeitige AV-Knoten-Blockade?',
      'Adenosin',
      '["Adenosin","Digoxin","Verapamil","Amiodaron"]'::jsonb,
      'Adenosin verursacht einen sehr kurz anhaltenden AV-Block und ist deshalb Mittel der Wahl zur Akuttherapie vieler supraventrikulaerer Reentry-Tachykardien.',
      'Which drug typically terminates AV nodal reentry tachycardia by causing a brief AV nodal block?',
      'Adenosine',
      '["Adenosine","Digoxin","Verapamil","Amiodarone"]'::jsonb,
      'Adenosine causes a very brief AV block and is therefore the drug of choice for acute treatment of many supraventricular reentry tachycardias.'
    ),
    (
      'online-plus-pharmakologie-10',
      'Pharmakologie',
      'Welcher Beta-Blocker blockiert zusaetzlich Alpha-1-Rezeptoren und ist fuer die Therapie der chronischen Herzinsuffizienz etabliert?',
      'Carvedilol',
      '["Carvedilol","Metoprolol","Atenolol","Esmolol"]'::jsonb,
      'Carvedilol blockiert Beta- und Alpha-1-Rezeptoren und wird unter anderem bei chronischer Herzinsuffizienz eingesetzt.',
      'Which beta blocker additionally blocks alpha-1 receptors and is established in treatment of chronic heart failure?',
      'Carvedilol',
      '["Carvedilol","Metoprolol","Atenolol","Esmolol"]'::jsonb,
      'Carvedilol blocks beta and alpha-1 receptors and is used in chronic heart failure.'
    ),
    (
      'online-plus-pharmakologie-11',
      'Pharmakologie',
      'Welches Antidot antagonisiert Benzodiazepine kompetitiv am GABA-A-Rezeptor?',
      'Flumazenil',
      '["Flumazenil","Naloxon","Biperiden","Physostigmin"]'::jsonb,
      'Flumazenil ist ein kompetitiver Antagonist an der Benzodiazepin-Bindungsstelle des GABA-A-Rezeptors.',
      'Which antidote competitively antagonizes benzodiazepines at the GABA-A receptor?',
      'Flumazenil',
      '["Flumazenil","Naloxone","Biperiden","Physostigmine"]'::jsonb,
      'Flumazenil is a competitive antagonist at the benzodiazepine binding site of the GABA-A receptor.'
    ),
    (
      'online-plus-pharmakologie-12',
      'Pharmakologie',
      'Welches kaliumsparende Diuretikum antagonisiert den Mineralokortikoidrezeptor im Sammelrohr?',
      'Spironolacton',
      '["Spironolacton","Amilorid","Furosemid","Indapamid"]'::jsonb,
      'Spironolacton blockiert den Mineralokortikoidrezeptor im Sammelrohr und wirkt dadurch kaliumsparend.',
      'Which potassium-sparing diuretic antagonizes the mineralocorticoid receptor in the collecting duct?',
      'Spironolactone',
      '["Spironolactone","Amiloride","Furosemide","Indapamide"]'::jsonb,
      'Spironolactone blocks the mineralocorticoid receptor in the collecting duct and therefore acts as a potassium-sparing diuretic.'
    ),
    (
      'online-plus-mikrobiologie-01',
      'Mikrobiologie',
      'Welcher Erreger verursacht klassisch eine pseudomembranoese Kolitis nach Antibiotikatherapie?',
      'Clostridioides difficile',
      '["Clostridioides difficile","Enterococcus faecalis","Bacteroides fragilis","Yersinia enterocolitica"]'::jsonb,
      'Clostridioides difficile produziert Toxine, die nach gestorter Darmflora zu pseudomembranoeser Kolitis fuehren koennen.',
      'Which pathogen classically causes pseudomembranous colitis after antibiotic therapy?',
      'Clostridioides difficile',
      '["Clostridioides difficile","Enterococcus faecalis","Bacteroides fragilis","Yersinia enterocolitica"]'::jsonb,
      'Clostridioides difficile produces toxins that can cause pseudomembranous colitis after the normal gut flora has been disrupted.'
    ),
    (
      'online-plus-mikrobiologie-02',
      'Mikrobiologie',
      'Welches Bakterium produziert das Alpha-Toxin der Gasbrandinfektion klassisch?',
      'Clostridium perfringens',
      '["Clostridium perfringens","Clostridium tetani","Clostridioides difficile","Bacillus cereus"]'::jsonb,
      'Das Alpha-Toxin von Clostridium perfringens ist eine Lecithinase und zentral fuer die Myonekrose beim Gasbrand.',
      'Which bacterium classically produces the alpha toxin of gas gangrene?',
      'Clostridium perfringens',
      '["Clostridium perfringens","Clostridium tetani","Clostridioides difficile","Bacillus cereus"]'::jsonb,
      'The alpha toxin of Clostridium perfringens is a lecithinase and is central to the myonecrosis of gas gangrene.'
    ),
    (
      'online-plus-mikrobiologie-03',
      'Mikrobiologie',
      'Welche Faerbung wird klassisch zum Nachweis saurefester Staebchen eingesetzt?',
      'Ziehl-Neelsen-Faerbung',
      '["Ziehl-Neelsen-Faerbung","Gram-Faerbung","India-Ink-Faerbung","Giemsa-Faerbung"]'::jsonb,
      'Mykobakterien behalten wegen ihrer mykolsaurereichen Zellwand den Farbstoff der Ziehl-Neelsen-Faerbung trotz Saeure-Alkohol-Entfaerbung.',
      'Which stain is classically used to detect acid-fast bacilli?',
      'Ziehl-Neelsen stain',
      '["Ziehl-Neelsen stain","Gram stain","India ink stain","Giemsa stain"]'::jsonb,
      'Because of their mycolic acid-rich cell wall, mycobacteria retain the dye in Ziehl-Neelsen staining despite acid alcohol decolorization.'
    ),
    (
      'online-plus-mikrobiologie-04',
      'Mikrobiologie',
      'Welches Influenzavirus besitzt ein segmentiertes Negativstrang-RNA-Genom und kann Antigenshift zeigen?',
      'Influenza A',
      '["Influenza A","Influenza B","Respiratory syncytial virus","Parainfluenzavirus"]'::jsonb,
      'Influenza A hat ein segmentiertes Negativstrang-RNA-Genom und kann durch Reassortment Antigenshift entwickeln.',
      'Which influenza virus has a segmented negative-sense RNA genome and can undergo antigenic shift?',
      'Influenza A',
      '["Influenza A","Influenza B","Respiratory syncytial virus","Parainfluenza virus"]'::jsonb,
      'Influenza A has a segmented negative-sense RNA genome and can undergo antigenic shift through reassortment.'
    ),
    (
      'online-plus-mikrobiologie-05',
      'Mikrobiologie',
      'Welcher Erreger verursacht bei AIDS klassisch multiple ringfoermig kontrastmittelaufnehmende Hirnlaesionen?',
      'Toxoplasma gondii',
      '["Toxoplasma gondii","Cryptococcus neoformans","JC-Virus","Listeria monocytogenes"]'::jsonb,
      'Reaktiviertes Toxoplasma gondii verursacht bei fortgeschrittener HIV-Infektion haeufig multiple ringfoermige Hirnlaesionen.',
      'Which pathogen classically causes multiple ring-enhancing brain lesions in AIDS?',
      'Toxoplasma gondii',
      '["Toxoplasma gondii","Cryptococcus neoformans","JC virus","Listeria monocytogenes"]'::jsonb,
      'Reactivated Toxoplasma gondii commonly causes multiple ring-enhancing brain lesions in advanced HIV infection.'
    ),
    (
      'online-plus-mikrobiologie-06',
      'Mikrobiologie',
      'Welches oxidasepositive Bakterium ist klassisch mit Ecthyma gangraenosum assoziiert?',
      'Pseudomonas aeruginosa',
      '["Pseudomonas aeruginosa","Escherichia coli","Klebsiella pneumoniae","Proteus mirabilis"]'::jsonb,
      'Ecthyma gangraenosum ist eine typische schwere Hautmanifestation bei Pseudomonas-aeruginosa-Bakteriaemie.',
      'Which oxidase-positive bacterium is classically associated with ecthyma gangrenosum?',
      'Pseudomonas aeruginosa',
      '["Pseudomonas aeruginosa","Escherichia coli","Klebsiella pneumoniae","Proteus mirabilis"]'::jsonb,
      'Ecthyma gangrenosum is a classic severe skin manifestation of Pseudomonas aeruginosa bacteremia.'
    ),
    (
      'online-plus-mikrobiologie-07',
      'Mikrobiologie',
      'Welche bekapselte Hefe wird im Liquor klassisch mit India-Ink sichtbar gemacht?',
      'Cryptococcus neoformans',
      '["Cryptococcus neoformans","Candida albicans","Histoplasma capsulatum","Aspergillus fumigatus"]'::jsonb,
      'Cryptococcus neoformans besitzt eine dicke Polysaccharidkapsel, die in der India-Ink-Praeparation als Aufhellung sichtbar wird.',
      'Which encapsulated yeast is classically visualized in cerebrospinal fluid with India ink?',
      'Cryptococcus neoformans',
      '["Cryptococcus neoformans","Candida albicans","Histoplasma capsulatum","Aspergillus fumigatus"]'::jsonb,
      'Cryptococcus neoformans has a thick polysaccharide capsule that appears as a clearing on India ink preparation.'
    ),
    (
      'online-plus-mikrobiologie-08',
      'Mikrobiologie',
      'Welcher Erreger verursacht eine atypische Pneumonie und ist mit Kaltagglutininen assoziiert?',
      'Mycoplasma pneumoniae',
      '["Mycoplasma pneumoniae","Legionella pneumophila","Streptococcus pneumoniae","Coxiella burnetii"]'::jsonb,
      'Mycoplasma pneumoniae verursacht eine atypische Pneumonie und kann ueber kreuzreagierende IgM-Antikoerper Kaltagglutinine ausloesen.',
      'Which pathogen causes atypical pneumonia and is associated with cold agglutinins?',
      'Mycoplasma pneumoniae',
      '["Mycoplasma pneumoniae","Legionella pneumophila","Streptococcus pneumoniae","Coxiella burnetii"]'::jsonb,
      'Mycoplasma pneumoniae causes atypical pneumonia and can trigger cold agglutinins through cross-reactive IgM antibodies.'
    ),
    (
      'online-plus-mikrobiologie-09',
      'Mikrobiologie',
      'Welcher Erreger besitzt eine Kapsel aus Poly-D-Glutamat?',
      'Bacillus anthracis',
      '["Bacillus anthracis","Streptococcus pneumoniae","Neisseria meningitidis","Haemophilus influenzae"]'::jsonb,
      'Bacillus anthracis ist unter den wichtigen humanpathogenen Bakterien ungewoehnlich, weil seine Kapsel aus Poly-D-Glutamat besteht.',
      'Which pathogen has a capsule made of poly-D-glutamate?',
      'Bacillus anthracis',
      '["Bacillus anthracis","Streptococcus pneumoniae","Neisseria meningitidis","Haemophilus influenzae"]'::jsonb,
      'Bacillus anthracis is unusual among major human pathogens because its capsule is made of poly-D-glutamate.'
    ),
    (
      'online-plus-mikrobiologie-10',
      'Mikrobiologie',
      'Welches Virus verbleibt latent im Ganglion trigeminale und verursacht rezidivierenden Herpes labialis?',
      'HSV-1',
      '["HSV-1","EBV","CMV","Varizella-Zoster-Virus"]'::jsonb,
      'HSV-1 persistiert latent in sensiblen Ganglien, besonders im Ganglion trigeminale, und reaktiviert als Herpes labialis.',
      'Which virus remains latent in the trigeminal ganglion and causes recurrent herpes labialis?',
      'HSV-1',
      '["HSV-1","EBV","CMV","Varicella-zoster virus"]'::jsonb,
      'HSV-1 persists latently in sensory ganglia, especially the trigeminal ganglion, and reactivates as herpes labialis.'
    ),
    (
      'online-plus-mikrobiologie-11',
      'Mikrobiologie',
      'Welcher Erreger verursacht den schmerzlosen harten Primaeraffekt der Syphilis?',
      'Treponema pallidum',
      '["Treponema pallidum","Haemophilus ducreyi","Klebsiella granulomatis","Chlamydia trachomatis L1-L3"]'::jsonb,
      'Der Primaeraffekt der Syphilis ist typischerweise ein schmerzloses Ulkus und wird durch Treponema pallidum verursacht.',
      'Which pathogen causes the painless hard chancre of syphilis?',
      'Treponema pallidum',
      '["Treponema pallidum","Haemophilus ducreyi","Klebsiella granulomatis","Chlamydia trachomatis L1-L3"]'::jsonb,
      'The primary chancre of syphilis is classically a painless ulcer and is caused by Treponema pallidum.'
    ),
    (
      'online-plus-mikrobiologie-12',
      'Mikrobiologie',
      'Welches Bakterium wird mit dem Harnstoff-Atemtest bei peptischer Ulkuskrankheit nachgewiesen?',
      'Helicobacter pylori',
      '["Helicobacter pylori","Campylobacter jejuni","Vibrio cholerae","Salmonella Typhi"]'::jsonb,
      'Helicobacter pylori besitzt eine starke Ureaseaktivitaet und kann deshalb mit dem Harnstoff-Atemtest nachgewiesen werden.',
      'Which bacterium is detected by the urea breath test in peptic ulcer disease?',
      'Helicobacter pylori',
      '["Helicobacter pylori","Campylobacter jejuni","Vibrio cholerae","Salmonella Typhi"]'::jsonb,
      'Helicobacter pylori has strong urease activity and can therefore be detected by the urea breath test.'
    ),
    (
      'online-plus-biochemie-01',
      'Biochemie',
      'Welches Enzym reduziert Ribonukleotide zu Desoxyribonukleotiden?',
      'Ribonukleotid-Reduktase',
      '["Ribonukleotid-Reduktase","DNA-Polymerase","Thymidylat-Synthase","Adenylat-Kinase"]'::jsonb,
      'Die Ribonukleotid-Reduktase liefert die Desoxyribonukleotide fuer die DNA-Synthese, indem sie den 2-Prime-Hydroxylrest reduziert.',
      'Which enzyme reduces ribonucleotides to deoxyribonucleotides?',
      'Ribonucleotide reductase',
      '["Ribonucleotide reductase","DNA polymerase","Thymidylate synthase","Adenylate kinase"]'::jsonb,
      'Ribonucleotide reductase supplies deoxyribonucleotides for DNA synthesis by reducing the 2-prime hydroxyl group.'
    ),
    (
      'online-plus-biochemie-02',
      'Biochemie',
      'Welche Aminosaeure ist Vorstufe sowohl fuer Katecholamine als auch fuer Melanin?',
      'Tyrosin',
      '["Tyrosin","Tryptophan","Phenylalanin","Histidin"]'::jsonb,
      'Tyrosin dient als Ausgangssubstanz fuer Dopamin, Noradrenalin und Adrenalin sowie fuer die Melaninsynthese.',
      'Which amino acid is a precursor for both catecholamines and melanin?',
      'Tyrosine',
      '["Tyrosine","Tryptophan","Phenylalanine","Histidine"]'::jsonb,
      'Tyrosine is the starting substrate for dopamine, norepinephrine, and epinephrine as well as for melanin synthesis.'
    ),
    (
      'online-plus-biochemie-03',
      'Biochemie',
      'Welches Enzym remethyliert Homocystein unter Verwendung von Vitamin B12 zu Methionin?',
      'Methionin-Synthase',
      '["Methionin-Synthase","Cystathionin-Beta-Synthase","Methylmalonyl-CoA-Mutase","Serin-Hydroxymethyltransferase"]'::jsonb,
      'Die Methionin-Synthase uebertraegt eine Methylgruppe von N5-Methyl-THF auf Homocystein und benoetigt dabei Vitamin B12.',
      'Which enzyme remethylates homocysteine to methionine using vitamin B12?',
      'Methionine synthase',
      '["Methionine synthase","Cystathionine beta-synthase","Methylmalonyl-CoA mutase","Serine hydroxymethyltransferase"]'::jsonb,
      'Methionine synthase transfers a methyl group from N5-methyl-THF to homocysteine and requires vitamin B12.'
    ),
    (
      'online-plus-biochemie-04',
      'Biochemie',
      'Welcher Enzymmangel der Glykolyse verursacht klassisch eine haemolytische Anaemie durch ATP-Mangel im Erythrozyten?',
      'Pyruvatkinase-Mangel',
      '["Pyruvatkinase-Mangel","Hexokinase-Mangel","Laktatdehydrogenase-Mangel","Aldolase-A-Mangel"]'::jsonb,
      'Erythrozyten sind auf die Glykolyse angewiesen. Ein Pyruvatkinase-Mangel senkt die ATP-Bildung und fuehrt so zu haematologischer Instabilitaet und Haemolyse.',
      'Which glycolytic enzyme deficiency classically causes hemolytic anemia due to ATP depletion in erythrocytes?',
      'Pyruvate kinase deficiency',
      '["Pyruvate kinase deficiency","Hexokinase deficiency","Lactate dehydrogenase deficiency","Aldolase A deficiency"]'::jsonb,
      'Erythrocytes depend on glycolysis. Pyruvate kinase deficiency lowers ATP production and thereby leads to membrane instability and hemolysis.'
    ),
    (
      'online-plus-biochemie-05',
      'Biochemie',
      'Welches Enzym kontrolliert den Transport langkettiger Fettsaeuren in die Mitochondrien zur Beta-Oxidation?',
      'Carnitin-Palmitoyltransferase I',
      '["Carnitin-Palmitoyltransferase I","Acetyl-CoA-Carboxylase","Hormonsensitive Lipase","Acyl-CoA-Dehydrogenase"]'::jsonb,
      'Carnitin-Palmitoyltransferase I sitzt an der aeusseren Mitochondrienmembran und ist der entscheidende Schritt fuer den Import langkettiger Fettsaeuren.',
      'Which enzyme controls transport of long-chain fatty acids into mitochondria for beta oxidation?',
      'Carnitine palmitoyltransferase I',
      '["Carnitine palmitoyltransferase I","Acetyl-CoA carboxylase","Hormone-sensitive lipase","Acyl-CoA dehydrogenase"]'::jsonb,
      'Carnitine palmitoyltransferase I is located on the outer mitochondrial membrane and is the key step for importing long-chain fatty acids.'
    ),
    (
      'online-plus-biochemie-06',
      'Biochemie',
      'Welches Enzym ist geschwindigkeitsbestimmend fuer die Haem-Synthese?',
      'ALA-Synthase',
      '["ALA-Synthase","Porphobilinogen-Desaminase","Ferrochelatase","Uroporphyrinogen-Decarboxylase"]'::jsonb,
      'Die ALA-Synthase katalysiert den ersten und geschwindigkeitsbestimmenden Schritt der Haem-Synthese aus Glycin und Succinyl-CoA.',
      'Which enzyme is rate-limiting for heme synthesis?',
      'ALA synthase',
      '["ALA synthase","Porphobilinogen deaminase","Ferrochelatase","Uroporphyrinogen decarboxylase"]'::jsonb,
      'ALA synthase catalyzes the first and rate-limiting step of heme synthesis from glycine and succinyl-CoA.'
    ),
    (
      'online-plus-biochemie-07',
      'Biochemie',
      'Welches Koenzym liefert Ein-Kohlenstoff-Gruppen fuer die Purin- und Thymidylatsynthese?',
      'Tetrahydrofolat',
      '["Tetrahydrofolat","Biotin","Lipoamid","Pyridoxalphosphat"]'::jsonb,
      'Tetrahydrofolat transportiert Ein-Kohlenstoff-Einheiten in verschiedenen Oxidationsstufen und ist zentral fuer die Nukleotidsynthese.',
      'Which coenzyme donates one-carbon units for purine and thymidylate synthesis?',
      'Tetrahydrofolate',
      '["Tetrahydrofolate","Biotin","Lipoamide","Pyridoxal phosphate"]'::jsonb,
      'Tetrahydrofolate carries one-carbon units in different oxidation states and is central to nucleotide synthesis.'
    ),
    (
      'online-plus-biochemie-08',
      'Biochemie',
      'Welches Enzym des Citratzyklus erzeugt direkt GTP?',
      'Succinyl-CoA-Synthetase',
      '["Succinyl-CoA-Synthetase","Citrat-Synthase","Isocitrat-Dehydrogenase","Malat-Dehydrogenase"]'::jsonb,
      'Die Succinyl-CoA-Synthetase katalysiert eine Substratkettenphosphorylierung und bildet dabei im Citratzyklus direkt GTP.',
      'Which enzyme of the citric acid cycle directly generates GTP?',
      'Succinyl-CoA synthetase',
      '["Succinyl-CoA synthetase","Citrate synthase","Isocitrate dehydrogenase","Malate dehydrogenase"]'::jsonb,
      'Succinyl-CoA synthetase catalyzes substrate-level phosphorylation and directly forms GTP in the citric acid cycle.'
    ),
    (
      'online-plus-biochemie-09',
      'Biochemie',
      'Welcher Enzymdefekt verursacht die klassische Galaktosaemie?',
      'Galaktose-1-Phosphat-Uridyltransferase-Mangel',
      '["Galaktose-1-Phosphat-Uridyltransferase-Mangel","Galaktokinase-Mangel","Aldolase-B-Mangel","Pyruvat-Dehydrogenase-Mangel"]'::jsonb,
      'Die klassische Galaktosaemie beruht auf einem Mangel der Galaktose-1-Phosphat-Uridyltransferase mit toxischer Akkumulation von Galaktose-1-phosphat.',
      'Which enzyme defect causes classic galactosemia?',
      'Galactose-1-phosphate uridyltransferase deficiency',
      '["Galactose-1-phosphate uridyltransferase deficiency","Galactokinase deficiency","Aldolase B deficiency","Pyruvate dehydrogenase deficiency"]'::jsonb,
      'Classic galactosemia is caused by galactose-1-phosphate uridyltransferase deficiency with toxic accumulation of galactose-1-phosphate.'
    ),
    (
      'online-plus-biochemie-10',
      'Biochemie',
      'Welcher Vitamin-abhaengige Kofaktor wird vom Branched-Chain-Alpha-Ketosaeure-Dehydrogenase-Komplex benoetigt?',
      'Thiaminpyrophosphat',
      '["Thiaminpyrophosphat","Biotin","Cobalamin","Niacin"]'::jsonb,
      'Der Branched-Chain-Alpha-Ketosaeure-Dehydrogenase-Komplex benoetigt wie andere Alpha-Ketosaeure-Dehydrogenasen Thiaminpyrophosphat.',
      'Which vitamin-dependent cofactor is required by the branched-chain alpha-ketoacid dehydrogenase complex?',
      'Thiamine pyrophosphate',
      '["Thiamine pyrophosphate","Biotin","Cobalamin","Niacin"]'::jsonb,
      'Like other alpha-ketoacid dehydrogenases, the branched-chain alpha-ketoacid dehydrogenase complex requires thiamine pyrophosphate.'
    ),
    (
      'online-plus-biochemie-11',
      'Biochemie',
      'Welches Enzym katalysiert in der Glykolyse die Umwandlung von 2-Phosphoglycerat zu Phosphoenolpyruvat?',
      'Enolase',
      '["Enolase","Pyruvatkinase","Phosphoglyceratkinase","Triosephosphat-Isomerase"]'::jsonb,
      'Die Enolase dehydriert 2-Phosphoglycerat zu Phosphoenolpyruvat und erzeugt damit eine energiereiche Zwischenstufe der Glykolyse.',
      'Which enzyme in glycolysis converts 2-phosphoglycerate to phosphoenolpyruvate?',
      'Enolase',
      '["Enolase","Pyruvate kinase","Phosphoglycerate kinase","Triose phosphate isomerase"]'::jsonb,
      'Enolase dehydrates 2-phosphoglycerate to phosphoenolpyruvate, creating a high-energy glycolytic intermediate.'
    ),
    (
      'online-plus-biochemie-12',
      'Biochemie',
      'Welches Enzym des oxidativen Pentosephosphatwegs erzeugt das meiste zytosolische NADPH im Erythrozyten?',
      'Glukose-6-Phosphat-Dehydrogenase',
      '["Glukose-6-Phosphat-Dehydrogenase","6-Phosphofructokinase-1","Pyruvat-Dehydrogenase","Laktat-Dehydrogenase"]'::jsonb,
      'Die Glukose-6-Phosphat-Dehydrogenase ist das Schrittmacherenzym des oxidativen Pentosephosphatwegs und liefert NADPH zum Schutz vor oxidativem Stress.',
      'Which oxidative pentose phosphate pathway enzyme produces most cytosolic NADPH in erythrocytes?',
      'Glucose-6-phosphate dehydrogenase',
      '["Glucose-6-phosphate dehydrogenase","Phosphofructokinase-1","Pyruvate dehydrogenase","Lactate dehydrogenase"]'::jsonb,
      'Glucose-6-phosphate dehydrogenase is the rate-limiting enzyme of the oxidative pentose phosphate pathway and provides NADPH for protection against oxidative stress.'
    ),
    (
      'online-plus-radiologie-01',
      'Radiologie',
      'Wie erscheint ein akutes Epiduralhaematom im nativen kranialen CT typischerweise?',
      'Linsenfoermige hyperdense extraaxiale Blutung',
      '["Linsenfoermige hyperdense extraaxiale Blutung","Sichelfoermige hypodense extraaxiale Blutung","Diffus hypodense intrazerebrale Blutung","Ringfoermig kontrastmittelaufnehmende Laesion"]'::jsonb,
      'Ein akutes Epiduralhaematom ist im CT klassisch bikonvex bis linsenfoermig hyperdens und kreuzt Schaedelnahte nicht.',
      'How does an acute epidural hematoma typically appear on non-contrast head CT?',
      'Lens-shaped hyperdense extra-axial hemorrhage',
      '["Lens-shaped hyperdense extra-axial hemorrhage","Crescent-shaped hypodense extra-axial hemorrhage","Diffuse hypodense intracerebral hemorrhage","Ring-enhancing lesion"]'::jsonb,
      'An acute epidural hematoma is classically biconvex or lens-shaped and hyperdense on CT, and it does not cross suture lines.'
    ),
    (
      'online-plus-radiologie-02',
      'Radiologie',
      'Welcher Befund im aufrechten Thoraxroentgen spricht fuer freie intraperitoneale Luft?',
      'Sichelfoermige Luft unter dem Zwerchfell',
      '["Sichelfoermige Luft unter dem Zwerchfell","Verbreiterter Mediastinalschatten","Wabenmuster beider Lungen","Milchglasverschattung basal"]'::jsonb,
      'Freie intraperitoneale Luft sammelt sich im Stehen subdiafragmal und erscheint dort im Thoraxroentgen als schmale sichelfoermige Aufhellung.',
      'Which upright chest radiograph finding suggests free intraperitoneal air?',
      'Crescent-shaped air beneath the diaphragm',
      '["Crescent-shaped air beneath the diaphragm","Widened mediastinum","Bilateral honeycombing","Basal ground-glass opacity"]'::jsonb,
      'Free intraperitoneal air rises beneath the diaphragm on upright films and appears as a thin crescent-shaped lucency.'
    ),
    (
      'online-plus-radiologie-03',
      'Radiologie',
      'Welche Bildgebung ist First-Line bei Verdacht auf symptomatische Cholezystolithiasis?',
      'Abdomensonographie',
      '["Abdomensonographie","Abdomen-CT mit Kontrastmittel","MRT des Oberbauchs","Natives Abdomenroentgen"]'::jsonb,
      'Die Sonographie ist fuer Gallensteine die primare Bildgebung, weil sie schnell, strahlenfrei und hoch sensitiv fuer cholezystische Konkremente ist.',
      'Which imaging study is first-line for suspected symptomatic cholelithiasis?',
      'Abdominal ultrasound',
      '["Abdominal ultrasound","Contrast-enhanced abdominal CT","Upper abdominal MRI","Plain abdominal radiograph"]'::jsonb,
      'Ultrasound is the primary imaging study for gallstones because it is fast, radiation-free, and highly sensitive for gallbladder stones.'
    ),
    (
      'online-plus-radiologie-04',
      'Radiologie',
      'In welcher MRT-Gewichtung erscheint freie Fluessigkeit typischerweise signalreich?',
      'T2-Gewichtung',
      '["T2-Gewichtung","T1-Gewichtung","In-Phase-Sequenz","Gradienten-Echo ohne T2-Anteil"]'::jsonb,
      'Freie Fluessigkeit zeigt in der T2-Gewichtung ein hohes Signal und erscheint deshalb hell.',
      'On which MRI weighting does free fluid typically appear hyperintense?',
      'T2 weighting',
      '["T2 weighting","T1 weighting","In-phase sequence","Gradient echo without T2 contribution"]'::jsonb,
      'Free fluid has high signal intensity on T2-weighted imaging and therefore appears bright.'
    ),
    (
      'online-plus-radiologie-05',
      'Radiologie',
      'Welche Bildgebung ist bei Verdacht auf akute intrakranielle Blutung initial Standard?',
      'Natives kraniales CT',
      '["Natives kraniales CT","Kontrastmittel-MRT des Schaedels","PET-CT","Digitale Subtraktionsangiographie"]'::jsonb,
      'Das native kraniale CT ist schnell verfuegbar und sehr empfindlich fuer frisches Blut, deshalb ist es initiale Standardbildgebung bei akuter intrakranieller Blutung.',
      'Which imaging study is the initial standard when acute intracranial hemorrhage is suspected?',
      'Non-contrast head CT',
      '["Non-contrast head CT","Contrast-enhanced brain MRI","PET-CT","Digital subtraction angiography"]'::jsonb,
      'Non-contrast head CT is rapidly available and highly sensitive for fresh blood, so it is the initial standard study in acute intracranial hemorrhage.'
    ),
    (
      'online-plus-radiologie-06',
      'Radiologie',
      'Welcher CT-Angiographie-Befund spricht direkt fuer eine Lungenembolie?',
      'Intraluminaler Fuellungsdefekt in einer Pulmonalarterie',
      '["Intraluminaler Fuellungsdefekt in einer Pulmonalarterie","Luftbronchogramm im Unterlappen","Subpleurale Milchglasverschattung","Diffuse Septumverdickung"]'::jsonb,
      'Die CT-Pulmonalisangiographie zeigt eine Lungenembolie direkt als kontrastausgesparten intraluminalen Fuellungsdefekt in einer Pulmonalarterie.',
      'Which CT angiography finding directly indicates pulmonary embolism?',
      'Intraluminal filling defect in a pulmonary artery',
      '["Intraluminal filling defect in a pulmonary artery","Air bronchogram in a lower lobe","Subpleural ground-glass opacity","Diffuse septal thickening"]'::jsonb,
      'CT pulmonary angiography shows pulmonary embolism directly as a contrast-outlined intraluminal filling defect in a pulmonary artery.'
    ),
    (
      'online-plus-radiologie-07',
      'Radiologie',
      'Welches typische Ultraschallartefakt liegt hinter einem kalzifizierten Gallenstein vor?',
      'Dorsaler Schallschatten',
      '["Dorsaler Schallschatten","Posteriores Schallverstaerkung","Kometenschweifartefakt","Spiegelartefakt"]'::jsonb,
      'Ein kalzifizierter Gallenstein reflektiert und absorbiert Ultraschall stark, sodass dahinter ein dorsaler Schallschatten entsteht.',
      'Which typical ultrasound artifact is seen behind a calcified gallstone?',
      'Posterior acoustic shadowing',
      '["Posterior acoustic shadowing","Posterior acoustic enhancement","Comet-tail artifact","Mirror artifact"]'::jsonb,
      'A calcified gallstone strongly reflects and absorbs ultrasound, producing posterior acoustic shadowing.'
    ),
    (
      'online-plus-radiologie-08',
      'Radiologie',
      'Welche Bildgebung ist in den ersten Stunden am empfindlichsten fuer eine fruehe ischaemische Diffusionsstoerung des Gehirns?',
      'Diffusionsgewichtete MRT',
      '["Diffusionsgewichtete MRT","Natives Schaedelroentgen","Konventionelle T1-MRT ohne Diffusion","Ultraschall der Halsweichteile"]'::jsonb,
      'Die diffusionsgewichtete MRT erkennt die zytotoxische Oedembildung bei akutem ischaemischem Schlaganfall bereits sehr frueh.',
      'Which imaging modality is most sensitive in the first hours for an early ischemic diffusion abnormality of the brain?',
      'Diffusion-weighted MRI',
      '["Diffusion-weighted MRI","Plain skull radiograph","Conventional T1 MRI without diffusion","Ultrasound of the neck soft tissues"]'::jsonb,
      'Diffusion-weighted MRI detects cytotoxic edema from acute ischemic stroke very early.'
    ),
    (
      'online-plus-radiologie-09',
      'Radiologie',
      'Welches Roentgenzeichen im Abdomen ist klassisch fuer einen Sigma-Volvulus?',
      'Coffee-bean-Zeichen',
      '["Coffee-bean-Zeichen","Rigler-Zeichen","Thumbprinting","Double-bubble-Zeichen"]'::jsonb,
      'Der dilatierte, verdrehte Sigmaabschnitt erzeugt im Roentgenbild die typische kaffeebohnenartige Konfiguration.',
      'Which abdominal radiographic sign is classic for sigmoid volvulus?',
      'Coffee bean sign',
      '["Coffee bean sign","Rigler sign","Thumbprinting","Double bubble sign"]'::jsonb,
      'The dilated and twisted sigmoid colon creates the classic coffee bean configuration on radiography.'
    ),
    (
      'online-plus-radiologie-10',
      'Radiologie',
      'Wie ist eine Milchglasverschattung im Thorax-CT definiert?',
      'Erhoehte Parenchymdichte bei erhaltener Sichtbarkeit der Gefaesse',
      '["Erhoehte Parenchymdichte bei erhaltener Sichtbarkeit der Gefaesse","Komplette Verschattung mit Ausloeschung aller Gefaesskonturen","Luftgefuellte Zyste mit duennem Rand","Kalzifizierte pleurale Plaque"]'::jsonb,
      'Eine Milchglasverschattung erhoeht die Dichte des Lungenparenchyms, ohne die bronchovaskulaeren Strukturen vollstaendig zu verdecken.',
      'How is ground-glass opacity defined on chest CT?',
      'Increased parenchymal attenuation with preserved visibility of vessels',
      '["Increased parenchymal attenuation with preserved visibility of vessels","Complete opacity with obscuration of all vascular markings","Air-filled cyst with a thin wall","Calcified pleural plaque"]'::jsonb,
      'Ground-glass opacity increases lung attenuation without completely obscuring the bronchovascular structures.'
    ),
    (
      'online-plus-radiologie-11',
      'Radiologie',
      'Welche Herzsilhouette im Thoraxroentgen ist klassisch fuer einen groesseren Perikarderguss?',
      'Wasserflaschenherz',
      '["Wasserflaschenherz","Schneemann-Herz","Stiefelherz","Holzschuhherz"]'::jsonb,
      'Ein groesserer Perikarderguss kann im Roentgenbild zu einer globulaeren, wasserflaschenartigen Herzsilhouette fuehren.',
      'Which cardiac silhouette on chest radiograph is classic for a large pericardial effusion?',
      'Water bottle heart',
      '["Water bottle heart","Snowman heart","Boot-shaped heart","Wooden-shoe heart"]'::jsonb,
      'A large pericardial effusion can produce a globular water-bottle cardiac silhouette on radiography.'
    ),
    (
      'online-plus-radiologie-12',
      'Radiologie',
      'Welche BI-RADS-Kategorie gilt als hochmalignitaetsverdaechtig und erfordert in der Regel eine Biopsie?',
      'BI-RADS 5',
      '["BI-RADS 5","BI-RADS 2","BI-RADS 3","BI-RADS 0"]'::jsonb,
      'BI-RADS 5 beschreibt einen hochgradig malignitaetsverdaechtigen Befund mit sehr hoher Karzinomwahrscheinlichkeit und fuehrt in der Regel zur histologischen Sicherung.',
      'Which BI-RADS category is highly suggestive of malignancy and usually requires biopsy?',
      'BI-RADS 5',
      '["BI-RADS 5","BI-RADS 2","BI-RADS 3","BI-RADS 0"]'::jsonb,
      'BI-RADS 5 describes a finding highly suggestive of malignancy with a very high probability of cancer and usually leads to tissue diagnosis.'
    )
),
upsert_questions as (
  insert into public.questions (
    slug,
    category,
    question,
    correct_answer,
    options,
    explanation
  )
  select
    slug,
    category,
    question_de,
    correct_de,
    options_de,
    explanation_de
  from question_rows
  on conflict (slug) do update
    set category = excluded.category,
        question = excluded.question,
        correct_answer = excluded.correct_answer,
        options = excluded.options,
        explanation = excluded.explanation,
        updated_at = now()
  returning id, slug
)
insert into public.question_translations (
  question_id,
  language,
  question,
  options,
  correct_answer,
  explanation
)
select
  upsert_questions.id,
  'en',
  question_rows.question_en,
  question_rows.options_en,
  question_rows.correct_en,
  question_rows.explanation_en
from upsert_questions
join question_rows
  on question_rows.slug = upsert_questions.slug
on conflict (question_id, language) do update
  set question = excluded.question,
      options = excluded.options,
      correct_answer = excluded.correct_answer,
      explanation = excluded.explanation,
      updated_at = now();
