-- Expand targeted online category pools with another precise bilingual pack.

with question_rows (
  slug,
  category,
  question_de,
  correct_de,
  options_de,
  explanation_de,
  question_en,
  correct_en,
  options_en,
  explanation_en
) as (
  values
    (
      'online-fokus-genetik-01',
      'Genetik',
      'Welches Gen ist bei der klassischen hereditaeren Haemochromatose am haeufigsten mutiert?',
      'HFE',
      '["HFE","CFTR","RB1","FBN1"]'::jsonb,
      'Die klassische hereditaere Haemochromatose ist am haeufigsten mit Mutationen im HFE-Gen, besonders C282Y, assoziiert.',
      'Which gene is most commonly mutated in classic hereditary hemochromatosis?',
      'HFE',
      '["HFE","CFTR","RB1","FBN1"]'::jsonb,
      'Classic hereditary hemochromatosis is most commonly associated with mutations in the HFE gene, especially C282Y.'
    ),
    (
      'online-fokus-genetik-02',
      'Genetik',
      'Welche Nukleotidsequenz ist bei der myotonen Dystrophie Typ 1 expandiert?',
      'CTG',
      '["CTG","CAG","CGG","GAA"]'::jsonb,
      'Die myotone Dystrophie Typ 1 beruht auf einer CTG-Repeat-Expansion im DMPK-Gen.',
      'Which nucleotide repeat is expanded in myotonic dystrophy type 1?',
      'CTG',
      '["CTG","CAG","CGG","GAA"]'::jsonb,
      'Myotonic dystrophy type 1 is caused by a CTG repeat expansion in the DMPK gene.'
    ),
    (
      'online-fokus-genetik-03',
      'Genetik',
      'Welche numerische Chromosomenaberration liegt beim Edwards-Syndrom vor?',
      'Trisomie 18',
      '["Trisomie 18","Trisomie 13","Trisomie 21","Monosomie X"]'::jsonb,
      'Das Edwards-Syndrom entspricht einer Trisomie 18.',
      'Which numeric chromosomal abnormality defines Edwards syndrome?',
      'Trisomy 18',
      '["Trisomy 18","Trisomy 13","Trisomy 21","Monosomy X"]'::jsonb,
      'Edwards syndrome is caused by trisomy 18.'
    ),
    (
      'online-fokus-genetik-04',
      'Genetik',
      'Welcher DNA-Reparaturweg ist beim Xeroderma pigmentosum defekt?',
      'Nukleotidexzisionsreparatur',
      '["Nukleotidexzisionsreparatur","Mismatch-Reparatur","Basenexzisionsreparatur","Nicht-homologe Endverknuepfung"]'::jsonb,
      'Beim Xeroderma pigmentosum ist die Nukleotidexzisionsreparatur defekt, wodurch UV-induzierte Pyrimidindimere nicht ausreichend entfernt werden.',
      'Which DNA repair pathway is defective in xeroderma pigmentosum?',
      'Nucleotide excision repair',
      '["Nucleotide excision repair","Mismatch repair","Base excision repair","Non-homologous end joining"]'::jsonb,
      'Xeroderma pigmentosum is caused by defective nucleotide excision repair, so UV-induced pyrimidine dimers are not adequately removed.'
    ),
    (
      'online-fokus-genetik-05',
      'Genetik',
      'Welches Gen ist bei der Duchenne-Muskeldystrophie betroffen?',
      'DMD',
      '["DMD","SMN1","LMNA","PMP22"]'::jsonb,
      'Die Duchenne-Muskeldystrophie wird durch Mutationen im DMD-Gen mit Ausfall von Dystrophin verursacht.',
      'Which gene is affected in Duchenne muscular dystrophy?',
      'DMD',
      '["DMD","SMN1","LMNA","PMP22"]'::jsonb,
      'Duchenne muscular dystrophy is caused by mutations in the DMD gene, leading to loss of dystrophin.'
    ),
    (
      'online-fokus-genetik-06',
      'Genetik',
      'Welche Mikrodeletion ist klassisch mit dem DiGeorge-Syndrom assoziiert?',
      '22q11.2-Deletion',
      '["22q11.2-Deletion","5p-Deletion","7q11.23-Deletion","17p13-Deletion"]'::jsonb,
      'Das DiGeorge-Syndrom ist klassisch mit einer 22q11.2-Mikrodeletion assoziiert.',
      'Which microdeletion is classically associated with DiGeorge syndrome?',
      '22q11.2 deletion',
      '["22q11.2 deletion","5p deletion","7q11.23 deletion","17p13 deletion"]'::jsonb,
      'DiGeorge syndrome is classically associated with a 22q11.2 microdeletion.'
    ),
    (
      'online-fokus-genetik-07',
      'Genetik',
      'Welches Tumorsuppressorgen ist beim hereditaeren Retinoblastom typischerweise mutiert?',
      'RB1',
      '["RB1","TP53","APC","VHL"]'::jsonb,
      'Das hereditaere Retinoblastom beruht typischerweise auf einer Keimbahnmutation im RB1-Tumorsuppressorgen.',
      'Which tumor suppressor gene is typically mutated in hereditary retinoblastoma?',
      'RB1',
      '["RB1","TP53","APC","VHL"]'::jsonb,
      'Hereditary retinoblastoma is typically caused by a germline mutation in the RB1 tumor suppressor gene.'
    ),
    (
      'online-fokus-genetik-08',
      'Genetik',
      'Welches Gen ist beim Rett-Syndrom typischerweise mutiert?',
      'MECP2',
      '["MECP2","NF1","TSC1","FMR1"]'::jsonb,
      'Das Rett-Syndrom ist meist durch Mutationen im MECP2-Gen verursacht.',
      'Which gene is typically mutated in Rett syndrome?',
      'MECP2',
      '["MECP2","NF1","TSC1","FMR1"]'::jsonb,
      'Rett syndrome is most commonly caused by mutations in the MECP2 gene.'
    ),
    (
      'online-fokus-genetik-09',
      'Genetik',
      'Welches Vererbungsmuster ist fuer mitochondriale Erkrankungen typisch?',
      'Maternale Vererbung',
      '["Maternale Vererbung","Autosomal-dominante Vererbung","X-chromosomal-rezessive Vererbung","Autosomal-rezessive Vererbung"]'::jsonb,
      'Mitochondriale DNA wird praktisch ausschliesslich maternal vererbt.',
      'Which inheritance pattern is typical for mitochondrial disorders?',
      'Maternal inheritance',
      '["Maternal inheritance","Autosomal dominant inheritance","X-linked recessive inheritance","Autosomal recessive inheritance"]'::jsonb,
      'Mitochondrial DNA is transmitted almost exclusively through the maternal line.'
    ),
    (
      'online-fokus-genetik-10',
      'Genetik',
      'Welches Gen ist bei der Mukoviszidose mutiert?',
      'CFTR',
      '["CFTR","COL1A1","FMR1","PTEN"]'::jsonb,
      'Die Mukoviszidose wird durch Mutationen im CFTR-Gen verursacht, am haeufigsten deltaF508.',
      'Which gene is mutated in cystic fibrosis?',
      'CFTR',
      '["CFTR","COL1A1","FMR1","PTEN"]'::jsonb,
      'Cystic fibrosis is caused by mutations in the CFTR gene, most commonly deltaF508.'
    ),
    (
      'online-fokus-chirurgie-01',
      'Chirurgie',
      'Welche Leistenhernie verlaeuft lateral der Vasa epigastrica inferiores?',
      'Indirekte Leistenhernie',
      '["Indirekte Leistenhernie","Direkte Leistenhernie","Schenkelhernie","Nabelhernie"]'::jsonb,
      'Die indirekte Leistenhernie zieht durch den inneren Leistenring und liegt lateral der Vasa epigastrica inferiores.',
      'Which groin hernia passes lateral to the inferior epigastric vessels?',
      'Indirect inguinal hernia',
      '["Indirect inguinal hernia","Direct inguinal hernia","Femoral hernia","Umbilical hernia"]'::jsonb,
      'An indirect inguinal hernia passes through the deep inguinal ring and lies lateral to the inferior epigastric vessels.'
    ),
    (
      'online-fokus-chirurgie-02',
      'Chirurgie',
      'Welches Manoever unterbricht voruebergehend den Zustrom ueber die Portaltrias?',
      'Pringle-Manoever',
      '["Pringle-Manoever","Kocher-Manoever","Valsalva-Manoever","Heimlich-Manoever"]'::jsonb,
      'Beim Pringle-Manoever wird das Ligamentum hepatoduodenale komprimiert und damit der Zufluss ueber die Portaltrias temporaer unterbrochen.',
      'Which maneuver temporarily interrupts inflow through the portal triad?',
      'Pringle maneuver',
      '["Pringle maneuver","Kocher maneuver","Valsalva maneuver","Heimlich maneuver"]'::jsonb,
      'The Pringle maneuver compresses the hepatoduodenal ligament and temporarily interrupts inflow through the portal triad.'
    ),
    (
      'online-fokus-chirurgie-03',
      'Chirurgie',
      'Welche Operation ist die Standardtherapie der Achalasie, wenn eine definitive chirurgische Behandlung gewaehlt wird?',
      'Heller-Myotomie',
      '["Heller-Myotomie","Billroth-II-Resektion","Nissen-Fundoplikatio","Hartmann-Operation"]'::jsonb,
      'Die definitive chirurgische Standardtherapie der Achalasie ist die Heller-Myotomie, haeufig laparoskopisch und mit Antirefluxprozedur kombiniert.',
      'Which operation is the standard treatment for achalasia when definitive surgical therapy is chosen?',
      'Heller myotomy',
      '["Heller myotomy","Billroth II resection","Nissen fundoplication","Hartmann procedure"]'::jsonb,
      'The standard definitive surgical treatment for achalasia is Heller myotomy, often performed laparoscopically and combined with an anti-reflux procedure.'
    ),
    (
      'online-fokus-chirurgie-04',
      'Chirurgie',
      'Welche Rekonstruktion wird nach totaler Gastrektomie standardmaessig angelegt?',
      'Roux-en-Y-Oesophagojejunostomie',
      '["Roux-en-Y-Oesophagojejunostomie","Billroth-I-Gastroduodenostomie","Billroth-II-Gastrojejunostomie","Braun-Anastomose"]'::jsonb,
      'Nach totaler Gastrektomie wird standardmaessig eine Roux-en-Y-Oesophagojejunostomie rekonstruiert.',
      'Which reconstruction is standard after total gastrectomy?',
      'Roux-en-Y esophagojejunostomy',
      '["Roux-en-Y esophagojejunostomy","Billroth I gastroduodenostomy","Billroth II gastrojejunostomy","Braun anastomosis"]'::jsonb,
      'After total gastrectomy, standard reconstruction is a Roux-en-Y esophagojejunostomy.'
    ),
    (
      'online-fokus-chirurgie-05',
      'Chirurgie',
      'Welche Operation ist bei perforierter Sigmadivertikulitis mit kotiger Peritonitis und instabilem Patienten klassisch?',
      'Hartmann-Operation',
      '["Hartmann-Operation","Whipple-Operation","Heller-Myotomie","Lichtenstein-Operation"]'::jsonb,
      'Bei perforierter Sigmadivertikulitis mit kotiger Peritonitis und haeufig instabiler Situation ist die Hartmann-Operation ein klassisches Vorgehen.',
      'Which operation is classically used for perforated sigmoid diverticulitis with feculent peritonitis in an unstable patient?',
      'Hartmann procedure',
      '["Hartmann procedure","Whipple procedure","Heller myotomy","Lichtenstein repair"]'::jsonb,
      'For perforated sigmoid diverticulitis with feculent peritonitis in an unstable patient, the Hartmann procedure is a classic approach.'
    ),
    (
      'online-fokus-chirurgie-06',
      'Chirurgie',
      'Welche Drainage arbeitet mit aktivem Unterdruck?',
      'Redon-Drainage',
      '["Redon-Drainage","Penrose-Drainage","T-Drainage","Easy-Flow-Drainage"]'::jsonb,
      'Die Redon-Drainage ist ein geschlossenes Saugdrainagesystem mit aktivem Unterdruck.',
      'Which drain uses active suction?',
      'Redon drain',
      '["Redon drain","Penrose drain","T-tube drain","Easy Flow drain"]'::jsonb,
      'A Redon drain is a closed suction drainage system that uses active negative pressure.'
    ),
    (
      'online-fokus-chirurgie-07',
      'Chirurgie',
      'Welche Operation ist das Standardverfahren der offenen Netzplastik bei primaerer Leistenhernie?',
      'Lichtenstein-Operation',
      '["Lichtenstein-Operation","Hartmann-Operation","Heller-Myotomie","Roux-en-Y-Gastrektomie"]'::jsonb,
      'Die offene spannungsfreie Netzplastik nach Lichtenstein ist ein Standardverfahren bei primaerer Leistenhernie.',
      'Which operation is the standard open mesh repair for a primary inguinal hernia?',
      'Lichtenstein repair',
      '["Lichtenstein repair","Hartmann procedure","Heller myotomy","Roux-en-Y gastrectomy"]'::jsonb,
      'Open tension-free mesh repair according to Lichtenstein is a standard procedure for primary inguinal hernia.'
    ),
    (
      'online-fokus-chirurgie-08',
      'Chirurgie',
      'Welche definitive Therapie ist Standard bei symptomatischer Cholezystolithiasis?',
      'Laparoskopische Cholezystektomie',
      '["Laparoskopische Cholezystektomie","Appendektomie","Splenektomie","Oesophagektomie"]'::jsonb,
      'Die laparoskopische Cholezystektomie ist die Standardtherapie bei symptomatischer Cholezystolithiasis.',
      'Which definitive treatment is standard for symptomatic cholecystolithiasis?',
      'Laparoscopic cholecystectomy',
      '["Laparoscopic cholecystectomy","Appendectomy","Splenectomy","Esophagectomy"]'::jsonb,
      'Laparoscopic cholecystectomy is the standard treatment for symptomatic gallstone disease.'
    ),
    (
      'online-fokus-chirurgie-09',
      'Chirurgie',
      'Welche Stomaform verbleibt nach abdominoperinealer Rektumexstirpation dauerhaft?',
      'Endstaendige Kolostomie',
      '["Endstaendige Kolostomie","Protektive Ileostomie","Doppellaeufige Jejunostomie","Nephrostomie"]'::jsonb,
      'Nach abdominoperinealer Rektumexstirpation bleibt regelhaft eine endstaendige Kolostomie bestehen.',
      'Which type of stoma remains permanently after abdominoperineal resection of the rectum?',
      'Permanent end colostomy',
      '["Permanent end colostomy","Protective ileostomy","Double-barrel jejunostomy","Nephrostomy"]'::jsonb,
      'After abdominoperineal resection, a permanent end colostomy is the standard stoma outcome.'
    ),
    (
      'online-fokus-chirurgie-10',
      'Chirurgie',
      'Welche Notfalloperation verschliesst ein perforiertes peptisches Ulkus haeufig mit Omentum?',
      'Graham-Patch',
      '["Graham-Patch","Whipple-Operation","Lichtenstein-Operation","Heller-Myotomie"]'::jsonb,
      'Ein perforiertes peptisches Ulkus wird in der Notfallsituation haeufig mit einem Graham-Patch unter Verwendung von Omentum verschlossen.',
      'Which emergency operation commonly closes a perforated peptic ulcer with an omental patch?',
      'Graham patch',
      '["Graham patch","Whipple procedure","Lichtenstein repair","Heller myotomy"]'::jsonb,
      'A perforated peptic ulcer is commonly closed in the emergency setting with a Graham patch using omentum.'
    ),
    (
      'online-fokus-pathologie-01',
      'Pathologie',
      'Welche Zelle ist charakteristisch fuer das klassische Hodgkin-Lymphom?',
      'Reed-Sternberg-Zelle',
      '["Reed-Sternberg-Zelle","Auer-Staebchen","Psammomkoerper","Negri-Koerper"]'::jsonb,
      'Die Reed-Sternberg-Zelle ist die charakteristische Tumorzelle des klassischen Hodgkin-Lymphoms.',
      'Which cell is characteristic of classical Hodgkin lymphoma?',
      'Reed-Sternberg cell',
      '["Reed-Sternberg cell","Auer rod","Psammoma body","Negri body"]'::jsonb,
      'The Reed-Sternberg cell is the characteristic tumor cell of classical Hodgkin lymphoma.'
    ),
    (
      'online-fokus-pathologie-02',
      'Pathologie',
      'Welche histochemische Faerbung weist Amyloid klassisch nach?',
      'Kongorot-Faerbung',
      '["Kongorot-Faerbung","Ziehl-Neelsen-Faerbung","Gram-Faerbung","Masson-Trichrom-Faerbung"]'::jsonb,
      'Amyloid wird klassisch mit Kongorot angefaerbt und zeigt im Polarisationslicht eine apfelgruene Doppelbrechung.',
      'Which histochemical stain classically identifies amyloid?',
      'Congo red stain',
      '["Congo red stain","Ziehl-Neelsen stain","Gram stain","Masson trichrome stain"]'::jsonb,
      'Amyloid is classically stained with Congo red and shows apple-green birefringence under polarized light.'
    ),
    (
      'online-fokus-pathologie-03',
      'Pathologie',
      'Welche Verkalkungsform ist typisch fuer das papillaere Schilddruesenkarzinom?',
      'Psammomkoerper',
      '["Psammomkoerper","Auer-Staebchen","Aschoff-Koerperchen","Verocay-Koerperchen"]'::jsonb,
      'Psammomkoerper sind konzentrisch geschichtete Verkalkungen und typisch fuer das papillaere Schilddruesenkarzinom.',
      'Which calcification pattern is typical of papillary thyroid carcinoma?',
      'Psammoma bodies',
      '["Psammoma bodies","Auer rods","Aschoff bodies","Verocay bodies"]'::jsonb,
      'Psammoma bodies are concentrically laminated calcifications typical of papillary thyroid carcinoma.'
    ),
    (
      'online-fokus-pathologie-04',
      'Pathologie',
      'Welche Nekroseform ist klassisch fuer Tuberkulosegranulome?',
      'Verkaesende Nekrose',
      '["Verkaesende Nekrose","Koagulationsnekrose","Fibrinoide Nekrose","Fettgewebsnekrose"]'::jsonb,
      'Tuberkulosegranulome zeigen klassisch eine zentrale verkaesende Nekrose.',
      'Which type of necrosis is classically seen in tuberculous granulomas?',
      'Caseating necrosis',
      '["Caseating necrosis","Coagulative necrosis","Fibrinoid necrosis","Fat necrosis"]'::jsonb,
      'Tuberculous granulomas classically show central caseating necrosis.'
    ),
    (
      'online-fokus-pathologie-05',
      'Pathologie',
      'Welche nodulaere Laesion ist typisch fuer die diabetische Nephropathie?',
      'Kimmelstiel-Wilson-Knoten',
      '["Kimmelstiel-Wilson-Knoten","Mallory-Denk-Koerper","Aschoff-Koerperchen","Negri-Koerper"]'::jsonb,
      'Die nodulaere Glomerulosklerose mit Kimmelstiel-Wilson-Knoten ist typisch fuer die diabetische Nephropathie.',
      'Which nodular lesion is typical of diabetic nephropathy?',
      'Kimmelstiel-Wilson nodules',
      '["Kimmelstiel-Wilson nodules","Mallory-Denk bodies","Aschoff bodies","Negri bodies"]'::jsonb,
      'Nodular glomerulosclerosis with Kimmelstiel-Wilson nodules is typical of diabetic nephropathy.'
    ),
    (
      'online-fokus-pathologie-06',
      'Pathologie',
      'Welche zytoplasmatischen Einschluesse sind typisch fuer die akute myeloische Leukaemie?',
      'Auer-Staebchen',
      '["Auer-Staebchen","Psammomkoerper","Negri-Koerper","Russell-Koerper"]'::jsonb,
      'Auer-Staebchen sind nadelfoermige azurophile Einschluesse in Myeloblasten und typisch fuer die akute myeloische Leukaemie.',
      'Which cytoplasmic inclusions are typical of acute myeloid leukemia?',
      'Auer rods',
      '["Auer rods","Psammoma bodies","Negri bodies","Russell bodies"]'::jsonb,
      'Auer rods are needle-shaped azurophilic inclusions in myeloblasts and are typical of acute myeloid leukemia.'
    ),
    (
      'online-fokus-pathologie-07',
      'Pathologie',
      'Welche Einschlusskoerper sind klassisch fuer Tollwut?',
      'Negri-Koerper',
      '["Negri-Koerper","Aschoff-Koerperchen","Howell-Jolly-Koerper","Councilman-Koerper"]'::jsonb,
      'Negri-Koerper sind intrazytoplasmatische Einschlusskoerper in Neuronen bei Tollwut.',
      'Which inclusion bodies are classically seen in rabies?',
      'Negri bodies',
      '["Negri bodies","Aschoff bodies","Howell-Jolly bodies","Councilman bodies"]'::jsonb,
      'Negri bodies are intracytoplasmic neuronal inclusion bodies seen in rabies.'
    ),
    (
      'online-fokus-pathologie-08',
      'Pathologie',
      'Welche Kernmorphologie ist typisch fuer das papillaere Schilddruesenkarzinom?',
      'Orphan-Annie-Augen-Kerne',
      '["Orphan-Annie-Augen-Kerne","Auer-Staebchen","Kimmelstiel-Wilson-Knoten","Verocay-Koerperchen"]'::jsonb,
      'Leere, optisch klare Orphan-Annie-Augen-Kerne sind ein klassischer histologischer Befund beim papillaeren Schilddruesenkarzinom.',
      'Which nuclear morphology is typical of papillary thyroid carcinoma?',
      'Orphan Annie eye nuclei',
      '["Orphan Annie eye nuclei","Auer rods","Kimmelstiel-Wilson nodules","Verocay bodies"]'::jsonb,
      'Empty-appearing, optically clear Orphan Annie eye nuclei are a classic histologic finding in papillary thyroid carcinoma.'
    ),
    (
      'online-fokus-pathologie-09',
      'Pathologie',
      'Welche Koerperchen sind typisch fuer das rheumatische Fieber im Myokard?',
      'Aschoff-Koerperchen',
      '["Aschoff-Koerperchen","Mallory-Denk-Koerper","Negri-Koerper","Psammomkoerper"]'::jsonb,
      'Aschoff-Koerperchen sind granulomartige Herde im Myokard und typisch fuer das rheumatische Fieber.',
      'Which bodies are typical of rheumatic fever in the myocardium?',
      'Aschoff bodies',
      '["Aschoff bodies","Mallory-Denk bodies","Negri bodies","Psammoma bodies"]'::jsonb,
      'Aschoff bodies are granulomatous foci in the myocardium and are typical of rheumatic fever.'
    ),
    (
      'online-fokus-pathologie-10',
      'Pathologie',
      'Welche histologische Struktur ist charakteristisch fuer das Schwannom?',
      'Verocay-Koerperchen',
      '["Verocay-Koerperchen","Psammomkoerper","Aschoff-Koerperchen","Negri-Koerper"]'::jsonb,
      'Verocay-Koerperchen entstehen durch palisadenfoermig angeordnete Kerne in Antoni-A-Arealen und sind typisch fuer das Schwannom.',
      'Which histologic structure is characteristic of schwannoma?',
      'Verocay bodies',
      '["Verocay bodies","Psammoma bodies","Aschoff bodies","Negri bodies"]'::jsonb,
      'Verocay bodies result from nuclear palisading in Antoni A areas and are characteristic of schwannoma.'
    ),
    (
      'online-fokus-immunologie-01',
      'Immunologie',
      'Wie lautet die C3-Konvertase des klassischen und des Lektinwegs?',
      'C4b2a',
      '["C4b2a","C3bBb","C5b-9","C1qrs"]'::jsonb,
      'Im klassischen und im Lektinweg spaltet die C3-Konvertase C4b2a das Komplementprotein C3.',
      'What is the C3 convertase of the classical and lectin pathways?',
      'C4b2a',
      '["C4b2a","C3bBb","C5b-9","C1qrs"]'::jsonb,
      'In the classical and lectin pathways, the C3 convertase C4b2a cleaves complement component C3.'
    ),
    (
      'online-fokus-immunologie-02',
      'Immunologie',
      'Welcher Faktor stabilisiert die alternative C3-Konvertase C3bBb?',
      'Properdin',
      '["Properdin","C1-Inhibitor","Faktor I","DAF"]'::jsonb,
      'Properdin stabilisiert die alternative C3-Konvertase C3bBb und verlaengert ihre Aktivitaet.',
      'Which factor stabilizes the alternative pathway C3 convertase C3bBb?',
      'Properdin',
      '["Properdin","C1 inhibitor","Factor I","DAF"]'::jsonb,
      'Properdin stabilizes the alternative pathway C3 convertase C3bBb and prolongs its activity.'
    ),
    (
      'online-fokus-immunologie-03',
      'Immunologie',
      'Welcher Transkriptionsfaktor ist charakteristisch fuer regulatorische T-Zellen?',
      'FOXP3',
      '["FOXP3","GATA3","T-bet","BCL6"]'::jsonb,
      'FOXP3 ist der Schluesseltranskriptionsfaktor regulatorischer T-Zellen.',
      'Which transcription factor is characteristic of regulatory T cells?',
      'FOXP3',
      '["FOXP3","GATA3","T-bet","BCL6"]'::jsonb,
      'FOXP3 is the key transcription factor of regulatory T cells.'
    ),
    (
      'online-fokus-immunologie-04',
      'Immunologie',
      'Welches Enzym ist fuer den Klassenwechsel von Immunglobulinen erforderlich?',
      'AID',
      '["AID","RAG1","BTK","ADA"]'::jsonb,
      'Die activation-induced cytidine deaminase, kurz AID, ist fuer Klassenwechsel und somatische Hypermutation erforderlich.',
      'Which enzyme is required for immunoglobulin class switching?',
      'AID',
      '["AID","RAG1","BTK","ADA"]'::jsonb,
      'Activation-induced cytidine deaminase, or AID, is required for class switching and somatic hypermutation.'
    ),
    (
      'online-fokus-immunologie-05',
      'Immunologie',
      'Welches Zytokin wird typischerweise von Th17-Zellen produziert?',
      'IL-17',
      '["IL-17","IL-4","IL-5","IFN-gamma"]'::jsonb,
      'Th17-Zellen produzieren charakteristisch IL-17 und spielen eine wichtige Rolle bei neutrophilen Entzuendungsreaktionen.',
      'Which cytokine is typically produced by Th17 cells?',
      'IL-17',
      '["IL-17","IL-4","IL-5","IFN-gamma"]'::jsonb,
      'Th17 cells characteristically produce IL-17 and play an important role in neutrophilic inflammatory responses.'
    ),
    (
      'online-fokus-immunologie-06',
      'Immunologie',
      'Welches Adhaesionsmolekuel vermittelt die feste Anheftung von Neutrophilen an das Endothel?',
      'LFA-1',
      '["LFA-1","P-Selektin","E-Selektin","PECAM-1"]'::jsonb,
      'Die feste Adhaesion von Neutrophilen an aktiviertes Endothel wird vor allem durch Integrine wie LFA-1 vermittelt.',
      'Which adhesion molecule mediates firm adhesion of neutrophils to endothelium?',
      'LFA-1',
      '["LFA-1","P-selectin","E-selectin","PECAM-1"]'::jsonb,
      'Firm adhesion of neutrophils to activated endothelium is mediated mainly by integrins such as LFA-1.'
    ),
    (
      'online-fokus-immunologie-07',
      'Immunologie',
      'Welcher Gendefekt verursacht die X-chromosomale Agammaglobulinaemie nach Bruton?',
      'BTK',
      '["BTK","FOXP3","WAS","CYBB"]'::jsonb,
      'Die X-chromosomale Agammaglobulinaemie nach Bruton wird durch Mutationen im BTK-Gen verursacht.',
      'Which gene defect causes X-linked agammaglobulinemia of Bruton?',
      'BTK',
      '["BTK","FOXP3","WAS","CYBB"]'::jsonb,
      'X-linked agammaglobulinemia of Bruton is caused by mutations in the BTK gene.'
    ),
    (
      'online-fokus-immunologie-08',
      'Immunologie',
      'Wodurch wird eine hyperakute Transplantatabstossung typischerweise vermittelt?',
      'Praeformierte Empfaengerantikoerper',
      '["Praeformierte Empfaengerantikoerper","Neu gebildete Treg-Zellen","IL-10-Ueberproduktion","Kompletter HLA-Match"]'::jsonb,
      'Die hyperakute Abstossung wird durch bereits vor der Transplantation vorhandene Antikoerper des Empfaengers gegen Spenderantigene vermittelt.',
      'What typically mediates hyperacute transplant rejection?',
      'Preformed recipient antibodies',
      '["Preformed recipient antibodies","Newly generated regulatory T cells","IL-10 overproduction","Complete HLA match"]'::jsonb,
      'Hyperacute rejection is mediated by antibodies already present in the recipient before transplantation that target donor antigens.'
    ),
    (
      'online-fokus-immunologie-09',
      'Immunologie',
      'Welcher Immundefekt zeigt typischerweise erniedrigtes IgG und haeufig auch erniedrigtes IgA oder IgM im Erwachsenenalter?',
      'CVID',
      '["CVID","SCID","DiGeorge-Syndrom","Bruton-Agammaglobulinaemie"]'::jsonb,
      'Die common variable immunodeficiency, kurz CVID, praesentiert sich typischerweise mit erniedrigtem IgG und haeufig reduziertem IgA oder IgM.',
      'Which immunodeficiency typically shows low IgG and often low IgA or IgM in adulthood?',
      'CVID',
      '["CVID","SCID","DiGeorge syndrome","Bruton agammaglobulinemia"]'::jsonb,
      'Common variable immunodeficiency, or CVID, typically presents with low IgG and often reduced IgA or IgM.'
    ),
    (
      'online-fokus-immunologie-10',
      'Immunologie',
      'Welches Signal aktiviert NK-Zellen im Sinne des missing-self-Konzepts?',
      'Verminderte HLA-Klasse-I-Expression',
      '["Verminderte HLA-Klasse-I-Expression","Erhoehte IgE-Produktion","C3-Mangel","Vermehrte IL-4-Freisetzung"]'::jsonb,
      'NK-Zellen werden aktiviert, wenn Zielzellen zu wenig HLA-Klasse-I exprimieren und dadurch inhibitorische Signale fehlen.',
      'Which signal activates NK cells according to the missing-self concept?',
      'Reduced HLA class I expression',
      '["Reduced HLA class I expression","Increased IgE production","C3 deficiency","Increased IL-4 release"]'::jsonb,
      'NK cells are activated when target cells express too little HLA class I, removing inhibitory signals.'
    ),
    (
      'online-fokus-pharmakologie-01',
      'Pharmakologie',
      'Welches Enzym wird durch Warfarin gehemmt?',
      'Vitamin-K-Epoxid-Reduktase',
      '["Vitamin-K-Epoxid-Reduktase","Xanthinoxidase","Dihydrofolat-Reduktase","Monoaminooxidase"]'::jsonb,
      'Warfarin hemmt die Vitamin-K-Epoxid-Reduktase und reduziert dadurch die Aktivierung der Vitamin-K-abhaengigen Gerinnungsfaktoren.',
      'Which enzyme is inhibited by warfarin?',
      'Vitamin K epoxide reductase',
      '["Vitamin K epoxide reductase","Xanthine oxidase","Dihydrofolate reductase","Monoamine oxidase"]'::jsonb,
      'Warfarin inhibits vitamin K epoxide reductase and thereby reduces activation of vitamin K dependent clotting factors.'
    ),
    (
      'online-fokus-pharmakologie-02',
      'Pharmakologie',
      'Welchen Thrombozytenrezeptor blockiert Clopidogrel irreversibel?',
      'P2Y12-Rezeptor',
      '["P2Y12-Rezeptor","GPIIb/IIIa-Rezeptor","PAR-1-Rezeptor","TXA2-Rezeptor"]'::jsonb,
      'Clopidogrel hemmt den ADP-Rezeptor P2Y12 irreversibel und vermindert dadurch die Thrombozytenaggregation.',
      'Which platelet receptor is irreversibly blocked by clopidogrel?',
      'P2Y12 receptor',
      '["P2Y12 receptor","GPIIb/IIIa receptor","PAR-1 receptor","TXA2 receptor"]'::jsonb,
      'Clopidogrel irreversibly inhibits the ADP receptor P2Y12 and thereby reduces platelet aggregation.'
    ),
    (
      'online-fokus-pharmakologie-03',
      'Pharmakologie',
      'Welches Enzym wird durch Allopurinol gehemmt?',
      'Xanthinoxidase',
      '["Xanthinoxidase","Cyclooxygenase-2","Aldehyddehydrogenase","HMG-CoA-Reduktase"]'::jsonb,
      'Allopurinol hemmt die Xanthinoxidase und senkt dadurch die Harnsaeurebildung.',
      'Which enzyme is inhibited by allopurinol?',
      'Xanthine oxidase',
      '["Xanthine oxidase","Cyclooxygenase-2","Aldehyde dehydrogenase","HMG-CoA reductase"]'::jsonb,
      'Allopurinol inhibits xanthine oxidase and thereby lowers uric acid production.'
    ),
    (
      'online-fokus-pharmakologie-04',
      'Pharmakologie',
      'Welches Enzym hemmt Carbidopa in der Peripherie?',
      'DOPA-Decarboxylase',
      '["DOPA-Decarboxylase","Monoaminooxidase B","Catechol-O-Methyltransferase","Tyrosinhydroxylase"]'::jsonb,
      'Carbidopa hemmt die periphere DOPA-Decarboxylase und erhoeht damit die zentrale Verfuegbarkeit von Levodopa.',
      'Which enzyme does carbidopa inhibit in the periphery?',
      'DOPA decarboxylase',
      '["DOPA decarboxylase","Monoamine oxidase B","Catechol-O-methyltransferase","Tyrosine hydroxylase"]'::jsonb,
      'Carbidopa inhibits peripheral DOPA decarboxylase and thereby increases central availability of levodopa.'
    ),
    (
      'online-fokus-pharmakologie-05',
      'Pharmakologie',
      'Welchen Ionenkanal schliessen Sulfonylharnstoffe in Betazellen?',
      'ATP-sensitiven Kaliumkanal',
      '["ATP-sensitiven Kaliumkanal","Spannungsabhaengigen Natriumkanal","Ryanodinrezeptor","L-Typ-Calciumkanal"]'::jsonb,
      'Sulfonylharnstoffe schliessen ATP-sensitive Kaliumkanaele in Betazellen und foerdern dadurch die Insulinfreisetzung.',
      'Which ion channel is closed by sulfonylureas in beta cells?',
      'ATP-sensitive potassium channel',
      '["ATP-sensitive potassium channel","Voltage-gated sodium channel","Ryanodine receptor","L-type calcium channel"]'::jsonb,
      'Sulfonylureas close ATP-sensitive potassium channels in beta cells and thereby promote insulin release.'
    ),
    (
      'online-fokus-pharmakologie-06',
      'Pharmakologie',
      'Welches Zielprotein hemmt Dantrolen bei maligner Hyperthermie?',
      'Ryanodinrezeptor RyR1',
      '["Ryanodinrezeptor RyR1","SERCA-Pumpe","Na-K-ATPase","L-Typ-Calciumkanal"]'::jsonb,
      'Dantrolen hemmt den Ryanodinrezeptor RyR1 im skelettalen Muskel und reduziert dadurch die Calciumfreisetzung aus dem sarkoplasmatischen Retikulum.',
      'Which target protein is inhibited by dantrolene in malignant hyperthermia?',
      'Ryanodine receptor RyR1',
      '["Ryanodine receptor RyR1","SERCA pump","Na-K ATPase","L-type calcium channel"]'::jsonb,
      'Dantrolene inhibits the ryanodine receptor RyR1 in skeletal muscle and thereby reduces calcium release from the sarcoplasmic reticulum.'
    ),
    (
      'online-fokus-pharmakologie-07',
      'Pharmakologie',
      'Welches Enzym wird durch Methotrexat gehemmt?',
      'Dihydrofolat-Reduktase',
      '["Dihydrofolat-Reduktase","Xanthinoxidase","Thymidylat-Synthase","Aromatase"]'::jsonb,
      'Methotrexat hemmt die Dihydrofolat-Reduktase und stoert damit die Purin- und Thymidinsynthese.',
      'Which enzyme is inhibited by methotrexate?',
      'Dihydrofolate reductase',
      '["Dihydrofolate reductase","Xanthine oxidase","Thymidylate synthase","Aromatase"]'::jsonb,
      'Methotrexate inhibits dihydrofolate reductase and thereby disrupts purine and thymidine synthesis.'
    ),
    (
      'online-fokus-pharmakologie-08',
      'Pharmakologie',
      'Welches Membranprotein wird durch Digoxin gehemmt?',
      'Na-K-ATPase',
      '["Na-K-ATPase","SERCA-Pumpe","Natrium-Calcium-Austauscher","L-Typ-Calciumkanal"]'::jsonb,
      'Digoxin hemmt die Na-K-ATPase und erhoeht dadurch indirekt die intrazellulaere Calciumkonzentration in Kardiomyozyten.',
      'Which membrane protein is inhibited by digoxin?',
      'Na-K ATPase',
      '["Na-K ATPase","SERCA pump","Sodium-calcium exchanger","L-type calcium channel"]'::jsonb,
      'Digoxin inhibits Na-K ATPase and thereby indirectly increases intracellular calcium in cardiomyocytes.'
    ),
    (
      'online-fokus-pharmakologie-09',
      'Pharmakologie',
      'Welchen Effekt hat Rifampicin auf das hepatische CYP450-System?',
      'Enzyminduktion',
      '["Enzyminduktion","Enzymhemmung","Irreversible Blockade aller Isoenzyme","Keinen Effekt"]'::jsonb,
      'Rifampicin ist ein starker Induktor mehrerer CYP450-Isoenzyme und kann dadurch die Spiegel vieler Medikamente senken.',
      'What effect does rifampicin have on the hepatic CYP450 system?',
      'Enzyme induction',
      '["Enzyme induction","Enzyme inhibition","Irreversible blockade of all isoenzymes","No effect"]'::jsonb,
      'Rifampicin is a strong inducer of several CYP450 isoenzymes and can therefore lower the levels of many drugs.'
    ),
    (
      'online-fokus-pharmakologie-10',
      'Pharmakologie',
      'Welches spezifische Antidot neutralisiert Dabigatran?',
      'Idarucizumab',
      '["Idarucizumab","Protamin","Vitamin K","Andexanet alfa"]'::jsonb,
      'Idarucizumab ist ein spezifisches Antidot gegen Dabigatran.',
      'Which specific antidote neutralizes dabigatran?',
      'Idarucizumab',
      '["Idarucizumab","Protamine","Vitamin K","Andexanet alfa"]'::jsonb,
      'Idarucizumab is a specific antidote for dabigatran.'
    )
),
upsert_questions as (
  insert into public.questions (
    slug,
    category,
    question,
    correct_answer,
    options,
    explanation
  )
  select
    slug,
    category,
    question_de,
    correct_de,
    options_de,
    explanation_de
  from question_rows
  on conflict (slug) do update
    set category = excluded.category,
        question = excluded.question,
        correct_answer = excluded.correct_answer,
        options = excluded.options,
        explanation = excluded.explanation,
        updated_at = now()
  returning id, slug
)
insert into public.question_translations (
  question_id,
  language,
  question,
  options,
  correct_answer,
  explanation
)
select
  upsert_questions.id,
  'en',
  question_rows.question_en,
  question_rows.options_en,
  question_rows.correct_en,
  question_rows.explanation_en
from upsert_questions
join question_rows
  on question_rows.slug = upsert_questions.slug
on conflict (question_id, language) do update
  set question = excluded.question,
      options = excluded.options,
      correct_answer = excluded.correct_answer,
      explanation = excluded.explanation,
      updated_at = now();
