-- Balanced general-category questions with less answer-length bias.
-- Generated from src/data/offlineBalancedGeneralCategoryRows.json.

alter table public.questions
  add column if not exists image_url text,
  add column if not exists image_alt text;

with question_rows (
  slug,
  category,
  question_de,
  correct_de,
  options_de,
  explanation_de,
  question_en,
  correct_en,
  options_en,
  explanation_en,
  image_url,
  image_alt
) as (
  values
    (
      'general-balanced-medizin-01',
      'Medizin',
      'Welche Kombination passt am ehesten zu einem Volumenmangelschock?',
      'Kaltschweissig und blass',
      '["Kaltschweissig und blass","Warme Haut und Bradykardie","Hoher Druck und rote Haut","Langsamer Puls im Schlaf"]'::jsonb,
      'Bei Volumenmangel versucht der Koerper die Durchblutung zentraler Organe zu sichern. Kalte, blasse Haut und Schweiss sind typische Warnzeichen.',
      'Which finding best fits hypovolemic shock?',
      'Cold clammy pale skin',
      '["Cold clammy pale skin","Warm skin with bradycardia","High pressure and flushing","Slow pulse during sleep"]'::jsonb,
      'In volume loss, the body preserves flow to vital organs. Cold pale skin and sweating are typical warning signs.',
      null,
      null
    ),
    (
      'general-balanced-medizin-02',
      'Medizin',
      'Wofuer steht FAST beim Schlaganfall-Screening?',
      'Gesicht, Arm, Sprache, Zeit',
      '["Gesicht, Arm, Sprache, Zeit","Fieber, Atemnot, Schwindel, Test","Fokus, Auge, Sensorik, Tonus","Fluessigkeit, Atemweg, Sauerstoff, Temperatur"]'::jsonb,
      'FAST prueft haeufige Schlaganfallzeichen: Gesichtshaelfte, Armschwaeche, Sprachstoerung und schnelles Handeln.',
      'What does FAST screen for in suspected stroke?',
      'Face, arm, speech, time',
      '["Face, arm, speech, time","Fever, airway, sugar, test","Focus, eye, sensation, tone","Fluid, oxygen, seizure, temp"]'::jsonb,
      'FAST checks common stroke signs: facial droop, arm weakness, speech trouble, and the need to act quickly.',
      null,
      null
    ),
    (
      'general-balanced-medizin-03',
      'Medizin',
      'Welches Medikament ist bei schwerer Anaphylaxie zentral?',
      'Adrenalin i.m.',
      '["Adrenalin i.m.","Ibuprofen oral","Furosemid i.v.","Insulin s.c."]'::jsonb,
      'Adrenalin intramuskulaer wirkt gegen Bronchospasmus, Gefaessweitstellung und Kreislaufabfall bei schwerer Anaphylaxie.',
      'Which drug is central in severe anaphylaxis?',
      'IM epinephrine',
      '["IM epinephrine","Oral ibuprofen","IV furosemide","SC insulin"]'::jsonb,
      'Intramuscular epinephrine treats bronchospasm, vasodilation, and circulatory collapse in severe anaphylaxis.',
      null,
      null
    ),
    (
      'general-balanced-medizin-04',
      'Medizin',
      'Welche Frequenz gilt als Zielbereich fuer Thoraxkompressionen bei Erwachsenen?',
      '100 bis 120 pro Minute',
      '["100 bis 120 pro Minute","40 bis 60 pro Minute","150 bis 170 pro Minute","20 bis 30 pro Minute"]'::jsonb,
      'Bei Erwachsenen wird fuer Herzdruckmassage meist ein Tempo von 100 bis 120 Kompressionen pro Minute empfohlen.',
      'Which rate is the usual adult chest compression target?',
      '100 to 120 per minute',
      '["100 to 120 per minute","40 to 60 per minute","150 to 170 per minute","20 to 30 per minute"]'::jsonb,
      'Adult CPR usually targets 100 to 120 chest compressions per minute.',
      null,
      null
    ),
    (
      'general-balanced-medizin-05',
      'Medizin',
      'Welcher Befund passt eher zu relevanter Dehydratation?',
      'Trockene Schleimhaeute',
      '["Trockene Schleimhaeute","Feuchte Lippen und Traenen","Warme Haut nach Dusche","Kurzes Gaehnen nach Schlaf"]'::jsonb,
      'Trockene Schleimhaeute, Durst, stehende Hautfalten oder wenig Urin koennen Hinweise auf Fluessigkeitsmangel sein.',
      'Which finding better fits clinically relevant dehydration?',
      'Dry mucous membranes',
      '["Dry mucous membranes","Moist lips with tears","Warm skin after shower","Brief yawning after sleep"]'::jsonb,
      'Dry mucous membranes, thirst, poor skin turgor, or low urine output can suggest fluid deficit.',
      null,
      null
    ),
    (
      'general-balanced-medizin-06',
      'Medizin',
      'Welche Zellen produzieren Insulin?',
      'Beta-Zellen im Pankreas',
      '["Beta-Zellen im Pankreas","Kupffer-Zellen der Leber","Osteoklasten im Knochen","Gliazellen im Gehirn"]'::jsonb,
      'Insulin wird in Beta-Zellen der Langerhans-Inseln im Pankreas gebildet und senkt den Blutzucker.',
      'Which cells produce insulin?',
      'Pancreatic beta cells',
      '["Pancreatic beta cells","Kupffer cells in liver","Osteoclasts in bone","Glial cells in brain"]'::jsonb,
      'Insulin is produced by beta cells in the pancreatic islets and lowers blood glucose.',
      null,
      null
    ),
    (
      'general-balanced-geschichte-01',
      'Geschichte',
      'Was staerkte der Westfaelische Frieden 1648 besonders?',
      'Rechte der Reichsstaende',
      '["Rechte der Reichsstaende","Direkte Kaiserherrschaft","Einheitliche Reichskirche","Kolonien in Amerika"]'::jsonb,
      'Der Westfaelische Frieden bestaetigte viele Rechte der Reichsstaende und schwaechte die Idee einer einheitlichen kaiserlichen Zentralmacht.',
      'What did the Peace of Westphalia especially strengthen?',
      'Rights of imperial estates',
      '["Rights of imperial estates","Direct imperial rule","One imperial church","Colonies in America"]'::jsonb,
      'The Peace of Westphalia confirmed many rights of imperial estates and weakened the idea of direct imperial central power.',
      null,
      null
    ),
    (
      'general-balanced-geschichte-02',
      'Geschichte',
      'Welches Ziel passt zur Meiji-Restauration in Japan?',
      'Zentraler moderner Staat',
      '["Zentraler moderner Staat","Rueckkehr zur Isolation","Spanische Kolonialmacht","Aufloesung der Armee"]'::jsonb,
      'Die Meiji-Regierung zentralisierte Verwaltung, Armee und Wirtschaft, um Japan schneller zu modernisieren.',
      'Which goal fits the Meiji Restoration in Japan?',
      'Central modern state',
      '["Central modern state","Return to isolation","Spanish colonial rule","Dissolving the army"]'::jsonb,
      'The Meiji government centralized administration, military, and economy to modernize Japan rapidly.',
      null,
      null
    ),
    (
      'general-balanced-geschichte-03',
      'Geschichte',
      'Worum ging es bei der Berliner Luftbruecke 1948/49?',
      'Versorgung West-Berlins',
      '["Versorgung West-Berlins","Evakuierung aus Paris","Grenzziehung in Afrika","Besetzung von Wien"]'::jsonb,
      'West-Berlin wurde waehrend der sowjetischen Blockade ueber Luftkorridore mit Lebensmitteln, Kohle und Guetern versorgt.',
      'What was the Berlin Airlift of 1948/49 about?',
      'Supplying West Berlin',
      '["Supplying West Berlin","Evacuating Paris","Drawing African borders","Occupying Vienna"]'::jsonb,
      'During the Soviet blockade, West Berlin was supplied by air corridors with food, coal, and other goods.',
      null,
      null
    ),
    (
      'general-balanced-geschichte-04',
      'Geschichte',
      'Was beschreibt Columbian Exchange am besten?',
      'Kontinenten-Austausch',
      '["Kontinenten-Austausch","Wahlrecht in Kolumbien","Ende des Roemischen Reichs","Bau der Seidenstrasse"]'::jsonb,
      'Nach 1492 wurden Pflanzen, Tiere, Krankheiten und Menschen zwischen Europa, Afrika und Amerika in grossem Umfang bewegt.',
      'What best describes the Columbian Exchange?',
      'Exchange between continents',
      '["Exchange between continents","Voting rights in Colombia","End of the Roman Empire","Building the Silk Road"]'::jsonb,
      'After 1492, plants, animals, diseases, and people moved on a large scale between Europe, Africa, and the Americas.',
      null,
      null
    ),
    (
      'general-balanced-geschichte-05',
      'Geschichte',
      'Welches Prinzip praegte den Wiener Kongress?',
      'Machtgleichgewicht',
      '["Machtgleichgewicht","Weltraumvertrag","Abschaffung aller Grenzen","Industrieplanwirtschaft"]'::jsonb,
      'Der Wiener Kongress ordnete Europa nach Napoleon neu und setzte stark auf Restauration und Gleichgewicht der Maechte.',
      'Which principle shaped the Congress of Vienna?',
      'Balance of power',
      '["Balance of power","Outer space treaty","Abolishing all borders","Industrial planning"]'::jsonb,
      'The Congress of Vienna reordered Europe after Napoleon and emphasized restoration and a balance among powers.',
      null,
      null
    ),
    (
      'general-balanced-geschichte-06',
      'Geschichte',
      'Warum waren roemische Strassen strategisch wichtig?',
      'Militaer und Verwaltung',
      '["Militaer und Verwaltung","Nur private Spazierwege","Verbotener Seehandel","Schneller Buchdruck"]'::jsonb,
      'Roemische Strassen halfen Legionen, Handel, Nachrichten und Verwaltung, grosse Gebiete besser zu verbinden.',
      'Why were Roman roads strategically important?',
      'Military and administration',
      '["Military and administration","Only private walking paths","Banned maritime trade","Faster printing presses"]'::jsonb,
      'Roman roads helped armies, trade, messages, and administration connect large territories more effectively.',
      null,
      null
    ),
    (
      'general-balanced-sachkunde-01',
      'Sachkunde',
      'Welches Prinzip nutzt ein Induktionskochfeld direkt?',
      'Magnetisches Wechselfeld',
      '["Magnetisches Wechselfeld","Radioaktiver Zerfall","Luftdruck im Topf","Sonnenlicht im Glas"]'::jsonb,
      'Ein wechselndes Magnetfeld erzeugt Wirbelstroeme im geeigneten Kochgeschirr. Dadurch wird der Topf selbst warm.',
      'Which principle does an induction cooktop use directly?',
      'Magnetic induction',
      '["Magnetic induction","Radioactive decay","Air pressure in the pot","Sunlight inside glass"]'::jsonb,
      'A changing magnetic field induces currents in suitable cookware. The pot itself heats up.',
      null,
      null
    ),
    (
      'general-balanced-sachkunde-02',
      'Sachkunde',
      'Was passiert beim Treibhauseffekt vereinfacht?',
      'Teilweiser Waermestau',
      '["Teilweiser Waermestau","Schwerkraft verschwindet","Sauerstoff wird zu Metall","Meere frieren sofort"]'::jsonb,
      'Treibhausgase lassen viel Sonnenlicht hinein, halten aber einen Teil der abgegebenen Waermestrahlung zurueck.',
      'What roughly happens in the greenhouse effect?',
      'Partial heat trapping',
      '["Partial heat trapping","Gravity disappears","Oxygen turns into metal","Oceans freeze at once"]'::jsonb,
      'Greenhouse gases let much sunlight in but retain part of the outgoing heat radiation.',
      null,
      null
    ),
    (
      'general-balanced-sachkunde-03',
      'Sachkunde',
      'Was macht eine Sicherung bei zu hohem Strom?',
      'Stromkreis trennen',
      '["Stromkreis trennen","Spannung verdoppeln","Kabel aktiv kuehlen","Magnetfeld loeschen"]'::jsonb,
      'Eine Sicherung unterbricht den Stromkreis, wenn zu viel Strom fliesst. So sinkt das Brand- und Schadensrisiko.',
      'What does a fuse do when current is too high?',
      'Breaks the circuit',
      '["Breaks the circuit","Doubles the voltage","Actively cools cables","Deletes magnetic fields"]'::jsonb,
      'A fuse interrupts the circuit when too much current flows, reducing fire and damage risk.',
      null,
      null
    ),
    (
      'general-balanced-sachkunde-04',
      'Sachkunde',
      'Welcher pH-Wert gilt bei Wasser als neutral?',
      'pH 7',
      '["pH 7","pH 1","pH 14","pH 0"]'::jsonb,
      'Neutral bedeutet, dass Saeure- und Basenwirkung ausgeglichen sind. Reines Wasser liegt bei Raumtemperatur etwa bei pH 7.',
      'Which pH value is neutral for water?',
      'pH 7',
      '["pH 7","pH 1","pH 14","pH 0"]'::jsonb,
      'Neutral means acid and base effects are balanced. Pure water at room temperature is around pH 7.',
      null,
      null
    ),
    (
      'general-balanced-sachkunde-05',
      'Sachkunde',
      'Was ist die Grundidee eines Hebels?',
      'Kraft gegen Weg tauschen',
      '["Kraft gegen Weg tauschen","Masse vollstaendig loeschen","Waerme in Salz verwandeln","Strom ohne Kreis erzeugen"]'::jsonb,
      'Ein Hebel kann eine kleinere Kraft ueber einen laengeren Weg in eine groessere Kraft ueber einen kuerzeren Weg uebersetzen.',
      'What is the basic idea of a lever?',
      'Trade force for distance',
      '["Trade force for distance","Erase mass completely","Turn heat into salt","Make current without a circuit"]'::jsonb,
      'A lever can trade a smaller force over a longer path for a larger force over a shorter path.',
      null,
      null
    ),
    (
      'general-balanced-sachkunde-06',
      'Sachkunde',
      'Warum kuehlt Verdunstung die Haut?',
      'Verdunstung entzieht Waerme',
      '["Verdunstung entzieht Waerme","Wasser erzeugt neuen Strom","Luft wird sofort schwerer","Salz blockiert Licht"]'::jsonb,
      'Beim Verdunsten gehen Molekuele in den Gaszustand ueber und nehmen Energie mit. Diese Energie fehlt dann als Waerme.',
      'Why does evaporation cool the skin?',
      'Evaporation removes heat',
      '["Evaporation removes heat","Water creates new current","Air gets heavy instantly","Salt blocks light"]'::jsonb,
      'When molecules evaporate, they enter the gas phase and carry energy away. That energy is no longer heat on the skin.',
      null,
      null
    ),
    (
      'general-balanced-politik-01',
      'Politik',
      'Was verlangt ein konstruktives Misstrauensvotum?',
      'Neuer Kanzler zugleich',
      '["Neuer Kanzler zugleich","Neuer Bundesadler","Neue Laendergrenzen","Neue Amtskleidung"]'::jsonb,
      'Der Bundestag kann den Kanzler nur abwaehlen, wenn gleichzeitig eine neue Person mit Mehrheit gewaehlt wird.',
      'What does a constructive no-confidence vote require?',
      'New chancellor at once',
      '["New chancellor at once","New federal eagle","New state borders","New official clothes"]'::jsonb,
      'The Bundestag can remove a chancellor only by electing a replacement with a majority at the same time.',
      null,
      null
    ),
    (
      'general-balanced-politik-02',
      'Politik',
      'Was meint Foederalismus im Kern?',
      'Macht wird verteilt',
      '["Macht wird verteilt","Wahlen werden verboten","Gerichte werden privat","Parteien verschwinden"]'::jsonb,
      'Foederalismus verteilt staatliche Aufgaben und Macht zwischen Bund und Laendern.',
      'What is the core idea of federalism?',
      'Power is divided',
      '["Power is divided","Elections are banned","Courts become private","Parties disappear"]'::jsonb,
      'Federalism divides state tasks and power between national and regional levels.',
      null,
      null
    ),
    (
      'general-balanced-politik-03',
      'Politik',
      'Was trennen Erst- und Zweitstimme grob?',
      'Person und Partei',
      '["Person und Partei","Gericht und Polizei","Steuer und Zoll","Kanzler und Koenig"]'::jsonb,
      'Die Erststimme waehlt eine Direktkandidatur im Wahlkreis, die Zweitstimme praegt die Sitzverteilung der Parteien.',
      'What do Germany''s first and second votes roughly separate?',
      'Person and party',
      '["Person and party","Court and police","Tax and customs","Chancellor and king"]'::jsonb,
      'The first vote chooses a district candidate, while the second vote strongly shapes party seat distribution.',
      null,
      null
    ),
    (
      'general-balanced-politik-04',
      'Politik',
      'Was bedeutet Rechtsstaatlichkeit besonders?',
      'Gesetze binden den Staat',
      '["Gesetze binden den Staat","Regierung steht ueber Recht","Gerichte stimmen Gesetze","Wahlen ersetzen Verfahren"]'::jsonb,
      'Im Rechtsstaat ist staatliches Handeln an Recht, Verfahren und gerichtliche Kontrolle gebunden.',
      'What does rule of law especially mean?',
      'Law binds the state',
      '["Law binds the state","Government outranks law","Courts vote on laws","Elections replace process"]'::jsonb,
      'Under the rule of law, state action is bound by law, procedure, and judicial review.',
      null,
      null
    ),
    (
      'general-balanced-politik-05',
      'Politik',
      'Welche Rolle hat der Bundesrat grob?',
      'Laender wirken mit',
      '["Laender wirken mit","Kanzler direkt waehlen","Gerichte besetzen","Parteien verbieten"]'::jsonb,
      'Der Bundesrat vertritt die Laender und beteiligt sie an vielen Gesetzgebungsverfahren des Bundes.',
      'What is the broad role of the Bundesrat?',
      'States take part',
      '["States take part","Elects chancellor directly","Staffs the courts","Bans all parties"]'::jsonb,
      'The Bundesrat represents the federal states and involves them in many national legislative procedures.',
      null,
      null
    ),
    (
      'general-balanced-politik-06',
      'Politik',
      'Was will Verhaeltniswahl abbilden?',
      'Stimmenanteile der Parteien',
      '["Stimmenanteile der Parteien","Alter aller Kandidaten","Laenge der Wahlzettel","Groesse der Wahllokale"]'::jsonb,
      'Bei Verhaeltniswahl sollen Sitze moeglichst proportional zu den Stimmenanteilen der Parteien vergeben werden.',
      'What does proportional representation try to reflect?',
      'Parties'' vote shares',
      '["Parties'' vote shares","Age of all candidates","Length of ballot papers","Size of polling places"]'::jsonb,
      'Proportional representation aims to allocate seats roughly according to parties'' shares of the vote.',
      null,
      null
    ),
    (
      'general-balanced-geografie-01',
      'Geografie',
      'Was ist ein Regenschatten?',
      'Trockene Leeseite',
      '["Trockene Leeseite","Nebel im Erdinneren","Fluss ohne Muendung","Insel aus Meereis"]'::jsonb,
      'Feuchte Luft regnet an der Luvseite eines Gebirges ab. Auf der Leeseite kommt oft trockenere Luft an.',
      'What is a rain shadow?',
      'Dry leeward side',
      '["Dry leeward side","Fog inside Earth","River without a mouth","Island made of sea ice"]'::jsonb,
      'Moist air rains out on the windward side of mountains. Drier air often reaches the leeward side.',
      null,
      null
    ),
    (
      'general-balanced-geografie-02',
      'Geografie',
      'Wie entsteht ein Flussdelta meist?',
      'Sedimente lagern sich ab',
      '["Sedimente lagern sich ab","Lava verdampft im Fluss","Wind hebt Berge an","Eis loest Salz auf"]'::jsonb,
      'Wenn ein Fluss langsamer wird, besonders an der Muendung, koennen Sand, Schluff und andere Sedimente abgelagert werden.',
      'How does a river delta usually form?',
      'Sediment is deposited',
      '["Sediment is deposited","Lava evaporates in rivers","Wind lifts mountains","Ice dissolves salt"]'::jsonb,
      'When a river slows, especially near its mouth, sand, silt, and other sediment can be deposited.',
      null,
      null
    ),
    (
      'general-balanced-geografie-03',
      'Geografie',
      'Wo entstehen viele starke Erdbeben?',
      'An Plattengrenzen',
      '["An Plattengrenzen","Im Zentrum ruhiger Seen","Nur ueber Sandduenen","Ausschliesslich am Pol"]'::jsonb,
      'An Plattengrenzen bauen sich Spannungen auf. Wenn sie sich ruckartig loesen, kann ein starkes Erdbeben entstehen.',
      'Where do many strong earthquakes occur?',
      'At plate boundaries',
      '["At plate boundaries","At centers of calm lakes","Only above sand dunes","Only at the pole"]'::jsonb,
      'Stress builds up at plate boundaries. When it releases suddenly, strong earthquakes can occur.',
      null,
      null
    ),
    (
      'general-balanced-geografie-04',
      'Geografie',
      'Was ist das Grundproblem jeder Weltkarte?',
      'Verzerrung durch Projektion',
      '["Verzerrung durch Projektion","Fehlende Nordrichtung","Unsichtbare Laendernamen","Nur eine erlaubte Farbe"]'::jsonb,
      'Die gekruemmte Erdoberflaeche wird auf eine Ebene uebertragen. Dabei werden Flaechen, Formen, Winkel oder Distanzen verzerrt.',
      'What is the basic problem of every world map?',
      'Distortion from projection',
      '["Distortion from projection","Missing north direction","Invisible country names","Only one allowed color"]'::jsonb,
      'A curved Earth surface is transferred to a plane, which distorts area, shape, angles, or distance.',
      null,
      null
    ),
    (
      'general-balanced-geografie-05',
      'Geografie',
      'Was praegt den Monsun besonders?',
      'Jahreszeitlicher Windwechsel',
      '["Jahreszeitlicher Windwechsel","Dauerfrost am Aequator","Taeglicher Vulkanausbruch","Stillstand der Ozeane"]'::jsonb,
      'Monsune entstehen durch jahreszeitliche Druck- und Temperaturunterschiede zwischen Land und Meer.',
      'What especially shapes a monsoon?',
      'Seasonal wind reversal',
      '["Seasonal wind reversal","Permanent equator frost","Daily volcanic eruption","Oceans standing still"]'::jsonb,
      'Monsoons arise from seasonal pressure and temperature differences between land and sea.',
      null,
      null
    ),
    (
      'general-balanced-geografie-06',
      'Geografie',
      'Warum gibt es Zeitzonen?',
      'Rotation und Sonnenstand',
      '["Rotation und Sonnenstand","Mondphasen und Gezeiten","Vulkane und Erdbeben","Grenzen und Flaggen"]'::jsonb,
      'Durch die Erdrotation ist Mittag nicht ueberall gleichzeitig. Zeitzonen ordnen diese Unterschiede praktisch.',
      'Why do time zones exist?',
      'Rotation and sun angle',
      '["Rotation and sun angle","Moon phases and tides","Volcanoes and earthquakes","Borders and flags"]'::jsonb,
      'Because Earth rotates, noon does not happen everywhere at once. Time zones organize those differences practically.',
      null,
      null
    ),
    (
      'general-balanced-brainrot-01',
      'Brainrot',
      'Welcher Meme-Begriff passt am ehesten zu kopiertem Tastatur-Text?',
      'Copypasta',
      '["Copypasta","Ratio","NPC Stream","Sigma Face"]'::jsonb,
      'Copypasta bezeichnet Textbloecke, die immer wieder kopiert und in Posts oder Kommentaren eingefuegt werden.',
      'Which meme term best fits copied keyboard text?',
      'Copypasta',
      '["Copypasta","Ratio","NPC Stream","Sigma Face"]'::jsonb,
      'Copypasta means text blocks that are repeatedly copied and pasted into posts or comments.',
      'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f6/Keyboard_Close_Up.jpg/960px-Keyboard_Close_Up.jpg',
      'Close-up photo of computer keyboard keys'
    ),
    (
      'general-balanced-brainrot-02',
      'Brainrot',
      'Welcher Italian-Brainrot-Name wird durch den Hai am ehesten angedeutet?',
      'Tralalero Tralala',
      '["Tralalero Tralala","Bombardiro Crocodilo","Ballerina Cappuccina","Tung Tung Sahur"]'::jsonb,
      'Tralalero Tralala wird im Brainrot-Kontext oft mit einem Hai-Motiv verbunden, hier aber ohne geschuetztes Meme-Bild dargestellt.',
      'Which Italian-brainrot name is hinted at by the shark?',
      'Tralalero Tralala',
      '["Tralalero Tralala","Bombardiro Crocodilo","Ballerina Cappuccina","Tung Tung Sahur"]'::jsonb,
      'In brainrot context, Tralalero Tralala is often linked to a shark motif, shown here without using protected meme artwork.',
      'https://upload.wikimedia.org/wikipedia/commons/0/0a/Basking_Shark.jpg',
      'Photo of a basking shark underwater'
    ),
    (
      'general-balanced-brainrot-03',
      'Brainrot',
      'Welcher Brainrot-Name passt am besten zum Trommelstock-Motiv?',
      'Tung Tung Sahur',
      '["Tung Tung Sahur","Tralalero Tralala","Skibidi Toilet","Sigma Face"]'::jsonb,
      'Tung Tung Sahur spielt klanglich auf rhythmisches Klopfen an und passt daher besser zum Trommelstock-Motiv.',
      'Which brainrot name best fits the drumstick motif?',
      'Tung Tung Sahur',
      '["Tung Tung Sahur","Tralalero Tralala","Skibidi Toilet","Sigma Face"]'::jsonb,
      'Tung Tung Sahur evokes rhythmic knocking, so it fits the drumstick motif better than the other choices.',
      'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ed/Drumstick_pair.jpg/960px-Drumstick_pair.jpg',
      'Photo of two wooden drumsticks'
    ),
    (
      'general-balanced-brainrot-04',
      'Brainrot',
      'Welcher Meme-Typ wird durch das Sigma-Zeichen angedeutet?',
      'Sigma Face',
      '["Sigma Face","NPC Stream","Corecore","Ratio"]'::jsonb,
      'Sigma-Memes ueberzeichnen eine unbeeindruckte Einzelgaenger-Persona und werden haeufig ironisch benutzt.',
      'Which meme type is hinted at by the sigma symbol?',
      'Sigma Face',
      '["Sigma Face","NPC Stream","Corecore","Ratio"]'::jsonb,
      'Sigma memes exaggerate an unimpressed loner persona and are often used ironically.',
      'https://upload.wikimedia.org/wikipedia/commons/c/c3/Greek_sigma.png',
      'Greek sigma letters on a white background'
    ),
    (
      'general-balanced-brainrot-05',
      'Brainrot',
      'Was bedeutet POV in vielen Meme-Captions?',
      'Point of view',
      '["Point of view","Proof of vote","Private online value","Pixel over volume"]'::jsonb,
      'POV rahmt ein Meme so, als wuerde man eine Szene selbst oder aus einer bestimmten Rolle heraus erleben.',
      'What does POV mean in many meme captions?',
      'Point of view',
      '["Point of view","Proof of vote","Private online value","Pixel over volume"]'::jsonb,
      'POV frames a meme as if the viewer experiences the scene directly or from a specific role.',
      'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0c/Old_camera_%28Unsplash%29.jpg/1280px-Old_camera_%28Unsplash%29.jpg',
      'Photo of an old camera with a screen'
    ),
    (
      'general-balanced-brainrot-06',
      'Brainrot',
      'Was imitiert ein NPC-Stream meistens?',
      'Spielfigur-Reaktionen',
      '["Spielfigur-Reaktionen","Klassische Nachrichten","Stille Diashow","Normales Wetterradar"]'::jsonb,
      'NPC-Streams nutzen wiederholbare Posen, kurze Sprueche und Trigger-Reaktionen, die an Figuren in Spielen erinnern.',
      'What does an NPC stream usually imitate?',
      'Game-character reactions',
      '["Game-character reactions","Classic news broadcast","Silent photo slideshow","Normal weather radar"]'::jsonb,
      'NPC streams use repeatable poses, short phrases, and trigger reactions that resemble characters in games.',
      'https://openclipart.org/image/2000px/172636',
      'Illustration of a retro game controller'
    ),
    (
      'general-balanced-survival-01',
      'Survival',
      'Welches Zeichen passt zu beginnender Unterkuehlung?',
      'Zittern und Ungeschick',
      '["Zittern und Ungeschick","Starker Sonnenbrand","Sofortiger Durststopp","Besseres Nachtsehen"]'::jsonb,
      'Zittern und schlechtere Koordination koennen fruehe Warnzeichen sein, wenn Kaelte dem Koerper Waerme entzieht.',
      'Which sign fits early hypothermia?',
      'Shivering and clumsiness',
      '["Shivering and clumsiness","Severe sunburn pain","Instant thirst stop","Better night vision"]'::jsonb,
      'Shivering and declining coordination can be early warnings when cold conditions draw heat from the body.',
      null,
      null
    ),
    (
      'general-balanced-survival-02',
      'Survival',
      'Wie wird unsicheres Wasser im Camp verlaesslicher sicherer?',
      'Filtern, dann abkochen',
      '["Filtern, dann abkochen","Nur klar stehen lassen","Mit Erde verruehren","In Schatten giessen"]'::jsonb,
      'Filtern entfernt Partikel, Abkochen reduziert viele Krankheitserreger. Klares Aussehen allein beweist keine Sicherheit.',
      'How can unsafe camp water be made more reliably safer?',
      'Filter, then boil',
      '["Filter, then boil","Let it stand clear","Mix it with soil","Pour it into shade"]'::jsonb,
      'Filtering removes particles, and boiling reduces many pathogens. Clear appearance alone does not prove safety.',
      null,
      null
    ),
    (
      'general-balanced-survival-03',
      'Survival',
      'Was braucht ein Feuerdreieck?',
      'Waerme, Brennstoff, O2',
      '["Waerme, Brennstoff, O2","Sand, Eis, Schatten","Salz, Metall, Wasser","Wind, Karte, Messer"]'::jsonb,
      'Feuer braucht Waerme, brennbares Material und Sauerstoff. Fehlt eines davon, kann die Flamme nicht stabil bleiben.',
      'What does the fire triangle need?',
      'Heat, fuel, oxygen',
      '["Heat, fuel, oxygen","Sand, ice, shade","Salt, metal, water","Wind, map, knife"]'::jsonb,
      'Fire needs heat, combustible material, and oxygen. If one is missing, the flame cannot remain stable.',
      null,
      null
    ),
    (
      'general-balanced-survival-04',
      'Survival',
      'Was meint Missweisung beim Kompass?',
      'Versatz zu echtem Nord',
      '["Versatz zu echtem Nord","Anzeige der Batterieladung","Laenge einer Wanderpause","Hoehe des Wasserstands"]'::jsonb,
      'Ein Kompass zeigt magnetisch Nord. Die Abweichung zu geografisch Nord heisst Missweisung und kann bei Navigation wichtig sein.',
      'What is compass declination?',
      'Offset from true north',
      '["Offset from true north","Battery level display","Length of a hiking break","Height of water level"]'::jsonb,
      'A compass points to magnetic north. The offset from true north is declination and can matter for navigation.',
      null,
      null
    ),
    (
      'general-balanced-survival-05',
      'Survival',
      'Was ist fuer einen Biwakplatz meist sinnvoll?',
      'Windschutz und Drainage',
      '["Windschutz und Drainage","Tiefste Mulde im Bachbett","Lose Steine ueber Kopf","Direkt unter Totholz"]'::jsonb,
      'Ein guter Platz meidet Wasseransammlungen, Wind und offensichtliche Gefahren wie Totholz oder Steinschlagbereiche.',
      'What is usually sensible for a bivouac site?',
      'Wind shelter and drainage',
      '["Wind shelter and drainage","Lowest hollow in a streambed","Loose rocks overhead","Directly under deadwood"]'::jsonb,
      'A good site avoids water pooling, wind exposure, and obvious hazards such as deadwood or rockfall areas.',
      null,
      null
    ),
    (
      'general-balanced-survival-06',
      'Survival',
      'Was ist eine Grundidee von Leave No Trace?',
      'Spuren klein halten',
      '["Spuren klein halten","Muellsack verstecken","Pfade breit treten","Feuerstellen sammeln"]'::jsonb,
      'Leave No Trace zielt darauf, Natur und andere Besucher moeglichst wenig zu belasten.',
      'What is a basic idea of Leave No Trace?',
      'Keep impact small',
      '["Keep impact small","Hide trash bags","Widen every trail","Collect fire rings"]'::jsonb,
      'Leave No Trace aims to reduce impact on nature and on other visitors as much as practical.',
      null,
      null
    )
),
upsert_questions as (
  insert into public.questions (
    slug,
    category,
    question,
    correct_answer,
    options,
    explanation,
    image_url,
    image_alt
  )
  select
    slug,
    category,
    question_de,
    correct_de,
    options_de,
    explanation_de,
    image_url,
    image_alt
  from question_rows
  on conflict (slug) do update
    set category = excluded.category,
        question = excluded.question,
        correct_answer = excluded.correct_answer,
        options = excluded.options,
        explanation = excluded.explanation,
        image_url = excluded.image_url,
        image_alt = excluded.image_alt,
        updated_at = now()
  returning id, slug
)
insert into public.question_translations (
  question_id,
  language,
  question,
  options,
  correct_answer,
  explanation
)
select
  upsert_questions.id,
  'en',
  question_rows.question_en,
  question_rows.options_en,
  question_rows.correct_en,
  question_rows.explanation_en
from upsert_questions
join question_rows
  on question_rows.slug = upsert_questions.slug
on conflict (question_id, language) do update
  set question = excluded.question,
      options = excluded.options,
      correct_answer = excluded.correct_answer,
      explanation = excluded.explanation,
      updated_at = now();
