-- Expand additional online category pools with another precise bilingual pack and stronger explanations.

with question_rows (
  slug,
  category,
  question_de,
  correct_de,
  options_de,
  explanation_de,
  question_en,
  correct_en,
  options_en,
  explanation_en
) as (
  values
    (
      'online-erklaert-mehr-anatomie-01',
      'Anatomie',
      'Welcher Nerv innerviert den M. serratus anterior?',
      'N. thoracicus longus',
      '["N. thoracicus longus","N. dorsalis scapulae","N. axillaris","N. suprascapularis"]'::jsonb,
      'Der M. serratus anterior wird vom N. thoracicus longus innerviert. Eine Laesion fuehrt typischerweise zu einer Scapula alata beim Armheben oder Wanddruecken.',
      'Which nerve innervates the serratus anterior muscle?',
      'Long thoracic nerve',
      '["Long thoracic nerve","Dorsal scapular nerve","Axillary nerve","Suprascapular nerve"]'::jsonb,
      'The serratus anterior muscle is innervated by the long thoracic nerve. A lesion classically causes scapular winging during arm elevation or wall push.'
    ),
    (
      'online-erklaert-mehr-anatomie-02',
      'Anatomie',
      'Welcher Nerv ist bei einer Fraktur am Collum chirurgicum des Humerus besonders gefaehrdet?',
      'N. axillaris',
      '["N. axillaris","N. radialis","N. medianus","N. musculocutaneus"]'::jsonb,
      'Der N. axillaris verlaeuft zusammen mit der A. circumflexa humeri posterior in unmittelbarer Naehe des Collum chirurgicum. Deshalb ist er bei Frakturen dort besonders vulnerabel.',
      'Which nerve is particularly at risk in a fracture of the surgical neck of the humerus?',
      'Axillary nerve',
      '["Axillary nerve","Radial nerve","Median nerve","Musculocutaneous nerve"]'::jsonb,
      'The axillary nerve runs together with the posterior circumflex humeral artery close to the surgical neck. It is therefore particularly vulnerable at this site.'
    ),
    (
      'online-erklaert-mehr-anatomie-03',
      'Anatomie',
      'Welcher Nerv verlaeuft durch den Canalis obturatorius?',
      'N. obturatorius',
      '["N. obturatorius","N. femoralis","N. ischiadicus","N. pudendus"]'::jsonb,
      'Der N. obturatorius zieht zusammen mit den Obturatorgefaessen durch den Canalis obturatorius in die Adduktorenloge. Er versorgt dort vor allem die Adduktoren motorisch.',
      'Which nerve passes through the obturator canal?',
      'Obturator nerve',
      '["Obturator nerve","Femoral nerve","Sciatic nerve","Pudendal nerve"]'::jsonb,
      'The obturator nerve passes with the obturator vessels through the obturator canal into the medial thigh. There it provides major motor innervation to the adductors.'
    ),
    (
      'online-erklaert-mehr-anatomie-04',
      'Anatomie',
      'Welcher Nerv verlaeuft oberhalb des M. piriformis durch das Foramen ischiadicum majus?',
      'N. gluteus superior',
      '["N. gluteus superior","N. gluteus inferior","N. ischiadicus","N. pudendus"]'::jsonb,
      'Der N. gluteus superior verlaeuft als wichtige Ausnahme oberhalb des M. piriformis durch das Foramen ischiadicum majus. Die meisten anderen grossen Strukturen verlassen das Becken darunter.',
      'Which nerve passes above the piriformis muscle through the greater sciatic foramen?',
      'Superior gluteal nerve',
      '["Superior gluteal nerve","Inferior gluteal nerve","Sciatic nerve","Pudendal nerve"]'::jsonb,
      'The superior gluteal nerve is the classic major structure that passes above piriformis through the greater sciatic foramen. Most other large structures leave the pelvis below the muscle.'
    ),
    (
      'online-erklaert-mehr-anatomie-05',
      'Anatomie',
      'Welche Arterie setzt sich nach Durchtritt durch den Hiatus adductorius als A. poplitea fort?',
      'A. femoralis',
      '["A. femoralis","A. profunda femoris","A. obturatoria","A. glutea inferior"]'::jsonb,
      'Die A. femoralis verlaeuft durch den Hiatus adductorius in die Kniekehle und heisst distal davon A. poplitea. Dieser Uebergang ist ein klassischer topografischer Landmark.',
      'Which artery continues as the popliteal artery after passing through the adductor hiatus?',
      'Femoral artery',
      '["Femoral artery","Deep femoral artery","Obturator artery","Inferior gluteal artery"]'::jsonb,
      'The femoral artery passes through the adductor hiatus into the popliteal fossa and is then called the popliteal artery. This transition is a classic anatomic landmark.'
    ),
    (
      'online-erklaert-mehr-anatomie-06',
      'Anatomie',
      'Welcher Handwurzelknochen frakturiert klassisch bei Druckschmerz in der Tabatiere?',
      'Os scaphoideum',
      '["Os scaphoideum","Os lunatum","Os capitatum","Os triquetrum"]'::jsonb,
      'Der Druckschmerz in der Tabatiere ist klassisch fuer eine Skaphoidfraktur. Das Os scaphoideum ist wegen seiner Blutversorgung zudem besonders gefaehrdet fuer eine Pseudarthrose.',
      'Which carpal bone is classically fractured when there is tenderness in the anatomical snuffbox?',
      'Scaphoid',
      '["Scaphoid","Lunate","Capitate","Triquetrum"]'::jsonb,
      'Tenderness in the anatomical snuffbox classically suggests a scaphoid fracture. Because of its blood supply, the scaphoid is also at special risk for nonunion.'
    ),
    (
      'online-erklaert-mehr-anatomie-07',
      'Anatomie',
      'Welche Muskelgruppe abductiert die Finger II bis V in den Grundgelenken?',
      'Mm. interossei dorsales',
      '["Mm. interossei dorsales","Mm. lumbricales","Mm. interossei palmares","Mm. thenares"]'::jsonb,
      'Die dorsalen Interossei spreizen die Finger von der Mittellinie der Hand weg und sorgen damit fuer die Abduktion von II bis V. Merkhilfe: DAB steht fuer dorsal abduct.',
      'Which muscle group abducts digits II through V at the metacarpophalangeal joints?',
      'Dorsal interossei',
      '["Dorsal interossei","Lumbricals","Palmar interossei","Thenar muscles"]'::jsonb,
      'The dorsal interossei spread the fingers away from the midline of the hand and therefore abduct digits II through V. A classic mnemonic is DAB for dorsal abduct.'
    ),
    (
      'online-erklaert-mehr-anatomie-08',
      'Anatomie',
      'Welcher Hirnnerv fuehrt die parasympathischen Fasern zur Glandula parotis?',
      'N. glossopharyngeus',
      '["N. glossopharyngeus","N. facialis","N. trigeminus","N. vagus"]'::jsonb,
      'Die praeganglionaeren parasympathischen Fasern zur Parotis stammen aus dem N. glossopharyngeus, ziehen ueber den N. petrosus minor zum Ganglion oticum und danach mit dem N. auriculotemporalis weiter.',
      'Which cranial nerve carries the parasympathetic fibers to the parotid gland?',
      'Glossopharyngeal nerve',
      '["Glossopharyngeal nerve","Facial nerve","Trigeminal nerve","Vagus nerve"]'::jsonb,
      'Preganglionic parasympathetic fibers to the parotid originate from the glossopharyngeal nerve, travel via the lesser petrosal nerve to the otic ganglion, and then continue with the auriculotemporal nerve.'
    ),
    (
      'online-erklaert-mehr-anatomie-09',
      'Anatomie',
      'Welche Vene vereinigt sich typischerweise mit der V. splenica zur V. portae hepatis?',
      'V. mesenterica superior',
      '["V. mesenterica superior","V. mesenterica inferior","V. cava inferior","V. hepatica media"]'::jsonb,
      'Die V. portae hepatis entsteht klassisch aus der Vereinigung von V. mesenterica superior und V. splenica. Die V. mesenterica inferior muendet haeufig zuvor in die V. splenica.',
      'Which vein typically joins the splenic vein to form the portal vein?',
      'Superior mesenteric vein',
      '["Superior mesenteric vein","Inferior mesenteric vein","Inferior vena cava","Middle hepatic vein"]'::jsonb,
      'The portal vein classically forms from the union of the superior mesenteric vein and the splenic vein. The inferior mesenteric vein often drains into the splenic vein beforehand.'
    ),
    (
      'online-erklaert-mehr-anatomie-10',
      'Anatomie',
      'Welcher Nerv verlaeuft im Sulcus nervi ulnaris hinter dem Epicondylus medialis humeri?',
      'N. ulnaris',
      '["N. ulnaris","N. medianus","N. radialis","N. axillaris"]'::jsonb,
      'Der N. ulnaris zieht oberflaechlich hinter dem Epicondylus medialis im Sulcus nervi ulnaris. Daher loest ein Schlag an dieser Stelle das typische Elektrisieren im kleinen Finger aus.',
      'Which nerve runs in the ulnar groove behind the medial epicondyle of the humerus?',
      'Ulnar nerve',
      '["Ulnar nerve","Median nerve","Radial nerve","Axillary nerve"]'::jsonb,
      'The ulnar nerve runs superficially behind the medial epicondyle in the ulnar groove. That is why striking this area causes the classic tingling sensation in the little finger.'
    ),
    (
      'online-erklaert-mehr-biochemie-01',
      'Biochemie',
      'Welcher Cofaktor wird von der Pyruvatdehydrogenase direkt benoetigt?',
      'Thiaminpyrophosphat',
      '["Thiaminpyrophosphat","Biotin","Vitamin C","Folsaeure"]'::jsonb,
      'Die Pyruvatdehydrogenase benoetigt mehrere Cofaktoren, darunter Thiaminpyrophosphat aus Vitamin B1. Ein Mangel stoert die oxidative Decarboxylierung von Pyruvat zu Acetyl-CoA.',
      'Which cofactor is directly required by pyruvate dehydrogenase?',
      'Thiamine pyrophosphate',
      '["Thiamine pyrophosphate","Biotin","Vitamin C","Folic acid"]'::jsonb,
      'Pyruvate dehydrogenase requires several cofactors, including thiamine pyrophosphate derived from vitamin B1. Deficiency impairs oxidative decarboxylation of pyruvate to acetyl-CoA.'
    ),
    (
      'online-erklaert-mehr-biochemie-02',
      'Biochemie',
      'Welches Enzym ist bei klassischer Galaktosaemie defekt?',
      'Galaktose-1-phosphat-Uridyltransferase',
      '["Galaktose-1-phosphat-Uridyltransferase","Galaktokinase","Aldolase B","Hexokinase"]'::jsonb,
      'Die klassische Galaktosaemie beruht auf einem Mangel der Galaktose-1-phosphat-Uridyltransferase. Dadurch akkumulieren toxische Metabolite wie Galaktose-1-phosphat und Galaktitol.',
      'Which enzyme is defective in classic galactosemia?',
      'Galactose-1-phosphate uridyltransferase',
      '["Galactose-1-phosphate uridyltransferase","Galactokinase","Aldolase B","Hexokinase"]'::jsonb,
      'Classic galactosemia is caused by deficiency of galactose-1-phosphate uridyltransferase. Toxic metabolites such as galactose-1-phosphate and galactitol therefore accumulate.'
    ),
    (
      'online-erklaert-mehr-biochemie-03',
      'Biochemie',
      'Welches Enzym ist beim Lesch-Nyhan-Syndrom defekt?',
      'HGPRT',
      '["HGPRT","APRT","Xanthinoxidase","Adenylatcyclase"]'::jsonb,
      'Beim Lesch-Nyhan-Syndrom ist die Purin-Salvage ueber HGPRT gestoert. Dadurch steigt die Harnsaeurebildung, waehrend recycelbare Purinbasen verloren gehen.',
      'Which enzyme is defective in Lesch-Nyhan syndrome?',
      'HGPRT',
      '["HGPRT","APRT","Xanthine oxidase","Adenylate cyclase"]'::jsonb,
      'In Lesch-Nyhan syndrome, purine salvage through HGPRT is defective. Uric acid production therefore rises while reusable purine bases are lost.'
    ),
    (
      'online-erklaert-mehr-biochemie-04',
      'Biochemie',
      'Welches Vitamin ist Cofaktor der Pyruvatcarboxylase?',
      'Biotin',
      '["Biotin","Thiamin","Niacin","Riboflavin"]'::jsonb,
      'Die Pyruvatcarboxylase ist ein biotinabhaengiges Enzym der Glukoneogenese. Sie carboxyliert Pyruvat zu Oxalacetat im Mitochondrium.',
      'Which vitamin is a cofactor for pyruvate carboxylase?',
      'Biotin',
      '["Biotin","Thiamine","Niacin","Riboflavin"]'::jsonb,
      'Pyruvate carboxylase is a biotin-dependent enzyme of gluconeogenesis. It carboxylates pyruvate to oxaloacetate in the mitochondrion.'
    ),
    (
      'online-erklaert-mehr-biochemie-05',
      'Biochemie',
      'Welches Enzym katalysiert die Umwandlung von Homocystein zu Cystathionin?',
      'Cystathionin-beta-Synthase',
      '["Cystathionin-beta-Synthase","Methioninsynthase","Homogentisat-Oxidase","Phenylalaninhydroxylase"]'::jsonb,
      'Die Cystathionin-beta-Synthase benoetigt Vitamin B6 und leitet Homocystein in den Transsulfatierungsweg ueber. Ein Defekt fuehrt klassisch zur Homocystinurie.',
      'Which enzyme catalyzes conversion of homocysteine to cystathionine?',
      'Cystathionine beta-synthase',
      '["Cystathionine beta-synthase","Methionine synthase","Homogentisate oxidase","Phenylalanine hydroxylase"]'::jsonb,
      'Cystathionine beta-synthase requires vitamin B6 and channels homocysteine into the transsulfuration pathway. Deficiency classically causes homocystinuria.'
    ),
    (
      'online-erklaert-mehr-biochemie-06',
      'Biochemie',
      'Welches lysosomale Enzym ist beim Morbus Fabry defekt?',
      'Alpha-Galaktosidase A',
      '["Alpha-Galaktosidase A","Beta-Glukozerebrosidase","Hexosaminidase A","Sphingomyelinase"]'::jsonb,
      'Morbus Fabry ist eine X-chromosomale Sphingolipidose durch Mangel an Alpha-Galaktosidase A. Dadurch akkumuliert vor allem Globotriaosylceramid in Endothel und anderen Geweben.',
      'Which lysosomal enzyme is deficient in Fabry disease?',
      'Alpha-galactosidase A',
      '["Alpha-galactosidase A","Beta-glucocerebrosidase","Hexosaminidase A","Sphingomyelinase"]'::jsonb,
      'Fabry disease is an X-linked sphingolipidosis caused by deficiency of alpha-galactosidase A. This leads to accumulation of globotriaosylceramide especially in endothelium and other tissues.'
    ),
    (
      'online-erklaert-mehr-biochemie-07',
      'Biochemie',
      'Welches glykolytische Enzym wird durch Fluorid gehemmt?',
      'Enolase',
      '["Enolase","Hexokinase","Pyruvatkinase","Aldolase"]'::jsonb,
      'Fluorid hemmt die Enolase und stoppt damit die Glykolyse in Blutproben. Deshalb wird Fluorid verwendet, wenn der Glukoseabbau nach Blutentnahme verhindert werden soll.',
      'Which glycolytic enzyme is inhibited by fluoride?',
      'Enolase',
      '["Enolase","Hexokinase","Pyruvate kinase","Aldolase"]'::jsonb,
      'Fluoride inhibits enolase and thereby halts glycolysis in blood samples. That is why fluoride is used when glucose consumption after collection should be prevented.'
    ),
    (
      'online-erklaert-mehr-biochemie-08',
      'Biochemie',
      'Welches Enzym reduziert Ribonukleotide zu Desoxyribonukleotiden?',
      'Ribonukleotidreduktase',
      '["Ribonukleotidreduktase","DNA-Polymerase","PRPP-Synthetase","Thymidylatsynthase"]'::jsonb,
      'Die Ribonukleotidreduktase liefert die Desoxyribonukleotide fuer die DNA-Synthese. Ohne diesen Schritt koennen proliferierende Zellen keine ausreichenden DNA-Bausteine bereitstellen.',
      'Which enzyme reduces ribonucleotides to deoxyribonucleotides?',
      'Ribonucleotide reductase',
      '["Ribonucleotide reductase","DNA polymerase","PRPP synthetase","Thymidylate synthase"]'::jsonb,
      'Ribonucleotide reductase supplies the deoxyribonucleotides required for DNA synthesis. Without this step, proliferating cells cannot generate enough DNA building blocks.'
    ),
    (
      'online-erklaert-mehr-biochemie-09',
      'Biochemie',
      'Welches Enzym wandelt Phenylalanin zu Tyrosin um?',
      'Phenylalaninhydroxylase',
      '["Phenylalaninhydroxylase","Tyrosinase","Dopamin-beta-Hydroxylase","Homogentisat-Oxidase"]'::jsonb,
      'Die Phenylalaninhydroxylase bildet aus Phenylalanin die Aminosaeure Tyrosin. Ein Defekt fuehrt klassisch zur Phenylketonurie mit Anstieg von Phenylalanin.',
      'Which enzyme converts phenylalanine to tyrosine?',
      'Phenylalanine hydroxylase',
      '["Phenylalanine hydroxylase","Tyrosinase","Dopamine beta-hydroxylase","Homogentisate oxidase"]'::jsonb,
      'Phenylalanine hydroxylase converts phenylalanine into the amino acid tyrosine. Deficiency classically causes phenylketonuria with elevated phenylalanine levels.'
    ),
    (
      'online-erklaert-mehr-biochemie-10',
      'Biochemie',
      'Welches Enzym bildet aus Carbamoylphosphat und Ornithin im Harnstoffzyklus Citrullin?',
      'Ornithin-Transcarbamylase',
      '["Ornithin-Transcarbamylase","Argininosuccinat-Synthetase","Carbamoylphosphat-Synthetase I","Arginase"]'::jsonb,
      'Die Ornithin-Transcarbamylase katalysiert einen fruehen mitochondrialen Schritt des Harnstoffzyklus. Ihr Defekt ist die haeufigste vererbte Stoerung des Harnstoffzyklus.',
      'Which enzyme forms citrulline from carbamoyl phosphate and ornithine in the urea cycle?',
      'Ornithine transcarbamylase',
      '["Ornithine transcarbamylase","Argininosuccinate synthetase","Carbamoyl phosphate synthetase I","Arginase"]'::jsonb,
      'Ornithine transcarbamylase catalyzes an early mitochondrial step of the urea cycle. Its deficiency is the most common inherited urea cycle disorder.'
    ),
    (
      'online-erklaert-mehr-mikrobiologie-01',
      'Mikrobiologie',
      'Welche Staphylokokkenart ist klassisch koagulasepositiv?',
      'Staphylococcus aureus',
      '["Staphylococcus aureus","Staphylococcus epidermidis","Staphylococcus saprophyticus","Streptococcus pyogenes"]'::jsonb,
      'Staphylococcus aureus ist der klassische koagulasepositive Staphylokokkus. Die Koagulase hilft diagnostisch bei der Abgrenzung von koagulasenegativen Staphylokokken.',
      'Which staphylococcal species is classically coagulase positive?',
      'Staphylococcus aureus',
      '["Staphylococcus aureus","Staphylococcus epidermidis","Staphylococcus saprophyticus","Streptococcus pyogenes"]'::jsonb,
      'Staphylococcus aureus is the classic coagulase-positive staphylococcus. The coagulase test helps distinguish it from coagulase-negative staphylococci.'
    ),
    (
      'online-erklaert-mehr-mikrobiologie-02',
      'Mikrobiologie',
      'Welche koagulasenegative Staphylokokkenart ist novobiocinsensibel und typisch fuer Protheseninfektionen?',
      'Staphylococcus epidermidis',
      '["Staphylococcus epidermidis","Staphylococcus saprophyticus","Staphylococcus aureus","Enterococcus faecalis"]'::jsonb,
      'Staphylococcus epidermidis ist novobiocinsensibel und bildet Biofilme auf Fremdmaterial. Deshalb ist er klassisch mit Katheter- und Protheseninfektionen assoziiert.',
      'Which coagulase-negative staphylococcal species is novobiocin sensitive and typical for prosthetic device infections?',
      'Staphylococcus epidermidis',
      '["Staphylococcus epidermidis","Staphylococcus saprophyticus","Staphylococcus aureus","Enterococcus faecalis"]'::jsonb,
      'Staphylococcus epidermidis is novobiocin sensitive and forms biofilms on foreign material. It is therefore classically associated with catheter and prosthetic device infections.'
    ),
    (
      'online-erklaert-mehr-mikrobiologie-03',
      'Mikrobiologie',
      'Welche koagulasenegative Staphylokokkenart ist novobiocinresistent und verursacht haeufig Harnwegsinfekte bei jungen Frauen?',
      'Staphylococcus saprophyticus',
      '["Staphylococcus saprophyticus","Staphylococcus epidermidis","Staphylococcus aureus","Proteus mirabilis"]'::jsonb,
      'Staphylococcus saprophyticus ist novobiocinresistent und ein klassischer Erreger unkomplizierter Harnwegsinfekte bei sexuell aktiven jungen Frauen.',
      'Which coagulase-negative staphylococcal species is novobiocin resistant and commonly causes urinary tract infection in young women?',
      'Staphylococcus saprophyticus',
      '["Staphylococcus saprophyticus","Staphylococcus epidermidis","Staphylococcus aureus","Proteus mirabilis"]'::jsonb,
      'Staphylococcus saprophyticus is novobiocin resistant and is a classic cause of uncomplicated urinary tract infection in sexually active young women.'
    ),
    (
      'online-erklaert-mehr-mikrobiologie-04',
      'Mikrobiologie',
      'Welche Bakterienart besitzt eine Kapsel aus Poly-D-Glutamat?',
      'Bacillus anthracis',
      '["Bacillus anthracis","Klebsiella pneumoniae","Streptococcus pneumoniae","Haemophilus influenzae"]'::jsonb,
      'Bacillus anthracis ist besonders, weil seine Kapsel nicht aus Polysacchariden, sondern aus Poly-D-Glutamat besteht. Diese Besonderheit ist ein klassisches Pruefungsmerkmal.',
      'Which bacterial species has a capsule made of poly-D-glutamate?',
      'Bacillus anthracis',
      '["Bacillus anthracis","Klebsiella pneumoniae","Streptococcus pneumoniae","Haemophilus influenzae"]'::jsonb,
      'Bacillus anthracis is unusual because its capsule is made of poly-D-glutamate rather than polysaccharide. This is a classic high-yield distinguishing feature.'
    ),
    (
      'online-erklaert-mehr-mikrobiologie-05',
      'Mikrobiologie',
      'Welcher Pilz wird im Liquor klassisch mit India-Ink-Darstellung sichtbar gemacht?',
      'Cryptococcus neoformans',
      '["Cryptococcus neoformans","Candida albicans","Aspergillus fumigatus","Histoplasma capsulatum"]'::jsonb,
      'Cryptococcus neoformans besitzt eine dicke Polysaccharidkapsel, die in der India-Ink-Darstellung als heller Hof erkennbar wird. Das ist klassisch bei Kryptokokkenmeningitis.',
      'Which fungus is classically visualized in cerebrospinal fluid with an India ink preparation?',
      'Cryptococcus neoformans',
      '["Cryptococcus neoformans","Candida albicans","Aspergillus fumigatus","Histoplasma capsulatum"]'::jsonb,
      'Cryptococcus neoformans has a thick polysaccharide capsule that appears as a clear halo on India ink preparation. This is classic in cryptococcal meningitis.'
    ),
    (
      'online-erklaert-mehr-mikrobiologie-06',
      'Mikrobiologie',
      'Welches Bakterium benoetigt fuer die Kultur klassisch BCYE-Agar mit Cystein und Eisen?',
      'Legionella pneumophila',
      '["Legionella pneumophila","Mycoplasma pneumoniae","Bordetella pertussis","Pseudomonas aeruginosa"]'::jsonb,
      'Legionella pneumophila waechst schlecht auf Standardmedien und benoetigt buffered charcoal yeast extract mit Cystein und Eisen. Diese Kulturbedingung ist hochspezifisch fuer den Erreger.',
      'Which bacterium classically requires BCYE agar with cysteine and iron for culture?',
      'Legionella pneumophila',
      '["Legionella pneumophila","Mycoplasma pneumoniae","Bordetella pertussis","Pseudomonas aeruginosa"]'::jsonb,
      'Legionella pneumophila grows poorly on routine media and classically requires buffered charcoal yeast extract with cysteine and iron. This culture requirement is highly characteristic.'
    ),
    (
      'online-erklaert-mehr-mikrobiologie-07',
      'Mikrobiologie',
      'Welches Bakterium ist ureasepositiv und mit MALT-Lymphom des Magens assoziiert?',
      'Helicobacter pylori',
      '["Helicobacter pylori","Campylobacter jejuni","Vibrio cholerae","Yersinia enterocolitica"]'::jsonb,
      'Helicobacter pylori produziert Urease und besiedelt dadurch das saure Milieu des Magens. Eine chronische Infektion ist mit peptischen Ulzera, Adenokarzinom und MALT-Lymphom assoziiert.',
      'Which bacterium is urease positive and associated with gastric MALT lymphoma?',
      'Helicobacter pylori',
      '["Helicobacter pylori","Campylobacter jejuni","Vibrio cholerae","Yersinia enterocolitica"]'::jsonb,
      'Helicobacter pylori produces urease and can therefore survive in the acidic stomach environment. Chronic infection is associated with peptic ulcer disease, adenocarcinoma, and gastric MALT lymphoma.'
    ),
    (
      'online-erklaert-mehr-mikrobiologie-08',
      'Mikrobiologie',
      'Welches Virus verursacht Ringelroeteln und kann bei Patienten mit Haemolyse eine aplastische Krise ausloesen?',
      'Parvovirus B19',
      '["Parvovirus B19","Epstein-Barr-Virus","Cytomegalievirus","Adenovirus"]'::jsonb,
      'Parvovirus B19 infiziert Erythroblasten ueber das P-Antigen und kann dadurch die Erythropoese voruebergehend stoppen. Bei chronischer Haemolyse fuehrt das klassisch zur aplastischen Krise.',
      'Which virus causes erythema infectiosum and can trigger aplastic crisis in patients with hemolysis?',
      'Parvovirus B19',
      '["Parvovirus B19","Epstein-Barr virus","Cytomegalovirus","Adenovirus"]'::jsonb,
      'Parvovirus B19 infects erythroid precursors through the P antigen and can temporarily shut down erythropoiesis. In chronic hemolysis, this classically triggers aplastic crisis.'
    ),
    (
      'online-erklaert-mehr-mikrobiologie-09',
      'Mikrobiologie',
      'Welches Bakterium bildet verzweigte grampositive Filamente und ist schwach saeurefest?',
      'Nocardia',
      '["Nocardia","Actinomyces","Clostridium","Corynebacterium"]'::jsonb,
      'Nocardia ist aerob, bildet verzweigte Filamente und ist wegen Mykolsauren in der Zellwand schwach saeurefest. Actinomyces bildet zwar ebenfalls Filamente, ist aber nicht saeurefest.',
      'Which bacterium forms branching gram-positive filaments and is weakly acid-fast?',
      'Nocardia',
      '["Nocardia","Actinomyces","Clostridium","Corynebacterium"]'::jsonb,
      'Nocardia is aerobic, forms branching filaments, and is weakly acid-fast because of mycolic acids in its cell wall. Actinomyces may also branch but is not acid-fast.'
    ),
    (
      'online-erklaert-mehr-mikrobiologie-10',
      'Mikrobiologie',
      'Welcher Parasit ist klassisch mit Vitamin-B12-Mangel nach Verzehr von Suesswasserfisch assoziiert?',
      'Diphyllobothrium latum',
      '["Diphyllobothrium latum","Taenia solium","Ascaris lumbricoides","Enterobius vermicularis"]'::jsonb,
      'Diphyllobothrium latum, der Fischbandwurm, kann im Darm Vitamin B12 verbrauchen und so eine megaloblastaere Anaemie beguenstigen. Die Ansteckung erfolgt typischerweise ueber rohen oder ungenuegend gegarten Fisch.',
      'Which parasite is classically associated with vitamin B12 deficiency after ingestion of freshwater fish?',
      'Diphyllobothrium latum',
      '["Diphyllobothrium latum","Taenia solium","Ascaris lumbricoides","Enterobius vermicularis"]'::jsonb,
      'Diphyllobothrium latum, the fish tapeworm, can consume vitamin B12 in the intestine and thereby promote megaloblastic anemia. Infection classically follows raw or undercooked fish.'
    ),
    (
      'online-erklaert-mehr-pathologie-01',
      'Pathologie',
      'In welchen Zellen finden sich Auer-Staebchen klassisch?',
      'Myeloblasten',
      '["Myeloblasten","Lymphoblasten","Plasmazellen","Megakaryozyten"]'::jsonb,
      'Auer-Staebchen sind azurophile Einschluesse in myeloischen Blasten und sprechen klassisch fuer eine akute myeloische Leukamie. Sie helfen besonders bei der morphologischen Einordnung.',
      'In which cells are Auer rods classically found?',
      'Myeloblasts',
      '["Myeloblasts","Lymphoblasts","Plasma cells","Megakaryocytes"]'::jsonb,
      'Auer rods are azurophilic inclusions in myeloid blasts and classically point to acute myeloid leukemia. They are especially useful in morphologic classification.'
    ),
    (
      'online-erklaert-mehr-pathologie-02',
      'Pathologie',
      'Welche Tumorart zeigt histologisch typische Keratinperlen?',
      'Plattenepithelkarzinom',
      '["Plattenepithelkarzinom","Adenokarzinom","Basalzellkarzinom","Melanom"]'::jsonb,
      'Keratinperlen entstehen durch Verhornung maligner Plattenepithelzellen und sind ein klassischer histologischer Hinweis auf ein Plattenepithelkarzinom.',
      'Which tumor type classically shows keratin pearls on histology?',
      'Squamous cell carcinoma',
      '["Squamous cell carcinoma","Adenocarcinoma","Basal cell carcinoma","Melanoma"]'::jsonb,
      'Keratin pearls result from keratinization of malignant squamous cells and are a classic histologic clue to squamous cell carcinoma.'
    ),
    (
      'online-erklaert-mehr-pathologie-03',
      'Pathologie',
      'Welcher Stoff zeigt nach Kongorotfaerbung eine apfelgruene Doppelbrechung im polarisierten Licht?',
      'Amyloid',
      '["Amyloid","Fibrin","Kollagen","Elastin"]'::jsonb,
      'Amyloid bindet Kongorot und zeigt im polarisierten Licht die klassische apfelgruene Doppelbrechung. Dieses Merkmal ist diagnostisch fuer Amyloidablagerungen.',
      'Which substance shows apple-green birefringence under polarized light after Congo red staining?',
      'Amyloid',
      '["Amyloid","Fibrin","Collagen","Elastin"]'::jsonb,
      'Amyloid binds Congo red and shows classic apple-green birefringence under polarized light. This is a diagnostic hallmark of amyloid deposition.'
    ),
    (
      'online-erklaert-mehr-pathologie-04',
      'Pathologie',
      'Welche Tumorart zeigt klassisch Verocay-Koerperchen?',
      'Schwannom',
      '["Schwannom","Neurofibrom","Meningeom","Glioblastom"]'::jsonb,
      'Verocay-Koerperchen entstehen durch palisadenartige Anordnung von Zellkernen in Antoni-A-Arealen. Sie sind ein klassischer histologischer Befund beim Schwannom.',
      'Which tumor classically shows Verocay bodies?',
      'Schwannoma',
      '["Schwannoma","Neurofibroma","Meningioma","Glioblastoma"]'::jsonb,
      'Verocay bodies arise from palisading nuclei within Antoni A areas. They are a classic histologic feature of schwannoma.'
    ),
    (
      'online-erklaert-mehr-pathologie-05',
      'Pathologie',
      'Welche Schilddruesenkarzinomform zeigt Orphan-Annie-Eye-Kerne?',
      'Papillaeres Schilddruesenkarzinom',
      '["Papillaeres Schilddruesenkarzinom","Follikulaeres Schilddruesenkarzinom","Medullaeres Schilddruesenkarzinom","Anaplastisches Schilddruesenkarzinom"]'::jsonb,
      'Die optisch leeren Orphan-Annie-Eye-Kerne sind ein klassisches Merkmal des papillaeren Schilddruesenkarzinoms. Haeufig finden sich zusaetzlich Psammomkoerperchen und Kernfurchen.',
      'Which thyroid carcinoma classically shows Orphan Annie eye nuclei?',
      'Papillary thyroid carcinoma',
      '["Papillary thyroid carcinoma","Follicular thyroid carcinoma","Medullary thyroid carcinoma","Anaplastic thyroid carcinoma"]'::jsonb,
      'The optically clear Orphan Annie eye nuclei are a classic feature of papillary thyroid carcinoma. Psammoma bodies and nuclear grooves are also often present.'
    ),
    (
      'online-erklaert-mehr-pathologie-06',
      'Pathologie',
      'Bei welcher Erkrankung finden sich klassisch nichtverkasende Granulome mit Schaumann- und Asteroidkoerperchen?',
      'Sarkoidose',
      '["Sarkoidose","Tuberkulose","Morbus Crohn","Wegener-Granulomatose"]'::jsonb,
      'Die Sarkoidose zeigt typischerweise nichtverkasende Granulome. Schaumann- und Asteroidkoerperchen koennen darin vorkommen und stuetzen die Diagnose.',
      'In which disease are noncaseating granulomas with Schaumann and asteroid bodies classically found?',
      'Sarcoidosis',
      '["Sarcoidosis","Tuberculosis","Crohn disease","Granulomatosis with polyangiitis"]'::jsonb,
      'Sarcoidosis typically shows noncaseating granulomas. Schaumann and asteroid bodies may be present within them and support the diagnosis.'
    ),
    (
      'online-erklaert-mehr-pathologie-07',
      'Pathologie',
      'Welche Erkrankung ist histologisch durch Aschoff-Knoetchen im Herzen gekennzeichnet?',
      'Akutes rheumatisches Fieber',
      '["Akutes rheumatisches Fieber","Infektioese Endokarditis","Virale Myokarditis","Amyloidose"]'::jsonb,
      'Aschoff-Knoetchen sind granulomartige Entzuendungsherde im Herzen und gelten als klassischer Befund des akuten rheumatischen Fiebers nach Streptokokkeninfektion.',
      'Which disease is characterized histologically by Aschoff bodies in the heart?',
      'Acute rheumatic fever',
      '["Acute rheumatic fever","Infective endocarditis","Viral myocarditis","Amyloidosis"]'::jsonb,
      'Aschoff bodies are granuloma-like inflammatory foci in the heart and are a classic finding of acute rheumatic fever after streptococcal infection.'
    ),
    (
      'online-erklaert-mehr-pathologie-08',
      'Pathologie',
      'Welche Lymphomerkrankung ist klassisch mit Reed-Sternberg-Zellen assoziiert?',
      'Hodgkin-Lymphom',
      '["Hodgkin-Lymphom","Burkitt-Lymphom","Mantelzelllymphom","Multiples Myelom"]'::jsonb,
      'Reed-Sternberg-Zellen sind grosse atypische B-Zellen und ein diagnostisches Leitmerkmal des Hodgkin-Lymphoms. Ihre Identifikation ist zentral fuer die histologische Sicherung.',
      'Which lymphoma is classically associated with Reed-Sternberg cells?',
      'Hodgkin lymphoma',
      '["Hodgkin lymphoma","Burkitt lymphoma","Mantle cell lymphoma","Multiple myeloma"]'::jsonb,
      'Reed-Sternberg cells are large atypical B cells and a hallmark of Hodgkin lymphoma. Identifying them is central to histologic diagnosis.'
    ),
    (
      'online-erklaert-mehr-pathologie-09',
      'Pathologie',
      'Welche Hirntumorform zeigt histologisch pseudopalisadierende Nekrosen?',
      'Glioblastom',
      '["Glioblastom","Meningeom","Oligodendrogliom","Ependymom"]'::jsonb,
      'Das Glioblastom zeigt hochgradige Atypie, Mikrogefaessproliferation und pseudopalisadierende Nekrosen. Diese Kombination ist fuer den Tumor sehr charakteristisch.',
      'Which brain tumor shows pseudopalisading necrosis on histology?',
      'Glioblastoma',
      '["Glioblastoma","Meningioma","Oligodendroglioma","Ependymoma"]'::jsonb,
      'Glioblastoma shows marked atypia, microvascular proliferation, and pseudopalisading necrosis. This combination is highly characteristic.'
    ),
    (
      'online-erklaert-mehr-pathologie-10',
      'Pathologie',
      'Welche Form der Lupusnephritis zeigt klassisch Drahtschlingenlaesionen?',
      'Diffuse proliferative Lupusnephritis',
      '["Diffuse proliferative Lupusnephritis","Minimal-Change-Nephropathie","Membranoese Nephropathie","Amyloidose der Niere"]'::jsonb,
      'Die diffuse proliferative Lupusnephritis entspricht Klasse IV und zeigt ausgepraegte Immunkomplexablagerungen. Dadurch entstehen in der Lichtmikroskopie die klassischen Drahtschlingenlaesionen.',
      'Which form of lupus nephritis classically shows wire-loop lesions?',
      'Diffuse proliferative lupus nephritis',
      '["Diffuse proliferative lupus nephritis","Minimal change disease","Membranous nephropathy","Renal amyloidosis"]'::jsonb,
      'Diffuse proliferative lupus nephritis is class IV and shows heavy immune complex deposition. This produces the classic wire-loop lesions on light microscopy.'
    ),
    (
      'online-erklaert-mehr-radiologie-01',
      'Radiologie',
      'Welche Bildgebung ist bei Verdacht auf Nephrolithiasis beim nicht schwangeren Erwachsenen in der Regel erste Wahl?',
      'Nativ-CT des Abdomens',
      '["Nativ-CT des Abdomens","MRT des Abdomens","Abdomensonografie allein","Roentgen Abdomen leer"]'::jsonb,
      'Das Nativ-CT ist sehr sensitiv fuer Harnsteine und zeigt deren Lage sowie eine Harnstauung schnell an. Kontrastmittel ist dafuer in der Regel nicht noetig.',
      'Which imaging study is generally first-line for suspected nephrolithiasis in a nonpregnant adult?',
      'Non-contrast abdominal CT',
      '["Non-contrast abdominal CT","Abdominal MRI","Ultrasound alone","Plain abdominal radiograph"]'::jsonb,
      'Non-contrast CT is highly sensitive for urinary stones and rapidly shows their location as well as any obstruction. Contrast is generally not required.'
    ),
    (
      'online-erklaert-mehr-radiologie-02',
      'Radiologie',
      'Welche Bildgebung ist die initiale Standarduntersuchung bei Verdacht auf Subarachnoidalblutung?',
      'Nativ-CT des Schaedels',
      '["Nativ-CT des Schaedels","MRT mit Kontrastmittel","Sonografie des Schaedels","PET-CT"]'::jsonb,
      'Das Nativ-CT ist die initiale Standardbildgebung bei Verdacht auf Subarachnoidalblutung, weil frisches Blut akut hyperdens erscheint und schnell erkannt werden kann.',
      'Which imaging study is the initial standard test for suspected subarachnoid hemorrhage?',
      'Non-contrast head CT',
      '["Non-contrast head CT","MRI with contrast","Head ultrasound","PET-CT"]'::jsonb,
      'Non-contrast CT is the initial standard imaging test for suspected subarachnoid hemorrhage because fresh blood appears hyperdense and can be identified quickly.'
    ),
    (
      'online-erklaert-mehr-radiologie-03',
      'Radiologie',
      'Welche Untersuchung ist das klassische Screeningverfahren fuer ein abdominales Aortenaneurysma?',
      'Abdomensonografie',
      '["Abdomensonografie","CT-Angiografie","MRT-Angiografie","Roentgen Thorax"]'::jsonb,
      'Die Abdomensonografie ist schnell, strahlungsfrei und sensitiv genug fuer das Screening des abdominalen Aortenaneurysmas. Deshalb ist sie dafuer das Standardverfahren.',
      'Which study is the classic screening test for an abdominal aortic aneurysm?',
      'Abdominal ultrasound',
      '["Abdominal ultrasound","CT angiography","MR angiography","Chest radiograph"]'::jsonb,
      'Abdominal ultrasound is fast, radiation-free, and sufficiently sensitive for abdominal aortic aneurysm screening. It is therefore the standard screening test.'
    ),
    (
      'online-erklaert-mehr-radiologie-04',
      'Radiologie',
      'Welche Untersuchung misst standardmaessig die Knochendichte bei Osteoporoseverdacht?',
      'DEXA',
      '["DEXA","PET-CT","Nativ-CT des Beckens","Skelettszintigrafie"]'::jsonb,
      'Die Dual-Energy-X-ray-Absorptiometrie, kurz DEXA, ist der Standard zur quantitativen Bestimmung der Knochenmineraldichte. Sie dient deshalb der Diagnostik und Verlaufskontrolle der Osteoporose.',
      'Which study standardly measures bone density when osteoporosis is suspected?',
      'DEXA',
      '["DEXA","PET-CT","Non-contrast pelvic CT","Bone scintigraphy"]'::jsonb,
      'Dual-energy X-ray absorptiometry, or DEXA, is the standard method for quantitative bone mineral density measurement. It is therefore used for diagnosis and follow-up of osteoporosis.'
    ),
    (
      'online-erklaert-mehr-radiologie-05',
      'Radiologie',
      'Welche nuklearmedizinische Untersuchung folgt typischerweise bei weiterem Verdacht auf akute Cholezystitis nach unklarem Ultraschall?',
      'HIDA-Szintigrafie',
      '["HIDA-Szintigrafie","PET-CT","Knochenszintigrafie","Ventilationsszintigrafie"]'::jsonb,
      'Wenn der Ultraschall keine sichere Antwort liefert, kann die HIDA-Szintigrafie den Verschluss des Ductus cysticus funktionell nachweisen. Das hilft besonders bei weiterhin hohem klinischem Verdacht.',
      'Which nuclear medicine study typically follows when acute cholecystitis is still suspected after an equivocal ultrasound?',
      'HIDA scan',
      '["HIDA scan","PET-CT","Bone scan","Ventilation scan"]'::jsonb,
      'If ultrasound remains inconclusive, a HIDA scan can functionally demonstrate cystic duct obstruction. This is especially useful when clinical suspicion remains high.'
    ),
    (
      'online-erklaert-mehr-radiologie-06',
      'Radiologie',
      'Welche Bildgebung ist bei Verdacht auf tiefe Beinvenenthrombose in der Schwangerschaft erste Wahl?',
      'Kompressionssonografie',
      '["Kompressionssonografie","CT-Phlebografie","PET-CT","DEXA"]'::jsonb,
      'Die Kompressionssonografie ist in der Schwangerschaft erste Wahl, weil sie ohne ionisierende Strahlung auskommt und proximale Thrombosen gut erfasst.',
      'Which imaging study is first-line for suspected deep venous thrombosis in pregnancy?',
      'Compression ultrasonography',
      '["Compression ultrasonography","CT venography","PET-CT","DEXA"]'::jsonb,
      'Compression ultrasonography is first-line in pregnancy because it avoids ionizing radiation and detects proximal thrombosis well.'
    ),
    (
      'online-erklaert-mehr-radiologie-07',
      'Radiologie',
      'Welcher Roentgenbefund im Stehen spricht klassisch fuer ein Pneumoperitoneum?',
      'Freie Luft subdiaphragmal',
      '["Freie Luft subdiaphragmal","Verkuerzte Rippen","Verbreiterter Mediastinumschatten","A-Linien beidseits"]'::jsonb,
      'Freie Luft unter dem Zwerchfell im Stehen ist ein klassischer Hinweis auf Pneumoperitoneum, etwa bei Hohlorganperforation. Dieser Befund ist akut chirurgisch relevant.',
      'Which upright radiographic finding classically suggests pneumoperitoneum?',
      'Free subdiaphragmatic air',
      '["Free subdiaphragmatic air","Shortened ribs","Widened mediastinum","Bilateral A-lines"]'::jsonb,
      'Free air beneath the diaphragm on an upright radiograph is a classic sign of pneumoperitoneum, for example after perforation of a hollow viscus. This finding is acutely relevant to surgery.'
    ),
    (
      'online-erklaert-mehr-radiologie-08',
      'Radiologie',
      'Welche Bildgebung ist am sensitivsten fuer demyelinisierende Herde bei Multipler Sklerose?',
      'MRT',
      '["MRT","Roentgen des Schaedels","DEXA","Sonografie des Thorax"]'::jsonb,
      'Die MRT ist am sensitivsten fuer die Darstellung entzuendlich-demyelinisierender Herde im Gehirn und Rueckenmark. Deshalb ist sie die zentrale Bildgebung bei Multipler Sklerose.',
      'Which imaging modality is most sensitive for demyelinating plaques in multiple sclerosis?',
      'MRI',
      '["MRI","Skull radiograph","DEXA","Thoracic ultrasound"]'::jsonb,
      'MRI is the most sensitive imaging modality for inflammatory demyelinating lesions in the brain and spinal cord. It is therefore the central imaging study in multiple sclerosis.'
    ),
    (
      'online-erklaert-mehr-radiologie-09',
      'Radiologie',
      'Welche Bildgebung ist bei erwachsenem Hochrisiko-Zervikaltrauma initial meist die Standarduntersuchung?',
      'CT der Halswirbelsaeule',
      '["CT der Halswirbelsaeule","MRT der Schulter","Roentgen des Beckens","DEXA"]'::jsonb,
      'Bei erwachsenen Hochrisikopatienten ist das CT der Halswirbelsaeule wegen seiner hohen Sensitivitaet fuer Frakturen die Standardbildgebung in der Akutsituation.',
      'Which imaging study is usually the initial standard in an adult with high-risk cervical spine trauma?',
      'CT of the cervical spine',
      '["CT of the cervical spine","MRI of the shoulder","Pelvic radiograph","DEXA"]'::jsonb,
      'In high-risk adult trauma patients, CT of the cervical spine is the standard acute imaging test because of its high sensitivity for fractures.'
    ),
    (
      'online-erklaert-mehr-radiologie-10',
      'Radiologie',
      'Welche Untersuchung erlaubt am Bett eine direkte Beurteilung der linksventrikulaeren Ejektionsfraktion?',
      'Echokardiografie',
      '["Echokardiografie","DEXA","Nativ-CT des Beckens","Mammografie"]'::jsonb,
      'Die Echokardiografie liefert in Echtzeit Information ueber Wandbewegung, Klappenfunktion und Ejektionsfraktion. Deshalb ist sie die klassische Bettkantenuntersuchung in der Kardiologie.',
      'Which study allows bedside direct assessment of left ventricular ejection fraction?',
      'Echocardiography',
      '["Echocardiography","DEXA","Non-contrast pelvic CT","Mammography"]'::jsonb,
      'Echocardiography provides real-time information on wall motion, valve function, and ejection fraction. It is therefore the classic bedside cardiac imaging study.'
    )
),
upsert_questions as (
  insert into public.questions (
    slug,
    category,
    question,
    correct_answer,
    options,
    explanation
  )
  select
    slug,
    category,
    question_de,
    correct_de,
    options_de,
    explanation_de
  from question_rows
  on conflict (slug) do update
    set category = excluded.category,
        question = excluded.question,
        correct_answer = excluded.correct_answer,
        options = excluded.options,
        explanation = excluded.explanation,
        updated_at = now()
  returning id, slug
)
insert into public.question_translations (
  question_id,
  language,
  question,
  options,
  correct_answer,
  explanation
)
select
  upsert_questions.id,
  'en',
  question_rows.question_en,
  question_rows.options_en,
  question_rows.correct_en,
  question_rows.explanation_en
from upsert_questions
join question_rows
  on question_rows.slug = upsert_questions.slug
on conflict (question_id, language) do update
  set question = excluded.question,
      options = excluded.options,
      correct_answer = excluded.correct_answer,
      explanation = excluded.explanation,
      updated_at = now();
