with updates (slug, explanation) as (
  values
    ('anatomie-lungenkreislauf', 'Der rechte Ventrikel pumpt Blut ueber die A. pulmonalis in den Lungenkreislauf. Dort wird es oxygeniert und gelangt ueber die Lungenvenen in den linken Vorhof.'),
    ('anatomie-leicht-01', 'Der Humerus bildet den Oberarm und verbindet Schulter mit dem Ellenbogen. Proximal artikuliert er mit der Scapula, distal mit Radius und Ulna.'),
    ('anatomie-leicht-02', 'Das Herz besitzt zwei Vorhoefe und zwei Ventrikel. So bleiben O2-armes und O2-reiches Blut in getrennten Kreislaufen.'),
    ('anatomie-leicht-03', 'Der M. gluteus maximus ist der groesste Muskel des Koerpers. Er streckt die Huefte und ist wichtig beim Aufstehen und Treppensteigen.'),
    ('anatomie-leicht-04', 'Die Milz liegt im linken Oberbauch unter dem Rippenbogen. Sie filtert Blut, baut alte Erythrozyten ab und unterstuetzt die Immunabwehr.'),
    ('anatomie-leicht-05', 'Die Patella ist ein Sesambein in der Quadrizepssehne. Sie vergroessert den Hebelarm des Kniestreckers und schuetzt das Gelenk.'),
    ('anatomie-mittel-01', 'Der N. musculocutaneus stammt aus dem Plexus brachialis (C5-C7) und innerviert Bizeps und Brachialis. Sensibel versorgt er die laterale Unterarmhaut.'),
    ('anatomie-mittel-02', 'Das Vorhofseptum trennt rechten und linken Vorhof. Ein persistierendes Foramen ovale kann einen Rechts-Links-Shunt ermoeglichen.'),
    ('anatomie-mittel-03', 'Die A. carotis interna versorgt den vorderen Hirnkreislauf und teilt sich in A. cerebri anterior und media. Sie speist grosse Teile der Grosshirnhemisphaeren.'),
    ('anatomie-mittel-04', 'Die rechte Lunge hat drei Lappen. Links sind es zwei Lappen, weil das Herz Raum einnimmt.'),
    ('anatomie-mittel-05', 'Das Foramen magnum liegt im Os occipitale. Durch die Oeffnung ziehen Medulla oblongata, Meningen und die Aa. vertebrales.'),
    ('anatomie-schwer-01', 'Durch das Foramen ovale zieht der N. mandibularis (V3) aus der mittleren Schaedelgrube. Er fuehrt motorische Fasern fuer die Kaumuskulatur und sensible Fasern fuer den Unterkiefer.'),
    ('anatomie-schwer-02', 'Zur Rotatorenmanschette gehoeren Supraspinatus, Infraspinatus, Teres minor und Subscapularis. Sie stabilisieren das Schultergelenk und ermoeglichen Rotation.'),
    ('anatomie-schwer-03', 'Die A. vesicalis superior entspringt aus der A. iliaca interna, meist als Ast der A. umbilicalis. Sie versorgt den oberen Teil der Harnblase.'),
    ('anatomie-schwer-04', 'Der Axis (C2) besitzt den Dens axis. Er bildet das Drehgelenk mit dem Atlas und ermoeglicht die Kopfdrehung.'),
    ('anatomie-schwer-05', 'Die Submukosa liegt direkt unter der Mukosa und enthaelt Gefaesse, Lymphbahnen und den Plexus submucosus. Sie ist wichtig fuer Sekretion und Durchblutung.'),
    ('physiologie-insulin', 'Insulin wird in den Beta-Zellen des Pankreas gebildet. Es senkt den Blutzucker durch vermehrte Glukoseaufnahme und foerdert Glykogenspeicherung.'),
    ('physiologie-leicht-01', 'Glukagon wird in den Alpha-Zellen des Pankreas gebildet. Es steigert den Blutzucker durch Glykogenolyse und Glukoneogenese und wirkt Insulin entgegen.'),
    ('physiologie-leicht-02', 'Die Einatemluft enthaelt etwa 21 % O2. In den Alveolen ist der O2-Anteil geringer, weil Wasserdampf und CO2 den Partialdruck senken.'),
    ('physiologie-leicht-03', 'Kalium bestimmt das Ruhemembranpotential, da die Membran in Ruhe vor allem fuer K+ permeabel ist. Die Na/K-ATPase haelt den Konzentrationsgradienten aufrecht.'),
    ('physiologie-leicht-04', 'Der Sinusknoten im rechten Vorhof erzeugt den Grundrhythmus des Herzens. Er feuert spontan und gibt typischerweise 60 bis 100 Impulse pro Minute vor.'),
    ('physiologie-leicht-05', 'Barorezeptoren im Karotissinus und Aortenbogen messen Druckaenderungen. Ueber vegetative Reflexe regulieren sie kurzfristig Herzfrequenz und Gefaesstonus.'),
    ('physiologie-mittel-01', 'Primaer aktiver Transport nutzt ATP direkt, z. B. die Na/K-ATPase. Sekundaer aktiver Transport verwendet den aufgebauten Ionengradienten.'),
    ('physiologie-mittel-02', 'Belegzellen produzieren Salzsaeure mit sehr niedrigem pH. Sie aktiviert Pepsinogen und dient der Keimabwehr; ausserdem bilden Belegzellen den Intrinsic Factor.'),
    ('physiologie-mittel-03', 'Erythrozyten leben etwa 120 Tage und werden vor allem in der Milz abgebaut. Da sie keinen Zellkern besitzen, koennen sie keine Proteine nachbilden.'),
    ('physiologie-mittel-04', 'Die Alveolen sind der Ort des Gasaustauschs mit extrem duennen Waenden und grosser Oberflaeche. O2 diffundiert ins Blut, CO2 in die Ausatemluft.'),
    ('physiologie-mittel-05', 'ADH wird im Hypothalamus gebildet und aus dem Hypophysenhinterlappen freigesetzt. Es foerdert Aquaporine im Sammelrohr und steigert die Wasserresorption.'),
    ('physiologie-schwer-01', 'Im Sinusknoten entsteht Phase 0 durch L-Typ-Calciumkanaele, nicht durch schnelle Natriumkanaele. Das erklaert den langsameren Aufstrich der Aktionspotentiale.'),
    ('physiologie-schwer-02', 'Die Henle-Schleife erzeugt den Gegenstromgradienten in der Nierenmarksubstanz. Der dicke aufsteigende Ast transportiert NaCl ohne Wasser und macht das Interstitium hyperosmolar.'),
    ('physiologie-schwer-03', 'Ein pH-Abfall verschiebt die O2-Bindungskurve nach rechts und erleichtert die O2-Abgabe im Gewebe. Aehnlich wirken Temperaturanstieg, CO2-Anstieg und mehr 2,3-BPG.'),
    ('physiologie-schwer-04', 'Die isovolumetrische Kontraktion beginnt direkt nach Schluss der AV-Klappen. Der Ventrikeldruck steigt bei konstantem Volumen, bis die Taschenklappen oeffnen.'),
    ('physiologie-schwer-05', 'Pneumozyten Typ II produzieren Surfactant und senken die Oberflaechenspannung der Alveolen. Sie koennen sich teilen und Typ-I-Zellen ersetzen.'),
    ('pharmakologie-vitamin-k-antagonist', 'Warfarin hemmt die Vitamin-K-Epoxid-Reduktase und reduziert die Aktivierung der Faktoren II, VII, IX und X. Die Wirkung setzt verzoegert ein und erfordert INR-Kontrolle.'),
    ('pharmakologie-leicht-01', 'Ibuprofen hemmt COX-1 und COX-2 und reduziert Prostaglandine. Dadurch wirkt es analgetisch, antipyretisch und antiinflammatorisch.'),
    ('pharmakologie-leicht-02', 'Metoprolol ist ein selektiver Beta1-Blocker. Er senkt Herzfrequenz und Blutdruck und reduziert den Sauerstoffbedarf des Herzens.'),
    ('pharmakologie-leicht-03', 'Amoxicillin ist ein Beta-Laktam-Antibiotikum, das die Zellwandsynthese hemmt. Es wirkt bakterizid und hat ein breites Spektrum.'),
    ('pharmakologie-leicht-04', 'Omeprazol ist ein Protonenpumpenhemmer und blockiert die H+/K+-ATPase irreversibel. Dadurch sinkt die Saeureproduktion im Magen.'),
    ('pharmakologie-leicht-05', 'Morphin ist ein starker Opioid-Agonist am mu-Rezeptor. Neben Analgesie koennen Atemdepression und Abhaengigkeit auftreten.'),
    ('pharmakologie-mittel-01', 'Atorvastatin hemmt die HMG-CoA-Reduktase und senkt die Cholesterinsynthese. Das reduziert LDL und das Risiko atherosklerotischer Ereignisse.'),
    ('pharmakologie-mittel-02', 'Furosemid hemmt den Na-K-2Cl-Cotransporter im dicken aufsteigenden Ast der Henle-Schleife. Es verursacht starke Diurese und kann Hypokaliaemie ausloesen.'),
    ('pharmakologie-mittel-03', 'ACE-Hemmer erhoehen Bradykinin, was trockenen Reizhusten ausloesen kann. Deshalb wird bei Husten oft auf AT1-Blocker gewechselt.'),
    ('pharmakologie-mittel-04', 'Rivaroxaban hemmt Faktor Xa direkt und oral. Es benoetigt keine routinemaessige INR-Kontrolle wie Warfarin.'),
    ('pharmakologie-mittel-05', 'Sertralin ist ein SSRI und erhoeht Serotonin im synaptischen Spalt. Es wird bei Depression, Angst und Zwangsstoerungen eingesetzt.'),
    ('pharmakologie-schwer-01', 'N-Acetylcystein fuellt Glutathion auf und entgiftet das toxische NAPQI. Es ist das Standardantidot bei Paracetamol-Ueberdosierung und wirkt am besten frueh.'),
    ('pharmakologie-schwer-02', 'Rocuronium blockiert nikotinische ACh-Rezeptoren an der motorischen Endplatte kompetitiv. Die Laehmung kann mit Sugammadex aufgehoben werden.'),
    ('pharmakologie-schwer-03', 'Amiodaron blockiert vor allem K-Kanaele und verlaengert die Repolarisation (Klasse III). Es kann aber Schilddruese, Lunge und Leber schaedigen.'),
    ('pharmakologie-schwer-04', 'Infliximab ist ein monoklonaler Antikoerper gegen TNF-alpha. Es wird bei Autoimmunerkrankungen eingesetzt und erhoeht das Risiko fuer Infektionen wie Tuberkulose.'),
    ('pharmakologie-schwer-05', 'Heparin aktiviert Antithrombin III und hemmt dadurch Thrombin und Faktor Xa. Die Wirkung tritt sofort ein und wird ueber die aPTT gesteuert.'),
    ('mikrobiologie-epstein-barr', 'Das Epstein-Barr-Virus infiziert B-Zellen und verursacht infektioese Mononukleose. Typisch sind Halsschmerzen, Lymphknotenschwellung und Splenomegalie.'),
    ('mikrobiologie-leicht-01', 'Staphylococcus aureus ist ein grampositiver Kokkus in Traubenlagerung. Er ist koagulasepositiv und haeufige Ursache von Haut- und Weichteilinfektionen.'),
    ('mikrobiologie-leicht-02', 'Flagellen sind fadenfoermige Strukturen aus Flagellin. Sie ermoeglichen Bewegung und Chemotaxis in Fluessigkeiten.'),
    ('mikrobiologie-leicht-03', 'RNA-Viren besitzen RNA als Genom und benoetigen eine RNA-abhaengige RNA-Polymerase. Sie mutieren meist schneller als DNA-Viren.'),
    ('mikrobiologie-leicht-04', 'Tinea ist eine Dermatophyteninfektion der Haut. Erreger wie Trichophyton nutzen Keratin in Haut, Haaren oder Naegeln.'),
    ('mikrobiologie-leicht-05', 'Masern werden durch das Masernvirus verursacht. Typisch sind Fieber, Exanthem und eine voruebergehende Immunsuppression.'),
    ('mikrobiologie-mittel-01', 'Escherichia coli stammt haeufig aus der Darmflora und besitzt Adhaesionsfaktoren fuer Uroepithel. Deshalb verursacht es die meisten unkomplizierten Harnwegsinfekte.'),
    ('mikrobiologie-mittel-02', 'Clostridium tetani ist anaerob und bildet Sporen. Sein Tetanospasmin blockiert inhibitorische Neurone und fuehrt zu spastischen Kraempfen.'),
    ('mikrobiologie-mittel-03', 'Rotaviren sind eine der haeufigsten Ursachen kindlicher Gastroenteritis. Sie verursachen waessrige Diarrhoe und koennen zu schneller Dehydratation fuehren.'),
    ('mikrobiologie-mittel-04', 'Mycobacterium tuberculosis ist saeurefest wegen Mykolsauren in der Zellwand. Dadurch benoetigt es spezielle Faerbungen wie Ziehl-Neelsen.'),
    ('mikrobiologie-mittel-05', 'Mycoplasma pneumoniae verursacht eine atypische Pneumonie mit trockenem Husten. Ohne Zellwand wirken Beta-Laktame nicht.'),
    ('mikrobiologie-schwer-01', 'Borrelia burgdorferi wird durch Ixodes-Zecken uebertragen. Frueh zeigt sich ein Erythema migrans, spaeter koennen Neuro- oder Gelenksymptome folgen.'),
    ('mikrobiologie-schwer-02', 'Das mecA-Gen codiert PBP2a, ein veraendertes Penicillin-Bindeprotein. Dadurch sind MRSA gegen viele Beta-Laktam-Antibiotika resistent.'),
    ('mikrobiologie-schwer-03', 'HIV ist ein Retrovirus mit Reverse Transkriptase. Es integriert sein Genom und infiziert vor allem CD4-T-Helferzellen.'),
    ('mikrobiologie-schwer-04', 'Legionella pneumophila verbreitet sich ueber Aerosole aus Wasseranlagen. Sie lebt intrazellulaer in Makrophagen und verursacht eine schwere atypische Pneumonie.'),
    ('mikrobiologie-schwer-05', 'Mycoplasmen besitzen keine Zellwand und sind pleomorph. Deshalb wirken Beta-Laktame nicht, und Makrolide sind haeufig Mittel der Wahl.'),
    ('pathologie-reed-sternberg', 'Reed-Sternberg-Zellen sind grosse, binukleare B-Zellen und das diagnostische Merkmal des Hodgkin-Lymphoms. Sie exprimieren typischerweise CD15 und CD30.'),
    ('pathologie-leicht-01', 'Ein Lipom ist ein gutartiger Tumor des Fettgewebes. Es ist meist weich, verschieblich und langsam wachsend.'),
    ('pathologie-leicht-02', 'Appendizitis ist die Entzuendung des Appendix vermiformis, oft durch Lumeneinengung oder Kotstein. Unbehandelt kann sie perforieren.'),
    ('pathologie-leicht-03', 'Fieber ist eine Erhoehung der Koerperkerntemperatur ueber 38 C durch einen hoeheren Sollwert im Hypothalamus. Pyrogene Zytokine sind eine haeufige Ursache.'),
    ('pathologie-leicht-04', 'Ein Infarkt ist Gewebsuntergang durch akute Ischaemie. Typische Beispiele sind Myokard- oder Hirninfarkt.'),
    ('pathologie-leicht-05', 'Petechien sind punktfoermige Hauteinblutungen durch Kapillarschaedigung oder Thrombozytopenie. Sie sind nicht wegdrueckbar.'),
    ('pathologie-mittel-01', 'PSA ist ein Marker fuer Prostatagewebe und wird bei Karzinom erhoeht gefunden. Er kann aber auch bei benigner Prostatahyperplasie ansteigen, daher dient er vor allem der Verlaufskontrolle.'),
    ('pathologie-mittel-02', 'Koagulationsnekrose ist typisch bei ischaemischen Infarkten des Herzens. Die Gewebsarchitektur bleibt zunaechst erhalten, obwohl Zellen abgestorben sind.'),
    ('pathologie-mittel-03', 'Metaplasie ist eine reversible Anpassung an chronische Reize. Beispiel ist Plattenepithelmetaplasie in den Bronchien von Rauchern.'),
    ('pathologie-mittel-04', 'Hashimoto-Thyreoiditis ist eine autoimmune Schilddruesenentzuendung mit Anti-TPO-Antikoerpern. Sie fuehrt haeufig zu Hypothyreose.'),
    ('pathologie-mittel-05', 'Mastzellen tragen IgE auf der Oberflaeche und degranulieren nach Allergenkontakt. Histamin verursacht Juckreiz, Quaddeln und Bronchospasmus.'),
    ('pathologie-schwer-01', 't(9;22) erzeugt das BCR-ABL-Fusionsprotein, das als Tyrosinkinase dauerhaft aktiv ist. Dieses Philadelphia-Chromosom ist typisch fuer CML und Ziel von Imatinib.'),
    ('pathologie-schwer-02', 'AL-Amyloid besteht aus Immunglobulin-Leichtketten. Es tritt bei Plasmazellerkrankungen wie multiplem Myelom auf und kann Organe infiltrieren.'),
    ('pathologie-schwer-03', 'HPV 16 und 18 sind Hochrisiko-Typen fuer Zervixkarzinom. Die Onkoproteine E6 und E7 inaktivieren p53 und Rb.'),
    ('pathologie-schwer-04', 'Anti-GBM-Antikoerper richten sich gegen die Basalmembran von Lunge und Niere. Klinisch zeigen sich Haemoptysen und rasch progrediente Glomerulonephritis.'),
    ('pathologie-schwer-05', 'RB1 ist ein Tumorsuppressor, der nach dem Zwei-Treffer-Modell inaktiviert wird. Das fuehrt zu Retinoblastom, oft bilateral bei erblichen Faellen.')
)
update public.questions q
set explanation = u.explanation
from updates u
where q.slug = u.slug
  and (q.explanation is null or btrim(q.explanation) = '');
