-- Expand online question pools with another precise bilingual pack and stronger explanations.

with question_rows (
  slug,
  category,
  question_de,
  correct_de,
  options_de,
  explanation_de,
  question_en,
  correct_en,
  options_en,
  explanation_en
) as (
  values
    (
      'online-erklaert-anatomie-01',
      'Anatomie',
      'Welcher Hirnnerv zieht durch das Foramen ovale?',
      'N. mandibularis',
      '["N. mandibularis","N. maxillaris","N. ophthalmicus","N. facialis"]'::jsonb,
      'Durch das Foramen ovale zieht der dritte Ast des Nervus trigeminus, also der N. mandibularis. Der N. maxillaris verlaeuft dagegen durch das Foramen rotundum.',
      'Which cranial nerve passes through the foramen ovale?',
      'Mandibular nerve',
      '["Mandibular nerve","Maxillary nerve","Ophthalmic nerve","Facial nerve"]'::jsonb,
      'The foramen ovale transmits the third branch of the trigeminal nerve, the mandibular nerve. The maxillary nerve passes through the foramen rotundum instead.'
    ),
    (
      'online-erklaert-anatomie-02',
      'Anatomie',
      'Welche Nervenstruktur verlaeuft durch den Karpaltunnel?',
      'N. medianus',
      '["N. medianus","N. ulnaris","N. radialis","N. musculocutaneus"]'::jsonb,
      'Im Karpaltunnel verlaufen die Fingerbeugesehnen und der N. medianus. Der N. ulnaris zieht ausserhalb des Karpaltunnels in der Guyon-Loge.',
      'Which nerve structure passes through the carpal tunnel?',
      'Median nerve',
      '["Median nerve","Ulnar nerve","Radial nerve","Musculocutaneous nerve"]'::jsonb,
      'The carpal tunnel contains the flexor tendons and the median nerve. The ulnar nerve travels outside the carpal tunnel in Guyon canal.'
    ),
    (
      'online-erklaert-anatomie-03',
      'Anatomie',
      'Welcher Muskel initiiert die ersten 15 Grad der Armabduktion?',
      'M. supraspinatus',
      '["M. supraspinatus","M. deltoideus","M. infraspinatus","M. subscapularis"]'::jsonb,
      'Die initiale Abduktion des Arms wird durch den M. supraspinatus eingeleitet. Erst danach uebernimmt vor allem der M. deltoideus den Hauptanteil der Bewegung.',
      'Which muscle initiates the first 15 degrees of arm abduction?',
      'Supraspinatus muscle',
      '["Supraspinatus muscle","Deltoid muscle","Infraspinatus muscle","Subscapularis muscle"]'::jsonb,
      'The first part of arm abduction is initiated by the supraspinatus muscle. After that, the deltoid becomes the main abductor.'
    ),
    (
      'online-erklaert-anatomie-04',
      'Anatomie',
      'Welche Arterie verlaeuft in der Foveola radialis, also der Tabatiere?',
      'A. radialis',
      '["A. radialis","A. ulnaris","A. brachialis","A. axillaris"]'::jsonb,
      'Die A. radialis verlaeuft oberflaechlich in der Tabatiere und ist dort klinisch tastbar. Die A. ulnaris zieht auf der ulnaren Seite des Unterarms.',
      'Which artery runs through the anatomical snuffbox?',
      'Radial artery',
      '["Radial artery","Ulnar artery","Brachial artery","Axillary artery"]'::jsonb,
      'The radial artery runs superficially through the anatomical snuffbox and can be palpated there. The ulnar artery courses along the ulnar side of the forearm.'
    ),
    (
      'online-erklaert-anatomie-05',
      'Anatomie',
      'Welcher Hirnnerv innerviert den M. rectus lateralis?',
      'N. abducens',
      '["N. abducens","N. oculomotorius","N. trochlearis","N. opticus"]'::jsonb,
      'Der M. rectus lateralis wird vom N. abducens innerviert und bewirkt die Abduktion des Bulbus. Eine Laesion fuehrt typischerweise zu Doppelbildern mit Einwaertsschielen.',
      'Which cranial nerve innervates the lateral rectus muscle?',
      'Abducens nerve',
      '["Abducens nerve","Oculomotor nerve","Trochlear nerve","Optic nerve"]'::jsonb,
      'The lateral rectus muscle is innervated by the abducens nerve and abducts the eyeball. A lesion typically causes diplopia with medial deviation of the eye.'
    ),
    (
      'online-erklaert-anatomie-06',
      'Anatomie',
      'Welchem Dermatom wird der Daumen typischerweise zugeordnet?',
      'C6',
      '["C6","C5","C7","C8"]'::jsonb,
      'Der Daumen gehoert klassisch zum Dermatom C6. Der Mittelfinger wird eher C7 und der Kleinfinger C8 zugeordnet.',
      'Which dermatome is classically assigned to the thumb?',
      'C6',
      '["C6","C5","C7","C8"]'::jsonb,
      'The thumb is classically assigned to the C6 dermatome. The middle finger is more typical of C7 and the little finger of C8.'
    ),
    (
      'online-erklaert-anatomie-07',
      'Anatomie',
      'Welche Vene drainiert aus der Orbita in den Sinus cavernosus?',
      'V. ophthalmica superior',
      '["V. ophthalmica superior","V. jugularis interna","V. facialis anterior","V. retromandibularis"]'::jsonb,
      'Die V. ophthalmica superior verbindet die Orbita mit dem Sinus cavernosus. Diese venoese Verbindung erklaert die klinische Ausbreitung von Infektionen aus dem Gesichtsbereich.',
      'Which vein drains from the orbit into the cavernous sinus?',
      'Superior ophthalmic vein',
      '["Superior ophthalmic vein","Internal jugular vein","Anterior facial vein","Retromandibular vein"]'::jsonb,
      'The superior ophthalmic vein connects the orbit to the cavernous sinus. This venous connection explains how facial infections can spread intracranially.'
    ),
    (
      'online-erklaert-anatomie-08',
      'Anatomie',
      'Welche Arterie versorgt den Femurkopf beim Erwachsenen ueberwiegend?',
      'A. circumflexa femoris medialis',
      '["A. circumflexa femoris medialis","A. obturatoria","A. femoralis superficialis","A. circumflexa iliaca superficialis"]'::jsonb,
      'Die wichtigste Blutversorgung des Femurkopfs beim Erwachsenen stammt aus der A. circumflexa femoris medialis. Deshalb gefaehrden Schenkelhalsfrakturen diese Perfusion besonders.',
      'Which artery provides the main blood supply to the adult femoral head?',
      'Medial circumflex femoral artery',
      '["Medial circumflex femoral artery","Obturator artery","Superficial femoral artery","Superficial circumflex iliac artery"]'::jsonb,
      'The adult femoral head receives most of its blood supply from the medial circumflex femoral artery. This is why femoral neck fractures particularly endanger femoral head perfusion.'
    ),
    (
      'online-erklaert-anatomie-09',
      'Anatomie',
      'Welcher Muskel abductiert den Arm vor allem zwischen 15 und 90 Grad?',
      'M. deltoideus',
      '["M. deltoideus","M. supraspinatus","M. latissimus dorsi","M. pectoralis major"]'::jsonb,
      'Nach der initialen Abduktion durch den M. supraspinatus uebernimmt der M. deltoideus den Hauptanteil der Bewegung bis etwa 90 Grad.',
      'Which muscle mainly abducts the arm between 15 and 90 degrees?',
      'Deltoid muscle',
      '["Deltoid muscle","Supraspinatus muscle","Latissimus dorsi muscle","Pectoralis major muscle"]'::jsonb,
      'After the supraspinatus initiates abduction, the deltoid muscle becomes the main arm abductor up to about 90 degrees.'
    ),
    (
      'online-erklaert-anatomie-10',
      'Anatomie',
      'Welcher Nerv innerviert das Zwerchfell motorisch?',
      'N. phrenicus',
      '["N. phrenicus","N. vagus","N. thoracicus longus","N. accessorius"]'::jsonb,
      'Das Zwerchfell wird motorisch durch den N. phrenicus aus C3 bis C5 innerviert. Deshalb lautet die Merkhilfe fuer seine Wurzeln oft C3, 4, 5 keep the diaphragm alive.',
      'Which nerve provides motor innervation to the diaphragm?',
      'Phrenic nerve',
      '["Phrenic nerve","Vagus nerve","Long thoracic nerve","Accessory nerve"]'::jsonb,
      'The diaphragm receives motor innervation from the phrenic nerve arising from C3 to C5. That is why the classic memory aid is C3, 4, 5 keep the diaphragm alive.'
    ),
    (
      'online-erklaert-biochemie-01',
      'Biochemie',
      'Welches Enzym ist das geschwindigkeitsbestimmende Enzym der Glykolyse?',
      'Phosphofructokinase-1',
      '["Phosphofructokinase-1","Hexokinase","Pyruvatkinase","Laktatdehydrogenase"]'::jsonb,
      'Die Phosphofructokinase-1 ist das zentrale Regulationsenzym der Glykolyse. Sie reagiert auf den Energiezustand der Zelle und wird unter anderem durch ATP gehemmt und durch AMP stimuliert.',
      'Which enzyme is the rate-limiting enzyme of glycolysis?',
      'Phosphofructokinase-1',
      '["Phosphofructokinase-1","Hexokinase","Pyruvate kinase","Lactate dehydrogenase"]'::jsonb,
      'Phosphofructokinase-1 is the key regulatory enzyme of glycolysis. It senses cellular energy state and is inhibited by ATP and stimulated by AMP.'
    ),
    (
      'online-erklaert-biochemie-02',
      'Biochemie',
      'Welches Enzym katalysiert den ersten obligaten Schritt des Harnstoffzyklus?',
      'Carbamoylphosphat-Synthetase I',
      '["Carbamoylphosphat-Synthetase I","Ornithin-Transcarbamylase","Arginase","Succinat-Dehydrogenase"]'::jsonb,
      'Die Carbamoylphosphat-Synthetase I liegt in den Mitochondrien und startet den Harnstoffzyklus durch Bildung von Carbamoylphosphat aus Ammoniak und Bicarbonat.',
      'Which enzyme catalyzes the first committed step of the urea cycle?',
      'Carbamoyl phosphate synthetase I',
      '["Carbamoyl phosphate synthetase I","Ornithine transcarbamylase","Arginase","Succinate dehydrogenase"]'::jsonb,
      'Carbamoyl phosphate synthetase I is located in mitochondria and starts the urea cycle by forming carbamoyl phosphate from ammonia and bicarbonate.'
    ),
    (
      'online-erklaert-biochemie-03',
      'Biochemie',
      'Welcher Kofaktor ist fuer Transaminierungsreaktionen erforderlich?',
      'Pyridoxalphosphat',
      '["Pyridoxalphosphat","Biotin","Tetrahydrofolat","Coenzym Q10"]'::jsonb,
      'Pyridoxalphosphat, die aktive Form von Vitamin B6, ist der typische Kofaktor der Aminotransferasen und damit fuer Transaminierungen essenziell.',
      'Which cofactor is required for transamination reactions?',
      'Pyridoxal phosphate',
      '["Pyridoxal phosphate","Biotin","Tetrahydrofolate","Coenzyme Q10"]'::jsonb,
      'Pyridoxal phosphate, the active form of vitamin B6, is the classic cofactor of aminotransferases and is essential for transamination.'
    ),
    (
      'online-erklaert-biochemie-04',
      'Biochemie',
      'Welches Enzym ist das geschwindigkeitsbestimmende Enzym der Cholesterinsynthese?',
      'HMG-CoA-Reduktase',
      '["HMG-CoA-Reduktase","Lipoproteinlipase","Acetyl-CoA-Carboxylase","Aldolase B"]'::jsonb,
      'Die HMG-CoA-Reduktase katalysiert die Bildung von Mevalonat und ist das zentrale Regulationsenzym der Cholesterinsynthese. Statine hemmen genau dieses Enzym.',
      'Which enzyme is the rate-limiting enzyme of cholesterol synthesis?',
      'HMG-CoA reductase',
      '["HMG-CoA reductase","Lipoprotein lipase","Acetyl-CoA carboxylase","Aldolase B"]'::jsonb,
      'HMG-CoA reductase catalyzes mevalonate formation and is the key regulatory enzyme of cholesterol synthesis. Statins inhibit this enzyme directly.'
    ),
    (
      'online-erklaert-biochemie-05',
      'Biochemie',
      'Welches Enzym ist bei hereditarer Fruktoseintoleranz defekt?',
      'Aldolase B',
      '["Aldolase B","Hexokinase","Galactose-1-phosphat-Uridyltransferase","Glucose-6-phosphatase"]'::jsonb,
      'Bei hereditarer Fruktoseintoleranz fuehrt ein Aldolase-B-Defekt zur Anreicherung von Fruktose-1-phosphat. Dadurch werden Phosphat und ATP verbraucht, was die Leber belastet.',
      'Which enzyme is deficient in hereditary fructose intolerance?',
      'Aldolase B',
      '["Aldolase B","Hexokinase","Galactose-1-phosphate uridyltransferase","Glucose-6-phosphatase"]'::jsonb,
      'In hereditary fructose intolerance, aldolase B deficiency causes fructose-1-phosphate accumulation. This traps phosphate and depletes ATP, especially in the liver.'
    ),
    (
      'online-erklaert-biochemie-06',
      'Biochemie',
      'Welches Enzym ist bei Morbus von Gierke defekt?',
      'Glucose-6-phosphatase',
      '["Glucose-6-phosphatase","Aldolase B","Pyruvatdehydrogenase","Acid alpha-Glucosidase"]'::jsonb,
      'Morbus von Gierke ist eine Glykogenspeicherkrankheit durch Defekt der Glucose-6-phosphatase. Dadurch kann die Leber keine freie Glukose in den Blutkreislauf abgeben.',
      'Which enzyme is deficient in von Gierke disease?',
      'Glucose-6-phosphatase',
      '["Glucose-6-phosphatase","Aldolase B","Pyruvate dehydrogenase","Acid alpha-glucosidase"]'::jsonb,
      'Von Gierke disease is a glycogen storage disorder caused by glucose-6-phosphatase deficiency. As a result, the liver cannot release free glucose into the bloodstream.'
    ),
    (
      'online-erklaert-biochemie-07',
      'Biochemie',
      'Welches Enzym ist bei Morbus Pompe defekt?',
      'Acid alpha-Glucosidase',
      '["Acid alpha-Glucosidase","Myophosphorylase","Glucose-6-phosphatase","Aldolase B"]'::jsonb,
      'Morbus Pompe beruht auf einem lysosomalen Defekt der acid alpha-Glucosidase. Dadurch lagert sich Glykogen in Lysosomen an, besonders in Herz- und Skelettmuskel.',
      'Which enzyme is deficient in Pompe disease?',
      'Acid alpha-glucosidase',
      '["Acid alpha-glucosidase","Myophosphorylase","Glucose-6-phosphatase","Aldolase B"]'::jsonb,
      'Pompe disease is caused by lysosomal acid alpha-glucosidase deficiency. Glycogen accumulates in lysosomes, especially in cardiac and skeletal muscle.'
    ),
    (
      'online-erklaert-biochemie-08',
      'Biochemie',
      'Welches System transportiert langkettige Fettsaeuren in die Mitochondrienmatrix?',
      'Carnitin-Shuttle',
      '["Carnitin-Shuttle","Malat-Aspartat-Shuttle","Harnstoffzyklus","Pentosephosphatweg"]'::jsonb,
      'Langkettige Fettsaeuren koennen die innere Mitochondrienmembran nicht frei passieren. Sie werden deshalb ueber das Carnitin-Shuttle in die Matrix eingeschleust.',
      'Which system transports long-chain fatty acids into the mitochondrial matrix?',
      'Carnitine shuttle',
      '["Carnitine shuttle","Malate-aspartate shuttle","Urea cycle","Pentose phosphate pathway"]'::jsonb,
      'Long-chain fatty acids cannot cross the inner mitochondrial membrane freely. They therefore require the carnitine shuttle to enter the matrix.'
    ),
    (
      'online-erklaert-biochemie-09',
      'Biochemie',
      'Welcher Enzymkomplex ist bei der Ahornsirupkrankheit defekt?',
      'Verzweigtkettige Alpha-Ketosaeure-Dehydrogenase',
      '["Verzweigtkettige Alpha-Ketosaeure-Dehydrogenase","Pyruvatdehydrogenase","Aldolase B","Arginase"]'::jsonb,
      'Bei der Ahornsirupkrankheit ist der Abbau verzweigtkettiger Aminosaeuren gestoert, weil die verzweigtkettige Alpha-Ketosaeure-Dehydrogenase ausfaellt.',
      'Which enzyme complex is defective in maple syrup urine disease?',
      'Branched-chain alpha-ketoacid dehydrogenase',
      '["Branched-chain alpha-ketoacid dehydrogenase","Pyruvate dehydrogenase","Aldolase B","Arginase"]'::jsonb,
      'In maple syrup urine disease, degradation of branched-chain amino acids is impaired because branched-chain alpha-ketoacid dehydrogenase is deficient.'
    ),
    (
      'online-erklaert-biochemie-10',
      'Biochemie',
      'Welches Enzym ist der einzige X-chromosomal vererbte Defekt des Harnstoffzyklus?',
      'Ornithin-Transcarbamylase',
      '["Ornithin-Transcarbamylase","Arginase","Carbamoylphosphat-Synthetase I","Argininosuccinat-Lyase"]'::jsonb,
      'Der Ornithin-Transcarbamylase-Mangel ist der klassische und einzige X-chromosomal vererbte Enzymdefekt des Harnstoffzyklus. Er fuehrt zu Hyperammoniaemie.',
      'Which enzyme defect is the only X-linked disorder of the urea cycle?',
      'Ornithine transcarbamylase',
      '["Ornithine transcarbamylase","Arginase","Carbamoyl phosphate synthetase I","Argininosuccinate lyase"]'::jsonb,
      'Ornithine transcarbamylase deficiency is the classic and only X-linked urea cycle enzyme defect. It causes hyperammonemia.'
    ),
    (
      'online-erklaert-mikrobiologie-01',
      'Mikrobiologie',
      'Welchen zellulaeren Faktor hemmt das Diphtherietoxin direkt?',
      'Elongationsfaktor 2',
      '["Elongationsfaktor 2","DNA-Polymerase","RNA-Polymerase","Peptidyltransferase"]'::jsonb,
      'Das Diphtherietoxin ADP-ribosyliert den Elongationsfaktor 2 und stoppt damit die Proteinsynthese der Wirtszelle. Genau dieser Mechanismus erklaert die ausgepraegte Gewebsnekrose.',
      'Which cellular factor is directly inhibited by diphtheria toxin?',
      'Elongation factor 2',
      '["Elongation factor 2","DNA polymerase","RNA polymerase","Peptidyl transferase"]'::jsonb,
      'Diphtheria toxin ADP-ribosylates elongation factor 2 and thereby shuts down host cell protein synthesis. This mechanism explains the marked tissue necrosis.'
    ),
    (
      'online-erklaert-mikrobiologie-02',
      'Mikrobiologie',
      'Welches SNARE-Protein wird durch Tetanospasmin gespalten?',
      'Synaptobrevin',
      '["Synaptobrevin","Aktin","Tubulin","Clathrin"]'::jsonb,
      'Das Tetanospasmin von Clostridium tetani spaltet Synaptobrevin und blockiert dadurch die Freisetzung inhibitorischer Neurotransmitter wie GABA und Glycin. Das fuehrt zu spastischen Kraempfen.',
      'Which SNARE protein is cleaved by tetanospasmin?',
      'Synaptobrevin',
      '["Synaptobrevin","Actin","Tubulin","Clathrin"]'::jsonb,
      'Tetanospasmin from Clostridium tetani cleaves synaptobrevin and blocks release of inhibitory neurotransmitters such as GABA and glycine. This produces spastic paralysis.'
    ),
    (
      'online-erklaert-mikrobiologie-03',
      'Mikrobiologie',
      'Welches Bakterium ist oxidasepositiv und fermentiert keine Laktose auf MacConkey-Agar?',
      'Pseudomonas aeruginosa',
      '["Pseudomonas aeruginosa","Escherichia coli","Klebsiella pneumoniae","Enterococcus faecalis"]'::jsonb,
      'Pseudomonas aeruginosa ist ein oxidasepositiver, nicht laktosefermentierender gramnegativer Staebchenkeim. Diese Kombination hilft, ihn von vielen Enterobacterales zu unterscheiden.',
      'Which bacterium is oxidase positive and does not ferment lactose on MacConkey agar?',
      'Pseudomonas aeruginosa',
      '["Pseudomonas aeruginosa","Escherichia coli","Klebsiella pneumoniae","Enterococcus faecalis"]'::jsonb,
      'Pseudomonas aeruginosa is an oxidase-positive, non-lactose-fermenting gram-negative rod. This combination helps distinguish it from many Enterobacterales.'
    ),
    (
      'online-erklaert-mikrobiologie-04',
      'Mikrobiologie',
      'Welcher bakterielle Erreger besitzt keine Zellwand?',
      'Mycoplasma pneumoniae',
      '["Mycoplasma pneumoniae","Streptococcus pneumoniae","Legionella pneumophila","Corynebacterium diphtheriae"]'::jsonb,
      'Mycoplasma pneumoniae besitzt keine Peptidoglykan-Zellwand. Deshalb spricht der Erreger nicht auf Beta-Laktam-Antibiotika an und ist im Gram-Praeparat schlecht darstellbar.',
      'Which bacterial pathogen lacks a cell wall?',
      'Mycoplasma pneumoniae',
      '["Mycoplasma pneumoniae","Streptococcus pneumoniae","Legionella pneumophila","Corynebacterium diphtheriae"]'::jsonb,
      'Mycoplasma pneumoniae lacks a peptidoglycan cell wall. It therefore does not respond to beta-lactam antibiotics and stains poorly on Gram stain.'
    ),
    (
      'online-erklaert-mikrobiologie-05',
      'Mikrobiologie',
      'Welches Kohlenhydrat fermentiert Neisseria gonorrhoeae im Gegensatz zu Neisseria meningitidis nicht?',
      'Maltose',
      '["Maltose","Glukose","Laktose","Saccharose"]'::jsonb,
      'Neisseria gonorrhoeae fermentiert nur Glukose, waehrend Neisseria meningitidis sowohl Glukose als auch Maltose fermentiert. Genau das dient klassisch zur Differenzierung.',
      'Which carbohydrate is not fermented by Neisseria gonorrhoeae, unlike Neisseria meningitidis?',
      'Maltose',
      '["Maltose","Glucose","Lactose","Sucrose"]'::jsonb,
      'Neisseria gonorrhoeae ferments glucose only, whereas Neisseria meningitidis ferments both glucose and maltose. This is a classic way to distinguish them.'
    ),
    (
      'online-erklaert-mikrobiologie-06',
      'Mikrobiologie',
      'Welcher Erreger verursacht typischerweise eine antibiotikaassoziierte pseudomembranoese Kolitis?',
      'Clostridioides difficile',
      '["Clostridioides difficile","Bacteroides fragilis","Helicobacter pylori","Shigella sonnei"]'::jsonb,
      'Clostridioides difficile produziert Toxine, die nach Stoerung der Darmflora eine pseudomembranoese Kolitis ausloesen. Typisch ist der Zusammenhang mit vorausgegangener Antibiotikatherapie.',
      'Which pathogen typically causes antibiotic-associated pseudomembranous colitis?',
      'Clostridioides difficile',
      '["Clostridioides difficile","Bacteroides fragilis","Helicobacter pylori","Shigella sonnei"]'::jsonb,
      'Clostridioides difficile produces toxins that trigger pseudomembranous colitis after disruption of the normal gut flora. Prior antibiotic therapy is the classic setting.'
    ),
    (
      'online-erklaert-mikrobiologie-07',
      'Mikrobiologie',
      'Welcher Pilz ist klassisch im Keimschlauchtest positiv?',
      'Candida albicans',
      '["Candida albicans","Aspergillus fumigatus","Cryptococcus neoformans","Mucor"]'::jsonb,
      'Candida albicans bildet im Keimschlauchtest typische Germ Tubes. Dieser einfache Laborbefund hilft bei der Abgrenzung von anderen Candida-Arten.',
      'Which fungus is classically germ tube test positive?',
      'Candida albicans',
      '["Candida albicans","Aspergillus fumigatus","Cryptococcus neoformans","Mucor"]'::jsonb,
      'Candida albicans forms characteristic germ tubes in the germ tube test. This simple laboratory finding helps distinguish it from other Candida species.'
    ),
    (
      'online-erklaert-mikrobiologie-08',
      'Mikrobiologie',
      'Welche Hyphenmorphologie ist typisch fuer Aspergillus fumigatus?',
      'Septierte Hyphen mit spitzwinkliger Verzweigung',
      '["Septierte Hyphen mit spitzwinkliger Verzweigung","Breite unseptierte Hyphen mit rechtwinkliger Verzweigung","Sphaerulen mit Endosporen","Kapseltragende Sprosszellen"]'::jsonb,
      'Aspergillus zeigt schmale, septierte Hyphen mit typischer spitzwinkliger Verzweigung von etwa 45 Grad. Mucorales sind dagegen breit und meist unseptiert.',
      'Which hyphal morphology is typical of Aspergillus fumigatus?',
      'Septate hyphae with acute-angle branching',
      '["Septate hyphae with acute-angle branching","Broad nonseptate hyphae with right-angle branching","Spherules with endospores","Encapsulated budding yeast"]'::jsonb,
      'Aspergillus shows narrow septate hyphae with characteristic acute-angle branching of about 45 degrees. Mucorales are broad and usually nonseptate instead.'
    ),
    (
      'online-erklaert-mikrobiologie-09',
      'Mikrobiologie',
      'Ueber welchen Rezeptor infiziert das Epstein-Barr-Virus bevorzugt B-Zellen?',
      'CD21',
      '["CD21","CD4","CD8","CCR5"]'::jsonb,
      'Das Epstein-Barr-Virus bindet an CD21 auf B-Zellen. Diese Tropismus-Eigenschaft erklaert die bevorzugte Infektion des B-Zell-Kompartiments.',
      'Through which receptor does Epstein-Barr virus preferentially infect B cells?',
      'CD21',
      '["CD21","CD4","CD8","CCR5"]'::jsonb,
      'Epstein-Barr virus binds to CD21 on B cells. This receptor tropism explains its preferential infection of the B-cell compartment.'
    ),
    (
      'online-erklaert-mikrobiologie-10',
      'Mikrobiologie',
      'Welche Plasmodium-Art infiziert Erythrozyten aller Altersstufen?',
      'Plasmodium falciparum',
      '["Plasmodium falciparum","Plasmodium vivax","Plasmodium ovale","Plasmodium malariae"]'::jsonb,
      'Plasmodium falciparum kann Erythrozyten unabhaengig vom Alter infizieren. Dadurch kann die Parasitenaemie besonders hoch werden, was zur Schwere der Malaria tropica beitraegt.',
      'Which Plasmodium species infects erythrocytes of all ages?',
      'Plasmodium falciparum',
      '["Plasmodium falciparum","Plasmodium vivax","Plasmodium ovale","Plasmodium malariae"]'::jsonb,
      'Plasmodium falciparum can infect erythrocytes regardless of age. This allows very high parasitemia and contributes to the severity of falciparum malaria.'
    ),
    (
      'online-erklaert-pathologie-01',
      'Pathologie',
      'Welche Einschluesse sind typisch fuer die alkoholische Hepatitis?',
      'Mallory-Denk-Koerper',
      '["Mallory-Denk-Koerper","Negri-Koerper","Auer-Staebchen","Aschoff-Koerperchen"]'::jsonb,
      'Mallory-Denk-Koerper bestehen aus aggregierten Zytokeratinfilamenten in Hepatozyten und sind ein klassischer histologischer Befund der alkoholischen Hepatitis.',
      'Which inclusions are typical of alcoholic hepatitis?',
      'Mallory-Denk bodies',
      '["Mallory-Denk bodies","Negri bodies","Auer rods","Aschoff bodies"]'::jsonb,
      'Mallory-Denk bodies are aggregates of cytokeratin filaments in hepatocytes and are a classic histologic finding in alcoholic hepatitis.'
    ),
    (
      'online-erklaert-pathologie-02',
      'Pathologie',
      'Welche Einschlusskoerper sind typisch fuer eine CMV-Infektion?',
      'Owl-eye-Inclusionen',
      '["Owl-eye-Inclusionen","Russell-Koerper","Verocay-Koerperchen","Psammomkoerper"]'::jsonb,
      'CMV-infizierte Zellen zeigen grosse intranukleaere Einschlusskoerper mit perinukleaerem Hof, die klassisch als Owl-eye-Inclusionen beschrieben werden.',
      'Which inclusion bodies are typical of CMV infection?',
      'Owl eye inclusions',
      '["Owl eye inclusions","Russell bodies","Verocay bodies","Psammoma bodies"]'::jsonb,
      'CMV-infected cells show large intranuclear inclusions with a surrounding halo, classically described as owl eye inclusions.'
    ),
    (
      'online-erklaert-pathologie-03',
      'Pathologie',
      'Welcher histologische Befund spricht fuer einen Alpha-1-Antitrypsin-Mangel in der Leber?',
      'PAS-positive diastaseresistente Globuli',
      '["PAS-positive diastaseresistente Globuli","Kimmelstiel-Wilson-Knoten","Psammomkoerper","Auer-Staebchen"]'::jsonb,
      'Fehlgefaltetes Alpha-1-Antitrypsin lagert sich in Hepatozyten ab und erscheint histologisch als PAS-positive, diastaseresistente Globuli.',
      'Which histologic finding suggests alpha-1 antitrypsin deficiency in the liver?',
      'PAS-positive diastase-resistant globules',
      '["PAS-positive diastase-resistant globules","Kimmelstiel-Wilson nodules","Psammoma bodies","Auer rods"]'::jsonb,
      'Misfolded alpha-1 antitrypsin accumulates in hepatocytes and appears histologically as PAS-positive, diastase-resistant globules.'
    ),
    (
      'online-erklaert-pathologie-04',
      'Pathologie',
      'Welche Riesenzellen sind typisch fuer ein tuberkuloeses Granulom?',
      'Langhans-Riesenzellen',
      '["Langhans-Riesenzellen","Touton-Riesenzellen","Osteoklasten","Megaloblasten"]'::jsonb,
      'Tuberkuloese Granulome enthalten oft Langhans-Riesenzellen mit randstaendig angeordneten Zellkernen. Sie sind ein klassischer granulomatoeser Befund.',
      'Which giant cells are typical of a tuberculous granuloma?',
      'Langhans giant cells',
      '["Langhans giant cells","Touton giant cells","Osteoclasts","Megaloblasts"]'::jsonb,
      'Tuberculous granulomas often contain Langhans giant cells with peripherally arranged nuclei. They are a classic granulomatous finding.'
    ),
    (
      'online-erklaert-pathologie-05',
      'Pathologie',
      'Welche Einschluesse entstehen durch Ansammlung von Immunglobulinen in Plasmazellen?',
      'Russell-Koerper',
      '["Russell-Koerper","Negri-Koerper","Mallory-Denk-Koerper","Aschoff-Koerperchen"]'::jsonb,
      'Russell-Koerper sind eosinophile Einschluesse in Plasmazellen, die durch angesammelte Immunglobuline im endoplasmatischen Retikulum entstehen.',
      'Which inclusions result from immunoglobulin accumulation in plasma cells?',
      'Russell bodies',
      '["Russell bodies","Negri bodies","Mallory-Denk bodies","Aschoff bodies"]'::jsonb,
      'Russell bodies are eosinophilic inclusions in plasma cells caused by accumulated immunoglobulins within the endoplasmic reticulum.'
    ),
    (
      'online-erklaert-pathologie-06',
      'Pathologie',
      'Welche apoptotischen Koerperchen sind typisch fuer die akute Virushepatitis?',
      'Councilman-Koerper',
      '["Councilman-Koerper","Psammomkoerper","Birbeck-Granula","Verocay-Koerperchen"]'::jsonb,
      'Councilman-Koerper sind eosinophile apoptotische Hepatozyten und ein klassischer histologischer Befund bei akuter Virushepatitis.',
      'Which apoptotic bodies are typical of acute viral hepatitis?',
      'Councilman bodies',
      '["Councilman bodies","Psammoma bodies","Birbeck granules","Verocay bodies"]'::jsonb,
      'Councilman bodies are eosinophilic apoptotic hepatocytes and are a classic histologic finding in acute viral hepatitis.'
    ),
    (
      'online-erklaert-pathologie-07',
      'Pathologie',
      'Welche histologischen Koerperchen sind charakteristisch fuer die Malakoplakie?',
      'Michaelis-Gutmann-Koerperchen',
      '["Michaelis-Gutmann-Koerperchen","Auer-Staebchen","Aschoff-Koerperchen","Psammomkoerper"]'::jsonb,
      'Michaelis-Gutmann-Koerperchen sind konzentrische intrazytoplasmatische Einschluesse in Makrophagen und typisch fuer die Malakoplakie.',
      'Which histologic bodies are characteristic of malakoplakia?',
      'Michaelis-Gutmann bodies',
      '["Michaelis-Gutmann bodies","Auer rods","Aschoff bodies","Psammoma bodies"]'::jsonb,
      'Michaelis-Gutmann bodies are concentric intracytoplasmic inclusions in macrophages and are characteristic of malakoplakia.'
    ),
    (
      'online-erklaert-pathologie-08',
      'Pathologie',
      'Welche zytoplasmatischen Organellen sind ultrastrukturell typisch fuer die Langerhans-Zell-Histiozytose?',
      'Birbeck-Granula',
      '["Birbeck-Granula","Auer-Staebchen","Negri-Koerper","Russell-Koerper"]'::jsonb,
      'Birbeck-Granula sind tennisracketfoermige Organellen in Langerhans-Zellen und ein klassischer ultrastruktureller Befund der Langerhans-Zell-Histiozytose.',
      'Which cytoplasmic organelles are ultrastructurally typical of Langerhans cell histiocytosis?',
      'Birbeck granules',
      '["Birbeck granules","Auer rods","Negri bodies","Russell bodies"]'::jsonb,
      'Birbeck granules are tennis-racket-shaped organelles in Langerhans cells and are a classic ultrastructural finding in Langerhans cell histiocytosis.'
    ),
    (
      'online-erklaert-pathologie-09',
      'Pathologie',
      'Welche Zelle ist charakteristisch fuer das rheumatische Fieber im Aschoff-Knoten?',
      'Anitschkow-Zelle',
      '["Anitschkow-Zelle","Reed-Sternberg-Zelle","Plasmazelle","Mastzelle"]'::jsonb,
      'Anitschkow-Zellen sind aktivierte Makrophagen mit charakteristischer Kernzeichnung und gehoeren zum klassischen Bild des Aschoff-Knotens beim rheumatischen Fieber.',
      'Which cell is characteristic of rheumatic fever within an Aschoff body?',
      'Anitschkow cell',
      '["Anitschkow cell","Reed-Sternberg cell","Plasma cell","Mast cell"]'::jsonb,
      'Anitschkow cells are activated macrophages with characteristic nuclear morphology and are part of the classic appearance of Aschoff bodies in rheumatic fever.'
    ),
    (
      'online-erklaert-pathologie-10',
      'Pathologie',
      'Welche histologische Struktur findet sich typischerweise bei der Pilzinfektion durch Aspergillus in Gewebeproben?',
      'Septierte Hyphen mit spitzwinkliger Verzweigung',
      '["Septierte Hyphen mit spitzwinkliger Verzweigung","Breite unseptierte Hyphen mit rechtwinkliger Verzweigung","Sphaerulen mit Endosporen","Pseudozysten mit Bradyzoiten"]'::jsonb,
      'In Gewebeschnitten zeigt Aspergillus typischerweise septierte Hyphen mit spitzwinkliger Verzweigung. Diese Morphologie grenzt den Erreger von Mucorales ab.',
      'Which histologic structure is typically seen in tissue samples infected by Aspergillus?',
      'Septate hyphae with acute-angle branching',
      '["Septate hyphae with acute-angle branching","Broad nonseptate hyphae with right-angle branching","Spherules with endospores","Pseudocysts with bradyzoites"]'::jsonb,
      'In tissue sections, Aspergillus typically shows septate hyphae with acute-angle branching. This morphology helps distinguish it from Mucorales.'
    ),
    (
      'online-erklaert-radiologie-01',
      'Radiologie',
      'Welche Bildgebung ist die Untersuchung der ersten Wahl bei Verdacht auf akute Cholezystitis?',
      'Abdomensonografie',
      '["Abdomensonografie","Nativ-CT des Abdomens","MRT des Abdomens","Roentgen Abdomen leer"]'::jsonb,
      'Die Sonografie ist bei Verdacht auf akute Cholezystitis die erste Wahl, weil sie Gallensteine, Wandverdickung, pericholezystische Fluessigkeit und einen sonografischen Murphy direkt erfassen kann.',
      'Which imaging study is first-line for suspected acute cholecystitis?',
      'Abdominal ultrasound',
      '["Abdominal ultrasound","Non-contrast abdominal CT","Abdominal MRI","Plain abdominal radiograph"]'::jsonb,
      'Ultrasound is first-line for suspected acute cholecystitis because it can directly show gallstones, wall thickening, pericholecystic fluid, and a sonographic Murphy sign.'
    ),
    (
      'online-erklaert-radiologie-02',
      'Radiologie',
      'Welche Bildgebung ist die Standarduntersuchung bei Verdacht auf akute intrakranielle Blutung?',
      'Nativ-CT des Schaedels',
      '["Nativ-CT des Schaedels","MRT mit Kontrastmittel","Roentgen des Schaedels","Sonografie des Schaedels"]'::jsonb,
      'Die akute intrakranielle Blutung wird standardmaessig mit einem Nativ-CT diagnostiziert, weil frisches Blut dort rasch und verlaesslich hyperdens erkannt wird.',
      'Which imaging study is standard for suspected acute intracranial hemorrhage?',
      'Non-contrast head CT',
      '["Non-contrast head CT","MRI with contrast","Skull radiograph","Head ultrasound"]'::jsonb,
      'Acute intracranial hemorrhage is standardly evaluated with non-contrast CT because fresh blood is rapidly and reliably seen as hyperdense.'
    ),
    (
      'online-erklaert-radiologie-03',
      'Radiologie',
      'Welche Blutungsform zeigt sich im CT typischerweise als sichelfoermige extraaxiale Hyperdensitaet?',
      'Subduralhaematom',
      '["Subduralhaematom","Epiduralhaematom","Subarachnoidalblutung","Intrazerebrales Haematom"]'::jsonb,
      'Das Subduralhaematom breitet sich entlang der Hemisphaerenoberflaeche aus und erscheint deshalb klassisch sichelfoermig. Ein Epiduralhaematom ist dagegen eher bikonvex.',
      'Which hemorrhage classically appears as a crescent-shaped extra-axial hyperdensity on CT?',
      'Subdural hematoma',
      '["Subdural hematoma","Epidural hematoma","Subarachnoid hemorrhage","Intracerebral hematoma"]'::jsonb,
      'A subdural hematoma spreads along the cerebral hemisphere surface and therefore classically appears crescent-shaped. An epidural hematoma is more often biconvex.'
    ),
    (
      'online-erklaert-radiologie-04',
      'Radiologie',
      'Welche Blutungsform zeigt sich im CT typischerweise als bikonvexe, linsenfoermige extraaxiale Hyperdensitaet?',
      'Epiduralhaematom',
      '["Epiduralhaematom","Subduralhaematom","Subarachnoidalblutung","Kontusionsblutung"]'::jsonb,
      'Das Epiduralhaematom loest die Dura von der Schaedelinnenseite ab und erscheint deshalb typischerweise linsenfoermig. Es ueberschreitet Nahtlinien in der Regel nicht.',
      'Which hemorrhage classically appears as a biconvex lens-shaped extra-axial hyperdensity on CT?',
      'Epidural hematoma',
      '["Epidural hematoma","Subdural hematoma","Subarachnoid hemorrhage","Contusion hemorrhage"]'::jsonb,
      'An epidural hematoma strips the dura from the inner skull and therefore classically appears lens-shaped. It usually does not cross suture lines.'
    ),
    (
      'online-erklaert-radiologie-05',
      'Radiologie',
      'Welche Untersuchung ist das Standard-Screening bei durchschnittlichem Brustkrebsrisiko?',
      'Mammografie',
      '["Mammografie","MRT der Brust","CT des Thorax","PET-CT"]'::jsonb,
      'Die Mammografie ist die etablierte Screeningmethode bei durchschnittlichem Brustkrebsrisiko, weil sie Mikrokalzifikationen und suspekte Verdichtungen frueh erfassen kann.',
      'Which study is the standard screening test for average-risk breast cancer detection?',
      'Mammography',
      '["Mammography","Breast MRI","Chest CT","PET-CT"]'::jsonb,
      'Mammography is the established screening method for average-risk breast cancer because it can detect microcalcifications and suspicious densities early.'
    ),
    (
      'online-erklaert-radiologie-06',
      'Radiologie',
      'Welche Bildgebung bestaetigt bei einem haemodynamisch stabilen Erwachsenen am ehesten eine Lungenembolie?',
      'CT-Pulmonalisangiografie',
      '["CT-Pulmonalisangiografie","Thoraxsonografie","Nativ-Roentgen des Thorax","Mammografie"]'::jsonb,
      'Bei haemodynamisch stabilen Erwachsenen ist die CT-Pulmonalisangiografie die Standardbildgebung zum direkten Nachweis von Fuellungsdefekten in den Pulmonalarterien.',
      'Which imaging study most directly confirms pulmonary embolism in a hemodynamically stable adult?',
      'CT pulmonary angiography',
      '["CT pulmonary angiography","Thoracic ultrasound","Plain chest radiograph","Mammography"]'::jsonb,
      'In hemodynamically stable adults, CT pulmonary angiography is the standard imaging study because it directly shows filling defects in the pulmonary arteries.'
    ),
    (
      'online-erklaert-radiologie-07',
      'Radiologie',
      'Welche Bildgebung ist bei Verdacht auf Appendizitis im Kindesalter die erste Wahl?',
      'Sonografie',
      '["Sonografie","CT des Abdomens","MRT mit Kontrastmittel","Roentgen Abdomen"]'::jsonb,
      'Bei Kindern wird die Sonografie bevorzugt, weil sie ohne ionisierende Strahlung auskommt und eine verdickte, nicht komprimierbare Appendix direkt zeigen kann.',
      'Which imaging modality is first-line for suspected appendicitis in children?',
      'Ultrasound',
      '["Ultrasound","Abdominal CT","MRI with contrast","Abdominal radiograph"]'::jsonb,
      'In children, ultrasound is preferred because it avoids ionizing radiation and can directly show a thickened, noncompressible appendix.'
    ),
    (
      'online-erklaert-radiologie-08',
      'Radiologie',
      'Wonach sucht die FAST-Untersuchung im Trauma primaer?',
      'Freie Fluessigkeit',
      '["Freie Fluessigkeit","Pneumonie","Nierensteine","Frakturlinien der Finger"]'::jsonb,
      'Die FAST-Untersuchung dient im Trauma primaer dem Nachweis freier Fluessigkeit, also meist Blut, in typischen Rezessus des Abdomens und Perikards.',
      'What does the FAST examination primarily look for in trauma?',
      'Free fluid',
      '["Free fluid","Pneumonia","Kidney stones","Finger fracture lines"]'::jsonb,
      'In trauma, FAST is primarily used to detect free fluid, usually blood, in the typical abdominal and pericardial recesses.'
    ),
    (
      'online-erklaert-radiologie-09',
      'Radiologie',
      'Welches Ultraschallartefakt ist typisch fuer einen Gallenstein?',
      'Dorsaler Schallschatten',
      '["Dorsaler Schallschatten","Kometenschweif-Artefakt","Spiegelartefakt","Reverberation in A-Linien"]'::jsonb,
      'Gallensteine erscheinen sonografisch echoreich und werfen typischerweise einen dorsalen Schallschatten, weil der Schall hinter dem Konkrement stark abgeschwaecht wird.',
      'Which ultrasound artifact is typical of a gallstone?',
      'Posterior acoustic shadow',
      '["Posterior acoustic shadow","Comet tail artifact","Mirror artifact","Reverberation as A-lines"]'::jsonb,
      'Gallstones are echogenic on ultrasound and typically cast a posterior acoustic shadow because sound is strongly attenuated behind the stone.'
    ),
    (
      'online-erklaert-radiologie-10',
      'Radiologie',
      'Welche Bildgebung arbeitet ohne ionisierende Strahlung?',
      'MRT',
      '["MRT","CT","Mammografie","Durchleuchtung"]'::jsonb,
      'Die MRT verwendet starke Magnetfelder und Radiofrequenzimpulse statt ionisierender Strahlung. CT, Mammografie und Durchleuchtung basieren dagegen auf Roentgenstrahlung.',
      'Which imaging modality operates without ionizing radiation?',
      'MRI',
      '["MRI","CT","Mammography","Fluoroscopy"]'::jsonb,
      'MRI uses strong magnetic fields and radiofrequency pulses rather than ionizing radiation. CT, mammography, and fluoroscopy all use X-rays.'
    )
),
upsert_questions as (
  insert into public.questions (
    slug,
    category,
    question,
    correct_answer,
    options,
    explanation
  )
  select
    slug,
    category,
    question_de,
    correct_de,
    options_de,
    explanation_de
  from question_rows
  on conflict (slug) do update
    set category = excluded.category,
        question = excluded.question,
        correct_answer = excluded.correct_answer,
        options = excluded.options,
        explanation = excluded.explanation,
        updated_at = now()
  returning id, slug
)
insert into public.question_translations (
  question_id,
  language,
  question,
  options,
  correct_answer,
  explanation
)
select
  upsert_questions.id,
  'en',
  question_rows.question_en,
  question_rows.options_en,
  question_rows.correct_en,
  question_rows.explanation_en
from upsert_questions
join question_rows
  on question_rows.slug = upsert_questions.slug
on conflict (question_id, language) do update
  set question = excluded.question,
      options = excluded.options,
      correct_answer = excluded.correct_answer,
      explanation = excluded.explanation,
      updated_at = now();
