-- Add hard non-medical general category questions.
-- Generated from src/data/offlineHardGeneralCategoryPack.json.

with question_rows (
  slug,
  category,
  question_de,
  correct_de,
  options_de,
  explanation_de,
  question_en,
  correct_en,
  options_en,
  explanation_en
) as (
  values
    (
      'general-geschichte-hard-01',
      'Geschichte',
      'Warum loeste der Augsburger Religionsfrieden von 1555 den Konfessionskonflikt nur begrenzt?',
      'Er regelte im Kern nur Katholiken und Lutheraner, nicht aber Calvinisten',
      '["Er regelte im Kern nur Katholiken und Lutheraner, nicht aber Calvinisten","Er verbot alle Fuerstenrechte im Reich","Er gruendete direkt den Deutschen Bund","Er erklaerte Frankreich zum Reichsteil"]'::jsonb,
      'Der Frieden stabilisierte das Reich kurzfristig, liess aber wichtige Konfessionsgruppen und Machtfragen offen. Das trug spaeter zu neuen Spannungen bei.',
      'Why did the Peace of Augsburg in 1555 only partly settle the confessional conflict?',
      'It mainly covered Catholics and Lutherans, not Calvinists',
      '["It mainly covered Catholics and Lutherans, not Calvinists","It abolished all princely rights in the Empire","It directly founded the German Confederation","It declared France part of the Empire"]'::jsonb,
      'The settlement stabilized the Empire for a time, but left major confessional groups and power questions unresolved, feeding later tensions.'
    ),
    (
      'general-geschichte-hard-02',
      'Geschichte',
      'Was war eine zentrale Folge des Berliner Kongresses von 1878?',
      'Der Vertrag von San Stefano wurde revidiert und russisch-bulgarischer Einfluss begrenzt',
      '["Der Vertrag von San Stefano wurde revidiert und russisch-bulgarischer Einfluss begrenzt","Das Osmanische Reich wurde vollstaendig aufgeloest","Deutschland erhielt direkte Kontrolle ueber Konstantinopel","Die NATO wurde als Buendnis gegruendet"]'::jsonb,
      'Der Kongress ordnete Teile Suedosteuropas neu und sollte das Machtgleichgewicht sichern, schuf aber neue Konfliktlinien auf dem Balkan.',
      'What was a central consequence of the Congress of Berlin in 1878?',
      'The Treaty of San Stefano was revised and Russian-Bulgarian influence was limited',
      '["The Treaty of San Stefano was revised and Russian-Bulgarian influence was limited","The Ottoman Empire was completely dissolved","Germany gained direct control of Constantinople","NATO was founded as an alliance"]'::jsonb,
      'The congress reordered parts of southeastern Europe and aimed to preserve the balance of power, but it also created new Balkan fault lines.'
    ),
    (
      'general-geschichte-hard-03',
      'Geschichte',
      'Welche Strukturveraenderung gehoerte zur Meiji-Restauration in Japan?',
      'Feudale Domaenen wurden durch zentral kontrollierte Praefekturen ersetzt',
      '["Feudale Domaenen wurden durch zentral kontrollierte Praefekturen ersetzt","Japan wurde eine spanische Kolonie","Die Samurai erhielten uneingeschraenkte Sonderrechte","Das Land schloss dauerhaft alle Aussenkontakte"]'::jsonb,
      'Die Meiji-Regierung zentralisierte den Staat, modernisierte Verwaltung, Armee und Wirtschaft und schwaechte die feudale Ordnung.',
      'Which structural change was part of the Meiji Restoration in Japan?',
      'Feudal domains were replaced by centrally controlled prefectures',
      '["Feudal domains were replaced by centrally controlled prefectures","Japan became a Spanish colony","Samurai received unlimited special rights","The country permanently closed all foreign contacts"]'::jsonb,
      'The Meiji government centralized the state, modernized administration, army, and economy, and weakened the feudal order.'
    ),
    (
      'general-geschichte-hard-04',
      'Geschichte',
      'Welche Bedeutung hatte der Vertrag von Tordesillas von 1494?',
      'Spanien und Portugal teilten ihre Ansprueche in ueberseeischen Gebieten auf',
      '["Spanien und Portugal teilten ihre Ansprueche in ueberseeischen Gebieten auf","Er beendete den Dreissigjaehrigen Krieg","Er gruendete die Hanse","Er verbot den Seehandel im Atlantik"]'::jsonb,
      'Der Vertrag zog eine Demarkationslinie fuer spanische und portugiesische Expansionsansprueche, wurde aber von anderen Maechten nicht dauerhaft akzeptiert.',
      'What was the significance of the Treaty of Tordesillas in 1494?',
      'Spain and Portugal divided their claims to overseas territories',
      '["Spain and Portugal divided their claims to overseas territories","It ended the Thirty Years War","It founded the Hanseatic League","It banned Atlantic maritime trade"]'::jsonb,
      'The treaty drew a demarcation line for Spanish and Portuguese expansion claims, though other powers did not permanently accept it.'
    ),
    (
      'general-geschichte-hard-05',
      'Geschichte',
      'Warum war der Deutsche Zollverein fuer die spaetere Reichsgruendung wichtig?',
      'Er vertiefte wirtschaftliche Integration ohne Oesterreich',
      '["Er vertiefte wirtschaftliche Integration ohne Oesterreich","Er schaffte alle deutschen Monarchien sofort ab","Er fuehrte bereits das allgemeine Frauenwahlrecht ein","Er machte Preussen zu einer franzoesischen Provinz"]'::jsonb,
      'Der Zollverein vereinheitlichte Maerkte und Abgaben vieler deutscher Staaten. Das staerkte Preussens Stellung und bereitete politische Integration mit vor.',
      'Why was the German Zollverein important for later unification?',
      'It deepened economic integration without Austria',
      '["It deepened economic integration without Austria","It immediately abolished all German monarchies","It already introduced universal female suffrage","It made Prussia a French province"]'::jsonb,
      'The Zollverein unified markets and customs rules across many German states. It strengthened Prussia and helped prepare political integration.'
    ),
    (
      'general-geschichte-hard-06',
      'Geschichte',
      'Welche langfristige Wirkung hatte die Glorious Revolution von 1688/89 in England?',
      'Sie staerkte Parlament und konstitutionelle Monarchie',
      '["Sie staerkte Parlament und konstitutionelle Monarchie","Sie fuehrte zur absoluten Herrschaft des Koenigs","Sie beendete die Industrialisierung","Sie gruendete das Byzantinische Reich neu"]'::jsonb,
      'Die Glorious Revolution begrenzte monarchische Macht und staerkte Parlamentsrechte, besonders sichtbar in der Bill of Rights von 1689.',
      'What long-term effect did the Glorious Revolution of 1688/89 have in England?',
      'It strengthened parliament and constitutional monarchy',
      '["It strengthened parliament and constitutional monarchy","It created absolute royal rule","It ended industrialization","It refounded the Byzantine Empire"]'::jsonb,
      'The Glorious Revolution limited monarchical power and strengthened parliamentary rights, especially through the Bill of Rights of 1689.'
    ),
    (
      'general-geschichte-hard-07',
      'Geschichte',
      'Wofuer steht die Bandung-Konferenz von 1955 historisch vor allem?',
      'Fuer antikoloniale Solidaritaet und den spaeteren Blockfreien-Kontext',
      '["Fuer antikoloniale Solidaritaet und den spaeteren Blockfreien-Kontext","Fuer die Gruendung der Europaeischen Union","Fuer den Beginn des Ersten Weltkriegs","Fuer die Teilung des Roemischen Reiches"]'::jsonb,
      'In Bandung trafen sich asiatische und afrikanische Staaten, viele mit kolonialer Erfahrung, und formulierten gemeinsame Interessen jenseits der Supermachtbloecke.',
      'What does the Bandung Conference of 1955 mainly stand for historically?',
      'Anti-colonial solidarity and the later non-aligned context',
      '["Anti-colonial solidarity and the later non-aligned context","The founding of the European Union","The beginning of World War I","The division of the Roman Empire"]'::jsonb,
      'Asian and African states, many with colonial experience, met at Bandung and articulated shared interests beyond the superpower blocs.'
    ),
    (
      'general-geschichte-hard-08',
      'Geschichte',
      'Welche Aussage beschreibt die Balfour-Deklaration von 1917 am genauesten?',
      'Grossbritannien unterstuetzte eine nationale Heimstaette fuer Juden in Palaestina bei Schutz nichtjuedischer Rechte',
      '["Grossbritannien unterstuetzte eine nationale Heimstaette fuer Juden in Palaestina bei Schutz nichtjuedischer Rechte","Sie erklaerte Indien zur unabhaengigen Republik","Sie gruendete den Warschauer Pakt","Sie beendete sofort das britische Mandatssystem"]'::jsonb,
      'Die Deklaration war diplomatisch bedeutsam, weil sie britische Unterstuetzung fuer eine juedische Heimstaette formulierte und zugleich Rechte anderer Bevoelkerungsgruppen erwaehnte.',
      'Which statement most accurately describes the Balfour Declaration of 1917?',
      'Britain supported a national home for Jews in Palestine while protecting non-Jewish rights',
      '["Britain supported a national home for Jews in Palestine while protecting non-Jewish rights","It declared India an independent republic","It founded the Warsaw Pact","It immediately ended the British mandate system"]'::jsonb,
      'The declaration mattered diplomatically because it stated British support for a Jewish national home while also mentioning rights of other communities.'
    ),
    (
      'general-sachkunde-hard-01',
      'Sachkunde',
      'Warum gart Essen in einem Schnellkochtopf schneller?',
      'Hoeherer Druck hebt den Siedepunkt des Wassers an',
      '["Hoeherer Druck hebt den Siedepunkt des Wassers an","Der Topf erzeugt Mikrowellen ohne Strom","Salz entsteht automatisch im Wasser","Die Waermeleitfaehigkeit der Luft wird null"]'::jsonb,
      'Im geschlossenen Topf steigt der Druck. Wasser siedet dann bei hoeherer Temperatur, wodurch Lebensmittel schneller garen.',
      'Why does food cook faster in a pressure cooker?',
      'Higher pressure raises the boiling point of water',
      '["Higher pressure raises the boiling point of water","The pot generates microwaves without electricity","Salt automatically forms in the water","Air thermal conductivity becomes zero"]'::jsonb,
      'Pressure rises in the closed pot. Water then boils at a higher temperature, so food cooks faster.'
    ),
    (
      'general-sachkunde-hard-02',
      'Sachkunde',
      'Warum kann Wechselstrom fuer Stromnetze praktisch vorteilhaft sein?',
      'Spannung laesst sich leicht transformieren, wodurch Leitungsverluste sinken koennen',
      '["Spannung laesst sich leicht transformieren, wodurch Leitungsverluste sinken koennen","Er fliesst ohne Leitungen durch Beton","Er benoetigt keine Generatoren","Er macht alle Sicherungen ueberfluessig"]'::jsonb,
      'Hohe Spannung bedeutet bei gleicher Leistung geringeren Strom. Dadurch sinken ohmsche Verluste in Leitungen, und Transformatoren machen die Anpassung praktikabel.',
      'Why can alternating current be practical for power grids?',
      'Voltage can be transformed easily, which can reduce transmission losses',
      '["Voltage can be transformed easily, which can reduce transmission losses","It flows through concrete without wires","It needs no generators","It makes every fuse unnecessary"]'::jsonb,
      'At the same power, higher voltage means lower current. That reduces resistive line losses, and transformers make voltage changes practical.'
    ),
    (
      'general-sachkunde-hard-03',
      'Sachkunde',
      'Warum sind LEDs meist effizienter als klassische Gluehlampen?',
      'Sie erzeugen Licht direkt in einem Halbleiter statt hauptsaechlich Waerme',
      '["Sie erzeugen Licht direkt in einem Halbleiter statt hauptsaechlich Waerme","Sie verbrennen Sauerstoff schneller","Sie nutzen immer radioaktive Stoffe","Sie speichern Licht dauerhaft im Glas"]'::jsonb,
      'Bei LEDs entsteht Licht durch Rekombination in Halbleitern. Gluehlampen erhitzen einen Draht und verlieren viel Energie als Waerme.',
      'Why are LEDs usually more efficient than classic incandescent bulbs?',
      'They produce light directly in a semiconductor instead of mostly heat',
      '["They produce light directly in a semiconductor instead of mostly heat","They burn oxygen faster","They always use radioactive materials","They store light permanently in glass"]'::jsonb,
      'LEDs emit light through recombination in semiconductors. Incandescent bulbs heat a filament and lose much energy as heat.'
    ),
    (
      'general-sachkunde-hard-04',
      'Sachkunde',
      'Warum muessen GPS-Satellitenuhren relativistisch korrigiert werden?',
      'Bewegung und geringere Gravitation im Orbit veraendern den Gang der Uhren',
      '["Bewegung und geringere Gravitation im Orbit veraendern den Gang der Uhren","Satelliten haben keine Atomuhren","Funksignale koennen keine Zeitinformation tragen","Die Erde steht im GPS-System still"]'::jsonb,
      'Spezielle und allgemeine Relativitaet wirken gegensaetzlich auf Satellitenuhren. Ohne Korrektur wuerden Positionsfehler schnell wachsen.',
      'Why do GPS satellite clocks need relativistic correction?',
      'Motion and weaker gravity in orbit change clock rates',
      '["Motion and weaker gravity in orbit change clock rates","Satellites do not have atomic clocks","Radio signals cannot carry time information","Earth is stationary in the GPS system"]'::jsonb,
      'Special and general relativity affect satellite clocks in opposite ways. Without correction, positioning errors would grow quickly.'
    ),
    (
      'general-sachkunde-hard-05',
      'Sachkunde',
      'Warum ist biologische Stickstofffixierung fuer Oekosysteme wichtig?',
      'Sie wandelt Luftstickstoff in fuer Lebewesen nutzbare Verbindungen um',
      '["Sie wandelt Luftstickstoff in fuer Lebewesen nutzbare Verbindungen um","Sie entfernt allen Sauerstoff aus der Atmosphaere","Sie macht Gestein magnetisch","Sie ersetzt Sonnenlicht bei der Fotosynthese"]'::jsonb,
      'Viele Organismen koennen N2 aus der Luft nicht direkt nutzen. Stickstofffixierende Mikroben machen daraus reaktivere Verbindungen fuer Nahrungsketten.',
      'Why is biological nitrogen fixation important for ecosystems?',
      'It converts atmospheric nitrogen into compounds living things can use',
      '["It converts atmospheric nitrogen into compounds living things can use","It removes all oxygen from the atmosphere","It makes rock magnetic","It replaces sunlight in photosynthesis"]'::jsonb,
      'Many organisms cannot use atmospheric N2 directly. Nitrogen-fixing microbes turn it into more reactive compounds for food webs.'
    ),
    (
      'general-sachkunde-hard-06',
      'Sachkunde',
      'Was unterscheidet Klima von Wetter fachlich am besten?',
      'Klima beschreibt statistische Muster ueber lange Zeitraeume, Wetter den aktuellen Zustand',
      '["Klima beschreibt statistische Muster ueber lange Zeitraeume, Wetter den aktuellen Zustand","Klima gilt nur nachts, Wetter nur tagsueber","Klima betrifft nur Meere, Wetter nur Gebirge","Beide Begriffe sind exakt gleich"]'::jsonb,
      'Wetter ist kurzfristig und konkret. Klima fasst Wetterdaten statistisch ueber lange Perioden zusammen, oft ueber Jahrzehnte.',
      'What best distinguishes climate from weather?',
      'Climate describes long-term statistical patterns, weather the current state',
      '["Climate describes long-term statistical patterns, weather the current state","Climate applies only at night and weather only by day","Climate concerns only seas and weather only mountains","Both terms are exactly identical"]'::jsonb,
      'Weather is short-term and concrete. Climate summarizes weather data statistically over long periods, often decades.'
    ),
    (
      'general-sachkunde-hard-07',
      'Sachkunde',
      'Warum kann Salz Eis auch unter 0 Grad Celsius teilweise schmelzen lassen?',
      'Eine Salzloesung hat einen niedrigeren Gefrierpunkt als reines Wasser',
      '["Eine Salzloesung hat einen niedrigeren Gefrierpunkt als reines Wasser","Salz erzeugt Kernfusion im Eis","Salz macht Eis elektrisch unsichtbar","Salz erhoeht die Masse des Mondes"]'::jsonb,
      'Geloeste Teilchen stoeren die Bildung eines festen Eiskristallgitters. Deshalb gefriert Salzwasser erst bei tieferen Temperaturen.',
      'Why can salt make ice partially melt even below 0 degrees Celsius?',
      'A salt solution has a lower freezing point than pure water',
      '["A salt solution has a lower freezing point than pure water","Salt creates nuclear fusion in ice","Salt makes ice electrically invisible","Salt increases the Moon''s mass"]'::jsonb,
      'Dissolved particles interfere with forming a solid ice crystal lattice. Saltwater therefore freezes only at lower temperatures.'
    ),
    (
      'general-sachkunde-hard-08',
      'Sachkunde',
      'Was beschreibt Halbwertszeit allgemein?',
      'Die Zeit, nach der eine betrachtete Menge auf die Haelfte gefallen ist',
      '["Die Zeit, nach der eine betrachtete Menge auf die Haelfte gefallen ist","Die halbe Lebensdauer jedes Lebewesens","Die Temperatur, bei der Wasser halb kocht","Die Zeit bis ein Akku doppelt so schwer wird"]'::jsonb,
      'Halbwertszeit wird besonders bei radioaktivem Zerfall genutzt, beschreibt aber allgemein exponentielle Abnahme auf die Haelfte.',
      'What does half-life generally describe?',
      'The time after which a measured quantity has fallen to half',
      '["The time after which a measured quantity has fallen to half","Half the lifespan of every living thing","The temperature at which water half-boils","The time until a battery doubles in weight"]'::jsonb,
      'Half-life is especially used for radioactive decay, but generally describes exponential decrease to half the amount.'
    ),
    (
      'general-politik-hard-01',
      'Politik',
      'Was ist der Kern eines konstruktiven Misstrauensvotums?',
      'Eine Regierung wird nur abgeloest, wenn zugleich eine neue Mehrheit fuer einen Nachfolger steht',
      '["Eine Regierung wird nur abgeloest, wenn zugleich eine neue Mehrheit fuer einen Nachfolger steht","Eine Opposition darf ohne Abstimmung regieren","Ein Gericht schreibt den Koalitionsvertrag","Der Bundesrat waehlt automatisch den Bundestag neu"]'::jsonb,
      'Das Prinzip soll instabile Abwahlmehrheiten vermeiden. Kritik an der Regierung reicht nicht; eine tragfaehige Alternative muss bereitstehen.',
      'What is the core of a constructive vote of no confidence?',
      'A government is removed only if a new majority for a successor exists at the same time',
      '["A government is removed only if a new majority for a successor exists at the same time","An opposition may govern without a vote","A court writes the coalition agreement","The upper chamber automatically reelects parliament"]'::jsonb,
      'The principle avoids unstable removal majorities. Criticizing the government is not enough; a viable alternative must be ready.'
    ),
    (
      'general-politik-hard-02',
      'Politik',
      'Was unterscheidet relative von absoluter Mehrheit?',
      'Relative Mehrheit heisst groesster Stimmenanteil, absolute Mehrheit mehr als die Haelfte',
      '["Relative Mehrheit heisst groesster Stimmenanteil, absolute Mehrheit mehr als die Haelfte","Relative Mehrheit ist immer einstimmig","Absolute Mehrheit bedeutet genau null Gegenstimmen","Beide Begriffe meinen immer dasselbe"]'::jsonb,
      'Bei relativer Mehrheit genuegt Platz eins im Vergleich. Absolute Mehrheit verlangt mehr als 50 Prozent der gueltigen Stimmen oder Sitze.',
      'What distinguishes plurality from absolute majority?',
      'Plurality means the largest share, absolute majority means more than half',
      '["Plurality means the largest share, absolute majority means more than half","Plurality is always unanimous","Absolute majority means exactly zero votes against","Both terms always mean the same thing"]'::jsonb,
      'A plurality only requires coming first. An absolute majority requires more than 50 percent of valid votes or seats.'
    ),
    (
      'general-politik-hard-03',
      'Politik',
      'Welche Wirkung hat Verhaeltniswahl typischerweise eher als Mehrheitswahl?',
      'Sitzanteile naehern sich staerker den Stimmenanteilen an und Koalitionen werden wahrscheinlicher',
      '["Sitzanteile naehern sich staerker den Stimmenanteilen an und Koalitionen werden wahrscheinlicher","Nur die groesste Partei erhaelt alle Sitze","Kleine Parteien werden immer verboten","Waehler duerfen nur eine Person ernennen"]'::jsonb,
      'Verhaeltniswahl bildet Stimmenanteile genauer ab. Dadurch ziehen mehr Parteien ein, und Regierungen muessen haeufiger Koalitionen bilden.',
      'What effect does proportional representation more typically have than plurality systems?',
      'Seat shares more closely match vote shares and coalitions become more likely',
      '["Seat shares more closely match vote shares and coalitions become more likely","Only the largest party receives all seats","Small parties are always banned","Voters may appoint only one person"]'::jsonb,
      'Proportional representation maps vote shares more accurately. More parties enter parliament, so governments more often need coalitions.'
    ),
    (
      'general-politik-hard-04',
      'Politik',
      'Was meint Subsidiaritaet in der Europaeischen Union?',
      'Entscheidungen sollen moeglichst buergernah fallen, ausser eine hoehere Ebene kann es besser leisten',
      '["Entscheidungen sollen moeglichst buergernah fallen, ausser eine hoehere Ebene kann es besser leisten","Alle Entscheidungen muessen immer in Bruessel fallen","Kommunen duerfen nie entscheiden","Gerichte ersetzen jede Wahl"]'::jsonb,
      'Subsidiaritaet begruendet, warum Aufgaben nicht automatisch zentralisiert werden sollen. Die hoehere Ebene greift ein, wenn sie wirksamer handeln kann.',
      'What does subsidiarity mean in the European Union?',
      'Decisions should be made as close to citizens as possible unless a higher level can do it better',
      '["Decisions should be made as close to citizens as possible unless a higher level can do it better","All decisions must always be made in Brussels","Municipalities may never decide","Courts replace every election"]'::jsonb,
      'Subsidiarity explains why tasks should not automatically be centralized. The higher level acts when it can be more effective.'
    ),
    (
      'general-politik-hard-05',
      'Politik',
      'Welche Funktion hat gerichtliche Normenkontrolle in einem Rechtsstaat?',
      'Sie prueft, ob Gesetze mit hoeherem Recht wie der Verfassung vereinbar sind',
      '["Sie prueft, ob Gesetze mit hoeherem Recht wie der Verfassung vereinbar sind","Sie ersetzt die Gesetzgebung durch Meinungsumfragen","Sie erlaubt Gerichten, jede Steuer selbst einzuziehen","Sie verhindert jede politische Debatte"]'::jsonb,
      'Normenkontrolle bindet den Gesetzgeber an die Verfassung. Gerichte koennen rechtswidrige Normen beanstanden oder fuer unanwendbar erklaeren.',
      'What is the function of judicial review of norms in a rule-of-law state?',
      'It checks whether laws are compatible with higher law such as the constitution',
      '["It checks whether laws are compatible with higher law such as the constitution","It replaces legislation with opinion polls","It lets courts collect every tax themselves","It prevents every political debate"]'::jsonb,
      'Judicial review binds lawmakers to the constitution. Courts can challenge or invalidate unlawful norms.'
    ),
    (
      'general-politik-hard-06',
      'Politik',
      'Warum existieren in vielen Staaten zwei Parlamentskammern?',
      'Eine zweite Kammer kann Gesetze pruefen, verzoegern oder Regionen vertreten',
      '["Eine zweite Kammer kann Gesetze pruefen, verzoegern oder Regionen vertreten","Damit keine Wahl mehr noetig ist","Damit Gerichte abgeschafft werden koennen","Damit jede Partei automatisch regiert"]'::jsonb,
      'Bikameralismus dient oft Kontrolle, Beratung oder territorialer Beteiligung. Die konkrete Macht der zweiten Kammer unterscheidet sich je nach System.',
      'Why do many states have two parliamentary chambers?',
      'A second chamber can review, delay, or represent regions in legislation',
      '["A second chamber can review, delay, or represent regions in legislation","So elections are no longer needed","So courts can be abolished","So every party automatically governs"]'::jsonb,
      'Bicameralism often serves oversight, deliberation, or territorial representation. The power of the second chamber varies by system.'
    ),
    (
      'general-politik-hard-07',
      'Politik',
      'Was unterscheidet parlamentarische Regierungssysteme stark von praesidentiellen?',
      'Die Regierung ist politisch vom Vertrauen des Parlaments abhaengig',
      '["Die Regierung ist politisch vom Vertrauen des Parlaments abhaengig","Das Parlament darf keine Gesetze beraten","Der Staat hat keine Verfassung","Wahlen finden nur bei Gerichtsverfahren statt"]'::jsonb,
      'In parlamentarischen Systemen entsteht und faellt die Regierung meist durch Parlamentsmehrheiten. Praesidentielle Systeme trennen Exekutive und Legislative staerker.',
      'What strongly distinguishes parliamentary systems from presidential ones?',
      'The government politically depends on parliament''s confidence',
      '["The government politically depends on parliament''s confidence","Parliament may not debate laws","The state has no constitution","Elections occur only during trials"]'::jsonb,
      'In parliamentary systems, governments usually arise and fall through parliamentary majorities. Presidential systems separate executive and legislature more strongly.'
    ),
    (
      'general-politik-hard-08',
      'Politik',
      'Warum gilt Foederalismus oft als Machtbegrenzung?',
      'Politische Kompetenzen werden zwischen Zentralstaat und Gliedstaaten verteilt',
      '["Politische Kompetenzen werden zwischen Zentralstaat und Gliedstaaten verteilt","Alle Macht wird bei einer einzigen Behoerde gesammelt","Regionen verlieren jede Verwaltung","Gerichte duerfen keine Verfassung anwenden"]'::jsonb,
      'Foederalismus verteilt Zustaendigkeiten vertikal. Dadurch entstehen mehrere Machtzentren, die einander politisch und rechtlich begrenzen koennen.',
      'Why is federalism often considered a limit on power?',
      'Political powers are divided between the central state and constituent states',
      '["Political powers are divided between the central state and constituent states","All power is collected in one single agency","Regions lose all administration","Courts may not apply a constitution"]'::jsonb,
      'Federalism distributes authority vertically. That creates multiple power centers that can politically and legally limit each other.'
    ),
    (
      'general-geografie-hard-01',
      'Geografie',
      'Wie entsteht ein Regenschatten hinter einem Gebirge?',
      'Luft steigt an der Luvseite auf, regnet aus und sinkt leeseitig trockener ab',
      '["Luft steigt an der Luvseite auf, regnet aus und sinkt leeseitig trockener ab","Der Berg wirft nachts Schatten auf Wolken","Fluesse verdunsten nur auf der Leeseite","Vulkane saugen Regen aus der Atmosphaere"]'::jsonb,
      'Orographische Hebung kuehlt Luft und foerdert Niederschlag. Hinter dem Gebirge sinkt trockenere Luft ab und erwaermt sich.',
      'How does a rain shadow form behind a mountain range?',
      'Air rises on the windward side, loses moisture, then descends drier on the leeward side',
      '["Air rises on the windward side, loses moisture, then descends drier on the leeward side","The mountain casts night shadows on clouds","Rivers evaporate only on the leeward side","Volcanoes suck rain from the atmosphere"]'::jsonb,
      'Orographic lifting cools air and promotes precipitation. Behind the range, drier air descends and warms.'
    ),
    (
      'general-geografie-hard-02',
      'Geografie',
      'Warum haben viele Mittelmeerklimate trockene Sommer?',
      'Subtropische Hochdruckgebiete verlagern sich im Sommer polwaerts',
      '["Subtropische Hochdruckgebiete verlagern sich im Sommer polwaerts","Der Mond blockiert Sommerregen","Alle Fluesse trocknen wegen Ebbe aus","Gebirge verschwinden im Sommer"]'::jsonb,
      'Absinkende Luft in subtropischen Hochdruckzonen hemmt Wolkenbildung. Im Winter verlagern sich Westwinde und Tiefdruckbahnen eher wieder in diese Breiten.',
      'Why do many Mediterranean climates have dry summers?',
      'Subtropical high-pressure belts shift poleward in summer',
      '["Subtropical high-pressure belts shift poleward in summer","The Moon blocks summer rain","All rivers dry out because of tides","Mountains disappear in summer"]'::jsonb,
      'Descending air in subtropical highs suppresses cloud formation. In winter, westerlies and storm tracks shift back toward these latitudes.'
    ),
    (
      'general-geografie-hard-03',
      'Geografie',
      'Was beschreibt das Modell des demografischen Uebergangs?',
      'Den Wandel von hohen zu niedrigen Geburten- und Sterberaten',
      '["Den Wandel von hohen zu niedrigen Geburten- und Sterberaten","Die taegliche Wanderung aller Pendler","Die Verschiebung von Zeitzonen durch Erdbeben","Die Entstehung einzelner Wolken"]'::jsonb,
      'Das Modell ordnet Bevoelkerungsentwicklung typisiert: erst sinkt meist die Sterberate, spaeter die Geburtenrate.',
      'What does the demographic transition model describe?',
      'The shift from high to low birth and death rates',
      '["The shift from high to low birth and death rates","The daily movement of all commuters","The shifting of time zones by earthquakes","The formation of individual clouds"]'::jsonb,
      'The model typifies population change: death rates usually fall first, followed later by birth rates.'
    ),
    (
      'general-geografie-hard-04',
      'Geografie',
      'Warum wandern Flussmaeander seitlich?',
      'Aussenufer werden erodiert, Innenufer durch Ablagerung aufgebaut',
      '["Aussenufer werden erodiert, Innenufer durch Ablagerung aufgebaut","Fluesse drehen sich wegen der Erdachse immer im Kreis","Wasser fliesst an beiden Ufern gleich schnell","Sedimente verschwinden vollstaendig im Grundwasser"]'::jsonb,
      'In Kurven ist die Stroemung aussen schneller und erodiert. Innen ist sie langsamer, sodass Sedimente abgelagert werden.',
      'Why do river meanders migrate sideways?',
      'Outer banks erode while inner banks build by deposition',
      '["Outer banks erode while inner banks build by deposition","Rivers rotate in circles because of Earth''s axis","Water flows equally fast on both banks","Sediment completely disappears into groundwater"]'::jsonb,
      'In bends, flow is faster on the outside and erodes. On the inside it is slower, so sediment is deposited.'
    ),
    (
      'general-geografie-hard-05',
      'Geografie',
      'Was unterscheidet eine Exklave von einer Enklave?',
      'Eine Exklave ist vom Hauptgebiet getrennt; eine Enklave ist vollstaendig von fremdem Gebiet umgeben',
      '["Eine Exklave ist vom Hauptgebiet getrennt; eine Enklave ist vollstaendig von fremdem Gebiet umgeben","Eine Exklave liegt immer im Meer","Eine Enklave hat nie Einwohner","Beide Begriffe bezeichnen nur Inseln"]'::jsonb,
      'Eine Exklave ist aus Sicht des eigenen Staates abgetrennt. Eine Enklave ist aus Sicht des umgebenden Staates eingeschlossen.',
      'What distinguishes an exclave from an enclave?',
      'An exclave is separated from the main territory; an enclave is completely surrounded by foreign territory',
      '["An exclave is separated from the main territory; an enclave is completely surrounded by foreign territory","An exclave is always at sea","An enclave never has inhabitants","Both terms refer only to islands"]'::jsonb,
      'An exclave is detached from its own state''s main territory. An enclave is enclosed from the perspective of the surrounding state.'
    ),
    (
      'general-geografie-hard-06',
      'Geografie',
      'Warum ist der Pazifische Feuerring besonders erdbeben- und vulkanreich?',
      'Viele Plattengrenzen und Subduktionszonen umgeben den Pazifik',
      '["Viele Plattengrenzen und Subduktionszonen umgeben den Pazifik","Der Pazifik ist komplett unbewegt","Dort gibt es keine ozeanische Kruste","Vulkane entstehen nur durch starke Winde"]'::jsonb,
      'Am Rand des Pazifiks tauchen Platten haeufig unter andere Platten ab. Das erzeugt Erdbeben, Magmaentstehung und Vulkanismus.',
      'Why is the Pacific Ring of Fire especially rich in earthquakes and volcanoes?',
      'Many plate boundaries and subduction zones surround the Pacific',
      '["Many plate boundaries and subduction zones surround the Pacific","The Pacific is completely motionless","There is no oceanic crust there","Volcanoes form only through strong winds"]'::jsonb,
      'Around the Pacific, plates frequently dive beneath other plates. This creates earthquakes, magma generation, and volcanism.'
    ),
    (
      'general-geografie-hard-07',
      'Geografie',
      'Was meint relative Lage in der Geografie?',
      'Die Lage eines Ortes im Verhaeltnis zu anderen Orten oder Raeumen',
      '["Die Lage eines Ortes im Verhaeltnis zu anderen Orten oder Raeumen","Die exakte Angabe in Breiten- und Laengengraden","Die Hoehe des Meeresspiegels bei Vollmond","Die Richtung eines Kompasses ohne Karte"]'::jsonb,
      'Absolute Lage nutzt Koordinaten. Relative Lage beschreibt Beziehungen, etwa Naehe zu Verkehrswegen, Maerkten, Grenzen oder Zentren.',
      'What does relative location mean in geography?',
      'The location of a place in relation to other places or spaces',
      '["The location of a place in relation to other places or spaces","The exact latitude and longitude coordinates","Sea level at full moon","Compass direction without a map"]'::jsonb,
      'Absolute location uses coordinates. Relative location describes relationships, such as proximity to routes, markets, borders, or centers.'
    ),
    (
      'general-geografie-hard-08',
      'Geografie',
      'Warum ist die Sahelzone besonders anfaellig fuer Desertifikation?',
      'Semiarides Klima, schwankende Niederschlaege und Nutzungsdruck treffen zusammen',
      '["Semiarides Klima, schwankende Niederschlaege und Nutzungsdruck treffen zusammen","Sie liegt vollstaendig unter Gletschern","Dort regnet es taeglich gleich viel","Alle Boeden sind dauerhaft vulkanisch beheizt"]'::jsonb,
      'In der Sahelzone koennen Duerren, Beweidung, Brennholznutzung und Bevoelkerungsdruck Boden und Vegetation stark belasten.',
      'Why is the Sahel especially vulnerable to desertification?',
      'Semi-arid climate, variable rainfall, and land-use pressure overlap',
      '["Semi-arid climate, variable rainfall, and land-use pressure overlap","It lies completely under glaciers","It receives exactly equal rainfall every day","All soils are permanently volcanically heated"]'::jsonb,
      'In the Sahel, droughts, grazing, fuelwood use, and population pressure can heavily stress soil and vegetation.'
    ),
    (
      'general-brainrot-hard-01',
      'Brainrot',
      'Was meint Template Drift bei Memes am ehesten?',
      'Ein Meme-Format veraendert durch Wiederverwendung schrittweise Bedeutung und Einsatz',
      '["Ein Meme-Format veraendert durch Wiederverwendung schrittweise Bedeutung und Einsatz","Ein Bild rutscht wegen schlechter Aufloesung nach unten","Ein Algorithmus loescht alle Kommentare","Ein Creator verliert automatisch Urheberrechte"]'::jsonb,
      'Durch Remixes, neue Captions und andere Kontexte kann ein Format weit vom urspruenglichen Sinn abwandern.',
      'What does template drift most likely mean for memes?',
      'A meme format gradually changes meaning and use through reuse',
      '["A meme format gradually changes meaning and use through reuse","An image slides downward because of low resolution","An algorithm deletes all comments","A creator automatically loses copyright"]'::jsonb,
      'Through remixes, new captions, and different contexts, a format can move far away from its original meaning.'
    ),
    (
      'general-brainrot-hard-02',
      'Brainrot',
      'Was macht ein Anti-Meme typischerweise aus?',
      'Es unterlaeuft die erwartete Pointe durch wortwoertliche oder absichtlich trockene Aufloesung',
      '["Es unterlaeuft die erwartete Pointe durch wortwoertliche oder absichtlich trockene Aufloesung","Es hat immer eine offizielle Werbelizenz","Es darf keine Schrift enthalten","Es besteht nur aus mathematischen Formeln"]'::jsonb,
      'Anti-Memes funktionieren oft, weil sie die erwartete Meme-Logik verweigern und gerade dadurch komisch oder absurd wirken.',
      'What typically defines an anti-meme?',
      'It undercuts the expected punchline with a literal or deliberately dry resolution',
      '["It undercuts the expected punchline with a literal or deliberately dry resolution","It always has an official advertising license","It may contain no writing","It consists only of mathematical formulas"]'::jsonb,
      'Anti-memes often work by refusing expected meme logic, which makes them funny or absurd.'
    ),
    (
      'general-brainrot-hard-03',
      'Brainrot',
      'Was bedeutet Context Collapse in sozialen Medien?',
      'Verschiedene Zielgruppen sehen denselben Post und lesen ihn mit unterschiedlichen Erwartungen',
      '["Verschiedene Zielgruppen sehen denselben Post und lesen ihn mit unterschiedlichen Erwartungen","Ein Video verliert alle Pixel","Eine App schliesst sich wegen leerem Akku","Ein Hashtag wird alphabetisch sortiert"]'::jsonb,
      'Insider, Fremde, Freunde, Eltern oder Arbeitgeber koennen denselben Inhalt sehen. Dadurch kollidieren Kontexte, Ton und Deutung.',
      'What does context collapse mean on social media?',
      'Different audiences see the same post and read it with different expectations',
      '["Different audiences see the same post and read it with different expectations","A video loses all pixels","An app closes because the battery is empty","A hashtag is sorted alphabetically"]'::jsonb,
      'Insiders, strangers, friends, parents, or employers may see the same content. Contexts, tone, and interpretation collide.'
    ),
    (
      'general-brainrot-hard-04',
      'Brainrot',
      'Was beschreibt Post-Ironie in Online-Humor am besten?',
      'Ironie und Ernsthaftigkeit werden absichtlich so vermischt, dass die Haltung unklar bleibt',
      '["Ironie und Ernsthaftigkeit werden absichtlich so vermischt, dass die Haltung unklar bleibt","Jeder Witz wird mit Quellenangabe erklaert","Ein Beitrag darf nur per Post verschickt werden","Der Humor ist immer komplett unpolitisch"]'::jsonb,
      'Post-ironischer Humor laesst oft offen, ob etwas gemeint, gespielt oder gleichzeitig beides ist.',
      'What best describes post-irony in online humor?',
      'Irony and sincerity are deliberately mixed so the stance remains unclear',
      '["Irony and sincerity are deliberately mixed so the stance remains unclear","Every joke is explained with citations","A post may only be sent by mail","The humor is always completely apolitical"]'::jsonb,
      'Post-ironic humor often leaves open whether something is sincere, performed, or both at once.'
    ),
    (
      'general-brainrot-hard-05',
      'Brainrot',
      'Warum funktioniert Rage Bait in Plattformlogiken oft gut?',
      'Empoerung erzeugt Kommentare, Reaktionen und Verweildauer',
      '["Empoerung erzeugt Kommentare, Reaktionen und Verweildauer","Wuetende Posts werden automatisch wahr","Alle Plattformen blockieren Streit sofort","Rage Bait braucht keine Zuschauer"]'::jsonb,
      'Wenn Nutzer widersprechen, teilen oder kommentieren, kann das Engagement steigen. Manche Systeme deuten dies als Relevanzsignal.',
      'Why does rage bait often work well in platform logic?',
      'Outrage creates comments, reactions, and time spent',
      '["Outrage creates comments, reactions, and time spent","Angry posts automatically become true","All platforms instantly block arguments","Rage bait needs no viewers"]'::jsonb,
      'When users object, share, or comment, engagement can rise. Some systems read this as a relevance signal.'
    ),
    (
      'general-brainrot-hard-06',
      'Brainrot',
      'Was ist Remix Culture im Meme-Kontext?',
      'Bestehende Motive werden neu kombiniert, um andere Bedeutungen oder Witze zu erzeugen',
      '["Bestehende Motive werden neu kombiniert, um andere Bedeutungen oder Witze zu erzeugen","Alle Inhalte muessen unveraendert bleiben","Nur staatliche Medien duerfen posten","Ein Meme darf keine Vorlage haben"]'::jsonb,
      'Memes leben oft von Wiederholung mit Variation. Entscheidend sind neue Kombination, Kontextverschiebung und Wiedererkennbarkeit.',
      'What is remix culture in the meme context?',
      'Existing motifs are recombined to create new meanings or jokes',
      '["Existing motifs are recombined to create new meanings or jokes","All content must remain unchanged","Only state media may post","A meme may not have a template"]'::jsonb,
      'Memes often rely on repetition with variation. New combinations, shifted context, and recognizability are central.'
    ),
    (
      'general-brainrot-hard-07',
      'Brainrot',
      'Was meint Algorithmic Amplification?',
      'Ein System verteilt bestimmte Inhalte staerker, weil Messsignale wie Klicks oder Watchtime hoch sind',
      '["Ein System verteilt bestimmte Inhalte staerker, weil Messsignale wie Klicks oder Watchtime hoch sind","Ein Mikrofon macht jedes Video lauter","Ein Meme wird automatisch gemeinfrei","Ein Kommentar wird in mehrere Sprachen uebersetzt"]'::jsonb,
      'Plattformen priorisieren oft Inhalte, die Verhalten ausloesen. Dadurch kann Sichtbarkeit stark wachsen, ohne dass Inhalt qualitativ besser sein muss.',
      'What does algorithmic amplification mean?',
      'A system distributes certain content more because signals like clicks or watch time are high',
      '["A system distributes certain content more because signals like clicks or watch time are high","A microphone makes every video louder","A meme automatically enters the public domain","A comment is translated into several languages"]'::jsonb,
      'Platforms often prioritize content that triggers behavior. Visibility can grow sharply without the content necessarily being better.'
    ),
    (
      'general-brainrot-hard-08',
      'Brainrot',
      'Warum ist Lore fuer Meme-Communities oft schwer fuer Aussenstehende?',
      'Bedeutung entsteht aus vielen frueheren Posts, Insider-Bezuegen und Wiederholungen',
      '["Bedeutung entsteht aus vielen frueheren Posts, Insider-Bezuegen und Wiederholungen","Lore besteht immer aus amtlichen Gesetzen","Alle Memes haben nur eine einzige Bedeutung","Aussenstehende koennen Bilder technisch nicht sehen"]'::jsonb,
      'Community-Lore ist kumulativ. Ohne Vorgeschichte wirken Figuren, Saetze oder Reaktionsmuster oft zufaellig oder sinnlos.',
      'Why is lore in meme communities often hard for outsiders?',
      'Meaning comes from many earlier posts, insider references, and repetitions',
      '["Meaning comes from many earlier posts, insider references, and repetitions","Lore always consists of official laws","All memes have only one meaning","Outsiders technically cannot see images"]'::jsonb,
      'Community lore is cumulative. Without the backstory, figures, phrases, or reaction patterns can seem random or meaningless.'
    ),
    (
      'general-survival-hard-01',
      'Survival',
      'Warum ist nasse Baumwolle bei Kaelte riskant?',
      'Sie verliert Isolation und foerdert Waermeverlust durch Verdunstung und Leitung',
      '["Sie verliert Isolation und foerdert Waermeverlust durch Verdunstung und Leitung","Sie erzeugt automatisch Frostschutz","Sie wird leichter als trockene Luft","Sie blockiert jeden Wind vollstaendig"]'::jsonb,
      'Baumwolle speichert Wasser. Nasse Kleidung leitet Waerme stark ab und Verdunstung kuehlt den Koerper zusaetzlich.',
      'Why is wet cotton risky in cold conditions?',
      'It loses insulation and promotes heat loss through evaporation and conduction',
      '["It loses insulation and promotes heat loss through evaporation and conduction","It automatically creates antifreeze","It becomes lighter than dry air","It blocks all wind completely"]'::jsonb,
      'Cotton holds water. Wet clothing conducts heat away strongly, and evaporation cools the body further.'
    ),
    (
      'general-survival-hard-02',
      'Survival',
      'Was zeigen eng beieinanderliegende Hoehenlinien auf einer topografischen Karte an?',
      'Steiles Gelaende',
      '["Steiles Gelaende","Eine asphaltierte Strasse","Trinkwasserqualitaet","Windrichtung bei Nacht"]'::jsonb,
      'Hoehenlinien verbinden Punkte gleicher Hoehe. Je dichter sie liegen, desto schneller aendert sich die Hoehe auf kurzer Strecke.',
      'What do closely spaced contour lines on a topographic map indicate?',
      'Steep terrain',
      '["Steep terrain","A paved road","Drinking water quality","Night wind direction"]'::jsonb,
      'Contour lines connect points of equal elevation. The closer they are, the faster elevation changes over a short distance.'
    ),
    (
      'general-survival-hard-03',
      'Survival',
      'Welche Grenze hat ein einfacher Outdoor-Wasserfilter oft?',
      'Er entfernt nicht zwingend Viren oder geloeste Chemikalien',
      '["Er entfernt nicht zwingend Viren oder geloeste Chemikalien","Er erzeugt immer Meerwasser","Er funktioniert nur mit Benzin","Er macht jedes Wasser sofort kochend heiss"]'::jsonb,
      'Viele Filter halten Bakterien und Partikel zurueck. Viren, Salze oder Chemikalien brauchen je nach Risiko zusaetzliche Verfahren.',
      'What limitation does a simple outdoor water filter often have?',
      'It does not necessarily remove viruses or dissolved chemicals',
      '["It does not necessarily remove viruses or dissolved chemicals","It always produces seawater","It works only with gasoline","It instantly makes all water boiling hot"]'::jsonb,
      'Many filters trap bacteria and particles. Viruses, salts, or chemicals may require additional treatment depending on the risk.'
    ),
    (
      'general-survival-hard-04',
      'Survival',
      'Welche drei Faktoren bilden das Feuerdreieck?',
      'Brennstoff, Sauerstoff und ausreichende Waerme',
      '["Brennstoff, Sauerstoff und ausreichende Waerme","Sand, Wasser und Mondlicht","Karte, Kompass und Uhr","Salz, Wind und Schatten"]'::jsonb,
      'Feuer braucht brennbares Material, Oxidationsmittel und Zuendtemperatur. Entfernt man einen Faktor, erlischt oder entsteht es nicht.',
      'Which three factors form the fire triangle?',
      'Fuel, oxygen, and sufficient heat',
      '["Fuel, oxygen, and sufficient heat","Sand, water, and moonlight","Map, compass, and watch","Salt, wind, and shade"]'::jsonb,
      'Fire needs combustible material, an oxidizer, and ignition temperature. Remove one factor and it goes out or cannot start.'
    ),
    (
      'general-survival-hard-05',
      'Survival',
      'Warum ist Whiteout im Schnee so gefaehrlich?',
      'Horizont, Konturen und Tiefenwahrnehmung koennen verschwinden',
      '["Horizont, Konturen und Tiefenwahrnehmung koennen verschwinden","Schnee wird dadurch sofort giftig","Kompassnadeln zeigen immer nach Sueden","Atmung ist automatisch unmoeglich"]'::jsonb,
      'Bei diffusem Licht und Schneefall fehlen visuelle Referenzen. Dadurch werden Orientierung, Hangneigung und Entfernungen schwer einschaetzbar.',
      'Why is whiteout in snow so dangerous?',
      'The horizon, contours, and depth perception can disappear',
      '["The horizon, contours, and depth perception can disappear","Snow instantly becomes poisonous","Compass needles always point south","Breathing automatically becomes impossible"]'::jsonb,
      'With diffuse light and snow, visual references vanish. Orientation, slope angle, and distance become hard to judge.'
    ),
    (
      'general-survival-hard-06',
      'Survival',
      'Warum priorisiert man bei starker Exposition oft Schutz vor Wasser- oder Nahrungssuche?',
      'Unterkuehlung oder Hitzestress kann schneller kritisch werden als Hunger',
      '["Unterkuehlung oder Hitzestress kann schneller kritisch werden als Hunger","Nahrung ist im Freien immer giftig","Wasser laesst sich nie transportieren","Schutz verbraucht keine Zeit"]'::jsonb,
      'Die Rule of Threes ist grob, aber nuetzlich: Temperatur- und Wetterschutz koennen unter harten Bedingungen sehr schnell entscheidend sein.',
      'Why is shelter often prioritized over water or food search in severe exposure?',
      'Hypothermia or heat stress can become critical faster than hunger',
      '["Hypothermia or heat stress can become critical faster than hunger","All outdoor food is poisonous","Water can never be carried","Shelter takes no time"]'::jsonb,
      'The rule of threes is rough but useful: temperature and weather protection can become decisive very quickly in harsh conditions.'
    ),
    (
      'general-survival-hard-07',
      'Survival',
      'Welche Lawinenlage ist besonders kritisch?',
      'Steile, windverfrachtete Haenge nach Neuschnee oder starker Erwaermung',
      '["Steile, windverfrachtete Haenge nach Neuschnee oder starker Erwaermung","Flacher Asphalt bei Sommerhitze","Ein trockener Strand ohne Schnee","Ein leerer Innenraum ohne Hang"]'::jsonb,
      'Hangneigung, frischer Schnee, Windtransport und Temperaturanstieg koennen instabile Schneeschichten erzeugen. Regionale Lawinenlageberichte sind entscheidend.',
      'Which avalanche situation is especially critical?',
      'Steep wind-loaded slopes after new snow or strong warming',
      '["Steep wind-loaded slopes after new snow or strong warming","Flat asphalt in summer heat","A dry beach without snow","An empty indoor room without a slope"]'::jsonb,
      'Slope angle, fresh snow, wind loading, and warming can create unstable snow layers. Regional avalanche forecasts are crucial.'
    ),
    (
      'general-survival-hard-08',
      'Survival',
      'Warum verliert ein nasser Daunenschlafsack stark an Leistung?',
      'Daunen verlieren Loft und damit die isolierende Luftschicht',
      '["Daunen verlieren Loft und damit die isolierende Luftschicht","Daunen werden zu Metall","Nasse Daunen erzeugen aktiven Wind","Wasser macht Isolation immer besser"]'::jsonb,
      'Daunen isolieren vor allem durch eingeschlossene Luft. Wenn sie verklumpen, bricht diese Luftschicht zusammen.',
      'Why does a wet down sleeping bag lose much of its performance?',
      'Down loses loft and therefore the insulating air layer',
      '["Down loses loft and therefore the insulating air layer","Down turns into metal","Wet down creates active wind","Water always improves insulation"]'::jsonb,
      'Down insulates mainly through trapped air. When it clumps, that air layer collapses.'
    )
),
upsert_questions as (
  insert into public.questions (
    slug,
    category,
    question,
    correct_answer,
    options,
    explanation
  )
  select
    slug,
    category,
    question_de,
    correct_de,
    options_de,
    explanation_de
  from question_rows
  on conflict (slug) do update
    set category = excluded.category,
        question = excluded.question,
        correct_answer = excluded.correct_answer,
        options = excluded.options,
        explanation = excluded.explanation,
        updated_at = now()
  returning id, slug
)
insert into public.question_translations (
  question_id,
  language,
  question,
  options,
  correct_answer,
  explanation
)
select
  upsert_questions.id,
  'en',
  question_rows.question_en,
  question_rows.options_en,
  question_rows.correct_en,
  question_rows.explanation_en
from upsert_questions
join question_rows
  on question_rows.slug = upsert_questions.slug
on conflict (question_id, language) do update
  set question = excluded.question,
      options = excluded.options,
      correct_answer = excluded.correct_answer,
      explanation = excluded.explanation,
      updated_at = now();
