-- Remove autogenerated placeholder questions from the database.
-- Criteria mirror the client-side autogen detection in quizService.

with autogen_candidates as (
  select q.id
  from public.questions q
  where (
    lower(
      concat_ws(
        ' ',
        coalesce(q.slug, ''),
        coalesce(q.question, ''),
        coalesce(q.explanation, '')
      )
    ) like any (
      array[
        '%auto-generated%',
        '%autogen%',
        '%wissenscheck%',
        '%ausgleichsfrage%',
        '%to ensure at least%',
        '%to complete 50 questions%'
      ]
    )
  )
  or (
    lower(trim(coalesce(q.correct_answer, ''))) = 'a'
    and jsonb_typeof(q.options) = 'array'
    and jsonb_array_length(q.options) = 4
    and lower(coalesce(q.options ->> 0, '')) = 'a'
    and lower(coalesce(q.options ->> 1, '')) = 'b'
    and lower(coalesce(q.options ->> 2, '')) = 'c'
    and lower(coalesce(q.options ->> 3, '')) = 'd'
  )
),
deleted_questions as (
  delete from public.questions q
  using autogen_candidates ac
  where q.id = ac.id
  returning q.id
)
select count(*)::int as deleted_autogen_questions
from deleted_questions;
