-- Expand more online category pools with another precise bilingual pack and stronger explanations.

with question_rows (
  slug,
  category,
  question_de,
  correct_de,
  options_de,
  explanation_de,
  question_en,
  correct_en,
  options_en,
  explanation_en
) as (
  values
    (
      'online-erklaert-plus-genetik-01',
      'Genetik',
      'Welcher Mutationstyp liegt der Sichelzellkrankheit klassisch zugrunde?',
      'Missense-Mutation',
      '["Missense-Mutation","Nonsense-Mutation","Frameshift-Mutation","Trinukleotidexpansion"]'::jsonb,
      'Die Sichelzellkrankheit entsteht durch einen Basenaustausch im Beta-Globin-Gen mit Aminosaeurewechsel von Glutamat zu Valin. Das ist definitionsgemaess eine Missense-Mutation.',
      'Which mutation type classically underlies sickle cell disease?',
      'Missense mutation',
      '["Missense mutation","Nonsense mutation","Frameshift mutation","Trinucleotide repeat expansion"]'::jsonb,
      'Sickle cell disease is caused by a base substitution in the beta-globin gene that changes glutamate to valine. By definition, this is a missense mutation.'
    ),
    (
      'online-erklaert-plus-genetik-02',
      'Genetik',
      'Welches Vererbungsmuster zeigt das Marfan-Syndrom klassisch?',
      'Autosomal-dominant',
      '["Autosomal-dominant","Autosomal-rezessiv","X-chromosomal-rezessiv","Mitochondrial"]'::jsonb,
      'Das Marfan-Syndrom beruht meist auf Mutationen in FBN1 und wird klassisch autosomal-dominant vererbt. Deshalb kann bereits ein mutiertes Allel zur Erkrankung fuehren.',
      'Which inheritance pattern is classic for Marfan syndrome?',
      'Autosomal dominant',
      '["Autosomal dominant","Autosomal recessive","X-linked recessive","Mitochondrial"]'::jsonb,
      'Marfan syndrome is usually caused by mutations in FBN1 and classically follows an autosomal dominant inheritance pattern. One mutated allele is therefore sufficient to cause disease.'
    ),
    (
      'online-erklaert-plus-genetik-03',
      'Genetik',
      'Welche Chromosomenregion ist beim Cri-du-chat-Syndrom deletiert?',
      '5p-Deletion',
      '["5p-Deletion","7q-Deletion","15q11-Deletion","22q11.2-Deletion"]'::jsonb,
      'Das Cri-du-chat-Syndrom entsteht durch Verlust des kurzen Arms von Chromosom 5. Daher lautet die klassische chromosomale Veraenderung 5p-Deletion.',
      'Which chromosomal region is deleted in cri-du-chat syndrome?',
      '5p deletion',
      '["5p deletion","7q deletion","15q11 deletion","22q11.2 deletion"]'::jsonb,
      'Cri-du-chat syndrome is caused by loss of the short arm of chromosome 5. The classic chromosomal abnormality is therefore a 5p deletion.'
    ),
    (
      'online-erklaert-plus-genetik-04',
      'Genetik',
      'Welches Trinukleotid ist bei Morbus Huntington expandiert?',
      'CAG',
      '["CAG","CGG","GAA","CTG"]'::jsonb,
      'Morbus Huntington wird durch eine CAG-Repeat-Expansion im HTT-Gen verursacht. Die Zahl der CAG-Wiederholungen korreliert mit Antizipation und frueherem Erkrankungsbeginn.',
      'Which trinucleotide repeat is expanded in Huntington disease?',
      'CAG',
      '["CAG","CGG","GAA","CTG"]'::jsonb,
      'Huntington disease is caused by a CAG repeat expansion in the HTT gene. The number of CAG repeats correlates with anticipation and earlier onset.'
    ),
    (
      'online-erklaert-plus-genetik-05',
      'Genetik',
      'Welcher DNA-Reparaturweg ist bei Xeroderma pigmentosum gestoert?',
      'Nukleotidexzisionsreparatur',
      '["Nukleotidexzisionsreparatur","Basenexzisionsreparatur","Mismatch-Reparatur","Nicht-homologes End-Joining"]'::jsonb,
      'Bei Xeroderma pigmentosum koennen UV-induzierte Pyrimidindimere nicht korrekt entfernt werden. Der defekte Reparaturweg ist deshalb die Nukleotidexzisionsreparatur.',
      'Which DNA repair pathway is defective in xeroderma pigmentosum?',
      'Nucleotide excision repair',
      '["Nucleotide excision repair","Base excision repair","Mismatch repair","Non-homologous end joining"]'::jsonb,
      'In xeroderma pigmentosum, UV-induced pyrimidine dimers cannot be removed properly. The defective repair pathway is therefore nucleotide excision repair.'
    ),
    (
      'online-erklaert-plus-genetik-06',
      'Genetik',
      'Von welchem Elternteil stammt bei mitochondrialer Vererbung typischerweise die mutierte DNA?',
      'Mutter',
      '["Mutter","Vater","Von beiden Elternteilen gleich","Nur vom maennlichen Geschwister"]'::jsonb,
      'Mitochondriale DNA wird bei der Befruchtung nahezu ausschliesslich ueber die Eizelle weitergegeben. Daher werden mitochondriale Erkrankungen klassisch maternal vererbt.',
      'From which parent does mutated DNA typically come in mitochondrial inheritance?',
      'Mother',
      '["Mother","Father","Equally from both parents","Only from a male sibling"]'::jsonb,
      'Mitochondrial DNA is transmitted almost exclusively through the oocyte at fertilization. Mitochondrial diseases therefore classically show maternal inheritance.'
    ),
    (
      'online-erklaert-plus-genetik-07',
      'Genetik',
      'Welche Mikrodeletion ist klassisch mit dem DiGeorge-Syndrom assoziiert?',
      '22q11.2-Deletion',
      '["22q11.2-Deletion","5p-Deletion","7q11-Deletion","13q14-Deletion"]'::jsonb,
      'Das DiGeorge-Syndrom ist klassisch mit einer 22q11.2-Deletion verbunden. Diese stoert unter anderem die Entwicklung der dritten und vierten Schlundtaschen.',
      'Which microdeletion is classically associated with DiGeorge syndrome?',
      '22q11.2 deletion',
      '["22q11.2 deletion","5p deletion","7q11 deletion","13q14 deletion"]'::jsonb,
      'DiGeorge syndrome is classically associated with a 22q11.2 deletion. This disrupts development of the third and fourth pharyngeal pouches among other structures.'
    ),
    (
      'online-erklaert-plus-genetik-08',
      'Genetik',
      'Welche Translokation liegt der chronischen myeloischen Leukamie klassisch zugrunde?',
      't(9;22)',
      '["t(9;22)","t(8;14)","t(15;17)","t(11;14)"]'::jsonb,
      'Die CML ist klassisch durch das Philadelphia-Chromosom mit BCR-ABL-Fusionsgen charakterisiert. Dieses entsteht durch die Translokation t(9;22).',
      'Which translocation classically underlies chronic myeloid leukemia?',
      't(9;22)',
      '["t(9;22)","t(8;14)","t(15;17)","t(11;14)"]'::jsonb,
      'CML is classically characterized by the Philadelphia chromosome with the BCR-ABL fusion gene. This results from the translocation t(9;22).'
    ),
    (
      'online-erklaert-plus-genetik-09',
      'Genetik',
      'Welcher Imprinting-Defekt verursacht das Angelman-Syndrom klassisch?',
      'Maternale Deletion von 15q11-q13',
      '["Maternale Deletion von 15q11-q13","Paternale Deletion von 15q11-q13","Trisomie 13","Monosomie X"]'::jsonb,
      'Das Angelman-Syndrom entsteht klassisch durch Verlust maternaler Genexpression im Bereich 15q11-q13. Die paternale Deletion desselben Bereichs verursacht dagegen typischerweise das Prader-Willi-Syndrom.',
      'Which imprinting defect classically causes Angelman syndrome?',
      'Maternal deletion of 15q11-q13',
      '["Maternal deletion of 15q11-q13","Paternal deletion of 15q11-q13","Trisomy 13","Monosomy X"]'::jsonb,
      'Angelman syndrome classically results from loss of maternal gene expression in the 15q11-q13 region. A paternal deletion of the same region instead typically causes Prader-Willi syndrome.'
    ),
    (
      'online-erklaert-plus-genetik-10',
      'Genetik',
      'Welcher Karyotyp ist klassisch fuer das Klinefelter-Syndrom?',
      '47,XXY',
      '["47,XXY","45,X","47,XYY","47,XXX"]'::jsonb,
      'Das Klinefelter-Syndrom beschreibt einen maennlichen Karyotyp mit einem zusaetzlichen X-Chromosom. Der klassische Befund ist daher 47,XXY.',
      'Which karyotype is classic for Klinefelter syndrome?',
      '47,XXY',
      '["47,XXY","45,X","47,XYY","47,XXX"]'::jsonb,
      'Klinefelter syndrome refers to a male karyotype with an extra X chromosome. The classic karyotype is therefore 47,XXY.'
    ),
    (
      'online-erklaert-plus-immunologie-01',
      'Immunologie',
      'Welche Immunglobulinklasse passiert die Plazenta?',
      'IgG',
      '["IgG","IgA","IgM","IgE"]'::jsonb,
      'IgG ist die einzige Immunglobulinklasse, die in relevantem Umfang plazentagaengig ist. Dadurch erhaelt das Neugeborene einen passiven Nestschutz.',
      'Which immunoglobulin class crosses the placenta?',
      'IgG',
      '["IgG","IgA","IgM","IgE"]'::jsonb,
      'IgG is the only immunoglobulin class that crosses the placenta in clinically relevant amounts. This provides passive neonatal immunity.'
    ),
    (
      'online-erklaert-plus-immunologie-02',
      'Immunologie',
      'Welche Immunglobulinklasse dominiert in Schleimhautsekreten?',
      'IgA',
      '["IgA","IgG","IgM","IgD"]'::jsonb,
      'Sekretorisches IgA ist das wichtigste Antikoerpermolekuel an Schleimhaeuten wie Darm, Atemwegen und Speichel. Es neutralisiert Erreger, ohne eine starke Entzuendungsreaktion auszuloesen.',
      'Which immunoglobulin class predominates in mucosal secretions?',
      'IgA',
      '["IgA","IgG","IgM","IgD"]'::jsonb,
      'Secretory IgA is the dominant antibody at mucosal surfaces such as the gut, respiratory tract, and saliva. It neutralizes pathogens without provoking strong inflammation.'
    ),
    (
      'online-erklaert-plus-immunologie-03',
      'Immunologie',
      'Welches Zytokin foerdert besonders die Aktivierung und Reifung von Eosinophilen?',
      'IL-5',
      '["IL-5","IL-2","IL-10","TNF-alpha"]'::jsonb,
      'IL-5 ist das Leitschluesselzytokin fuer Eosinophile. Es foerdert deren Wachstum, Reifung und Aktivierung und ist daher besonders bei Allergien und Helmintheninfektionen wichtig.',
      'Which cytokine particularly promotes eosinophil activation and maturation?',
      'IL-5',
      '["IL-5","IL-2","IL-10","TNF-alpha"]'::jsonb,
      'IL-5 is the key cytokine for eosinophils. It promotes their growth, maturation, and activation and is especially important in allergy and helminth infection.'
    ),
    (
      'online-erklaert-plus-immunologie-04',
      'Immunologie',
      'Ein Defekt welcher Komplementkomponenten beguenstigt rezidivierende Neisserieninfektionen?',
      'C5-C9',
      '["C5-C9","C1-Inhibitor","C3a und C5a","Faktor B allein"]'::jsonb,
      'Die terminalen Komplementkomponenten C5 bis C9 bilden den Membranangriffskomplex. Dessen Ausfall erhoeht klassisch die Anfaelligkeit fuer Neisseria-Infektionen.',
      'Deficiency of which complement components predisposes to recurrent Neisseria infections?',
      'C5-C9',
      '["C5-C9","C1 inhibitor","C3a and C5a","Factor B alone"]'::jsonb,
      'The terminal complement components C5 through C9 form the membrane attack complex. Loss of this complex classically increases susceptibility to Neisseria infections.'
    ),
    (
      'online-erklaert-plus-immunologie-05',
      'Immunologie',
      'Welche Zellen praesentieren koerpereigene Peptide ueber MHC-I?',
      'Alle kernhaltigen Zellen',
      '["Alle kernhaltigen Zellen","Nur dendritische Zellen","Nur B-Lymphozyten","Nur Makrophagen"]'::jsonb,
      'MHC-I wird grundsaetzlich von nahezu allen kernhaltigen Zellen exprimiert und praesentiert endogene Peptide an CD8-positive T-Zellen. Erythrozyten sind eine wichtige Ausnahme, weil sie keinen Kern besitzen.',
      'Which cells present endogenous peptides via MHC I?',
      'All nucleated cells',
      '["All nucleated cells","Only dendritic cells","Only B lymphocytes","Only macrophages"]'::jsonb,
      'MHC I is expressed by nearly all nucleated cells and presents endogenous peptides to CD8-positive T cells. Erythrocytes are a key exception because they lack a nucleus.'
    ),
    (
      'online-erklaert-plus-immunologie-06',
      'Immunologie',
      'Welcher Test weist Antikoerper oder Komplement direkt auf Erythrozyten des Patienten nach?',
      'Direkter Coombs-Test',
      '["Direkter Coombs-Test","Indirekter Coombs-Test","ELISA auf IgE","Monospot-Test"]'::jsonb,
      'Der direkte Coombs-Test weist Immunglobuline oder Komplement nach, die bereits an die Erythrozytenoberflaeche gebunden sind. Er ist daher typisch bei autoimmunhaemolytischer Anaemie oder Transfusionsreaktionen.',
      'Which test detects antibodies or complement directly bound to patient erythrocytes?',
      'Direct Coombs test',
      '["Direct Coombs test","Indirect Coombs test","IgE ELISA","Monospot test"]'::jsonb,
      'The direct Coombs test detects immunoglobulins or complement already bound to the erythrocyte surface. It is therefore typical in autoimmune hemolytic anemia and transfusion reactions.'
    ),
    (
      'online-erklaert-plus-immunologie-07',
      'Immunologie',
      'Welcher Enzymdefekt liegt der chronischen Granulomatose zugrunde?',
      'NADPH-Oxidase',
      '["NADPH-Oxidase","Myeloperoxidase","Adenosin-Desaminase","Tyrosinkinase BTK"]'::jsonb,
      'Bei der chronischen Granulomatose ist die NADPH-Oxidase defekt. Dadurch faellt der respiratorische Burst aus und betroffene Patienten sind besonders anfaellig fuer katalasepositive Erreger.',
      'Which enzyme defect underlies chronic granulomatous disease?',
      'NADPH oxidase',
      '["NADPH oxidase","Myeloperoxidase","Adenosine deaminase","BTK tyrosine kinase"]'::jsonb,
      'In chronic granulomatous disease, NADPH oxidase is defective. This abolishes the respiratory burst and makes patients particularly vulnerable to catalase-positive organisms.'
    ),
    (
      'online-erklaert-plus-immunologie-08',
      'Immunologie',
      'Welche Tyrosinkinase ist bei der X-chromosomalen Agammaglobulinaemie nach Bruton mutiert?',
      'BTK',
      '["BTK","JAK2","ABL","SYK"]'::jsonb,
      'Die Bruton-Agammaglobulinaemie beruht auf Mutationen der Brutons Tyrosinkinase, kurz BTK. Dadurch ist die B-Zell-Reifung gestoppt und reife B-Zellen fehlen weitgehend.',
      'Which tyrosine kinase is mutated in X-linked agammaglobulinemia of Bruton?',
      'BTK',
      '["BTK","JAK2","ABL","SYK"]'::jsonb,
      'Bruton agammaglobulinemia is caused by mutations in Brutons tyrosine kinase, abbreviated BTK. B-cell maturation is therefore arrested and mature B cells are largely absent.'
    ),
    (
      'online-erklaert-plus-immunologie-09',
      'Immunologie',
      'Welcher Hypersensitivitaetstyp liegt einer akuten haemolytischen Transfusionsreaktion zugrunde?',
      'Typ II',
      '["Typ II","Typ I","Typ III","Typ IV"]'::jsonb,
      'Die akute haemolytische Transfusionsreaktion wird durch Antikoerper gegen Zelloberflaechenantigene vermittelt. Das entspricht der antikoerpervermittelten zytotoxischen Reaktion vom Typ II.',
      'Which hypersensitivity type underlies an acute hemolytic transfusion reaction?',
      'Type II',
      '["Type II","Type I","Type III","Type IV"]'::jsonb,
      'An acute hemolytic transfusion reaction is mediated by antibodies against cell-surface antigens. This corresponds to antibody-mediated cytotoxic hypersensitivity, or type II.'
    ),
    (
      'online-erklaert-plus-immunologie-10',
      'Immunologie',
      'Welche Erkrankung ist die haeufigste primaere Antikoerper-Mangelerkrankung?',
      'Selektiver IgA-Mangel',
      '["Selektiver IgA-Mangel","SCID","CVID","DiGeorge-Syndrom"]'::jsonb,
      'Der selektive IgA-Mangel ist die haeufigste primaere Antikoerper-Mangelerkrankung. Viele Betroffene bleiben asymptomatisch, andere zeigen wiederkehrende Schleimhautinfekte.',
      'Which disorder is the most common primary antibody deficiency?',
      'Selective IgA deficiency',
      '["Selective IgA deficiency","SCID","CVID","DiGeorge syndrome"]'::jsonb,
      'Selective IgA deficiency is the most common primary antibody deficiency. Many affected individuals remain asymptomatic, while others develop recurrent mucosal infections.'
    ),
    (
      'online-erklaert-plus-physiologie-01',
      'Physiologie',
      'In welchem Nephronsegment werden prozentual die meisten Natriumionen rueckresorbiert?',
      'Proximaler Tubulus',
      '["Proximaler Tubulus","Dicker aufsteigender Teil der Henle-Schleife","Distaler Tubulus","Sammelrohr"]'::jsonb,
      'Der proximale Tubulus resorbiert den groessten Anteil des filtrierten Natriums und Wassers. Weiter distal erfolgt eher die Feinregulation als die mengenmaessig groesste Rueckresorption.',
      'Which nephron segment reabsorbs the largest proportion of filtered sodium?',
      'Proximal tubule',
      '["Proximal tubule","Thick ascending limb of the loop of Henle","Distal tubule","Collecting duct"]'::jsonb,
      'The proximal tubule reabsorbs the largest share of filtered sodium and water. More distal nephron segments mainly handle fine regulation rather than the bulk of reabsorption.'
    ),
    (
      'online-erklaert-plus-physiologie-02',
      'Physiologie',
      'In welcher Form wird Kohlendioxid im Blut ueberwiegend transportiert?',
      'Als Bikarbonat',
      '["Als Bikarbonat","Als frei geloestes CO2","Gebunden an Albumin","Als Kohlensaeure im Plasma"]'::jsonb,
      'Der groesste Teil des CO2 wird nach Umwandlung in den Erythrozyten als Bikarbonat im Blut transportiert. Nur ein kleinerer Anteil liegt physikalisch geloest oder an Proteine gebunden vor.',
      'In which form is carbon dioxide transported predominantly in blood?',
      'As bicarbonate',
      '["As bicarbonate","As dissolved CO2","Bound to albumin","As carbonic acid in plasma"]'::jsonb,
      'Most carbon dioxide is transported in blood as bicarbonate after conversion within erythrocytes. Only a smaller fraction is physically dissolved or protein bound.'
    ),
    (
      'online-erklaert-plus-physiologie-03',
      'Physiologie',
      'Welcher kardiale Schrittmacher hat physiologisch die hoechste spontane Frequenz?',
      'Sinusknoten',
      '["Sinusknoten","AV-Knoten","His-Buendel","Purkinje-Fasern"]'::jsonb,
      'Der Sinusknoten depolarisiert physiologisch am schnellsten und gibt deshalb den Herzrhythmus vor. Nachgeschaltete Schrittmacherzentren feuern langsamer und werden normalerweise uebersteuert.',
      'Which cardiac pacemaker has the highest spontaneous firing rate under physiologic conditions?',
      'Sinoatrial node',
      '["Sinoatrial node","Atrioventricular node","His bundle","Purkinje fibers"]'::jsonb,
      'The sinoatrial node depolarizes fastest under physiologic conditions and therefore sets the heart rate. Downstream pacemakers fire more slowly and are normally overdriven.'
    ),
    (
      'online-erklaert-plus-physiologie-04',
      'Physiologie',
      'Welcher Lungenparameter kann mit einfacher Spirometrie nicht direkt gemessen werden?',
      'Residualvolumen',
      '["Residualvolumen","Vitalkapazitaet","Atemzugvolumen","Inspiratorisches Reservevolumen"]'::jsonb,
      'Die Spirometrie erfasst nur Luftvolumina, die ein- oder ausgeatmet werden koennen. Das nach maximaler Exspiration verbleibende Residualvolumen ist daher nicht direkt messbar.',
      'Which lung parameter cannot be measured directly by simple spirometry?',
      'Residual volume',
      '["Residual volume","Vital capacity","Tidal volume","Inspiratory reserve volume"]'::jsonb,
      'Spirometry measures only volumes that can be inhaled or exhaled. The residual volume remaining after maximal expiration therefore cannot be measured directly.'
    ),
    (
      'online-erklaert-plus-physiologie-05',
      'Physiologie',
      'Welche Zellen produzieren den pulmonalen Surfactant?',
      'Typ-II-Pneumozyten',
      '["Typ-II-Pneumozyten","Typ-I-Pneumozyten","Alveolarmakrophagen","Club-Zellen"]'::jsonb,
      'Typ-II-Pneumozyten synthetisieren und sezernieren Surfactant, das die Oberflaechenspannung in den Alveolen senkt. Dadurch wird der Kollaps kleiner Alveolen waehrend der Exspiration verhindert.',
      'Which cells produce pulmonary surfactant?',
      'Type II pneumocytes',
      '["Type II pneumocytes","Type I pneumocytes","Alveolar macrophages","Club cells"]'::jsonb,
      'Type II pneumocytes synthesize and secrete surfactant, which lowers alveolar surface tension. This helps prevent collapse of small alveoli during expiration.'
    ),
    (
      'online-erklaert-plus-physiologie-06',
      'Physiologie',
      'Welches Hormon fuehrt ueber V2-Rezeptoren zum Einbau von Aquaporin-2 im Sammelrohr?',
      'ADH',
      '["ADH","Aldosteron","ANP","Renin"]'::jsonb,
      'ADH, auch Vasopressin genannt, bindet an V2-Rezeptoren der Hauptzellen im Sammelrohr. Das foerdert den Einbau von Aquaporin-2 und steigert die Wasserrueckresorption.',
      'Which hormone causes insertion of aquaporin-2 in the collecting duct via V2 receptors?',
      'ADH',
      '["ADH","Aldosterone","ANP","Renin"]'::jsonb,
      'ADH, also called vasopressin, binds to V2 receptors on principal cells in the collecting duct. This promotes aquaporin-2 insertion and increases water reabsorption.'
    ),
    (
      'online-erklaert-plus-physiologie-07',
      'Physiologie',
      'Welcher Nerv vermittelt den afferenten Schenkel des Karotissinusreflexes?',
      'N. glossopharyngeus',
      '["N. glossopharyngeus","N. vagus","N. phrenicus","N. facialis"]'::jsonb,
      'Die Barorezeptoren des Karotissinus leiten ihre Signale ueber den Nervus glossopharyngeus zum Hirnstamm. Der N. vagus ist dagegen der afferente Nerv des Aortenbogenreflexes.',
      'Which nerve carries the afferent limb of the carotid sinus reflex?',
      'Glossopharyngeal nerve',
      '["Glossopharyngeal nerve","Vagus nerve","Phrenic nerve","Facial nerve"]'::jsonb,
      'Baroreceptors in the carotid sinus send their signals to the brainstem through the glossopharyngeal nerve. The vagus nerve instead carries afferents from the aortic arch.'
    ),
    (
      'online-erklaert-plus-physiologie-08',
      'Physiologie',
      'Wo ist die Stroemungsgeschwindigkeit des Blutes wegen der groessten Gesamtquerschnittsflaeche am geringsten?',
      'Kapillaren',
      '["Kapillaren","Aorta","Arteriolen","Vena cava"]'::jsonb,
      'Die Gesamtquerschnittsflaeche ist im Kapillarbett am groessten. Deshalb ist dort die lineare Stroemungsgeschwindigkeit am niedrigsten, was den Stoffaustausch erleichtert.',
      'Where is blood flow velocity lowest because total cross-sectional area is greatest?',
      'Capillaries',
      '["Capillaries","Aorta","Arterioles","Vena cava"]'::jsonb,
      'Total cross-sectional area is greatest in the capillary bed. Blood flow velocity is therefore lowest there, which facilitates exchange of gases and solutes.'
    ),
    (
      'online-erklaert-plus-physiologie-09',
      'Physiologie',
      'Wie ist das Ventilations-Perfusions-Verhaeltnis an der Lungenspitze im Vergleich zur Lungenbasis?',
      'Hoeher',
      '["Hoeher","Gleich","Niedriger","Null"]'::jsonb,
      'An der Lungenspitze nehmen sowohl Ventilation als auch Perfusion ab, die Perfusion aber staerker. Deshalb ist das V/Q-Verhaeltnis apikal hoeher als basal.',
      'How does the ventilation-perfusion ratio at the lung apex compare with the base of the lung?',
      'Higher',
      '["Higher","Equal","Lower","Zero"]'::jsonb,
      'At the lung apex, both ventilation and perfusion decrease, but perfusion decreases more. The V/Q ratio is therefore higher at the apex than at the base.'
    ),
    (
      'online-erklaert-plus-physiologie-10',
      'Physiologie',
      'Welche Phase des Herzzyklus liegt zwischen dem Schluss der AV-Klappen und der Oeffnung der Taschenklappen?',
      'Isovolumetrische Kontraktion',
      '["Isovolumetrische Kontraktion","Austreibungsphase","Isovolumetrische Relaxation","Schnelle Fuellungsphase"]'::jsonb,
      'In dieser Phase sind alle Herzklappen geschlossen. Der Ventrikeldruck steigt rasch an, waehrend das Volumen noch unveraendert bleibt, daher isovolumetrische Kontraktion.',
      'Which phase of the cardiac cycle lies between closure of the AV valves and opening of the semilunar valves?',
      'Isovolumetric contraction',
      '["Isovolumetric contraction","Ejection phase","Isovolumetric relaxation","Rapid filling phase"]'::jsonb,
      'During this phase, all heart valves are closed. Ventricular pressure rises rapidly while volume remains unchanged, hence the term isovolumetric contraction.'
    ),
    (
      'online-erklaert-plus-pharmakologie-01',
      'Pharmakologie',
      'Welches Antidot neutralisiert unfraktioniertes Heparin?',
      'Protaminsulfat',
      '["Protaminsulfat","Vitamin K","Naloxon","Atropin"]'::jsonb,
      'Protamin ist ein stark basisches Protein und bindet das saure Heparin. Dadurch wird die antikoagulatorische Wirkung von unfraktioniertem Heparin rasch aufgehoben.',
      'Which antidote neutralizes unfractionated heparin?',
      'Protamine sulfate',
      '["Protamine sulfate","Vitamin K","Naloxone","Atropine"]'::jsonb,
      'Protamine is a strongly basic protein that binds acidic heparin. This rapidly reverses the anticoagulant effect of unfractionated heparin.'
    ),
    (
      'online-erklaert-plus-pharmakologie-02',
      'Pharmakologie',
      'Welches Enzym wird durch Warfarin gehemmt?',
      'Vitamin-K-Epoxidreduktase',
      '["Vitamin-K-Epoxidreduktase","Thrombin","Cyclooxygenase-1","Faktor Xa"]'::jsonb,
      'Warfarin hemmt die Vitamin-K-Epoxidreduktase und verhindert damit die Regeneration von reduziertem Vitamin K. Dadurch sinkt die Gamma-Carboxylierung mehrerer Gerinnungsfaktoren.',
      'Which enzyme is inhibited by warfarin?',
      'Vitamin K epoxide reductase',
      '["Vitamin K epoxide reductase","Thrombin","Cyclooxygenase-1","Factor Xa"]'::jsonb,
      'Warfarin inhibits vitamin K epoxide reductase and thereby prevents regeneration of reduced vitamin K. This decreases gamma-carboxylation of several clotting factors.'
    ),
    (
      'online-erklaert-plus-pharmakologie-03',
      'Pharmakologie',
      'Welchen Rezeptor blockiert Clopidogrel irreversibel?',
      'P2Y12-Rezeptor',
      '["P2Y12-Rezeptor","GPIIb/IIIa-Rezeptor","Beta-1-Rezeptor","M2-Rezeptor"]'::jsonb,
      'Clopidogrel hemmt irreversibel den ADP-Rezeptor P2Y12 auf Thrombozyten. Dadurch wird die Aktivierung des GPIIb/IIIa-Komplexes und damit die Aggregation gehemmt.',
      'Which receptor is irreversibly blocked by clopidogrel?',
      'P2Y12 receptor',
      '["P2Y12 receptor","GPIIb/IIIa receptor","Beta-1 receptor","M2 receptor"]'::jsonb,
      'Clopidogrel irreversibly inhibits the platelet ADP receptor P2Y12. This prevents activation of the GPIIb/IIIa complex and thereby inhibits aggregation.'
    ),
    (
      'online-erklaert-plus-pharmakologie-04',
      'Pharmakologie',
      'Welches Antidot hebt eine akute Opioidwirkung am schnellsten auf?',
      'Naloxon',
      '["Naloxon","Flumazenil","Physostigmin","N-Acetylcystein"]'::jsonb,
      'Naloxon ist ein kompetitiver Opioidrezeptor-Antagonist mit raschem Wirkungseintritt. Es wird deshalb bei opioidbedingter Atemdepression als Akutantidot eingesetzt.',
      'Which antidote most rapidly reverses acute opioid effects?',
      'Naloxone',
      '["Naloxone","Flumazenil","Physostigmine","N-acetylcysteine"]'::jsonb,
      'Naloxone is a competitive opioid receptor antagonist with rapid onset of action. It is therefore used as the acute antidote in opioid-induced respiratory depression.'
    ),
    (
      'online-erklaert-plus-pharmakologie-05',
      'Pharmakologie',
      'An welchem Nephronabschnitt wirken Schleifendiuretika primaer?',
      'Dicker aufsteigender Teil der Henle-Schleife',
      '["Dicker aufsteigender Teil der Henle-Schleife","Proximaler Tubulus","Distaler Tubulus","Sammelrohr"]'::jsonb,
      'Schleifendiuretika hemmen den Na-K-2Cl-Kotransporter im dicken aufsteigenden Teil der Henle-Schleife. Dadurch wird die Rueckresorption von Natrium, Kalium und Chlorid stark vermindert.',
      'At which nephron segment do loop diuretics act primarily?',
      'Thick ascending limb of the loop of Henle',
      '["Thick ascending limb of the loop of Henle","Proximal tubule","Distal tubule","Collecting duct"]'::jsonb,
      'Loop diuretics inhibit the Na-K-2Cl cotransporter in the thick ascending limb of the loop of Henle. This markedly reduces sodium, potassium, and chloride reabsorption.'
    ),
    (
      'online-erklaert-plus-pharmakologie-06',
      'Pharmakologie',
      'Welches Antiarrhythmikum der Klasse III verlaengert die Repolarisation?',
      'Amiodaron',
      '["Amiodaron","Lidocain","Verapamil","Metoprolol"]'::jsonb,
      'Amiodaron zaehlt ueberwiegend zur Klasse III und verlaengert das Aktionspotenzial vor allem durch Kaliumkanalblockade. Dadurch wird die Repolarisation verzoegert.',
      'Which class III antiarrhythmic prolongs repolarization?',
      'Amiodarone',
      '["Amiodarone","Lidocaine","Verapamil","Metoprolol"]'::jsonb,
      'Amiodarone is primarily a class III antiarrhythmic and prolongs the action potential mainly through potassium channel blockade. This delays repolarization.'
    ),
    (
      'online-erklaert-plus-pharmakologie-07',
      'Pharmakologie',
      'Welchen Rezeptortyp antagonisiert Atropin kompetitiv?',
      'Muskarinischer Acetylcholinrezeptor',
      '["Muskarinischer Acetylcholinrezeptor","Nikotinerger Acetylcholinrezeptor","Alpha-1-Rezeptor","D2-Rezeptor"]'::jsonb,
      'Atropin blockiert kompetitiv muskarinische Acetylcholinrezeptoren. Deshalb hemmt es parasympathische Effekte wie Bradykardie, Sekretion und Miosis.',
      'Which receptor type is competitively antagonized by atropine?',
      'Muscarinic acetylcholine receptor',
      '["Muscarinic acetylcholine receptor","Nicotinic acetylcholine receptor","Alpha-1 receptor","D2 receptor"]'::jsonb,
      'Atropine competitively blocks muscarinic acetylcholine receptors. It therefore inhibits parasympathetic effects such as bradycardia, secretion, and miosis.'
    ),
    (
      'online-erklaert-plus-pharmakologie-08',
      'Pharmakologie',
      'Welches orale Antidiabetikum senkt vor allem die hepatische Glukoneogenese?',
      'Metformin',
      '["Metformin","Glibenclamid","Sitagliptin","Acarbose"]'::jsonb,
      'Metformin vermindert vor allem die hepatische Glukoseproduktion und verbessert die Insulinsensitivitaet. Im Gegensatz zu Sulfonylharnstoffen verursacht es alleine typischerweise keine Hypoglykaemie.',
      'Which oral antidiabetic mainly lowers hepatic gluconeogenesis?',
      'Metformin',
      '["Metformin","Glibenclamide","Sitagliptin","Acarbose"]'::jsonb,
      'Metformin mainly reduces hepatic glucose production and improves insulin sensitivity. Unlike sulfonylureas, it typically does not cause hypoglycemia when used alone.'
    ),
    (
      'online-erklaert-plus-pharmakologie-09',
      'Pharmakologie',
      'Welcher Bronchodilatator ist ein kurzwirksamer Beta-2-Agonist fuer den akuten Asthmaanfall?',
      'Salbutamol',
      '["Salbutamol","Tiotropium","Montelukast","Budesonid"]'::jsonb,
      'Salbutamol ist ein kurzwirksamer Beta-2-Agonist und fuehrt rasch zur Bronchodilatation. Deshalb ist es das klassische Bedarfsmedikament beim akuten Asthmaanfall.',
      'Which bronchodilator is a short-acting beta-2 agonist for an acute asthma attack?',
      'Salbutamol',
      '["Salbutamol","Tiotropium","Montelukast","Budesonide"]'::jsonb,
      'Salbutamol is a short-acting beta-2 agonist and produces rapid bronchodilation. It is therefore the classic rescue medication in an acute asthma attack.'
    ),
    (
      'online-erklaert-plus-pharmakologie-10',
      'Pharmakologie',
      'Welches Zytostatikum hemmt die Dihydrofolatreduktase?',
      'Methotrexat',
      '["Methotrexat","Cyclophosphamid","Vincristin","Doxorubicin"]'::jsonb,
      'Methotrexat hemmt die Dihydrofolatreduktase und reduziert damit die Tetrahydrofolatbildung. Dadurch wird die Synthese von Purinen und Thymidylat gehemmt.',
      'Which cytotoxic drug inhibits dihydrofolate reductase?',
      'Methotrexate',
      '["Methotrexate","Cyclophosphamide","Vincristine","Doxorubicin"]'::jsonb,
      'Methotrexate inhibits dihydrofolate reductase and thereby reduces tetrahydrofolate formation. This impairs purine and thymidylate synthesis.'
    ),
    (
      'online-erklaert-plus-chirurgie-01',
      'Chirurgie',
      'Welche Leistenhernie tritt medial der Vasa epigastrica inferiora durch das Hesselbach-Dreieck aus?',
      'Direkte Leistenhernie',
      '["Direkte Leistenhernie","Indirekte Leistenhernie","Schenkelhernie","Narbenhernie"]'::jsonb,
      'Die direkte Leistenhernie durchtritt die Bauchwand medial der Vasa epigastrica inferiora im Hesselbach-Dreieck. Die indirekte Leistenhernie verlaeuft dagegen lateral ueber den inneren Leistenring.',
      'Which inguinal hernia emerges medial to the inferior epigastric vessels through Hesselbach triangle?',
      'Direct inguinal hernia',
      '["Direct inguinal hernia","Indirect inguinal hernia","Femoral hernia","Incisional hernia"]'::jsonb,
      'A direct inguinal hernia passes through the abdominal wall medial to the inferior epigastric vessels in Hesselbach triangle. An indirect hernia instead runs lateral through the deep inguinal ring.'
    ),
    (
      'online-erklaert-plus-chirurgie-02',
      'Chirurgie',
      'Welche Sofortmassnahme ist bei klinisch vermutetem Spannungspneumothorax lebensrettend?',
      'Unverzuegliche Entlastungspunktion',
      '["Unverzuegliche Entlastungspunktion","Abwarten auf CT","Sofortige Bronchoskopie","Nur Sauerstoff ohne Entlastung"]'::jsonb,
      'Der Spannungspneumothorax ist eine klinische Notfalldiagnose. Vor jeder Bildgebung muss der Ueberdruck sofort durch Entlastungspunktion oder gleichwertige Notfallentlastung reduziert werden.',
      'Which immediate measure is life-saving in clinically suspected tension pneumothorax?',
      'Immediate needle decompression',
      '["Immediate needle decompression","Wait for CT","Immediate bronchoscopy","Oxygen only without decompression"]'::jsonb,
      'Tension pneumothorax is a clinical emergency diagnosis. Before any imaging, pressure must be relieved immediately by needle decompression or an equivalent emergency decompression maneuver.'
    ),
    (
      'online-erklaert-plus-chirurgie-03',
      'Chirurgie',
      'Welche definitive Therapie erfordert ein akutes Kompartmentsyndrom?',
      'Fasziotomie',
      '["Fasziotomie","Elastischer Verband","Nur Hochlagerung","Alleinige Analgesie"]'::jsonb,
      'Beim akuten Kompartmentsyndrom steigt der Gewebedruck so stark an, dass Durchblutung und Nervenfunktion bedroht sind. Die definitive Therapie ist deshalb die operative Fasziotomie.',
      'Which definitive therapy is required for acute compartment syndrome?',
      'Fasciotomy',
      '["Fasciotomy","Elastic bandage","Elevation alone","Analgesia alone"]'::jsonb,
      'In acute compartment syndrome, tissue pressure rises high enough to threaten perfusion and nerve function. The definitive treatment is therefore surgical fasciotomy.'
    ),
    (
      'online-erklaert-plus-chirurgie-04',
      'Chirurgie',
      'Welcher naechste Schritt ist bei haemodynamisch instabilem Bauchtrauma mit positivem FAST angezeigt?',
      'Notfalllaparotomie',
      '["Notfalllaparotomie","Kontrastmittel-CT abwarten","Koloskopie","Elektive MRT"]'::jsonb,
      'Ein instabiler Traumapatient mit positiver FAST-Untersuchung hat bis zum Beweis des Gegenteils eine relevante intraabdominelle Blutung. In dieser Konstellation ist die Notfalllaparotomie der richtige naechste Schritt.',
      'What is the next step in hemodynamically unstable abdominal trauma with a positive FAST exam?',
      'Emergency laparotomy',
      '["Emergency laparotomy","Wait for contrast CT","Colonoscopy","Elective MRI"]'::jsonb,
      'An unstable trauma patient with a positive FAST examination must be assumed to have significant intra-abdominal bleeding until proven otherwise. In this setting, emergency laparotomy is the correct next step.'
    ),
    (
      'online-erklaert-plus-chirurgie-05',
      'Chirurgie',
      'Welche Arterie ist bei einem Epiduralhaematom nach Schlaefentrauma klassisch verletzt?',
      'A. meningea media',
      '["A. meningea media","A. cerebri media","A. ophthalmica","A. carotis externa"]'::jsonb,
      'Das klassische Epiduralhaematom nach Fraktur im Bereich des Pterions entsteht durch Ruptur der A. meningea media. Dadurch bildet sich im CT typischerweise eine bikonvexe Blutung.',
      'Which artery is classically injured in an epidural hematoma after temporal trauma?',
      'Middle meningeal artery',
      '["Middle meningeal artery","Middle cerebral artery","Ophthalmic artery","External carotid artery"]'::jsonb,
      'The classic epidural hematoma after a fracture near the pterion results from rupture of the middle meningeal artery. This typically produces a biconvex bleed on CT.'
    ),
    (
      'online-erklaert-plus-chirurgie-06',
      'Chirurgie',
      'Welche Erstmassnahme ist beim akuten arteriellen Extremitaetenverschluss ohne Kontraindikation indiziert?',
      'Sofortige Heparinisierung',
      '["Sofortige Heparinisierung","Kompressionsverband","Nur orale Analgesie","Bettruhe ohne Therapie"]'::jsonb,
      'Beim akuten arteriellen Verschluss soll die Thrombusausdehnung sofort begrenzt werden. Deshalb wird ohne Kontraindikation umgehend systemisch heparinisiert, noch bevor die definitive Revaskularisation erfolgt.',
      'Which initial measure is indicated in acute arterial limb occlusion if there is no contraindication?',
      'Immediate heparinization',
      '["Immediate heparinization","Compression bandage","Oral analgesia only","Bed rest without treatment"]'::jsonb,
      'In acute arterial occlusion, clot propagation should be limited immediately. Systemic heparinization is therefore started at once if no contraindication exists, before definitive revascularization.'
    ),
    (
      'online-erklaert-plus-chirurgie-07',
      'Chirurgie',
      'Welche Standardoperation ist bei unkomplizierter akuter Appendizitis angezeigt?',
      'Laparoskopische Appendektomie',
      '["Laparoskopische Appendektomie","Gastrektomie","Hemikolektomie rechts","Splenektomie"]'::jsonb,
      'Bei unkomplizierter akuter Appendizitis ist die laparoskopische Appendektomie der chirurgische Standard. Sie erlaubt Diagnosesicherung und Therapie in einem Eingriff.',
      'Which standard operation is indicated for uncomplicated acute appendicitis?',
      'Laparoscopic appendectomy',
      '["Laparoscopic appendectomy","Gastrectomy","Right hemicolectomy","Splenectomy"]'::jsonb,
      'For uncomplicated acute appendicitis, laparoscopic appendectomy is the surgical standard. It provides both definitive diagnosis and treatment in one procedure.'
    ),
    (
      'online-erklaert-plus-chirurgie-08',
      'Chirurgie',
      'Welche Formel verwendet 4 mL x kg Koerpergewicht x Prozent verbrannte Koerperoberflaeche zur initialen Fluessigkeitsgabe?',
      'Parkland-Formel',
      '["Parkland-Formel","MELD-Score","Child-Pugh-Score","Glasgow-Coma-Scale"]'::jsonb,
      'Die Parkland-Formel ist ein klassisches Schema fuer die initiale Volumentherapie bei groesseren Verbrennungen. Sie berechnet die Fluessigkeitsmenge mit 4 mL pro kg Koerpergewicht und Prozent verbrannter Koerperoberflaeche.',
      'Which formula uses 4 mL x body weight in kg x percent burned body surface area for initial fluid therapy?',
      'Parkland formula',
      '["Parkland formula","MELD score","Child-Pugh score","Glasgow Coma Scale"]'::jsonb,
      'The Parkland formula is a classic method for initial fluid resuscitation in major burns. It calculates fluid needs as 4 mL per kilogram body weight per percent burned body surface area.'
    ),
    (
      'online-erklaert-plus-chirurgie-09',
      'Chirurgie',
      'Welche Erkrankung ist durch die Charcot-Trias aus Fieber, Ikterus und Oberbauchschmerz gekennzeichnet?',
      'Akute Cholangitis',
      '["Akute Cholangitis","Akute Pankreatitis","Ulcus perforatum","Akute Appendizitis"]'::jsonb,
      'Die Charcot-Trias beschreibt die typische Kombination aus Fieber, Ikterus und rechtsbetontem Oberbauchschmerz bei aufsteigender biliaerer Infektion. Das spricht klassisch fuer eine akute Cholangitis.',
      'Which disease is characterized by the Charcot triad of fever, jaundice, and upper abdominal pain?',
      'Acute cholangitis',
      '["Acute cholangitis","Acute pancreatitis","Perforated peptic ulcer","Acute appendicitis"]'::jsonb,
      'The Charcot triad describes the typical combination of fever, jaundice, and right upper abdominal pain in an ascending biliary infection. This classically indicates acute cholangitis.'
    ),
    (
      'online-erklaert-plus-chirurgie-10',
      'Chirurgie',
      'Welche Leistenhernie verlaeuft lateral der Vasa epigastrica inferiora durch den inneren Leistenring?',
      'Indirekte Leistenhernie',
      '["Indirekte Leistenhernie","Direkte Leistenhernie","Schenkelhernie","Nabelhernie"]'::jsonb,
      'Die indirekte Leistenhernie tritt lateral der Vasa epigastrica inferiora in den inneren Leistenring ein und folgt dem Verlauf des Leistenkanals. Damit unterscheidet sie sich anatomisch klar von der direkten Hernie.',
      'Which inguinal hernia passes lateral to the inferior epigastric vessels through the deep inguinal ring?',
      'Indirect inguinal hernia',
      '["Indirect inguinal hernia","Direct inguinal hernia","Femoral hernia","Umbilical hernia"]'::jsonb,
      'An indirect inguinal hernia enters the deep inguinal ring lateral to the inferior epigastric vessels and follows the inguinal canal. This clearly distinguishes it anatomically from a direct hernia.'
    )
),
upsert_questions as (
  insert into public.questions (
    slug,
    category,
    question,
    correct_answer,
    options,
    explanation
  )
  select
    slug,
    category,
    question_de,
    correct_de,
    options_de,
    explanation_de
  from question_rows
  on conflict (slug) do update
    set category = excluded.category,
        question = excluded.question,
        correct_answer = excluded.correct_answer,
        options = excluded.options,
        explanation = excluded.explanation,
        updated_at = now()
  returning id, slug
)
insert into public.question_translations (
  question_id,
  language,
  question,
  options,
  correct_answer,
  explanation
)
select
  upsert_questions.id,
  'en',
  question_rows.question_en,
  question_rows.options_en,
  question_rows.correct_en,
  question_rows.explanation_en
from upsert_questions
join question_rows
  on question_rows.slug = upsert_questions.slug
on conflict (question_id, language) do update
  set question = excluded.question,
      options = excluded.options,
      correct_answer = excluded.correct_answer,
      explanation = excluded.explanation,
      updated_at = now();
