-- Add a curated precise bilingual category pack to the online Supabase question pool.

with question_rows (
  slug,
  category,
  question_de,
  correct_de,
  options_de,
  explanation_de,
  question_en,
  correct_en,
  options_en,
  explanation_en
) as (
  values
    (
      'online-praezise-anatomie-01',
      'Anatomie',
      'Welche Kehlkopfmuskeln werden primaer vom N. laryngeus recurrens innerviert?',
      'Fast alle inneren Kehlkopfmuskeln ausser dem M. cricothyroideus',
      '["Fast alle inneren Kehlkopfmuskeln ausser dem M. cricothyroideus","Nur der M. cricothyroideus","Nur die suprahyalen Muskeln","Die Schlundmuskulatur des Oesophagus"]'::jsonb,
      'Der N. laryngeus recurrens innerviert fast alle inneren Kehlkopfmuskeln motorisch. Der M. cricothyroideus wird dagegen vom N. laryngeus superior versorgt.',
      'Which laryngeal muscles are primarily innervated by the recurrent laryngeal nerve?',
      'Almost all intrinsic laryngeal muscles except the cricothyroid muscle',
      '["Almost all intrinsic laryngeal muscles except the cricothyroid muscle","Only the cricothyroid muscle","Only the suprahyoid muscles","The pharyngeal muscles of the esophagus"]'::jsonb,
      'The recurrent laryngeal nerve supplies almost all intrinsic laryngeal muscles. The cricothyroid muscle is instead innervated by the superior laryngeal nerve.'
    ),
    (
      'online-praezise-anatomie-02',
      'Anatomie',
      'Welcher Muskel initiiert die ersten Grade der Armabduktion im Schultergelenk?',
      'M. supraspinatus',
      '["M. supraspinatus","M. deltoideus","M. infraspinatus","M. subscapularis"]'::jsonb,
      'Der M. supraspinatus startet die Armabduktion. Danach uebernimmt der M. deltoideus den groesseren Bewegungsanteil.',
      'Which muscle initiates the first degrees of arm abduction at the shoulder joint?',
      'Supraspinatus muscle',
      '["Supraspinatus muscle","Deltoid muscle","Infraspinatus muscle","Subscapularis muscle"]'::jsonb,
      'The supraspinatus initiates arm abduction. The deltoid then takes over the larger share of the movement.'
    ),
    (
      'online-praezise-anatomie-03',
      'Anatomie',
      'In welchen Venenwinkel muendet der Ductus thoracicus typischerweise?',
      'Linker Venenwinkel',
      '["Linker Venenwinkel","Rechter Venenwinkel","V. cava superior","V. azygos"]'::jsonb,
      'Der Ductus thoracicus endet typischerweise am linken Venenwinkel, also am Uebergang von V. jugularis interna sinistra und V. subclavia sinistra.',
      'Into which venous angle does the thoracic duct typically drain?',
      'Left venous angle',
      '["Left venous angle","Right venous angle","Superior vena cava","Azygos vein"]'::jsonb,
      'The thoracic duct typically drains into the left venous angle, where the left internal jugular and left subclavian veins join.'
    ),
    (
      'online-praezise-anatomie-04',
      'Anatomie',
      'Auf welcher Hoehe durchtritt die Aorta typischerweise das Zwerchfell?',
      'Th12',
      '["Th12","Th8","Th10","L1"]'::jsonb,
      'Die Aorta zieht durch den Hiatus aorticus auf Hoehe Th12. Die klassischen Zwerchfelloeffnungen lauten vereinfacht Th8, Th10 und Th12.',
      'At which vertebral level does the aorta typically pass through the diaphragm?',
      'T12',
      '["T12","T8","T10","L1"]'::jsonb,
      'The aorta passes through the aortic hiatus at T12. The classic diaphragm opening levels are remembered as T8, T10, and T12.'
    ),
    (
      'online-praezise-anatomie-05',
      'Anatomie',
      'Welche Struktur gehoert zum Inhalt des Ligamentum hepatoduodenale?',
      'V. portae',
      '["V. portae","V. hepatica","A. mesenterica superior","V. cava inferior"]'::jsonb,
      'Im Ligamentum hepatoduodenale verlaeuft die Portal-Trias aus V. portae, A. hepatica propria und Ductus choledochus.',
      'Which structure is part of the hepatoduodenal ligament?',
      'Portal vein',
      '["Portal vein","Hepatic vein","Superior mesenteric artery","Inferior vena cava"]'::jsonb,
      'The hepatoduodenal ligament contains the portal triad: portal vein, proper hepatic artery, and common bile duct.'
    ),
    (
      'online-praezise-anatomie-06',
      'Anatomie',
      'Welcher Hirnnerv zieht nicht durch das Foramen jugulare?',
      'N. hypoglossus',
      '["N. hypoglossus","N. glossopharyngeus","N. vagus","N. accessorius"]'::jsonb,
      'Durch das Foramen jugulare ziehen die Hirnnerven IX, X und XI. Der N. hypoglossus verlaeuft durch den Canalis nervi hypoglossi.',
      'Which cranial nerve does not pass through the jugular foramen?',
      'Hypoglossal nerve',
      '["Hypoglossal nerve","Glossopharyngeal nerve","Vagus nerve","Accessory nerve"]'::jsonb,
      'Cranial nerves IX, X, and XI pass through the jugular foramen. The hypoglossal nerve travels through the hypoglossal canal.'
    ),
    (
      'online-praezise-biochemie-01',
      'Biochemie',
      'Welcher Vitaminmangel beeintraechtigt den Pyruvatdehydrogenase-Komplex besonders?',
      'Vitamin-B1-Mangel',
      '["Vitamin-B1-Mangel","Vitamin-B12-Mangel","Vitamin-C-Mangel","Vitamin-D-Mangel"]'::jsonb,
      'Der Pyruvatdehydrogenase-Komplex benoetigt Thiaminpyrophosphat als Kofaktor. Deshalb stoert ein Vitamin-B1-Mangel diesen Schritt.',
      'Deficiency of which vitamin particularly impairs the pyruvate dehydrogenase complex?',
      'Vitamin B1 deficiency',
      '["Vitamin B1 deficiency","Vitamin B12 deficiency","Vitamin C deficiency","Vitamin D deficiency"]'::jsonb,
      'The pyruvate dehydrogenase complex requires thiamine pyrophosphate as a cofactor. Vitamin B1 deficiency therefore impairs this step.'
    ),
    (
      'online-praezise-biochemie-02',
      'Biochemie',
      'Welches Molekuel wird in der Reaktion der Glukose-6-Phosphat-Dehydrogenase direkt gebildet?',
      'NADPH',
      '["NADPH","FADH2","ATP","Acetyl-CoA"]'::jsonb,
      'Die Glukose-6-Phosphat-Dehydrogenase erzeugt im Pentosephosphatweg NADPH. Dieses Reduktionsaequivalent ist wichtig fuer den antioxidativen Schutz.',
      'Which molecule is generated directly in the reaction catalyzed by glucose-6-phosphate dehydrogenase?',
      'NADPH',
      '["NADPH","FADH2","ATP","Acetyl-CoA"]'::jsonb,
      'Glucose-6-phosphate dehydrogenase generates NADPH in the pentose phosphate pathway. This reducing equivalent is important for antioxidant defense.'
    ),
    (
      'online-praezise-biochemie-03',
      'Biochemie',
      'Welcher allosterische Aktivator stimuliert die Phosphofructokinase-1 besonders stark?',
      'Fructose-2,6-Bisphosphat',
      '["Fructose-2,6-Bisphosphat","Citrat","ATP","Acetyl-CoA"]'::jsonb,
      'Fructose-2,6-Bisphosphat ist ein starker Aktivator der PFK-1 und foerdert damit die Glykolyse.',
      'Which allosteric activator strongly stimulates phosphofructokinase-1?',
      'Fructose-2,6-bisphosphate',
      '["Fructose-2,6-bisphosphate","Citrate","ATP","Acetyl-CoA"]'::jsonb,
      'Fructose-2,6-bisphosphate is a strong activator of PFK-1 and promotes glycolysis.'
    ),
    (
      'online-praezise-biochemie-04',
      'Biochemie',
      'Welches Transportsystem schleust langkettige Fettsaeuren in die Mitochondrienmatrix ein?',
      'Carnitin-Shuttle',
      '["Carnitin-Shuttle","Malat-Aspartat-Shuttle","Glycerol-3-Phosphat-Shuttle","Urea-Transporter"]'::jsonb,
      'Langkettige Fettsaeuren benoetigen fuer den Transport in die Mitochondrienmatrix das Carnitin-Shuttle.',
      'Which transport system carries long-chain fatty acids into the mitochondrial matrix?',
      'Carnitine shuttle',
      '["Carnitine shuttle","Malate-aspartate shuttle","Glycerol-3-phosphate shuttle","Urea transporter"]'::jsonb,
      'Long-chain fatty acids require the carnitine shuttle to enter the mitochondrial matrix.'
    ),
    (
      'online-praezise-biochemie-05',
      'Biochemie',
      'Welcher Enzymdefekt verursacht die klassische Phenylketonurie am haeufigsten?',
      'Phenylalaninhydroxylase-Mangel',
      '["Phenylalaninhydroxylase-Mangel","Homogentisat-Dioxygenase-Mangel","Galaktokinase-Mangel","Pyruvatkinase-Mangel"]'::jsonb,
      'Die klassische Phenylketonurie beruht meist auf einem Mangel der Phenylalaninhydroxylase. Dadurch kann Phenylalanin nicht ausreichend zu Tyrosin umgesetzt werden.',
      'Which enzyme defect most commonly causes classic phenylketonuria?',
      'Phenylalanine hydroxylase deficiency',
      '["Phenylalanine hydroxylase deficiency","Homogentisate dioxygenase deficiency","Galactokinase deficiency","Pyruvate kinase deficiency"]'::jsonb,
      'Classic phenylketonuria is usually caused by phenylalanine hydroxylase deficiency, preventing normal conversion of phenylalanine to tyrosine.'
    ),
    (
      'online-praezise-biochemie-06',
      'Biochemie',
      'Welches Apolipoprotein aktiviert die Lipoproteinlipase direkt?',
      'ApoC-II',
      '["ApoC-II","ApoB-100","ApoA-I","ApoE"]'::jsonb,
      'ApoC-II ist der direkte Aktivator der Lipoproteinlipase und damit entscheidend fuer den Abbau triglyceridreicher Lipoproteine.',
      'Which apolipoprotein directly activates lipoprotein lipase?',
      'ApoC-II',
      '["ApoC-II","ApoB-100","ApoA-I","ApoE"]'::jsonb,
      'ApoC-II directly activates lipoprotein lipase and is therefore essential for the breakdown of triglyceride-rich lipoproteins.'
    ),
    (
      'online-praezise-chirurgie-01',
      'Chirurgie',
      'Wofuer spricht eine schmerzlose Ikterus-Symptomatik mit palpabel vergroesserter Gallenblase nach Courvoisier am ehesten?',
      'Maligne distale Gallenwegsobstruktion',
      '["Maligne distale Gallenwegsobstruktion","Akute Virushepatitis","Nierenkolik","Duodenalulkus ohne Stauung"]'::jsonb,
      'Das Courvoisier-Zeichen weist auf eine Abflussbehinderung der extrahepatischen Gallenwege hin, haeufig durch ein Pankreaskopfkarzinom.',
      'What does painless jaundice with a palpable enlarged gallbladder according to Courvoisier most strongly suggest?',
      'Malignant distal biliary obstruction',
      '["Malignant distal biliary obstruction","Acute viral hepatitis","Renal colic","Duodenal ulcer without obstruction"]'::jsonb,
      'Courvoisier sign points to obstruction of the extrahepatic biliary tract, often from pancreatic head cancer.'
    ),
    (
      'online-praezise-chirurgie-02',
      'Chirurgie',
      'Welche sofortige medikamentoese Massnahme gehoert typischerweise zur Initialtherapie einer akuten arteriellen Gliedmassenischaemie?',
      'Systemische Heparinisierung',
      '["Systemische Heparinisierung","Hochdosis Insulin","Langsame Eiseninfusion","Ausschliesslich orale Analgesie"]'::jsonb,
      'Bei akuter arterieller Gliedmassenischaemie wird frueh systemisch heparinisiert, um eine weitere Thrombuspropagation zu verhindern.',
      'Which immediate medical step typically belongs to the initial treatment of acute arterial limb ischemia?',
      'Systemic heparinization',
      '["Systemic heparinization","High-dose insulin","Slow iron infusion","Oral analgesia only"]'::jsonb,
      'In acute arterial limb ischemia, systemic heparin is started early to prevent further thrombus propagation.'
    ),
    (
      'online-praezise-chirurgie-03',
      'Chirurgie',
      'Welcher klinische Druckschmerzpunkt ist fuer eine akute Appendizitis klassisch?',
      'McBurney-Punkt',
      '["McBurney-Punkt","Mayo-Robson-Punkt","Murphy-Punkt","Lanz-Punkt am linken Unterbauch"]'::jsonb,
      'Der McBurney-Punkt liegt im rechten Unterbauch auf der Verbindungslinie zwischen Nabel und Spina iliaca anterior superior und ist klassisch bei Appendizitis druckschmerzhaft.',
      'Which point of maximal tenderness is classically associated with acute appendicitis?',
      'McBurney point',
      '["McBurney point","Mayo-Robson point","Murphy point","Lanz point in the left lower abdomen"]'::jsonb,
      'McBurney point lies in the right lower abdomen on the line between the umbilicus and the anterior superior iliac spine and is classically tender in appendicitis.'
    ),
    (
      'online-praezise-chirurgie-04',
      'Chirurgie',
      'Welche lebensrettende Sofortmassnahme ist bei einem Spannungspneumothorax angezeigt?',
      'Sofortige Nadeldekompression',
      '["Sofortige Nadeldekompression","Abwarten unter Sauerstoffgabe","Nur orale Schmerztherapie","Elektive Spirometrie"]'::jsonb,
      'Der Spannungspneumothorax ist eine akute vitale Bedrohung. Er muss sofort durch Nadeldekompression entlastet werden, gefolgt von einer Thoraxdrainage.',
      'Which immediate life-saving measure is indicated in tension pneumothorax?',
      'Immediate needle decompression',
      '["Immediate needle decompression","Observation with oxygen only","Oral analgesia only","Elective spirometry"]'::jsonb,
      'Tension pneumothorax is an acute life-threatening condition. It must be relieved immediately with needle decompression, followed by chest tube placement.'
    ),
    (
      'online-praezise-chirurgie-05',
      'Chirurgie',
      'Welche Klassifikation wird fuer offene Frakturen standardmaessig verwendet?',
      'Gustilo-Anderson-Klassifikation',
      '["Gustilo-Anderson-Klassifikation","Child-Pugh-Klassifikation","Bismuth-Klassifikation","ASA-Klassifikation"]'::jsonb,
      'Offene Frakturen werden standardmaessig nach Gustilo und Anderson klassifiziert. Die Einteilung beschreibt Ausmass der Weichteilschaedigung und Kontamination.',
      'Which classification system is standard for open fractures?',
      'Gustilo-Anderson classification',
      '["Gustilo-Anderson classification","Child-Pugh classification","Bismuth classification","ASA classification"]'::jsonb,
      'Open fractures are classically classified with the Gustilo-Anderson system, which describes soft tissue damage and contamination.'
    ),
    (
      'online-praezise-chirurgie-06',
      'Chirurgie',
      'Welche definitive Notfalltherapie ist bei einem akuten Kompartmentsyndrom erforderlich?',
      'Sofortige Fasziotomie',
      '["Sofortige Fasziotomie","Nur Hochlagerung","Alleinige Eisapplikation","Elastischer Druckverband"]'::jsonb,
      'Das akute Kompartmentsyndrom gefaehrdet Muskeln und Nerven durch kritischen Gewebedruck. Die definitive Therapie ist die sofortige Fasziotomie.',
      'Which definitive emergency treatment is required for acute compartment syndrome?',
      'Immediate fasciotomy',
      '["Immediate fasciotomy","Elevation only","Ice application alone","Elastic compression bandage"]'::jsonb,
      'Acute compartment syndrome endangers muscles and nerves because of critically increased tissue pressure. The definitive treatment is immediate fasciotomy.'
    ),
    (
      'online-praezise-chirurgie-07',
      'Chirurgie',
      'Welche Arterie ist bei einer starken Blutung aus einem posterioren Duodenalulkus klassischerweise betroffen?',
      'A. gastroduodenalis',
      '["A. gastroduodenalis","A. gastrica sinistra","A. lienalis","A. mesenterica inferior"]'::jsonb,
      'Ein posteriores Duodenalulkus kann in die A. gastroduodenalis einbrechen und so eine massive obere Gastrointestinalblutung ausloesen.',
      'Which artery is classically involved in major bleeding from a posterior duodenal ulcer?',
      'Gastroduodenal artery',
      '["Gastroduodenal artery","Left gastric artery","Splenic artery","Inferior mesenteric artery"]'::jsonb,
      'A posterior duodenal ulcer can erode into the gastroduodenal artery and cause massive upper gastrointestinal bleeding.'
    ),
    (
      'online-praezise-chirurgie-08',
      'Chirurgie',
      'Welche Standardoperation ist bei symptomatischer Cholezystolithiasis ohne Kontraindikationen die definitive Therapie?',
      'Laparoskopische Cholezystektomie',
      '["Laparoskopische Cholezystektomie","Sigmaresektion","Appendektomie","Splenektomie"]'::jsonb,
      'Bei symptomatischer Cholezystolithiasis ist die laparoskopische Cholezystektomie die Standardtherapie, sofern keine Kontraindikationen bestehen.',
      'Which standard operation is the definitive treatment for symptomatic cholelithiasis when no contraindications exist?',
      'Laparoscopic cholecystectomy',
      '["Laparoscopic cholecystectomy","Sigmoid resection","Appendectomy","Splenectomy"]'::jsonb,
      'For symptomatic cholelithiasis, laparoscopic cholecystectomy is the standard definitive treatment when no contraindications exist.'
    ),
    (
      'online-praezise-genetik-01',
      'Genetik',
      'Eine Mutation welches Gens ist typisch fuer das Marfan-Syndrom?',
      'FBN1',
      '["FBN1","COL1A1","DMD","CFTR"]'::jsonb,
      'Das Marfan-Syndrom beruht typischerweise auf Mutationen im FBN1-Gen, das fuer Fibrillin-1 kodiert.',
      'Mutation of which gene is typical of Marfan syndrome?',
      'FBN1',
      '["FBN1","COL1A1","DMD","CFTR"]'::jsonb,
      'Marfan syndrome is typically caused by mutations in the FBN1 gene, which encodes fibrillin-1.'
    ),
    (
      'online-praezise-genetik-02',
      'Genetik',
      'Welche Chromosomenkonstellation ist klassisch fuer ein Down-Syndrom durch Robertson-Translokation?',
      'Translokation zwischen Chromosom 14 und 21',
      '["Translokation zwischen Chromosom 14 und 21","Monosomie X","Trisomie 13","Deletion auf Chromosom 5p"]'::jsonb,
      'Ein familiaeres Down-Syndrom kann durch eine Robertson-Translokation mit Beteiligung von Chromosom 21 entstehen, besonders rob(14;21).',
      'Which chromosome arrangement is classic for Down syndrome due to Robertsonian translocation?',
      'Translocation between chromosomes 14 and 21',
      '["Translocation between chromosomes 14 and 21","Monosomy X","Trisomy 13","Deletion on chromosome 5p"]'::jsonb,
      'Familial Down syndrome can result from a Robertsonian translocation involving chromosome 21, especially rob(14;21).'
    ),
    (
      'online-praezise-genetik-03',
      'Genetik',
      'Welche Trinukleotid-Repeat-Sequenz expandiert beim Morbus Huntington?',
      'CAG',
      '["CAG","CGG","CTG","GAA"]'::jsonb,
      'Beim Morbus Huntington liegt eine CAG-Repeat-Expansion im HTT-Gen vor. Sie fuehrt zu einer Polyglutamin-Erkrankung.',
      'Which trinucleotide repeat sequence expands in Huntington disease?',
      'CAG',
      '["CAG","CGG","CTG","GAA"]'::jsonb,
      'Huntington disease is caused by a CAG repeat expansion in the HTT gene, producing a polyglutamine disorder.'
    ),
    (
      'online-praezise-genetik-04',
      'Genetik',
      'Welche DNA-Reparaturbahn ist beim Lynch-Syndrom typischerweise defekt?',
      'Mismatch-Reparatur',
      '["Mismatch-Reparatur","Basenexzisionsreparatur","Nukleotidexzisionsreparatur","Nicht-homologes End-Joining"]'::jsonb,
      'Das Lynch-Syndrom beruht auf Defekten der Mismatch-Reparatur, zum Beispiel in MLH1, MSH2, MSH6 oder PMS2.',
      'Which DNA repair pathway is typically defective in Lynch syndrome?',
      'Mismatch repair',
      '["Mismatch repair","Base excision repair","Nucleotide excision repair","Non-homologous end joining"]'::jsonb,
      'Lynch syndrome is caused by defects in mismatch repair genes such as MLH1, MSH2, MSH6, or PMS2.'
    ),
    (
      'online-praezise-genetik-05',
      'Genetik',
      'Welches Vererbungsmuster ist fuer mitochondriale Erkrankungen typisch?',
      'Maternal',
      '["Maternal","Autosomal-dominant","X-chromosomal-dominant","Y-chromosomal"]'::jsonb,
      'Mitochondriale DNA wird nahezu ausschliesslich ueber die Mutter vererbt. Deshalb zeigen mitochondriale Erkrankungen ein maternales Vererbungsmuster.',
      'Which inheritance pattern is typical of mitochondrial disorders?',
      'Maternal',
      '["Maternal","Autosomal dominant","X-linked dominant","Y-linked"]'::jsonb,
      'Mitochondrial DNA is inherited almost exclusively from the mother. Mitochondrial disorders therefore show maternal inheritance.'
    ),
    (
      'online-praezise-genetik-06',
      'Genetik',
      'Welche Chromosomendeletion ist typisch fuer das Cri-du-chat-Syndrom?',
      'Deletion auf 5p',
      '["Deletion auf 5p","Deletion auf 7q","Deletion auf 15q","Deletion auf 22q"]'::jsonb,
      'Das Cri-du-chat-Syndrom ist klassisch mit einer Deletion auf dem kurzen Arm von Chromosom 5 assoziiert.',
      'Which chromosomal deletion is typical of cri-du-chat syndrome?',
      'Deletion on 5p',
      '["Deletion on 5p","Deletion on 7q","Deletion on 15q","Deletion on 22q"]'::jsonb,
      'Cri-du-chat syndrome is classically associated with a deletion on the short arm of chromosome 5.'
    ),
    (
      'online-praezise-genetik-07',
      'Genetik',
      'Welche Repeat-Expansion im FMR1-Gen ist fuer das Fragile-X-Syndrom typisch?',
      'CGG',
      '["CGG","CAG","CTG","GAA"]'::jsonb,
      'Das Fragile-X-Syndrom wird durch eine CGG-Repeat-Expansion im FMR1-Gen verursacht, meist mit nachfolgender Gen-Silencing.',
      'Which repeat expansion in the FMR1 gene is typical of fragile X syndrome?',
      'CGG',
      '["CGG","CAG","CTG","GAA"]'::jsonb,
      'Fragile X syndrome is caused by a CGG repeat expansion in the FMR1 gene, usually followed by gene silencing.'
    ),
    (
      'online-praezise-immunologie-01',
      'Immunologie',
      'Welches Komplementfragment opsonisiert Erreger besonders effektiv?',
      'C3b',
      '["C3b","C5a","C1q","C9"]'::jsonb,
      'C3b lagert sich an die Oberflaeche von Erregern an und erleichtert deren Phagozytose. Es ist das klassische Opsonin des Komplementsystems.',
      'Which complement fragment is especially effective at opsonizing pathogens?',
      'C3b',
      '["C3b","C5a","C1q","C9"]'::jsonb,
      'C3b coats pathogen surfaces and facilitates phagocytosis. It is the classic opsonin of the complement system.'
    ),
    (
      'online-praezise-mikrobiologie-01',
      'Mikrobiologie',
      'Welcher Erreger ist klassischerweise oxidasepositiv und bildet haeufig blaugruene Pigmente?',
      'Pseudomonas aeruginosa',
      '["Pseudomonas aeruginosa","Escherichia coli","Klebsiella pneumoniae","Shigella sonnei"]'::jsonb,
      'Pseudomonas aeruginosa ist oxidasepositiv und kann Pigmente wie Pyocyanin bilden, die eine blaugruene Faerbung verursachen.',
      'Which pathogen is classically oxidase positive and often produces blue-green pigments?',
      'Pseudomonas aeruginosa',
      '["Pseudomonas aeruginosa","Escherichia coli","Klebsiella pneumoniae","Shigella sonnei"]'::jsonb,
      'Pseudomonas aeruginosa is oxidase positive and can produce pigments such as pyocyanin that create a blue-green color.'
    ),
    (
      'online-praezise-mikrobiologie-02',
      'Mikrobiologie',
      'Mit welchem malignen Krankheitsbild ist eine Streptococcus gallolyticus-Bakteriaemie besonders assoziiert?',
      'Kolonkarzinom',
      '["Kolonkarzinom","Nierenzellkarzinom","Schilddruesenkarzinom","Hepatozellulaeres Karzinom"]'::jsonb,
      'Streptococcus gallolyticus, frueher S. bovis, ist klassisch mit Kolonneoplasien assoziiert. Deshalb sollte bei einer solchen Bakteriaemie gezielt danach gesucht werden.',
      'Streptococcus gallolyticus bacteremia is especially associated with which malignancy?',
      'Colorectal carcinoma',
      '["Colorectal carcinoma","Renal cell carcinoma","Thyroid carcinoma","Hepatocellular carcinoma"]'::jsonb,
      'Streptococcus gallolyticus, formerly S. bovis, is classically associated with colorectal neoplasia.'
    ),
    (
      'online-praezise-mikrobiologie-03',
      'Mikrobiologie',
      'Welcher Erreger besitzt keine Zellwand und ist deshalb gegen Beta-Laktam-Antibiotika intrinsisch unempfindlich?',
      'Mycoplasma pneumoniae',
      '["Mycoplasma pneumoniae","Streptococcus pneumoniae","Listeria monocytogenes","Corynebacterium diphtheriae"]'::jsonb,
      'Mykoplasmen besitzen keine Peptidoglykan-Zellwand. Deshalb wirken Beta-Laktam-Antibiotika gegen sie nicht.',
      'Which pathogen lacks a cell wall and is therefore intrinsically resistant to beta-lactam antibiotics?',
      'Mycoplasma pneumoniae',
      '["Mycoplasma pneumoniae","Streptococcus pneumoniae","Listeria monocytogenes","Corynebacterium diphtheriae"]'::jsonb,
      'Mycoplasmas have no peptidoglycan cell wall. That is why beta-lactam antibiotics do not work against them.'
    ),
    (
      'online-praezise-mikrobiologie-04',
      'Mikrobiologie',
      'Welcher Influenzatyp besitzt ein segmentiertes Genom und kann dadurch Antigen-Shift zeigen?',
      'Influenza-A-Virus',
      '["Influenza-A-Virus","Rhinovirus","Adenovirus","Parvovirus B19"]'::jsonb,
      'Das Influenza-A-Virus besitzt ein segmentiertes RNA-Genom. Reassortment zwischen Segmenten kann zu Antigen-Shift fuehren.',
      'Which influenza type has a segmented genome and can therefore undergo antigenic shift?',
      'Influenza A virus',
      '["Influenza A virus","Rhinovirus","Adenovirus","Parvovirus B19"]'::jsonb,
      'Influenza A virus has a segmented RNA genome. Reassortment between segments can produce antigenic shift.'
    ),
    (
      'online-praezise-mikrobiologie-05',
      'Mikrobiologie',
      'Welcher Erreger ist typisch fuer eine pseudomembranoese Kolitis nach Antibiotikatherapie?',
      'Clostridioides difficile',
      '["Clostridioides difficile","Bacteroides fragilis","Helicobacter pylori","Campylobacter jejuni"]'::jsonb,
      'Clostridioides difficile kann nach Antibiotikagabe die Darmflora verdraengen und eine toxische pseudomembranoese Kolitis ausloesen.',
      'Which pathogen is typical of pseudomembranous colitis after antibiotic therapy?',
      'Clostridioides difficile',
      '["Clostridioides difficile","Bacteroides fragilis","Helicobacter pylori","Campylobacter jejuni"]'::jsonb,
      'Clostridioides difficile can overgrow after antibiotics disrupt the normal gut flora and cause pseudomembranous colitis.'
    ),
    (
      'online-praezise-mikrobiologie-06',
      'Mikrobiologie',
      'Welcher Virulenzfaktor ist fuer invasive Erkrankungen durch Streptococcus pneumoniae am wichtigsten?',
      'Polysaccharidkapsel',
      '["Polysaccharidkapsel","Flagellen","Endosporen","Lipopolysaccharid"]'::jsonb,
      'Die Polysaccharidkapsel schuetzt Pneumokokken vor Phagozytose und ist der entscheidende Virulenzfaktor fuer invasive Infektionen.',
      'Which virulence factor is most important for invasive disease caused by Streptococcus pneumoniae?',
      'Polysaccharide capsule',
      '["Polysaccharide capsule","Flagella","Endospores","Lipopolysaccharide"]'::jsonb,
      'The polysaccharide capsule protects pneumococci from phagocytosis and is the key virulence factor for invasive infection.'
    ),
    (
      'online-praezise-mikrobiologie-07',
      'Mikrobiologie',
      'Auf welchem Spezialmedium wird Legionella pneumophila klassischerweise kultiviert?',
      'BCYE-Agar',
      '["BCYE-Agar","MacConkey-Agar","Sabouraud-Agar","Lowenstein-Jensen-Agar"]'::jsonb,
      'Legionella pneumophila wird klassischerweise auf Buffered Charcoal Yeast Extract, also BCYE-Agar, kultiviert.',
      'On which special medium is Legionella pneumophila classically cultured?',
      'BCYE agar',
      '["BCYE agar","MacConkey agar","Sabouraud agar","Lowenstein-Jensen agar"]'::jsonb,
      'Legionella pneumophila is classically cultured on buffered charcoal yeast extract, or BCYE agar.'
    ),
    (
      'online-praezise-pathologie-01',
      'Pathologie',
      'Welcher histologische Befund ist fuer eine rasch progrediente Glomerulonephritis charakteristisch?',
      'Halbmondbildungen in Bowman-Kapseln',
      '["Halbmondbildungen in Bowman-Kapseln","Mesangiale Amyloidablagerungen","Ausschliesslich hyaline Arteriolosklerose","Papillennekrosen im Nierenbecken"]'::jsonb,
      'Die rasch progrediente Glomerulonephritis zeigt typischerweise Halbmondbildungen aus proliferierenden Zellen und Fibrin in Bowman-Kapseln.',
      'Which histologic finding is characteristic of rapidly progressive glomerulonephritis?',
      'Crescent formation in Bowman capsules',
      '["Crescent formation in Bowman capsules","Mesangial amyloid deposits","Exclusively hyaline arteriolosclerosis","Papillary necrosis in the renal pelvis"]'::jsonb,
      'Rapidly progressive glomerulonephritis classically shows crescents formed by proliferating cells and fibrin in Bowman capsules.'
    ),
    (
      'online-praezise-pathologie-02',
      'Pathologie',
      'Welche metaplastische Veraenderung kennzeichnet den Barrett-Oesophagus?',
      'Intestinale Metaplasie mit Becherzellen',
      '["Intestinale Metaplasie mit Becherzellen","Plattenepithelhyperplasie ohne Zellwandel","Verkalkung der Submukosa","Dysplasie des Muskelgewebes"]'::jsonb,
      'Beim Barrett-Oesophagus wird das normale Plattenepithel durch intestinal gepraegtes Zylinderepithel mit Becherzellen ersetzt.',
      'Which metaplastic change characterizes Barrett esophagus?',
      'Intestinal metaplasia with goblet cells',
      '["Intestinal metaplasia with goblet cells","Squamous hyperplasia without lineage change","Submucosal calcification","Dysplasia of muscle tissue"]'::jsonb,
      'In Barrett esophagus, normal squamous epithelium is replaced by intestinal-type columnar epithelium with goblet cells.'
    ),
    (
      'online-praezise-pathologie-03',
      'Pathologie',
      'Welcher Zellkernbefund ist fuer das papillaere Schilddruesenkarzinom klassisch?',
      'Orphan-Annie-eye-Kerne',
      '["Orphan-Annie-eye-Kerne","Auerstaebchen","Russell-Koerperchen","Negri-Koerperchen"]'::jsonb,
      'Das papillaere Schilddruesenkarzinom zeigt typische optisch aufgehellte Kerne, die als Orphan-Annie-eye-Kerne beschrieben werden.',
      'Which nuclear finding is classic for papillary thyroid carcinoma?',
      'Orphan Annie eye nuclei',
      '["Orphan Annie eye nuclei","Auer rods","Russell bodies","Negri bodies"]'::jsonb,
      'Papillary thyroid carcinoma characteristically shows optically clear nuclei known as Orphan Annie eye nuclei.'
    ),
    (
      'online-praezise-pathologie-04',
      'Pathologie',
      'Welches Emphysem-Muster passt am ehesten zu einem Alpha-1-Antitrypsin-Mangel?',
      'Panazinaeres Emphysem der Unterlappen',
      '["Panazinaeres Emphysem der Unterlappen","Zentrolobulaeres Emphysem der Oberlappen","Paraseptales Emphysem nur apikal","Bullae ausschliesslich im Mittellappen"]'::jsonb,
      'Beim Alpha-1-Antitrypsin-Mangel entsteht typischerweise ein panazinaeres Emphysem, besonders in den Unterlappen.',
      'Which emphysema pattern best fits alpha-1 antitrypsin deficiency?',
      'Panacinar emphysema of the lower lobes',
      '["Panacinar emphysema of the lower lobes","Centrilobular emphysema of the upper lobes","Paraseptal emphysema only at the apex","Bullae exclusively in the middle lobe"]'::jsonb,
      'Alpha-1 antitrypsin deficiency typically causes panacinar emphysema, especially in the lower lobes.'
    ),
    (
      'online-praezise-pharmakologie-01',
      'Pharmakologie',
      'Welcher Laborwert wird zur Therapiekontrolle unter Warfarin typischerweise verwendet?',
      'INR',
      '["INR","aPTT","Troponin","D-Dimer"]'::jsonb,
      'Warfarin beeinflusst die Vitamin-K-abhaengige Gerinnung und wird klinisch ueber die Prothrombinzeit bzw. den INR-Wert kontrolliert.',
      'Which laboratory value is typically used to monitor warfarin therapy?',
      'INR',
      '["INR","aPTT","Troponin","D-dimer"]'::jsonb,
      'Warfarin affects vitamin K-dependent clotting factor synthesis and is monitored clinically with the INR.'
    ),
    (
      'online-praezise-pharmakologie-02',
      'Pharmakologie',
      'Welches Antidot neutralisiert unfraktioniertes Heparin am direktesten?',
      'Protamin',
      '["Protamin","Vitamin K","Idarucizumab","Atropin"]'::jsonb,
      'Protamin bindet an Heparin und neutralisiert dessen antikoagulatorische Wirkung. Es ist das klassische Antidot fuer unfraktioniertes Heparin.',
      'Which antidote most directly neutralizes unfractionated heparin?',
      'Protamine',
      '["Protamine","Vitamin K","Idarucizumab","Atropine"]'::jsonb,
      'Protamine binds heparin and neutralizes its anticoagulant effect. It is the classic reversal agent for unfractionated heparin.'
    ),
    (
      'online-praezise-pharmakologie-03',
      'Pharmakologie',
      'Welchen Transporter hemmen Schleifendiuretika im dicken aufsteigenden Teil der Henle-Schleife?',
      'NKCC2',
      '["NKCC2","ENaC","Na+/K+-ATPase","SGLT2"]'::jsonb,
      'Schleifendiuretika blockieren den Na-K-2Cl-Kotransporter NKCC2 im dicken aufsteigenden Ast und steigern dadurch die Diurese.',
      'Which transporter is inhibited by loop diuretics in the thick ascending limb of the loop of Henle?',
      'NKCC2',
      '["NKCC2","ENaC","Na+/K+-ATPase","SGLT2"]'::jsonb,
      'Loop diuretics block the Na-K-2Cl cotransporter NKCC2 in the thick ascending limb and thereby increase diuresis.'
    ),
    (
      'online-praezise-pharmakologie-04',
      'Pharmakologie',
      'An welche ribosomale Zielstruktur binden Makrolide primaer?',
      '50S-Untereinheit',
      '["50S-Untereinheit","30S-Untereinheit","DNA-Gyrase","Peptidoglykan"]'::jsonb,
      'Makrolide binden an die 50S-Untereinheit bakterieller Ribosomen und hemmen dadurch die Proteinsynthese.',
      'Which ribosomal target structure do macrolides primarily bind?',
      '50S subunit',
      '["50S subunit","30S subunit","DNA gyrase","Peptidoglycan"]'::jsonb,
      'Macrolides bind the 50S bacterial ribosomal subunit and inhibit protein synthesis.'
    ),
    (
      'online-praezise-pharmakologie-05',
      'Pharmakologie',
      'Welche gefuerchtete Komplikation erklaert die Vorsicht mit Metformin bei schwerer Niereninsuffizienz?',
      'Laktatazidose',
      '["Laktatazidose","Agranuzytose","Rhabdomyolyse","Aplastische Anaemie"]'::jsonb,
      'Metformin kann sich bei schwer eingeschraenkter Nierenfunktion anreichern und das Risiko einer Laktatazidose erhoehen.',
      'Which feared complication explains the caution with metformin in severe renal impairment?',
      'Lactic acidosis',
      '["Lactic acidosis","Agranulocytosis","Rhabdomyolysis","Aplastic anemia"]'::jsonb,
      'Metformin can accumulate in severe renal impairment and increase the risk of lactic acidosis.'
    ),
    (
      'online-praezise-pharmakologie-06',
      'Pharmakologie',
      'Welche Rezeptorfamilie wird durch Atropin kompetitiv blockiert?',
      'Muskarinische Acetylcholinrezeptoren',
      '["Muskarinische Acetylcholinrezeptoren","Nikotinische Acetylcholinrezeptoren","Beta-2-Rezeptoren","Dopamin-D2-Rezeptoren"]'::jsonb,
      'Atropin wirkt als kompetitiver Antagonist an muskarinischen Acetylcholinrezeptoren und hemmt damit parasympathische Effekte.',
      'Which receptor family is competitively blocked by atropine?',
      'Muscarinic acetylcholine receptors',
      '["Muscarinic acetylcholine receptors","Nicotinic acetylcholine receptors","Beta-2 receptors","Dopamine D2 receptors"]'::jsonb,
      'Atropine acts as a competitive antagonist at muscarinic acetylcholine receptors and suppresses parasympathetic effects.'
    ),
    (
      'online-praezise-physiologie-01',
      'Physiologie',
      'Welche Groesse registriert die Macula densa fuer das tubuloglomerulaere Feedback besonders?',
      'NaCl-Konzentration im distalen Tubulus',
      '["NaCl-Konzentration im distalen Tubulus","Sauerstoffpartialdruck im Sammelrohr","Albuminkonzentration in Bowman-Kapsel","Kalziumspiegel im proximalen Tubulus"]'::jsonb,
      'Die Macula densa misst vor allem die Natriumchloridbeladung im distalen Tubulus. Darueber beeinflusst sie den Tonus der afferenten Arteriole.',
      'Which variable is especially sensed by the macula densa for tubuloglomerular feedback?',
      'NaCl concentration in the distal tubule',
      '["NaCl concentration in the distal tubule","Oxygen partial pressure in the collecting duct","Albumin concentration in Bowman space","Calcium level in the proximal tubule"]'::jsonb,
      'The macula densa mainly senses sodium chloride delivery in the distal tubule. This signal adjusts afferent arteriolar tone.'
    ),
    (
      'online-praezise-physiologie-02',
      'Physiologie',
      'Welche direkte Folge beschreibt den Frank-Starling-Mechanismus des Herzens am besten?',
      'Mehr enddiastolische Fuellung erhoeht das Schlagvolumen',
      '["Mehr enddiastolische Fuellung erhoeht das Schlagvolumen","Hoehere Herzfrequenz senkt das Schlagvolumen immer","Verminderte Nachlast reduziert die Kontraktilitaet direkt","Mehr Sympathikus senkt die Vorlast"]'::jsonb,
      'Eine groessere enddiastolische Dehnung fuehrt zu einer kraeftigeren Kontraktion. Deshalb steigt bei hoeherer Vorlast das Schlagvolumen.',
      'Which direct consequence best describes the Frank-Starling mechanism of the heart?',
      'Greater end-diastolic filling increases stroke volume',
      '["Greater end-diastolic filling increases stroke volume","Higher heart rate always lowers stroke volume","Reduced afterload directly lowers contractility","More sympathetic tone lowers preload"]'::jsonb,
      'Greater end-diastolic stretch leads to a stronger contraction. That is why higher preload increases stroke volume.'
    ),
    (
      'online-praezise-physiologie-03',
      'Physiologie',
      'Welche Veraenderung verschiebt die Sauerstoffbindungskurve des Haemoglobins im Sinne des Bohr-Effekts nach rechts?',
      'Anstieg von CO2 und H+-Konzentration',
      '["Anstieg von CO2 und H+-Konzentration","Abfall der Temperatur","Abnahme von 2,3-BPG","Alkalose"]'::jsonb,
      'Mehr CO2 und mehr Protonen senken die Sauerstoffaffinitaet des Haemoglobins und verschieben die Kurve nach rechts. Das erleichtert die O2-Abgabe im Gewebe.',
      'Which change shifts the hemoglobin oxygen dissociation curve to the right through the Bohr effect?',
      'Increase in CO2 and hydrogen ion concentration',
      '["Increase in CO2 and hydrogen ion concentration","Decrease in temperature","Decrease in 2,3-BPG","Alkalosis"]'::jsonb,
      'More CO2 and more protons reduce hemoglobin oxygen affinity and shift the curve to the right. This facilitates oxygen unloading in tissue.'
    ),
    (
      'online-praezise-physiologie-04',
      'Physiologie',
      'Welche Wirkung hat ADH ueber den V2-Rezeptor in den Hauptzellen des Sammelrohrs?',
      'Einbau von Aquaporin-2 in die apikale Membran',
      '["Einbau von Aquaporin-2 in die apikale Membran","Hemmung der Harnstoffresorption","Blockade von ENaC","Verminderte Wasserpermeabilitaet"]'::jsonb,
      'ADH aktiviert ueber den V2-Rezeptor cAMP und fuehrt zum Einbau von Aquaporin-2. Dadurch steigt die Wasserpermeabilitaet des Sammelrohrs.',
      'What effect does ADH exert through the V2 receptor in principal cells of the collecting duct?',
      'Insertion of aquaporin-2 into the apical membrane',
      '["Insertion of aquaporin-2 into the apical membrane","Inhibition of urea reabsorption","Blockade of ENaC","Reduced water permeability"]'::jsonb,
      'ADH activates cAMP through the V2 receptor and inserts aquaporin-2 into the apical membrane. This increases water permeability.'
    ),
    (
      'online-praezise-physiologie-05',
      'Physiologie',
      'Welche Wirkung hat Parathormon auf die renale Phosphatrueckresorption im proximalen Tubulus?',
      'Sie nimmt ab',
      '["Sie nimmt ab","Sie nimmt zu","Sie bleibt unveraendert","Sie wird nur nachts gesteigert"]'::jsonb,
      'Parathormon hemmt Natrium-Phosphat-Kotransporter im proximalen Tubulus. Dadurch sinkt die Phosphatrueckresorption und die Phosphatausscheidung steigt.',
      'What effect does parathyroid hormone have on renal phosphate reabsorption in the proximal tubule?',
      'It decreases',
      '["It decreases","It increases","It stays unchanged","It increases only at night"]'::jsonb,
      'Parathyroid hormone inhibits sodium-phosphate cotransporters in the proximal tubule. As a result, phosphate reabsorption falls.'
    ),
    (
      'online-praezise-physiologie-06',
      'Physiologie',
      'Welcher Transporter wird in Muskel- und Fettzellen durch Insulin vermehrt an die Zellmembran gebracht?',
      'GLUT4',
      '["GLUT4","GLUT1","SGLT1","ENaC"]'::jsonb,
      'Insulin foerdert in Muskel- und Fettzellen die Translokation von GLUT4 an die Zellmembran. Dadurch steigt die Glukoseaufnahme.',
      'Which transporter is translocated to the cell membrane in muscle and fat cells by insulin?',
      'GLUT4',
      '["GLUT4","GLUT1","SGLT1","ENaC"]'::jsonb,
      'Insulin promotes GLUT4 translocation to the cell membrane in muscle and fat cells. This increases glucose uptake.'
    ),
    (
      'online-praezise-radiologie-01',
      'Radiologie',
      'Worauf zielt die FAST-Sonographie im Schockraum primaer ab?',
      'Nachweis freier Fluessigkeit',
      '["Nachweis freier Fluessigkeit","Messung der Knochendichte","Bestimmung des Herzzeitvolumens per MRT","Sicherung einer Hirnstammblutung"]'::jsonb,
      'Die FAST-Untersuchung sucht schnell nach freier Fluessigkeit in Abdomen, Perikard und gegebenenfalls Thorax.',
      'What is the primary goal of FAST ultrasound in the trauma bay?',
      'Detection of free fluid',
      '["Detection of free fluid","Measurement of bone density","Assessment of cardiac output by MRI","Confirmation of brainstem hemorrhage"]'::jsonb,
      'FAST is designed to rapidly detect free fluid in the abdomen, pericardium, and sometimes thorax.'
    ),
    (
      'online-praezise-radiologie-02',
      'Radiologie',
      'Welche Form zeigt ein subdurales Haematom im CT typischerweise?',
      'Sichelfoermig',
      '["Sichelfoermig","Linsenfoermig","Ringfoermig","Sternfoermig"]'::jsonb,
      'Ein subdurales Haematom breitet sich entlang der Hirnoberflaeche aus und erscheint deshalb meist sichelfoermig.',
      'Which shape does a subdural hematoma typically have on CT?',
      'Crescent-shaped',
      '["Crescent-shaped","Lens-shaped","Ring-shaped","Star-shaped"]'::jsonb,
      'A subdural hematoma spreads along the brain surface and therefore usually appears crescent-shaped.'
    ),
    (
      'online-praezise-radiologie-03',
      'Radiologie',
      'Welche Bildgebung ist bei haemodynamisch stabilem Verdacht auf Lungenembolie typischerweise erste Wahl?',
      'CT-Pulmonalisangiographie',
      '["CT-Pulmonalisangiographie","Konventionelles Thoraxroentgen","MRT Thorax ohne Kontrastmittel","Skelettszintigrafie"]'::jsonb,
      'Bei haemodynamisch stabilem Verdacht auf Lungenembolie ist die CT-Pulmonalisangiographie die Standardbildgebung der ersten Wahl.',
      'Which imaging study is typically first choice for suspected pulmonary embolism in a hemodynamically stable patient?',
      'CT pulmonary angiography',
      '["CT pulmonary angiography","Plain chest radiography","Thoracic MRI without contrast","Bone scintigraphy"]'::jsonb,
      'In a hemodynamically stable patient with suspected pulmonary embolism, CT pulmonary angiography is the standard first-line imaging study.'
    ),
    (
      'online-praezise-radiologie-04',
      'Radiologie',
      'Welche Bildgebung wird in der Akutsituation primaer verwendet, um eine intrakranielle Blutung beim Schlaganfallverdacht auszuschliessen?',
      'Natives CT des Schaedels',
      '["Natives CT des Schaedels","Kontrastmittel-MRT des Schaedels","PET-CT des Gehirns","Ultraschall der Karotiden"]'::jsonb,
      'Das native CT des Schaedels steht in der Akutsituation schnell zur Verfuegung und kann eine intrakranielle Blutung rasch nachweisen oder ausschliessen.',
      'Which imaging study is primarily used in the acute setting to exclude intracranial hemorrhage in suspected stroke?',
      'Non-contrast head CT',
      '["Non-contrast head CT","Contrast-enhanced brain MRI","Brain PET-CT","Carotid ultrasound"]'::jsonb,
      'Non-contrast head CT is rapidly available in the acute setting and can quickly detect or exclude intracranial hemorrhage.'
    ),
    (
      'online-praezise-radiologie-05',
      'Radiologie',
      'Welches sonographische Artefakt ist hinter einem verkalkten Gallenstein typisch?',
      'Dorsaler Schallschatten',
      '["Dorsaler Schallschatten","Posteriores Enhancement","Reverberationsartefakt","Spiegelartefakt"]'::jsonb,
      'Verkalkte oder stark reflektierende Strukturen wie Gallensteine erzeugen typischerweise einen dorsalen Schallschatten.',
      'Which sonographic artifact is typical behind a calcified gallstone?',
      'Posterior acoustic shadowing',
      '["Posterior acoustic shadowing","Posterior acoustic enhancement","Reverberation artifact","Mirror artifact"]'::jsonb,
      'Calcified or strongly reflective structures such as gallstones typically create posterior acoustic shadowing.'
    ),
    (
      'online-praezise-radiologie-06',
      'Radiologie',
      'Welche Bildgebung ist bei Verdacht auf Hodentorsion typischerweise erste Wahl?',
      'Doppler-Sonographie',
      '["Doppler-Sonographie","Natives CT des Beckens","MRT Abdomen","Roentgen des Skrotums"]'::jsonb,
      'Bei Verdacht auf Hodentorsion ist die Doppler-Sonographie die typische Erstbildgebung, weil sie die Perfusion beurteilen kann.',
      'Which imaging study is typically first choice for suspected testicular torsion?',
      'Doppler ultrasound',
      '["Doppler ultrasound","Non-contrast pelvic CT","Abdominal MRI","Scrotal radiography"]'::jsonb,
      'For suspected testicular torsion, Doppler ultrasound is the usual first-line imaging study because it can assess perfusion.'
    ),
    (
      'online-praezise-radiologie-07',
      'Radiologie',
      'Welche Einheit beschreibt in der Radiologie die absorbierte Strahlendosis?',
      'Gray',
      '["Gray","Sievert","Becquerel","Candela"]'::jsonb,
      'Gray ist die Einheit der absorbierten Dosis. Sievert beschreibt dagegen die biologische Effektivdosis.',
      'Which unit describes absorbed radiation dose in radiology?',
      'Gray',
      '["Gray","Sievert","Becquerel","Candela"]'::jsonb,
      'Gray is the unit of absorbed dose. Sievert, by contrast, describes biologically weighted effective dose.'
    )
),
upsert_questions as (
  insert into public.questions (
    slug,
    category,
    question,
    correct_answer,
    options,
    explanation
  )
  select
    slug,
    category,
    question_de,
    correct_de,
    options_de,
    explanation_de
  from question_rows
  on conflict (slug) do update
    set category = excluded.category,
        question = excluded.question,
        correct_answer = excluded.correct_answer,
        options = excluded.options,
        explanation = excluded.explanation,
        updated_at = now()
  returning id, slug
)
insert into public.question_translations (
  question_id,
  language,
  question,
  options,
  correct_answer,
  explanation
)
select
  upsert_questions.id,
  'en',
  question_rows.question_en,
  question_rows.options_en,
  question_rows.correct_en,
  question_rows.explanation_en
from upsert_questions
join question_rows
  on question_rows.slug = upsert_questions.slug
on conflict (question_id, language) do update
  set question = excluded.question,
      options = excluded.options,
      correct_answer = excluded.correct_answer,
      explanation = excluded.explanation,
      updated_at = now();
