-- Expand the thinnest online category pools with another precise bilingual pack.

with question_rows (
  slug,
  category,
  question_de,
  correct_de,
  options_de,
  explanation_de,
  question_en,
  correct_en,
  options_en,
  explanation_en
) as (
  values
    (
      'online-ausbau-biochemie-01',
      'Biochemie',
      'Welcher Laborbefund ist bei einem Ornithin-Transcarbamylase-Mangel typischerweise erhoeht?',
      'Orotat im Urin',
      '["Orotat im Urin","Methylmalonat im Urin","Homogentisinsaeure im Urin","Bilirubin im Urin"]'::jsonb,
      'Beim Ornithin-Transcarbamylase-Mangel akkumuliert mitochondrial Carbamoylphosphat und wird vermehrt in die Pyrimidinsynthese umgeleitet. Dadurch steigt Orotat im Urin an.',
      'Which laboratory finding is typically elevated in ornithine transcarbamylase deficiency?',
      'Urinary orotate',
      '["Urinary orotate","Urinary methylmalonate","Urinary homogentisic acid","Urinary bilirubin"]'::jsonb,
      'In ornithine transcarbamylase deficiency, mitochondrial carbamoyl phosphate accumulates and is diverted into pyrimidine synthesis. This leads to elevated urinary orotate.'
    ),
    (
      'online-ausbau-biochemie-02',
      'Biochemie',
      'Welcher Enzymdefekt ist fuer die hereditare Fructoseintoleranz klassisch?',
      'Aldolase-B-Mangel',
      '["Aldolase-B-Mangel","Fructokinase-Mangel","Hexokinase-Mangel","Glukose-6-Phosphatase-Mangel"]'::jsonb,
      'Die hereditare Fructoseintoleranz wird klassisch durch einen Aldolase-B-Mangel verursacht. Dadurch akkumuliert Fructose-1-phosphat und es kommt zu schwerer Hypoglykaemie.',
      'Which enzyme defect is classic for hereditary fructose intolerance?',
      'Aldolase B deficiency',
      '["Aldolase B deficiency","Fructokinase deficiency","Hexokinase deficiency","Glucose-6-phosphatase deficiency"]'::jsonb,
      'Hereditary fructose intolerance is classically caused by aldolase B deficiency. Fructose-1-phosphate accumulates and can cause severe hypoglycemia.'
    ),
    (
      'online-ausbau-biochemie-03',
      'Biochemie',
      'Welcher Enzymdefekt liegt der MCAD-Erkrankung zugrunde?',
      'Medium-chain-Acyl-CoA-Dehydrogenase-Mangel',
      '["Medium-chain-Acyl-CoA-Dehydrogenase-Mangel","Carnitin-Acyltransferase-I-Mangel","Pyruvatcarboxylase-Mangel","Succinat-Dehydrogenase-Mangel"]'::jsonb,
      'Bei der MCAD-Erkrankung ist der Abbau mittelkettiger Fettsaeuren gestoert. Die Ursache ist ein Defekt der Medium-chain-Acyl-CoA-Dehydrogenase.',
      'Which enzyme defect underlies MCAD disease?',
      'Medium-chain acyl-CoA dehydrogenase deficiency',
      '["Medium-chain acyl-CoA dehydrogenase deficiency","Carnitine acyltransferase I deficiency","Pyruvate carboxylase deficiency","Succinate dehydrogenase deficiency"]'::jsonb,
      'In MCAD disease, oxidation of medium-chain fatty acids is impaired. The cause is deficiency of medium-chain acyl-CoA dehydrogenase.'
    ),
    (
      'online-ausbau-biochemie-04',
      'Biochemie',
      'Welcher Enzymdefekt ist fuer das Lesch-Nyhan-Syndrom klassisch?',
      'HGPRT-Mangel',
      '["HGPRT-Mangel","Adenosin-Desaminase-Mangel","Xanthinoxidase-Mangel","Aldolase-B-Mangel"]'::jsonb,
      'Das Lesch-Nyhan-Syndrom beruht auf einem Mangel der Hypoxanthin-Guanin-Phosphoribosyltransferase, kurz HGPRT. Dadurch ist der Purin-Salvage-Pathway gestoert.',
      'Which enzyme defect is classic for Lesch-Nyhan syndrome?',
      'HGPRT deficiency',
      '["HGPRT deficiency","Adenosine deaminase deficiency","Xanthine oxidase deficiency","Aldolase B deficiency"]'::jsonb,
      'Lesch-Nyhan syndrome is caused by deficiency of hypoxanthine-guanine phosphoribosyltransferase, or HGPRT. This disrupts the purine salvage pathway.'
    ),
    (
      'online-ausbau-biochemie-05',
      'Biochemie',
      'Welches Enzym ist das geschwindigkeitsbestimmende Enzym der Fettsaeureneubildung?',
      'Acetyl-CoA-Carboxylase',
      '["Acetyl-CoA-Carboxylase","Fettsaeurensynthase","HMG-CoA-Reduktase","Carnitin-Palmitoyltransferase I"]'::jsonb,
      'Die Acetyl-CoA-Carboxylase bildet Malonyl-CoA und ist das geschwindigkeitsbestimmende Enzym der Fettsaeureneubildung.',
      'Which enzyme is the rate-limiting enzyme of fatty acid synthesis?',
      'Acetyl-CoA carboxylase',
      '["Acetyl-CoA carboxylase","Fatty acid synthase","HMG-CoA reductase","Carnitine palmitoyltransferase I"]'::jsonb,
      'Acetyl-CoA carboxylase forms malonyl-CoA and is the rate-limiting enzyme of fatty acid synthesis.'
    ),
    (
      'online-ausbau-biochemie-06',
      'Biochemie',
      'Wo ist die Carbamoylphosphat-Synthetase II zellulaer lokalisiert?',
      'Im Zytosol',
      '["Im Zytosol","In den Mitochondrien","Im Zellkern","Im endoplasmatischen Retikulum"]'::jsonb,
      'Die Carbamoylphosphat-Synthetase II ist Teil der Pyrimidinsynthese und liegt im Zytosol. Die mitochondriale Form des Harnstoffzyklus ist dagegen CPS I.',
      'Where is carbamoyl phosphate synthetase II located within the cell?',
      'In the cytosol',
      '["In the cytosol","In the mitochondria","In the nucleus","In the endoplasmic reticulum"]'::jsonb,
      'Carbamoyl phosphate synthetase II is part of pyrimidine synthesis and is located in the cytosol. The mitochondrial urea cycle enzyme is CPS I.'
    ),
    (
      'online-ausbau-biochemie-07',
      'Biochemie',
      'Welches Shuttle uebertraegt Reduktionsaequivalente des zytosolischen NADH typischerweise in Herz und Leber in die Mitochondrien?',
      'Malat-Aspartat-Shuttle',
      '["Malat-Aspartat-Shuttle","Carnitin-Shuttle","Ornithin-Shuttle","Glukose-Alanin-Shuttle"]'::jsonb,
      'Das Malat-Aspartat-Shuttle uebertraegt die Elektronen des zytosolischen NADH in die Mitochondrien, besonders in Herz und Leber.',
      'Which shuttle typically transfers reducing equivalents of cytosolic NADH into mitochondria in heart and liver?',
      'Malate-aspartate shuttle',
      '["Malate-aspartate shuttle","Carnitine shuttle","Ornithine shuttle","Glucose-alanine shuttle"]'::jsonb,
      'The malate-aspartate shuttle transfers the electrons of cytosolic NADH into mitochondria, especially in heart and liver.'
    ),
    (
      'online-ausbau-biochemie-08',
      'Biochemie',
      'Welcher Komplex der Atmungskette reduziert Sauerstoff direkt zu Wasser?',
      'Komplex IV',
      '["Komplex IV","Komplex I","Komplex II","Komplex III"]'::jsonb,
      'Komplex IV, auch Cytochrom-c-Oxidase, uebertraegt Elektronen auf Sauerstoff und reduziert ihn zu Wasser.',
      'Which complex of the electron transport chain directly reduces oxygen to water?',
      'Complex IV',
      '["Complex IV","Complex I","Complex II","Complex III"]'::jsonb,
      'Complex IV, also called cytochrome c oxidase, transfers electrons to oxygen and reduces it to water.'
    ),
    (
      'online-ausbau-biochemie-09',
      'Biochemie',
      'Welches Enzym katalysiert in der Gluconeogenese die Umwandlung von Fructose-1,6-bisphosphat zu Fructose-6-phosphat?',
      'Fructose-1,6-Bisphosphatase',
      '["Fructose-1,6-Bisphosphatase","Phosphofructokinase-1","Hexokinase","Aldolase B"]'::jsonb,
      'Die Fructose-1,6-Bisphosphatase umgeht in der Gluconeogenese den irreversiblen Schritt der Phosphofructokinase-1.',
      'Which enzyme catalyzes the conversion of fructose-1,6-bisphosphate to fructose-6-phosphate in gluconeogenesis?',
      'Fructose-1,6-bisphosphatase',
      '["Fructose-1,6-bisphosphatase","Phosphofructokinase-1","Hexokinase","Aldolase B"]'::jsonb,
      'Fructose-1,6-bisphosphatase bypasses the irreversible phosphofructokinase-1 step during gluconeogenesis.'
    ),
    (
      'online-ausbau-biochemie-10',
      'Biochemie',
      'Welcher Cofaktor des Pyruvatdehydrogenase-Komplexes wird durch Arsenit funktionell gehemmt?',
      'Lipoamid',
      '["Lipoamid","Biotin","Cobalamin","Tetrahydrofolat"]'::jsonb,
      'Arsenit bindet an Lipoamid und hemmt dadurch mehrere alpha-Ketosaeure-Dehydrogenase-Komplexe, darunter den Pyruvatdehydrogenase-Komplex.',
      'Which cofactor of the pyruvate dehydrogenase complex is functionally inhibited by arsenite?',
      'Lipoamide',
      '["Lipoamide","Biotin","Cobalamin","Tetrahydrofolate"]'::jsonb,
      'Arsenite binds lipoamide and thereby inhibits several alpha-ketoacid dehydrogenase complexes, including the pyruvate dehydrogenase complex.'
    ),
    (
      'online-ausbau-biochemie-11',
      'Biochemie',
      'Welches Apolipoprotein vermittelt die hepatische Aufnahme von Chylomikron-Remnants?',
      'ApoE',
      '["ApoE","ApoC-II","ApoB-48","ApoA-I"]'::jsonb,
      'ApoE vermittelt die Bindung von Remnant-Partikeln an hepatische Rezeptoren und ist damit zentral fuer ihre Aufnahme in die Leber.',
      'Which apolipoprotein mediates hepatic uptake of chylomicron remnants?',
      'ApoE',
      '["ApoE","ApoC-II","ApoB-48","ApoA-I"]'::jsonb,
      'ApoE mediates binding of remnant particles to hepatic receptors and is therefore central to their uptake by the liver.'
    ),
    (
      'online-ausbau-biochemie-12',
      'Biochemie',
      'Welches Intermediat des Harnstoffzyklus wird aus den Mitochondrien ins Zytosol exportiert?',
      'Citrullin',
      '["Citrullin","Arginin","Ornithin","Fumarat"]'::jsonb,
      'Im Harnstoffzyklus entsteht Citrullin in den Mitochondrien und wird danach ins Zytosol exportiert, wo die weiteren Schritte ablaufen.',
      'Which urea cycle intermediate is exported from the mitochondria into the cytosol?',
      'Citrulline',
      '["Citrulline","Arginine","Ornithine","Fumarate"]'::jsonb,
      'In the urea cycle, citrulline is formed in the mitochondria and is then exported to the cytosol for the remaining steps.'
    ),
    (
      'online-ausbau-genetik-01',
      'Genetik',
      'Mutationen welches Gens sind klassisch mit MEN 2 assoziiert?',
      'RET',
      '["RET","APC","RB1","MEN1"]'::jsonb,
      'MEN 2 wird klassisch durch aktivierende Mutationen im RET-Protoonkogen verursacht.',
      'Mutations in which gene are classically associated with MEN 2?',
      'RET',
      '["RET","APC","RB1","MEN1"]'::jsonb,
      'MEN 2 is classically caused by activating mutations in the RET proto-oncogene.'
    ),
    (
      'online-ausbau-genetik-02',
      'Genetik',
      'Welches Gen ist beim familiaeren adenomatoesen Polyposis-Syndrom typischerweise mutiert?',
      'APC',
      '["APC","RET","VHL","NF2"]'::jsonb,
      'Die familiaere adenomatoese Polyposis ist klassisch mit Mutationen im APC-Tumorsuppressorgen assoziiert.',
      'Which gene is typically mutated in familial adenomatous polyposis?',
      'APC',
      '["APC","RET","VHL","NF2"]'::jsonb,
      'Familial adenomatous polyposis is classically associated with mutations in the APC tumor suppressor gene.'
    ),
    (
      'online-ausbau-genetik-03',
      'Genetik',
      'Welches Tumorsuppressorgen ist bei hereditaerem Retinoblastom typischerweise betroffen?',
      'RB1',
      '["RB1","TP53","WT1","BRCA1"]'::jsonb,
      'Das hereditaere Retinoblastom beruht klassisch auf Mutationen im RB1-Gen und folgt dem Two-hit-Modell.',
      'Which tumor suppressor gene is typically affected in hereditary retinoblastoma?',
      'RB1',
      '["RB1","TP53","WT1","BRCA1"]'::jsonb,
      'Hereditary retinoblastoma is classically caused by RB1 mutations and follows the two-hit model.'
    ),
    (
      'online-ausbau-genetik-04',
      'Genetik',
      'Welches Gen ist beim von-Hippel-Lindau-Syndrom typischerweise mutiert?',
      'VHL',
      '["VHL","RB1","RET","DMD"]'::jsonb,
      'Das von-Hippel-Lindau-Syndrom ist klassisch mit Keimbahnmutationen im VHL-Tumorsuppressorgen assoziiert.',
      'Which gene is typically mutated in von Hippel-Lindau syndrome?',
      'VHL',
      '["VHL","RB1","RET","DMD"]'::jsonb,
      'Von Hippel-Lindau syndrome is classically associated with germline mutations in the VHL tumor suppressor gene.'
    ),
    (
      'online-ausbau-genetik-05',
      'Genetik',
      'Welche Mutation ist fuer die Achondroplasie klassisch?',
      'Aktivierende FGFR3-Mutation',
      '["Aktivierende FGFR3-Mutation","Inaktivierende APC-Mutation","DMD-Deletion","VHL-Frameshift"]'::jsonb,
      'Die Achondroplasie entsteht klassisch durch eine aktivierende Mutation im FGFR3-Gen.',
      'Which mutation is classic for achondroplasia?',
      'Activating FGFR3 mutation',
      '["Activating FGFR3 mutation","Inactivating APC mutation","DMD deletion","VHL frameshift"]'::jsonb,
      'Achondroplasia is classically caused by an activating mutation in the FGFR3 gene.'
    ),
    (
      'online-ausbau-genetik-06',
      'Genetik',
      'Welches Gen ist bei Morbus Wilson klassisch mutiert?',
      'ATP7B',
      '["ATP7B","CFTR","MEN1","RET"]'::jsonb,
      'Morbus Wilson wird klassisch durch Mutationen im ATP7B-Gen verursacht, das fuer einen Kupfertransporter kodiert.',
      'Which gene is classically mutated in Wilson disease?',
      'ATP7B',
      '["ATP7B","CFTR","MEN1","RET"]'::jsonb,
      'Wilson disease is classically caused by mutations in the ATP7B gene, which encodes a copper transporter.'
    ),
    (
      'online-ausbau-genetik-07',
      'Genetik',
      'Mutationen welches Gens verursachen typischerweise die Haemophilie A?',
      'F8',
      '["F8","F9","HBB","NF1"]'::jsonb,
      'Die Haemophilie A beruht auf Mutationen im F8-Gen mit daraus resultierendem Faktor-VIII-Mangel.',
      'Mutations in which gene typically cause hemophilia A?',
      'F8',
      '["F8","F9","HBB","NF1"]'::jsonb,
      'Hemophilia A is caused by mutations in the F8 gene, resulting in factor VIII deficiency.'
    ),
    (
      'online-ausbau-genetik-08',
      'Genetik',
      'Ein Defekt welcher Struktur ist fuer die Osteogenesis imperfecta klassisch?',
      'Typ-I-Kollagen',
      '["Typ-I-Kollagen","Elastin","Dystrophin","Fibrillin-2"]'::jsonb,
      'Die Osteogenesis imperfecta beruht klassisch auf Stoerungen des Typ-I-Kollagens, meist durch COL1A1- oder COL1A2-Mutationen.',
      'A defect in which structure is classic for osteogenesis imperfecta?',
      'Type I collagen',
      '["Type I collagen","Elastin","Dystrophin","Fibrillin-2"]'::jsonb,
      'Osteogenesis imperfecta is classically caused by defects in type I collagen, usually due to COL1A1 or COL1A2 mutations.'
    ),
    (
      'online-ausbau-genetik-09',
      'Genetik',
      'Welches Gen ist bei der Neurofibromatose Typ 2 typischerweise mutiert?',
      'NF2',
      '["NF2","NF1","VHL","WT1"]'::jsonb,
      'Die Neurofibromatose Typ 2 ist klassisch mit Mutationen im NF2-Gen assoziiert.',
      'Which gene is typically mutated in neurofibromatosis type 2?',
      'NF2',
      '["NF2","NF1","VHL","WT1"]'::jsonb,
      'Neurofibromatosis type 2 is classically associated with mutations in the NF2 gene.'
    ),
    (
      'online-ausbau-genetik-10',
      'Genetik',
      'Welche numerische Chromosomenaberration ist fuer das Edwards-Syndrom klassisch?',
      'Trisomie 18',
      '["Trisomie 18","Trisomie 13","Monosomie X","Trisomie 21"]'::jsonb,
      'Das Edwards-Syndrom entspricht klassisch einer Trisomie 18.',
      'Which numerical chromosomal abnormality is classic for Edwards syndrome?',
      'Trisomy 18',
      '["Trisomy 18","Trisomy 13","Monosomy X","Trisomy 21"]'::jsonb,
      'Edwards syndrome classically corresponds to trisomy 18.'
    ),
    (
      'online-ausbau-genetik-11',
      'Genetik',
      'Welche numerische Chromosomenaberration ist fuer das Patau-Syndrom klassisch?',
      'Trisomie 13',
      '["Trisomie 13","Trisomie 18","Trisomie 21","47,XXY"]'::jsonb,
      'Das Patau-Syndrom entspricht klassisch einer Trisomie 13.',
      'Which numerical chromosomal abnormality is classic for Patau syndrome?',
      'Trisomy 13',
      '["Trisomy 13","Trisomy 18","Trisomy 21","47,XXY"]'::jsonb,
      'Patau syndrome classically corresponds to trisomy 13.'
    ),
    (
      'online-ausbau-genetik-12',
      'Genetik',
      'Welches Gen ist beim MEN-1-Syndrom typischerweise mutiert?',
      'MEN1',
      '["MEN1","RET","APC","FGFR3"]'::jsonb,
      'Das MEN-1-Syndrom ist klassisch mit Mutationen im MEN1-Gen assoziiert.',
      'Which gene is typically mutated in MEN 1 syndrome?',
      'MEN1',
      '["MEN1","RET","APC","FGFR3"]'::jsonb,
      'MEN 1 syndrome is classically associated with mutations in the MEN1 gene.'
    )
    ,
    (
      'online-ausbau-radiologie-01',
      'Radiologie',
      'Welche Bildgebung dient standardmaessig zur Messung der Knochendichte bei Osteoporose?',
      'DEXA',
      '["DEXA","CT-Angiographie","MRCP","PET-CT"]'::jsonb,
      'Die Dual-Energy-X-ray-Absorptiometry, kurz DEXA, ist der Standard zur Messung der Knochendichte bei Osteoporose.',
      'Which imaging study is standard for measuring bone density in osteoporosis?',
      'DEXA',
      '["DEXA","CT angiography","MRCP","PET-CT"]'::jsonb,
      'Dual-energy X-ray absorptiometry, or DEXA, is the standard study for measuring bone density in osteoporosis.'
    ),
    (
      'online-ausbau-radiologie-02',
      'Radiologie',
      'Welche Bildgebung ist bei klinischem Verdacht auf eine tiefe Beinvenenthrombose typischerweise erste Wahl?',
      'Kompressionssonographie',
      '["Kompressionssonographie","Natives CT des Beins","MRT des Unterschenkels","DEXA"]'::jsonb,
      'Bei Verdacht auf eine tiefe Venenthrombose ist die Kompressionssonographie die Standard-Erstuntersuchung.',
      'Which imaging study is typically first-line for suspected deep vein thrombosis of the leg?',
      'Compression ultrasonography',
      '["Compression ultrasonography","Non-contrast CT of the leg","MRI of the lower leg","DEXA"]'::jsonb,
      'For suspected deep vein thrombosis, compression ultrasonography is the standard first-line examination.'
    ),
    (
      'online-ausbau-radiologie-03',
      'Radiologie',
      'Welche Untersuchung wird bei Verdacht auf akute Cholezystitis typischerweise ergaenzend eingesetzt, wenn die Sonographie nicht eindeutig ist?',
      'HIDA-Szintigraphie',
      '["HIDA-Szintigraphie","Mammographie","DEXA","PET-CT"]'::jsonb,
      'Die HIDA-Szintigraphie kann bei unklarer Sonographie eine akute Cholezystitis funktionell absichern.',
      'Which study is typically used as an additional test when acute cholecystitis is suspected but ultrasound is equivocal?',
      'HIDA scan',
      '["HIDA scan","Mammography","DEXA","PET-CT"]'::jsonb,
      'A HIDA scan can functionally confirm acute cholecystitis when ultrasound findings are equivocal.'
    ),
    (
      'online-ausbau-radiologie-04',
      'Radiologie',
      'Welche nuklearmedizinische Untersuchung ist bei Verdacht auf Lungenembolie eine typische Alternative, wenn eine CT-Pulmonalisangiographie kontraindiziert ist?',
      'Ventilations-Perfusions-Szintigraphie',
      '["Ventilations-Perfusions-Szintigraphie","MRCP","DEXA","HIDA-Szintigraphie"]'::jsonb,
      'Wenn eine CT-Pulmonalisangiographie nicht moeglich ist, wird bei passender Fragestellung haeufig eine Ventilations-Perfusions-Szintigraphie eingesetzt.',
      'Which nuclear medicine study is a typical alternative in suspected pulmonary embolism when CT pulmonary angiography is contraindicated?',
      'Ventilation-perfusion scan',
      '["Ventilation-perfusion scan","MRCP","DEXA","HIDA scan"]'::jsonb,
      'When CT pulmonary angiography cannot be performed, a ventilation-perfusion scan is a common alternative in the right clinical setting.'
    ),
    (
      'online-ausbau-radiologie-05',
      'Radiologie',
      'Welche MRT-Sequenz unterdrueckt Fett besonders effektiv?',
      'STIR',
      '["STIR","FLAIR","DWI","TOF"]'::jsonb,
      'STIR ist eine fettunterdrueckende MRT-Sequenz und wird haeufig in der muskuloskelettalen Bildgebung verwendet.',
      'Which MRI sequence suppresses fat particularly effectively?',
      'STIR',
      '["STIR","FLAIR","DWI","TOF"]'::jsonb,
      'STIR is a fat-suppressed MRI sequence and is commonly used in musculoskeletal imaging.'
    ),
    (
      'online-ausbau-radiologie-06',
      'Radiologie',
      'Welche MRT-Technik zeigt eine Blut-Hirn-Schrankenstoerung nach Kontrastmittelgabe typischerweise am besten?',
      'T1-gewichtete MRT nach Gadolinium',
      '["T1-gewichtete MRT nach Gadolinium","DWI ohne Kontrast","STIR","FLAIR ohne Kontrast"]'::jsonb,
      'Eine Blut-Hirn-Schrankenstoerung zeigt sich typischerweise als Kontrastmittelaufnahme in einer T1-gewichteten MRT nach Gadolinium.',
      'Which MRI technique best demonstrates blood-brain barrier disruption after contrast administration?',
      'T1-weighted MRI after gadolinium',
      '["T1-weighted MRI after gadolinium","DWI without contrast","STIR","FLAIR without contrast"]'::jsonb,
      'Blood-brain barrier disruption typically appears as contrast enhancement on T1-weighted MRI after gadolinium.'
    ),
    (
      'online-ausbau-radiologie-07',
      'Radiologie',
      'Welches typische sonographische Zeichen spricht bei Kindern fuer eine Invagination?',
      'Target-Zeichen',
      '["Target-Zeichen","Deep-sulcus-Zeichen","Bird-beak-Zeichen","Rigler-Zeichen"]'::jsonb,
      'Bei der Invagination zeigt die Sonographie typischerweise ein konzentrisches Target-Zeichen.',
      'Which typical ultrasound sign supports the diagnosis of intussusception in children?',
      'Target sign',
      '["Target sign","Deep sulcus sign","Bird-beak sign","Rigler sign"]'::jsonb,
      'In intussusception, ultrasound typically shows a concentric target sign.'
    ),
    (
      'online-ausbau-radiologie-08',
      'Radiologie',
      'Welche Bildgebung ist bei Verdacht auf hypertrophe Pylorusstenose im Saeuglingsalter typischerweise erste Wahl?',
      'Sonographie',
      '["Sonographie","DEXA","MRT des Oberbauchs","PET-CT"]'::jsonb,
      'Bei der hypertrophen Pylorusstenose im Saeuglingsalter ist die Sonographie die typische Erstuntersuchung.',
      'Which imaging study is typically first-line for suspected infantile hypertrophic pyloric stenosis?',
      'Ultrasound',
      '["Ultrasound","DEXA","Upper abdominal MRI","PET-CT"]'::jsonb,
      'For suspected infantile hypertrophic pyloric stenosis, ultrasound is typically the first-line study.'
    ),
    (
      'online-ausbau-radiologie-09',
      'Radiologie',
      'Welches Kontrastmittelzeichen im Oesophagusbreischluck ist fuer Achalasie klassisch?',
      'Bird-beak-Zeichen',
      '["Bird-beak-Zeichen","Target-Zeichen","Deep-sulcus-Zeichen","String-sign des Pankreas"]'::jsonb,
      'Bei der Achalasie zeigt der Breischluck klassisch ein zugespitztes Bird-beak-Zeichen am distalen Oesophagus.',
      'Which contrast swallow sign is classic for achalasia?',
      'Bird-beak sign',
      '["Bird-beak sign","Target sign","Deep sulcus sign","Pancreatic string sign"]'::jsonb,
      'In achalasia, contrast swallow classically shows a tapered bird-beak sign at the distal esophagus.'
    ),
    (
      'online-ausbau-radiologie-10',
      'Radiologie',
      'Welches Roentgenzeichen im liegenden Thoraxbild spricht klassisch fuer einen Pneumothorax?',
      'Deep-sulcus-Zeichen',
      '["Deep-sulcus-Zeichen","Target-Zeichen","Apple-core-Zeichen","Bird-beak-Zeichen"]'::jsonb,
      'Im liegenden Thoraxroentgen kann ein Pneumothorax durch ein abnorm vertieftes costophrenisches Rezessusbild als Deep-sulcus-Zeichen auffallen.',
      'Which radiographic sign on a supine chest film classically suggests pneumothorax?',
      'Deep sulcus sign',
      '["Deep sulcus sign","Target sign","Apple-core sign","Bird-beak sign"]'::jsonb,
      'On a supine chest radiograph, pneumothorax can present as an abnormally deep costophrenic sulcus, known as the deep sulcus sign.'
    ),
    (
      'online-ausbau-radiologie-11',
      'Radiologie',
      'Welcher Befund im stehenden Abdomenroentgen spricht typischerweise fuer einen mechanischen Ileus?',
      'Mehrere Luft-Fluessigkeits-Spiegel',
      '["Mehrere Luft-Fluessigkeits-Spiegel","Beidseitige Pleuraerguesse","Diffuse Hilusvergroesserung","Subakute Verkalkung der Aorta"]'::jsonb,
      'Mehrere Luft-Fluessigkeits-Spiegel in dilatierten Darmschlingen sprechen im stehenden Abdomenroentgen fuer einen mechanischen Ileus.',
      'Which finding on an upright abdominal radiograph typically suggests mechanical bowel obstruction?',
      'Multiple air-fluid levels',
      '["Multiple air-fluid levels","Bilateral pleural effusions","Diffuse hilar enlargement","Subacute aortic calcification"]'::jsonb,
      'Multiple air-fluid levels in dilated bowel loops on an upright abdominal radiograph suggest mechanical bowel obstruction.'
    ),
    (
      'online-ausbau-radiologie-12',
      'Radiologie',
      'Welche angiographische Technik nutzt digitale Subtraktion zur Gefaessdarstellung?',
      'DSA',
      '["DSA","DEXA","DWI","FLAIR"]'::jsonb,
      'Die digitale Subtraktionsangiographie, kurz DSA, entfernt ueberlagernde Strukturen rechnerisch und stellt Gefaesse gezielt dar.',
      'Which angiographic technique uses digital subtraction to visualize vessels?',
      'DSA',
      '["DSA","DEXA","DWI","FLAIR"]'::jsonb,
      'Digital subtraction angiography, or DSA, computationally removes overlying structures and specifically visualizes vessels.'
    ),
    (
      'online-ausbau-chirurgie-01',
      'Chirurgie',
      'Welche Anastomose definiert eine Billroth-I-Rekonstruktion?',
      'Gastroduodenostomie',
      '["Gastroduodenostomie","Gastrojejunostomie","Ileoanale Anastomose","Choledochojejunostomie"]'::jsonb,
      'Die Billroth-I-Rekonstruktion verbindet den Magenrest direkt mit dem Duodenum und ist daher eine Gastroduodenostomie.',
      'Which anastomosis defines a Billroth I reconstruction?',
      'Gastroduodenostomy',
      '["Gastroduodenostomy","Gastrojejunostomy","Ileoanal anastomosis","Choledochojejunostomy"]'::jsonb,
      'Billroth I reconstruction connects the gastric remnant directly to the duodenum and is therefore a gastroduodenostomy.'
    ),
    (
      'online-ausbau-chirurgie-02',
      'Chirurgie',
      'Welche Anastomose definiert eine Billroth-II-Rekonstruktion?',
      'Gastrojejunostomie',
      '["Gastrojejunostomie","Gastroduodenostomie","Kolokolische Anastomose","Pankreatikogastrostomie"]'::jsonb,
      'Die Billroth-II-Rekonstruktion verbindet den Magen mit dem Jejunum und ist damit eine Gastrojejunostomie.',
      'Which anastomosis defines a Billroth II reconstruction?',
      'Gastrojejunostomy',
      '["Gastrojejunostomy","Gastroduodenostomy","Colocolic anastomosis","Pancreaticogastrostomy"]'::jsonb,
      'Billroth II reconstruction connects the stomach to the jejunum and is therefore a gastrojejunostomy.'
    ),
    (
      'online-ausbau-chirurgie-03',
      'Chirurgie',
      'Welche Operation ist die klassische chirurgische Therapie der Achalasie?',
      'Heller-Myotomie',
      '["Heller-Myotomie","Hartmann-Operation","Nissen-Fundoplikatio","Whipple-Operation"]'::jsonb,
      'Die Heller-Myotomie spaltet den unteren Oesophagussphinkter und ist die klassische chirurgische Therapie der Achalasie.',
      'Which operation is the classic surgical treatment for achalasia?',
      'Heller myotomy',
      '["Heller myotomy","Hartmann procedure","Nissen fundoplication","Whipple procedure"]'::jsonb,
      'Heller myotomy divides the lower esophageal sphincter and is the classic surgical treatment for achalasia.'
    ),
    (
      'online-ausbau-chirurgie-04',
      'Chirurgie',
      'Welche Operation ist die klassische chirurgische Antirefluxtherapie bei GERD?',
      'Nissen-Fundoplikatio',
      '["Nissen-Fundoplikatio","Heller-Myotomie","Billroth-II-Rekonstruktion","Hemikolektomie rechts"]'::jsonb,
      'Die Nissen-Fundoplikatio umschlaegt den distalen Oesophagus mit dem Fundus und ist die klassische chirurgische Antirefluxtherapie.',
      'Which operation is the classic surgical anti-reflux treatment for GERD?',
      'Nissen fundoplication',
      '["Nissen fundoplication","Heller myotomy","Billroth II reconstruction","Right hemicolectomy"]'::jsonb,
      'Nissen fundoplication wraps the fundus around the distal esophagus and is the classic surgical anti-reflux treatment.'
    ),
    (
      'online-ausbau-chirurgie-05',
      'Chirurgie',
      'Welche Operation ist die definitive chirurgische Therapie bei therapieresistenter Colitis ulcerosa?',
      'Totale Proktokolektomie',
      '["Totale Proktokolektomie","Sigmaresektion","Appendektomie","Splenektomie"]'::jsonb,
      'Die definitive chirurgische Therapie der Colitis ulcerosa besteht in der totalen Entfernung von Kolon und Rektum, also der totalen Proktokolektomie.',
      'Which operation is the definitive surgical treatment for therapy-refractory ulcerative colitis?',
      'Total proctocolectomy',
      '["Total proctocolectomy","Sigmoid resection","Appendectomy","Splenectomy"]'::jsonb,
      'Definitive surgical treatment of ulcerative colitis is removal of the colon and rectum, that is, total proctocolectomy.'
    ),
    (
      'online-ausbau-chirurgie-06',
      'Chirurgie',
      'Welche Arterie verlaeuft typischerweise im Calot-Dreieck?',
      'Arteria cystica',
      '["Arteria cystica","Arteria gastrica sinistra","Arteria lienalis","Arteria mesenterica inferior"]'::jsonb,
      'Die Arteria cystica verlaeuft typischerweise im Calot-Dreieck und wird bei der Cholezystektomie identifiziert und versorgt.',
      'Which artery typically runs within Calot triangle?',
      'Cystic artery',
      '["Cystic artery","Left gastric artery","Splenic artery","Inferior mesenteric artery"]'::jsonb,
      'The cystic artery typically runs within Calot triangle and is identified and controlled during cholecystectomy.'
    ),
    (
      'online-ausbau-chirurgie-07',
      'Chirurgie',
      'Welche bariatrische Operation laesst einen schlauchfoermigen Restmagen zurueck?',
      'Sleeve-Gastrektomie',
      '["Sleeve-Gastrektomie","Whipple-Operation","Hartmann-Operation","Fundoplikatio"]'::jsonb,
      'Bei der Sleeve-Gastrektomie wird die grosse Kurvatur reseziert, sodass ein schlauchfoermiger Restmagen verbleibt.',
      'Which bariatric operation leaves behind a tubular gastric remnant?',
      'Sleeve gastrectomy',
      '["Sleeve gastrectomy","Whipple procedure","Hartmann procedure","Fundoplication"]'::jsonb,
      'In sleeve gastrectomy, the greater curvature is resected so that a tubular gastric remnant remains.'
    ),
    (
      'online-ausbau-chirurgie-08',
      'Chirurgie',
      'Welche Operation dient klassisch der Entfernung eines akuten arteriellen Embolus mit Ballonkatheter?',
      'Fogarty-Embolektomie',
      '["Fogarty-Embolektomie","Nissen-Fundoplikatio","Cholezystektomie","Parathyreoidektomie"]'::jsonb,
      'Die Fogarty-Embolektomie nutzt einen Ballonkatheter zur Entfernung eines akuten arteriellen Embolus.',
      'Which operation classically removes an acute arterial embolus with a balloon catheter?',
      'Fogarty embolectomy',
      '["Fogarty embolectomy","Nissen fundoplication","Cholecystectomy","Parathyroidectomy"]'::jsonb,
      'Fogarty embolectomy uses a balloon catheter to remove an acute arterial embolus.'
    ),
    (
      'online-ausbau-chirurgie-09',
      'Chirurgie',
      'Welcher Nerv ist am ehesten verletzt, wenn nach einer Thyreoidektomie hohe Toene nicht mehr erreicht werden?',
      'Ramus externus des Nervus laryngeus superior',
      '["Ramus externus des Nervus laryngeus superior","Nervus phrenicus","Nervus hypoglossus","Nervus vagus thoracicus"]'::jsonb,
      'Der Ramus externus des Nervus laryngeus superior innerviert den Musculus cricothyroideus. Eine Laesion erschwert das Erreichen hoher Toene.',
      'Which nerve is most likely injured if high-pitched phonation is lost after thyroidectomy?',
      'External branch of the superior laryngeal nerve',
      '["External branch of the superior laryngeal nerve","Phrenic nerve","Hypoglossal nerve","Thoracic vagus nerve"]'::jsonb,
      'The external branch of the superior laryngeal nerve innervates the cricothyroid muscle. Injury makes high-pitched phonation difficult.'
    ),
    (
      'online-ausbau-chirurgie-10',
      'Chirurgie',
      'Welche Arterie wird bei der Splenektomie typischerweise frueh ligiert, um den Zufluss zur Milz zu reduzieren?',
      'Arteria lienalis',
      '["Arteria lienalis","Arteria cystica","Arteria gastrica dextra","Arteria appendicularis"]'::jsonb,
      'Bei der Splenektomie wird die Arteria lienalis typischerweise frueh kontrolliert, um den Blutfluss zur Milz zu reduzieren.',
      'Which artery is typically ligated early during splenectomy to reduce splenic inflow?',
      'Splenic artery',
      '["Splenic artery","Cystic artery","Right gastric artery","Appendiceal artery"]'::jsonb,
      'During splenectomy, the splenic artery is typically controlled early to reduce blood flow to the spleen.'
    ),
    (
      'online-ausbau-chirurgie-11',
      'Chirurgie',
      'Welche Rekonstruktion ist nach totaler Gastrektomie typischerweise Standard?',
      'Roux-en-Y-Oesophagojejunostomie',
      '["Roux-en-Y-Oesophagojejunostomie","Gastroduodenostomie","Ileozostomie","Choledochoduodenostomie"]'::jsonb,
      'Nach totaler Gastrektomie wird typischerweise eine Roux-en-Y-Oesophagojejunostomie angelegt, um die Passage wiederherzustellen.',
      'Which reconstruction is typically standard after total gastrectomy?',
      'Roux-en-Y esophagojejunostomy',
      '["Roux-en-Y esophagojejunostomy","Gastroduodenostomy","Ileostomy","Choledochoduodenostomy"]'::jsonb,
      'After total gastrectomy, Roux-en-Y esophagojejunostomy is typically constructed to restore alimentary continuity.'
    ),
    (
      'online-ausbau-chirurgie-12',
      'Chirurgie',
      'Welche Operation ist bei einem einzelnen Nebenschilddruesenadenom die typische definitive Therapie des primaeren Hyperparathyreoidismus?',
      'Parathyreoidektomie',
      '["Parathyreoidektomie","Splenektomie","Heller-Myotomie","Billroth-I-Rekonstruktion"]'::jsonb,
      'Bei primaerem Hyperparathyreoidismus durch ein einzelnes Adenom ist die operative Entfernung der betroffenen Nebenschilddruese die definitive Therapie.',
      'Which operation is the typical definitive treatment for primary hyperparathyroidism caused by a single parathyroid adenoma?',
      'Parathyroidectomy',
      '["Parathyroidectomy","Splenectomy","Heller myotomy","Billroth I reconstruction"]'::jsonb,
      'For primary hyperparathyroidism caused by a single adenoma, surgical removal of the affected parathyroid gland is the definitive treatment.'
    )
),
upsert_questions as (
  insert into public.questions (
    slug,
    category,
    question,
    correct_answer,
    options,
    explanation
  )
  select
    slug,
    category,
    question_de,
    correct_de,
    options_de,
    explanation_de
  from question_rows
  on conflict (slug) do update
    set category = excluded.category,
        question = excluded.question,
        correct_answer = excluded.correct_answer,
        options = excluded.options,
        explanation = excluded.explanation,
        updated_at = now()
  returning id, slug
)
insert into public.question_translations (
  question_id,
  language,
  question,
  options,
  correct_answer,
  explanation
)
select
  upsert_questions.id,
  'en',
  question_rows.question_en,
  question_rows.options_en,
  question_rows.correct_en,
  question_rows.explanation_en
from upsert_questions
join question_rows
  on question_rows.slug = upsert_questions.slug
on conflict (question_id, language) do update
  set question = excluded.question,
      options = excluded.options,
      correct_answer = excluded.correct_answer,
      explanation = excluded.explanation,
      updated_at = now();
