-- Expand the thinnest online categories with another precise bilingual pack.

with question_rows (
  slug,
  category,
  question_de,
  correct_de,
  options_de,
  explanation_de,
  question_en,
  correct_en,
  options_en,
  explanation_en
) as (
  values
    (
      'online-fokus-biochemie-01',
      'Biochemie',
      'Welches mitochondriale Enzym katalysiert den ersten Schritt des Harnstoffzyklus?',
      'Carbamoylphosphat-Synthetase I',
      '["Carbamoylphosphat-Synthetase I","Ornithin-Transcarbamylase","Argininosuccinat-Synthetase","Arginase"]'::jsonb,
      'Der Harnstoffzyklus beginnt in den Mitochondrien mit der Carbamoylphosphat-Synthetase I. Sie bildet aus Ammoniak und CO2 Carbamoylphosphat.',
      'Which mitochondrial enzyme catalyzes the first step of the urea cycle?',
      'Carbamoyl phosphate synthetase I',
      '["Carbamoyl phosphate synthetase I","Ornithine transcarbamylase","Argininosuccinate synthetase","Arginase"]'::jsonb,
      'The urea cycle begins in the mitochondria with carbamoyl phosphate synthetase I. It generates carbamoyl phosphate from ammonia and CO2.'
    ),
    (
      'online-fokus-biochemie-02',
      'Biochemie',
      'Welches Enzym wandelt Pyruvat in der Gluconeogenese zunaechst zu Oxalacetat um?',
      'Pyruvatcarboxylase',
      '["Pyruvatcarboxylase","Pyruvatkinase","Phosphoenolpyruvat-Carboxykinase","Laktatdehydrogenase"]'::jsonb,
      'Die Gluconeogenese umgeht die Pyruvatkinase-Reaktion zuerst ueber die Pyruvatcarboxylase. Dabei entsteht in den Mitochondrien Oxalacetat.',
      'Which enzyme first converts pyruvate to oxaloacetate during gluconeogenesis?',
      'Pyruvate carboxylase',
      '["Pyruvate carboxylase","Pyruvate kinase","Phosphoenolpyruvate carboxykinase","Lactate dehydrogenase"]'::jsonb,
      'Gluconeogenesis bypasses pyruvate kinase first through pyruvate carboxylase. This mitochondrial step produces oxaloacetate.'
    ),
    (
      'online-fokus-biochemie-03',
      'Biochemie',
      'Welches Enzym ist das geschwindigkeitsbestimmende Schrittmacherenzym der Haemsynthese?',
      'ALA-Synthase',
      '["ALA-Synthase","ALA-Dehydratase","Porphobilinogen-Desaminase","Ferrochelatase"]'::jsonb,
      'Die ALA-Synthase katalysiert den geschwindigkeitsbestimmenden ersten Schritt der Haemsynthese in den Mitochondrien. Sie kondensiert Glycin und Succinyl-CoA.',
      'Which enzyme is the rate-limiting enzyme of heme synthesis?',
      'ALA synthase',
      '["ALA synthase","ALA dehydratase","Porphobilinogen deaminase","Ferrochelatase"]'::jsonb,
      'ALA synthase catalyzes the rate-limiting first step of heme synthesis in the mitochondria. It condenses glycine and succinyl-CoA.'
    ),
    (
      'online-fokus-biochemie-04',
      'Biochemie',
      'Welcher Enzymdefekt ist typisch fuer Morbus von Gierke (Glykogenspeicherkrankheit Typ I)?',
      'Glukose-6-Phosphatase-Mangel',
      '["Glukose-6-Phosphatase-Mangel","Debranching-Enzym-Mangel","Lysosomale saure Maltase-Mangel","Muskelphosphorylase-Mangel"]'::jsonb,
      'Morbus von Gierke beruht auf einem Mangel der Glukose-6-Phosphatase. Dadurch kann Glukose nicht ausreichend aus der Leber ins Blut freigesetzt werden.',
      'Which enzyme defect is typical of von Gierke disease (glycogen storage disease type I)?',
      'Glucose-6-phosphatase deficiency',
      '["Glucose-6-phosphatase deficiency","Debranching enzyme deficiency","Lysosomal acid maltase deficiency","Muscle phosphorylase deficiency"]'::jsonb,
      'Von Gierke disease is caused by glucose-6-phosphatase deficiency. As a result, the liver cannot adequately release free glucose into the bloodstream.'
    ),
    (
      'online-fokus-biochemie-05',
      'Biochemie',
      'Welcher Enzymkomplex ist bei der Ahornsirupkrankheit (Maple syrup urine disease) defekt?',
      'Verzweigtkettiger alpha-Ketosaeure-Dehydrogenase-Komplex',
      '["Verzweigtkettiger alpha-Ketosaeure-Dehydrogenase-Komplex","Pyruvatdehydrogenase-Komplex","Alpha-Ketoglutarat-Dehydrogenase-Komplex","Succinat-Dehydrogenase"]'::jsonb,
      'Bei der Ahornsirupkrankheit ist der Abbau der verzweigtkettigen Aminosaeuren gestoert. Der typische Defekt liegt im verzweigtkettigen alpha-Ketosaeure-Dehydrogenase-Komplex.',
      'Which enzyme complex is defective in maple syrup urine disease?',
      'Branched-chain alpha-keto acid dehydrogenase complex',
      '["Branched-chain alpha-keto acid dehydrogenase complex","Pyruvate dehydrogenase complex","Alpha-ketoglutarate dehydrogenase complex","Succinate dehydrogenase"]'::jsonb,
      'In maple syrup urine disease, degradation of branched-chain amino acids is impaired. The classic defect is in the branched-chain alpha-keto acid dehydrogenase complex.'
    ),
    (
      'online-fokus-biochemie-06',
      'Biochemie',
      'Welcher Enzymdefekt ist fuer die Alkaptonurie klassisch?',
      'Homogentisat-1,2-Dioxygenase-Mangel',
      '["Homogentisat-1,2-Dioxygenase-Mangel","Phenylalaninhydroxylase-Mangel","Tyrosinase-Mangel","Fumarylacetoacetat-Hydrolase-Mangel"]'::jsonb,
      'Die Alkaptonurie entsteht durch einen Defekt der Homogentisat-1,2-Dioxygenase im Tyrosinabbau. Dadurch akkumuliert Homogentisinsaeure.',
      'Which enzyme defect is classic for alkaptonuria?',
      'Homogentisate 1,2-dioxygenase deficiency',
      '["Homogentisate 1,2-dioxygenase deficiency","Phenylalanine hydroxylase deficiency","Tyrosinase deficiency","Fumarylacetoacetate hydrolase deficiency"]'::jsonb,
      'Alkaptonuria is caused by a defect in homogentisate 1,2-dioxygenase in tyrosine degradation. This leads to homogentisic acid accumulation.'
    ),
    (
      'online-fokus-biochemie-07',
      'Biochemie',
      'Welches Citratzyklusenzym ist zugleich Komplex II der Atmungskette?',
      'Succinat-Dehydrogenase',
      '["Succinat-Dehydrogenase","Citrat-Synthase","Isocitrat-Dehydrogenase","Malat-Dehydrogenase"]'::jsonb,
      'Die Succinat-Dehydrogenase ist besonders, weil sie sowohl Teil des Citratzyklus als auch Komplex II der Atmungskette ist. Sie uebertraegt Elektronen auf FAD.',
      'Which citric acid cycle enzyme is also complex II of the electron transport chain?',
      'Succinate dehydrogenase',
      '["Succinate dehydrogenase","Citrate synthase","Isocitrate dehydrogenase","Malate dehydrogenase"]'::jsonb,
      'Succinate dehydrogenase is unique because it is both part of the citric acid cycle and complex II of the electron transport chain. It transfers electrons to FAD.'
    ),
    (
      'online-fokus-biochemie-08',
      'Biochemie',
      'Welches Lipoprotein transportiert endogene Triglyzeride von der Leber in die Peripherie?',
      'VLDL',
      '["VLDL","HDL","LDL","Chylomikron"]'::jsonb,
      'VLDL wird in der Leber gebildet und transportiert endogene Triglyzeride in periphere Gewebe. Chylomikronen transportieren dagegen vor allem exogene Fette aus dem Darm.',
      'Which lipoprotein transports endogenous triglycerides from the liver to peripheral tissues?',
      'VLDL',
      '["VLDL","HDL","LDL","Chylomicron"]'::jsonb,
      'VLDL is produced by the liver and carries endogenous triglycerides to peripheral tissues. Chylomicrons instead transport mainly exogenous fat from the intestine.'
    ),
    (
      'online-fokus-biochemie-09',
      'Biochemie',
      'Welche Aminosaeure ist unmittelbarer Vorlaeufer von S-Adenosylmethionin (SAM)?',
      'Methionin',
      '["Methionin","Serin","Glycin","Tyrosin"]'::jsonb,
      'S-Adenosylmethionin entsteht aus Methionin und ATP. Es ist der wichtigste universelle Methylgruppendonor des Stoffwechsels.',
      'Which amino acid is the direct precursor of S-adenosylmethionine (SAM)?',
      'Methionine',
      '["Methionine","Serine","Glycine","Tyrosine"]'::jsonb,
      'S-adenosylmethionine is formed from methionine and ATP. It is the major universal methyl group donor in metabolism.'
    ),
    (
      'online-fokus-biochemie-10',
      'Biochemie',
      'Welcher Metabolit aktiviert die Pyruvatcarboxylase allosterisch?',
      'Acetyl-CoA',
      '["Acetyl-CoA","Laktat","Fructose-1,6-Bisphosphat","Oxalacetat"]'::jsonb,
      'Die Pyruvatcarboxylase wird allosterisch durch Acetyl-CoA aktiviert. Das signalisiert, dass fuer den Citratzyklus vermehrt Oxalacetat benoetigt wird.',
      'Which metabolite allosterically activates pyruvate carboxylase?',
      'Acetyl-CoA',
      '["Acetyl-CoA","Lactate","Fructose-1,6-bisphosphate","Oxaloacetate"]'::jsonb,
      'Pyruvate carboxylase is allosterically activated by acetyl-CoA. This signals that additional oxaloacetate is needed for the citric acid cycle.'
    ),
    (
      'online-fokus-immunologie-01',
      'Immunologie',
      'Welches Immunglobulin dominiert typischerweise die Primaerantwort vor dem Klassenwechsel?',
      'IgM',
      '["IgM","IgG","IgA","IgE"]'::jsonb,
      'In der Primaerantwort wird zuerst vor allem IgM gebildet. Erst spaeter folgt nach Klassenwechsel vermehrt die Produktion anderer Immunglobulinklassen.',
      'Which immunoglobulin typically dominates the primary immune response before class switching?',
      'IgM',
      '["IgM","IgG","IgA","IgE"]'::jsonb,
      'IgM is produced first in the primary immune response. Only later does class switching generate larger amounts of other immunoglobulin classes.'
    ),
    (
      'online-fokus-immunologie-02',
      'Immunologie',
      'Welches Immunglobulin wird aktiv ueber die Plazenta auf den Fetus uebertragen?',
      'IgG',
      '["IgG","IgM","IgA","IgD"]'::jsonb,
      'IgG wird ueber den neonatalen Fc-Rezeptor aktiv durch die Plazenta transportiert. Deshalb vermittelt muetterliches IgG dem Neugeborenen einen passiven Schutz.',
      'Which immunoglobulin is actively transferred across the placenta to the fetus?',
      'IgG',
      '["IgG","IgM","IgA","IgD"]'::jsonb,
      'IgG is actively transported across the placenta by the neonatal Fc receptor. This is why maternal IgG provides passive protection to the newborn.'
    ),
    (
      'online-fokus-immunologie-03',
      'Immunologie',
      'Welches Zytokin foerdert den Klassenwechsel von B-Zellen zu IgE besonders stark?',
      'IL-4',
      '["IL-4","IL-2","IFN-gamma","TNF-alpha"]'::jsonb,
      'IL-4 ist ein Schluesselzytokin der Th2-Antwort und foerdert den Klassenwechsel zu IgE. Genau das verbindet IL-4 direkt mit atopischen Reaktionen.',
      'Which cytokine strongly promotes B-cell class switching to IgE?',
      'IL-4',
      '["IL-4","IL-2","IFN-gamma","TNF-alpha"]'::jsonb,
      'IL-4 is a key Th2 cytokine and strongly promotes class switching to IgE. This directly links IL-4 to atopic responses.'
    ),
    (
      'online-fokus-immunologie-04',
      'Immunologie',
      'Welcher Immundefekt praedisponiert klassisch zu rezidivierenden Infektionen mit Neisserien?',
      'Terminaler Komplementdefekt C5-C9',
      '["Terminaler Komplementdefekt C5-C9","IgA-Mangel","Kompletter B-Zell-Mangel","Mangel an C1-Esterase-Inhibitor"]'::jsonb,
      'Defekte der terminalen Komplementkomponenten C5 bis C9 stoeren die Bildung des Membranangriffskomplexes. Dadurch steigt besonders die Anfaelligkeit fuer Neisserieninfektionen.',
      'Which immune defect classically predisposes to recurrent Neisseria infections?',
      'Terminal complement deficiency C5-C9',
      '["Terminal complement deficiency C5-C9","IgA deficiency","Complete B-cell deficiency","C1 esterase inhibitor deficiency"]'::jsonb,
      'Defects of the terminal complement components C5 through C9 impair formation of the membrane attack complex. This particularly increases susceptibility to Neisseria infections.'
    ),
    (
      'online-fokus-immunologie-05',
      'Immunologie',
      'Welcher Transkriptionsfaktor ist charakteristisch fuer regulatorische T-Zellen?',
      'FOXP3',
      '["FOXP3","GATA3","T-bet","BCL6"]'::jsonb,
      'Regulatorische T-Zellen werden durch den Transkriptionsfaktor FOXP3 charakterisiert. Seine Funktion ist essenziell fuer die immunologische Toleranz.',
      'Which transcription factor is characteristic of regulatory T cells?',
      'FOXP3',
      '["FOXP3","GATA3","T-bet","BCL6"]'::jsonb,
      'Regulatory T cells are defined by the transcription factor FOXP3. Its function is essential for maintaining immune tolerance.'
    ),
    (
      'online-fokus-immunologie-06',
      'Immunologie',
      'Welcher Toll-like-Rezeptor erkennt bakterielles Lipopolysaccharid (LPS) am direktesten?',
      'TLR4',
      '["TLR4","TLR2","TLR3","TLR5"]'::jsonb,
      'TLR4 erkennt zusammen mit Korezeptoren bakterielles Lipopolysaccharid gramnegativer Erreger. Das macht TLR4 zu einem zentralen Sensor fuer LPS.',
      'Which toll-like receptor most directly recognizes bacterial lipopolysaccharide (LPS)?',
      'TLR4',
      '["TLR4","TLR2","TLR3","TLR5"]'::jsonb,
      'TLR4, together with co-receptors, recognizes lipopolysaccharide from Gram-negative bacteria. This makes TLR4 a central sensor for LPS.'
    ),
    (
      'online-fokus-immunologie-07',
      'Immunologie',
      'Welcher Typ der Hypersensitivitaet liegt der Myasthenia gravis zugrunde?',
      'Typ-II-Hypersensitivitaet',
      '["Typ-II-Hypersensitivitaet","Typ-I-Hypersensitivitaet","Typ-III-Hypersensitivitaet","Typ-IV-Hypersensitivitaet"]'::jsonb,
      'Bei Myasthenia gravis richten sich Antikoerper gegen den nikotinischen Acetylcholinrezeptor. Das ist eine antikoerpervermittelte Typ-II-Hypersensitivitaet.',
      'Which type of hypersensitivity underlies myasthenia gravis?',
      'Type II hypersensitivity',
      '["Type II hypersensitivity","Type I hypersensitivity","Type III hypersensitivity","Type IV hypersensitivity"]'::jsonb,
      'In myasthenia gravis, antibodies target the nicotinic acetylcholine receptor. This is an antibody-mediated type II hypersensitivity reaction.'
    ),
    (
      'online-fokus-immunologie-08',
      'Immunologie',
      'Welches Zytokin wird von Th17-Zellen charakteristisch produziert?',
      'IL-17',
      '["IL-17","IL-4","IL-5","IL-10"]'::jsonb,
      'Th17-Zellen sind vor allem durch die Produktion von IL-17 charakterisiert. Dieses Zytokin foerdert die Rekrutierung neutrophiler Granulozyten.',
      'Which cytokine is characteristically produced by Th17 cells?',
      'IL-17',
      '["IL-17","IL-4","IL-5","IL-10"]'::jsonb,
      'Th17 cells are primarily defined by production of IL-17. This cytokine promotes recruitment of neutrophils.'
    ),
    (
      'online-fokus-immunologie-09',
      'Immunologie',
      'Welche MHC-Klasse praesentiert endogene Peptide typischerweise an CD8-positive T-Zellen?',
      'MHC I',
      '["MHC I","MHC II","CD1","Fc-Rezeptor"]'::jsonb,
      'MHC I praesentiert endogene Peptide an CD8-positive zytotoxische T-Zellen. MHC II praesentiert dagegen vor allem exogene Antigene an CD4-positive T-Helferzellen.',
      'Which MHC class typically presents endogenous peptides to CD8-positive T cells?',
      'MHC I',
      '["MHC I","MHC II","CD1","Fc receptor"]'::jsonb,
      'MHC I presents endogenous peptides to CD8-positive cytotoxic T cells. By contrast, MHC II mainly presents exogenous antigens to CD4-positive helper T cells.'
    ),
    (
      'online-fokus-immunologie-10',
      'Immunologie',
      'Welche Zelle aktiviert naive T-Zellen am effizientesten?',
      'Dendritische Zelle',
      '["Dendritische Zelle","Neutrophiler Granulozyt","Erythrozyt","Mastzelle"]'::jsonb,
      'Dendritische Zellen sind die effizientesten professionellen antigenpraesentierenden Zellen fuer naive T-Zellen. Sie liefern Antigenpraesentation, Kostimulation und Zytokinsignale.',
      'Which cell activates naive T cells most efficiently?',
      'Dendritic cell',
      '["Dendritic cell","Neutrophil","Erythrocyte","Mast cell"]'::jsonb,
      'Dendritic cells are the most efficient professional antigen-presenting cells for naive T cells. They provide antigen presentation, co-stimulation, and cytokine signals.'
    ),
    (
      'online-fokus-genetik-01',
      'Genetik',
      'Welche chromosomale Deletion ist klassisch mit dem DiGeorge-Syndrom assoziiert?',
      'Deletion 22q11.2',
      '["Deletion 22q11.2","Deletion 5p","Deletion 7q11.23","Deletion 15q11-q13"]'::jsonb,
      'Das DiGeorge-Syndrom ist klassisch mit einer Deletion auf Chromosom 22q11.2 assoziiert. Diese Mikrodeletion stoert unter anderem die Entwicklung der Schlundbogentaschen.',
      'Which chromosomal deletion is classically associated with DiGeorge syndrome?',
      'Deletion 22q11.2',
      '["Deletion 22q11.2","Deletion 5p","Deletion 7q11.23","Deletion 15q11-q13"]'::jsonb,
      'DiGeorge syndrome is classically associated with a deletion on chromosome 22q11.2. This microdeletion disrupts, among other things, development of the pharyngeal pouches.'
    ),
    (
      'online-fokus-genetik-02',
      'Genetik',
      'Mutationen welches Gens verursachen typischerweise die Duchenne-Muskeldystrophie?',
      'DMD',
      '["DMD","FBN1","NF1","SMN1"]'::jsonb,
      'Die Duchenne-Muskeldystrophie wird durch Mutationen im DMD-Gen verursacht. Dieses Gen kodiert Dystrophin.',
      'Mutations in which gene typically cause Duchenne muscular dystrophy?',
      'DMD',
      '["DMD","FBN1","NF1","SMN1"]'::jsonb,
      'Duchenne muscular dystrophy is caused by mutations in the DMD gene. This gene encodes dystrophin.'
    ),
    (
      'online-fokus-genetik-03',
      'Genetik',
      'Wie nennt man das genetische Phaenomen, bei dem Repeat-Erkrankungen in nachfolgenden Generationen frueher und schwerer auftreten?',
      'Antizipation',
      '["Antizipation","Mosaizismus","Uniparentale Disomie","Penetranz"]'::jsonb,
      'Antizipation beschreibt das fruehere Auftreten und die zunehmende Schwere bestimmter Repeat-Erkrankungen in nachfolgenden Generationen. Ursache ist meist eine weitere Repeat-Expansion.',
      'What is the genetic phenomenon called in which repeat disorders appear earlier and more severely in successive generations?',
      'Anticipation',
      '["Anticipation","Mosaicism","Uniparental disomy","Penetrance"]'::jsonb,
      'Anticipation describes earlier onset and increasing severity of certain repeat disorders in successive generations. It is usually caused by further repeat expansion.'
    ),
    (
      'online-fokus-genetik-04',
      'Genetik',
      'Welches Syndrom entsteht klassisch durch den Verlust der vaeterlichen Expression im Bereich 15q11-q13?',
      'Prader-Willi-Syndrom',
      '["Prader-Willi-Syndrom","Angelman-Syndrom","Turner-Syndrom","Williams-Syndrom"]'::jsonb,
      'Beim Prader-Willi-Syndrom fehlt die vaeterliche Genexpression im Bereich 15q11-q13. Das kann durch Deletion, maternale uniparentale Disomie oder Imprinting-Defekte entstehen.',
      'Which syndrome classically results from loss of paternal expression in the 15q11-q13 region?',
      'Prader-Willi syndrome',
      '["Prader-Willi syndrome","Angelman syndrome","Turner syndrome","Williams syndrome"]'::jsonb,
      'Prader-Willi syndrome results from loss of paternal gene expression in the 15q11-q13 region. This can occur through deletion, maternal uniparental disomy, or imprinting defects.'
    ),
    (
      'online-fokus-genetik-05',
      'Genetik',
      'Welche Karyotyp-Konstellation ist typisch fuer das Turner-Syndrom?',
      '45,X',
      '["45,X","47,XXY","47,XXX","46,XY"]'::jsonb,
      'Das Turner-Syndrom ist klassisch mit einer Monosomie X verbunden. Der typische Karyotyp lautet 45,X.',
      'Which karyotype is typical of Turner syndrome?',
      '45,X',
      '["45,X","47,XXY","47,XXX","46,XY"]'::jsonb,
      'Turner syndrome is classically associated with monosomy X. The typical karyotype is 45,X.'
    ),
    (
      'online-fokus-genetik-06',
      'Genetik',
      'Welche DNA-Reparaturbahn ist beim Xeroderma pigmentosum defekt?',
      'Nukleotidexzisionsreparatur',
      '["Nukleotidexzisionsreparatur","Mismatch-Reparatur","Basenexzisionsreparatur","Homologe Rekombination"]'::jsonb,
      'Beim Xeroderma pigmentosum ist die Nukleotidexzisionsreparatur defekt. Dadurch koennen UV-bedingte Pyrimidindimere nicht ausreichend entfernt werden.',
      'Which DNA repair pathway is defective in xeroderma pigmentosum?',
      'Nucleotide excision repair',
      '["Nucleotide excision repair","Mismatch repair","Base excision repair","Homologous recombination"]'::jsonb,
      'In xeroderma pigmentosum, nucleotide excision repair is defective. As a result, UV-induced pyrimidine dimers cannot be adequately removed.'
    ),
    (
      'online-fokus-genetik-07',
      'Genetik',
      'Welche Mutationsart fuehrt definitionsgemaess zu einem vorzeitigen Stopcodon?',
      'Nonsense-Mutation',
      '["Nonsense-Mutation","Missense-Mutation","Stille Mutation","In-Frame-Deletion"]'::jsonb,
      'Eine Nonsense-Mutation verwandelt ein kodierendes Codon in ein Stopcodon. Dadurch endet die Translation vorzeitig.',
      'Which type of mutation by definition creates a premature stop codon?',
      'Nonsense mutation',
      '["Nonsense mutation","Missense mutation","Silent mutation","In-frame deletion"]'::jsonb,
      'A nonsense mutation converts a coding codon into a stop codon. Translation therefore terminates prematurely.'
    ),
    (
      'online-fokus-genetik-08',
      'Genetik',
      'Mutationen welches Gens sind typisch fuer die Neurofibromatose Typ 1?',
      'NF1',
      '["NF1","RET","RB1","APC"]'::jsonb,
      'Die Neurofibromatose Typ 1 wird klassisch durch Mutationen im NF1-Gen verursacht. Das Gen kodiert Neurofibromin.',
      'Mutations in which gene are typical of neurofibromatosis type 1?',
      'NF1',
      '["NF1","RET","RB1","APC"]'::jsonb,
      'Neurofibromatosis type 1 is classically caused by mutations in the NF1 gene. This gene encodes neurofibromin.'
    ),
    (
      'online-fokus-genetik-09',
      'Genetik',
      'Welches Vererbungsmuster hat die Mukoviszidose typischerweise?',
      'Autosomal-rezessiv',
      '["Autosomal-rezessiv","Autosomal-dominant","X-chromosomal-rezessiv","Mitochondrial"]'::jsonb,
      'Die Mukoviszidose wird durch pathogene Varianten in beiden Allelen des CFTR-Gens verursacht. Deshalb ist das Vererbungsmuster autosomal-rezessiv.',
      'Which inheritance pattern is typical of cystic fibrosis?',
      'Autosomal recessive',
      '["Autosomal recessive","Autosomal dominant","X-linked recessive","Mitochondrial"]'::jsonb,
      'Cystic fibrosis is caused by pathogenic variants in both alleles of the CFTR gene. Therefore its inheritance pattern is autosomal recessive.'
    ),
    (
      'online-fokus-genetik-10',
      'Genetik',
      'Welche Karyotyp-Konstellation ist typisch fuer das Klinefelter-Syndrom?',
      '47,XXY',
      '["47,XXY","45,X","47,XYY","46,XX"]'::jsonb,
      'Das Klinefelter-Syndrom ist klassisch mit dem Karyotyp 47,XXY verbunden. Es betrifft maennliche Patienten mit einem zusaetzlichen X-Chromosom.',
      'Which karyotype is typical of Klinefelter syndrome?',
      '47,XXY',
      '["47,XXY","45,X","47,XYY","46,XX"]'::jsonb,
      'Klinefelter syndrome is classically associated with the karyotype 47,XXY. It affects male patients who carry an extra X chromosome.'
    ),
    (
      'online-fokus-radiologie-01',
      'Radiologie',
      'Welche Form zeigt ein epidurales Haematom im CT typischerweise?',
      'Linsenfoermig',
      '["Linsenfoermig","Sichelfoermig","Sternfoermig","Retikulaer"]'::jsonb,
      'Ein epidurales Haematom ist im CT typischerweise linsenfoermig begrenzt. Es loest sich nicht frei ueber Schaedelnahte hinaus aus.',
      'Which shape does an epidural hematoma typically have on CT?',
      'Lens-shaped',
      '["Lens-shaped","Crescent-shaped","Star-shaped","Reticular"]'::jsonb,
      'An epidural hematoma is typically lens-shaped on CT. It does not spread freely across skull sutures.'
    ),
    (
      'online-fokus-radiologie-02',
      'Radiologie',
      'Welche MRT-Sequenz weist einen akuten ischaemischen Schlaganfall am fruehesten nach?',
      'Diffusionsgewichtete Bildgebung (DWI)',
      '["Diffusionsgewichtete Bildgebung (DWI)","T1-gewichtete Sequenz","MR-Angiographie ohne Diffusion","T2*-Sequenz ohne Diffusion"]'::jsonb,
      'Die diffusionsgewichtete MRT-Sequenz zeigt die fruehe Diffusionsstoerung ischaemischen Gewebes besonders empfindlich. Deshalb ist DWI die frueheste MRT-Sequenz fuer den akuten ischaemischen Infarkt.',
      'Which MRI sequence detects an acute ischemic stroke earliest?',
      'Diffusion-weighted imaging (DWI)',
      '["Diffusion-weighted imaging (DWI)","T1-weighted sequence","MR angiography without diffusion","T2* sequence without diffusion"]'::jsonb,
      'Diffusion-weighted MRI is particularly sensitive to the early diffusion abnormality of ischemic tissue. That is why DWI is the earliest MRI sequence for acute ischemic infarction.'
    ),
    (
      'online-fokus-radiologie-03',
      'Radiologie',
      'Welche Bildgebung ist bei Verdacht auf symptomatische Cholezystolithiasis typischerweise erste Wahl?',
      'Abdomensonographie',
      '["Abdomensonographie","MRT Abdomen","Natives CT Abdomen","ERCP als Erstdiagnostik"]'::jsonb,
      'Die Sonographie ist bei Verdacht auf Gallensteine die Standard-Erstbildgebung. Sie erkennt Steine, Schallschatten und Gallenblasenwandveraenderungen gut.',
      'Which imaging study is typically first choice for suspected symptomatic cholelithiasis?',
      'Abdominal ultrasound',
      '["Abdominal ultrasound","Abdominal MRI","Non-contrast abdominal CT","ERCP as first-line diagnostics"]'::jsonb,
      'Ultrasound is the standard first-line imaging study for suspected gallstones. It readily detects stones, acoustic shadowing, and gallbladder wall changes.'
    ),
    (
      'online-fokus-radiologie-04',
      'Radiologie',
      'Welche Bildgebung ist bei haemodynamisch stabilem Verdacht auf Aortendissektion typischerweise erste Wahl?',
      'CT-Angiographie der Aorta',
      '["CT-Angiographie der Aorta","Konventionelles Thoraxroentgen","Skelettszintigrafie","Mammographie"]'::jsonb,
      'Bei haemodynamisch stabilem Verdacht auf Aortendissektion ist die CT-Angiographie die Standard-Erstbildgebung. Sie zeigt das wahre und falsche Lumen schnell und zuverlaessig.',
      'Which imaging study is typically first choice for suspected aortic dissection in a hemodynamically stable patient?',
      'CT angiography of the aorta',
      '["CT angiography of the aorta","Plain chest radiography","Bone scintigraphy","Mammography"]'::jsonb,
      'In a hemodynamically stable patient with suspected aortic dissection, CT angiography is the standard first-line imaging study. It rapidly and reliably shows the true and false lumen.'
    ),
    (
      'online-fokus-radiologie-05',
      'Radiologie',
      'Welcher Roentgenbefund im aufrechten Thoraxbild spricht klassisch fuer ein Pneumoperitoneum?',
      'Freie Luft subdiaphragmal',
      '["Freie Luft subdiaphragmal","Pleuraerguss basal","Diffuse interstitielle Zeichnungsvermehrung","Mediastinalverbreiterung ohne Luftsichel"]'::jsonb,
      'Freie Luft unter dem Zwerchfell im aufrechten Thorax- oder Abdomenbild spricht klassisch fuer freie intraperitoneale Luft. Das passt typischerweise zu einer Hohlorganperforation.',
      'Which radiographic finding on an upright chest film classically suggests pneumoperitoneum?',
      'Free subdiaphragmatic air',
      '["Free subdiaphragmatic air","Basal pleural effusion","Diffuse interstitial prominence","Mediastinal widening without an air crescent"]'::jsonb,
      'Free air beneath the diaphragm on an upright chest or abdominal film classically suggests free intraperitoneal air. This typically matches a perforated hollow viscus.'
    ),
    (
      'online-fokus-radiologie-06',
      'Radiologie',
      'Welche nichtinvasive MRT-Technik stellt die Gallenwege gezielt dar?',
      'MRCP',
      '["MRCP","DWI","MRA der Karotiden","DXA"]'::jsonb,
      'Die Magnetresonanz-Cholangiopankreatikographie, kurz MRCP, stellt Gallen- und Pankreasgaenge nichtinvasiv dar. Sie wird vor allem zur Darstellung von Gangobstruktionen genutzt.',
      'Which noninvasive MRI technique is specifically used to visualize the biliary tree?',
      'MRCP',
      '["MRCP","DWI","Carotid MRA","DXA"]'::jsonb,
      'Magnetic resonance cholangiopancreatography, or MRCP, noninvasively visualizes the biliary and pancreatic ducts. It is mainly used to assess ductal obstruction.'
    ),
    (
      'online-fokus-radiologie-07',
      'Radiologie',
      'Welche Bildgebung ist bei Verdacht auf Urolithiasis beim nicht schwangeren Erwachsenen typischerweise erste Wahl?',
      'Natives CT von Abdomen und Becken',
      '["Natives CT von Abdomen und Becken","MRT Abdomen mit Kontrastmittel","Kolonkontrasteinlauf","Schilddruesensonographie"]'::jsonb,
      'Beim nicht schwangeren Erwachsenen ist das native CT von Abdomen und Becken die Standard-Erstbildgebung bei Verdacht auf Urolithiasis. Es erkennt Steine schnell und sensitiv.',
      'Which imaging study is typically first choice for suspected urolithiasis in a non-pregnant adult?',
      'Non-contrast CT of the abdomen and pelvis',
      '["Non-contrast CT of the abdomen and pelvis","Contrast-enhanced abdominal MRI","Contrast enema","Thyroid ultrasound"]'::jsonb,
      'In a non-pregnant adult, non-contrast CT of the abdomen and pelvis is the standard first-line imaging study for suspected urolithiasis. It detects stones rapidly and sensitively.'
    ),
    (
      'online-fokus-radiologie-08',
      'Radiologie',
      'Wie erscheint eine akute intrazerebrale Blutung im nativen CT typischerweise?',
      'Hyperdens',
      '["Hyperdens","Hypodens","Isodens zu Liquor","Signalarm nur in T1-MRT"]'::jsonb,
      'Akutes Blut erscheint im nativen CT typischerweise hyperdens. Diese hohe Dichte macht das native CT zur schnellen Notfallbildgebung bei Blutungsverdacht.',
      'How does an acute intracerebral hemorrhage typically appear on non-contrast CT?',
      'Hyperdense',
      '["Hyperdense","Hypodense","Isodense to cerebrospinal fluid","Low signal only on T1 MRI"]'::jsonb,
      'Acute blood typically appears hyperdense on non-contrast CT. This high density is why non-contrast CT is a rapid emergency study for suspected hemorrhage.'
    ),
    (
      'online-fokus-radiologie-09',
      'Radiologie',
      'Welche Kontrastmittelklasse wird in der MRT typischerweise verwendet?',
      'Gadoliniumhaltige Kontrastmittel',
      '["Gadoliniumhaltige Kontrastmittel","Bariumsulfat","Jodhaltige Roentgenkontrastmittel","Luft als positives Kontrastmittel"]'::jsonb,
      'In der MRT werden typischerweise gadoliniumhaltige Kontrastmittel verwendet. Jodhaltige Kontrastmittel werden dagegen vor allem in der CT eingesetzt.',
      'Which class of contrast agent is typically used in MRI?',
      'Gadolinium-based contrast agents',
      '["Gadolinium-based contrast agents","Barium sulfate","Iodinated X-ray contrast agents","Air as a positive contrast agent"]'::jsonb,
      'MRI typically uses gadolinium-based contrast agents. Iodinated contrast agents are mainly used in CT instead.'
    ),
    (
      'online-fokus-radiologie-10',
      'Radiologie',
      'Welche BI-RADS-Kategorie ist hochgradig malignitaetsverdaechtig?',
      'BI-RADS 5',
      '["BI-RADS 5","BI-RADS 1","BI-RADS 2","BI-RADS 3"]'::jsonb,
      'BI-RADS 5 bedeutet hochgradigen Verdacht auf Malignitaet und erfordert eine zeitnahe histologische Abklaerung. BI-RADS 3 ist dagegen nur wahrscheinlich gutartig.',
      'Which BI-RADS category is highly suggestive of malignancy?',
      'BI-RADS 5',
      '["BI-RADS 5","BI-RADS 1","BI-RADS 2","BI-RADS 3"]'::jsonb,
      'BI-RADS 5 indicates a high suspicion of malignancy and requires prompt tissue diagnosis. By contrast, BI-RADS 3 is only probably benign.'
    ),
    (
      'online-fokus-chirurgie-01',
      'Chirurgie',
      'Welche Hernienform verlaeuft medial der Vasa epigastrica inferiores durch das Hesselbach-Dreieck?',
      'Direkte Leistenhernie',
      '["Direkte Leistenhernie","Indirekte Leistenhernie","Schenkelhernie","Nabelhernie"]'::jsonb,
      'Die direkte Leistenhernie tritt medial der epigastrischen Gefaesse durch das Hesselbach-Dreieck vor. Genau diese Lage grenzt sie von der indirekten Leistenhernie ab.',
      'Which type of hernia passes medial to the inferior epigastric vessels through Hesselbach''s triangle?',
      'Direct inguinal hernia',
      '["Direct inguinal hernia","Indirect inguinal hernia","Femoral hernia","Umbilical hernia"]'::jsonb,
      'A direct inguinal hernia protrudes medial to the inferior epigastric vessels through Hesselbach''s triangle. This location distinguishes it from an indirect inguinal hernia.'
    ),
    (
      'online-fokus-chirurgie-02',
      'Chirurgie',
      'Welche Hernienform tritt lateral der Vasa epigastrica inferiores durch den inneren Leistenring ein?',
      'Indirekte Leistenhernie',
      '["Indirekte Leistenhernie","Direkte Leistenhernie","Narbenhernie","Hiatushernie"]'::jsonb,
      'Die indirekte Leistenhernie zieht lateral der epigastrischen Gefaesse durch den inneren Leistenring. Sie folgt damit dem Verlauf des Leistenkanals.',
      'Which type of hernia enters through the deep inguinal ring lateral to the inferior epigastric vessels?',
      'Indirect inguinal hernia',
      '["Indirect inguinal hernia","Direct inguinal hernia","Incisional hernia","Hiatal hernia"]'::jsonb,
      'An indirect inguinal hernia passes lateral to the inferior epigastric vessels through the deep inguinal ring. It therefore follows the course of the inguinal canal.'
    ),
    (
      'online-fokus-chirurgie-03',
      'Chirurgie',
      'Welche Klassifikation beschreibt den praeoperativen Allgemeinzustand eines Patienten im Sinne des Anaesthesierisikos?',
      'ASA-Klassifikation',
      '["ASA-Klassifikation","TNM-Klassifikation","Bismuth-Klassifikation","Child-Pugh-Klassifikation"]'::jsonb,
      'Die ASA-Klassifikation beschreibt den praeoperativen Allgemeinzustand und das anaesthesiologische Risiko. Sie ist ein Standard vor operativen Eingriffen.',
      'Which classification describes the preoperative physical status of a patient in terms of anesthesia risk?',
      'ASA classification',
      '["ASA classification","TNM classification","Bismuth classification","Child-Pugh classification"]'::jsonb,
      'The ASA classification describes preoperative physical status and anesthetic risk. It is standard before surgical procedures.'
    ),
    (
      'online-fokus-chirurgie-04',
      'Chirurgie',
      'Wann sollte eine chirurgische Antibiotikaprophylaxe typischerweise spaetestens begonnen werden?',
      'Innerhalb von 60 Minuten vor Hautschnitt',
      '["Innerhalb von 60 Minuten vor Hautschnitt","Erst nach Wundverschluss","Fruehestens 24 Stunden nach Hautschnitt","Nur nach positivem Wundabstrich"]'::jsonb,
      'Die chirurgische Antibiotikaprophylaxe soll vor dem Hautschnitt wirksam sein. Standard ist deshalb die Gabe innerhalb von 60 Minuten vor Inzision.',
      'When should surgical antibiotic prophylaxis typically be started at the latest?',
      'Within 60 minutes before skin incision',
      '["Within 60 minutes before skin incision","Only after wound closure","Not until 24 hours after incision","Only after a positive wound swab"]'::jsonb,
      'Surgical antibiotic prophylaxis should already be active at the time of skin incision. The standard is therefore administration within 60 minutes before incision.'
    ),
    (
      'online-fokus-chirurgie-05',
      'Chirurgie',
      'Welche Formel wird zur initialen Volumentherapie bei groesseren Verbrennungen klassisch verwendet?',
      'Parkland-Formel',
      '["Parkland-Formel","MELD-Formel","Ranson-Score","Wells-Score"]'::jsonb,
      'Die Parkland-Formel dient zur initialen Berechnung des Fluessigkeitsbedarfs bei Verbrennungen. Sie basiert auf Koerpergewicht, verbrannter Koerperoberflaeche und kristalloider Gabe.',
      'Which formula is classically used for initial fluid resuscitation in major burns?',
      'Parkland formula',
      '["Parkland formula","MELD formula","Ranson score","Wells score"]'::jsonb,
      'The Parkland formula is used for initial calculation of fluid requirements in burns. It is based on body weight, burned body surface area, and crystalloid replacement.'
    ),
    (
      'online-fokus-chirurgie-06',
      'Chirurgie',
      'Welche Operation wird bei perforiertem peptischem Ulkus des stabilen Patienten klassisch zur Defektdeckung verwendet?',
      'Graham-Patch',
      '["Graham-Patch","Whipple-Operation","Hartmann-Operation","Nissen-Fundoplikatio"]'::jsonb,
      'Beim perforierten peptischen Ulkus wird der Defekt klassisch mit einem Omentum-Patch gedeckt. Diese Technik ist als Graham-Patch bekannt.',
      'Which operation is classically used to cover the defect in a stable patient with a perforated peptic ulcer?',
      'Graham patch',
      '["Graham patch","Whipple procedure","Hartmann procedure","Nissen fundoplication"]'::jsonb,
      'In perforated peptic ulcer disease, the defect is classically covered with an omental patch. This technique is known as the Graham patch.'
    ),
    (
      'online-fokus-chirurgie-07',
      'Chirurgie',
      'Welche Strukturengruppe wird durch das Pringle-Manoever temporaer abgeklemmt?',
      'Portal-Trias im Ligamentum hepatoduodenale',
      '["Portal-Trias im Ligamentum hepatoduodenale","Vv. hepaticae an der V. cava inferior","A. mesenterica superior allein","Milzhilus mit A. und V. lienalis"]'::jsonb,
      'Beim Pringle-Manoever wird das Ligamentum hepatoduodenale komprimiert. Damit werden V. portae, A. hepatica propria und Ductus choledochus, also die Portal-Trias, temporaer abgeklemmt.',
      'Which group of structures is temporarily occluded by the Pringle maneuver?',
      'Portal triad within the hepatoduodenal ligament',
      '["Portal triad within the hepatoduodenal ligament","Hepatic veins at the inferior vena cava","Superior mesenteric artery alone","Splenic hilum with splenic artery and vein"]'::jsonb,
      'The Pringle maneuver compresses the hepatoduodenal ligament. This temporarily occludes the portal vein, proper hepatic artery, and bile duct, together known as the portal triad.'
    ),
    (
      'online-fokus-chirurgie-08',
      'Chirurgie',
      'Was ist beim Polytrauma mit positivem FAST und gleichzeitiger haemodynamischer Instabilitaet typischerweise der naechste Schritt?',
      'Notfalllaparotomie',
      '["Notfalllaparotomie","Entlassung mit ambulanter Kontrolle","Elektive Koloskopie","Belastungs-EKG"]'::jsonb,
      'Ein positives FAST bei gleichzeitiger haemodynamischer Instabilitaet spricht fuer eine relevante intraabdominelle Blutung. Typischerweise folgt dann die umgehende Notfalllaparotomie.',
      'In polytrauma with a positive FAST examination and simultaneous hemodynamic instability, what is typically the next step?',
      'Emergency laparotomy',
      '["Emergency laparotomy","Discharge with outpatient follow-up","Elective colonoscopy","Exercise ECG"]'::jsonb,
      'A positive FAST examination together with hemodynamic instability suggests major intra-abdominal bleeding. The typical next step is immediate emergency laparotomy.'
    ),
    (
      'online-fokus-chirurgie-09',
      'Chirurgie',
      'Welche postoperative Stoerung erklaert periorale Paraesthesien und Tetanie nach Thyreoidektomie am ehesten?',
      'Hypokalzaemie durch Hypoparathyreoidismus',
      '["Hypokalzaemie durch Hypoparathyreoidismus","Hyperkaliaemie durch Nierenversagen","Hypernatraemie durch Diabetes insipidus","Hypoglykaemie durch Insulinom"]'::jsonb,
      'Nach einer Thyreoidektomie kann eine Schaedigung oder Devaskularisation der Nebenschilddruesen zu Hypoparathyreoidismus fuehren. Die Folge ist eine Hypokalzaemie mit Tetaniesymptomen.',
      'Which postoperative disturbance most likely explains perioral paresthesias and tetany after thyroidectomy?',
      'Hypocalcemia due to hypoparathyroidism',
      '["Hypocalcemia due to hypoparathyroidism","Hyperkalemia due to renal failure","Hypernatremia due to diabetes insipidus","Hypoglycemia due to insulinoma"]'::jsonb,
      'After thyroidectomy, damage to or devascularization of the parathyroid glands can cause hypoparathyroidism. The result is hypocalcemia with tetany symptoms.'
    ),
    (
      'online-fokus-chirurgie-10',
      'Chirurgie',
      'Was charakterisiert die Hartmann-Operation definitionsgemaess?',
      'Endkolostoma mit blind verschlossenem Rektumstumpf',
      '["Endkolostoma mit blind verschlossenem Rektumstumpf","Ileoanaler Pouch nach totaler Kolektomie","Duodenojejunostomie nach Whipple","Fundoplikatio um den unteren Oesophagus"]'::jsonb,
      'Die Hartmann-Operation umfasst typischerweise eine Resektion des betroffenen Kolonabschnitts, ein endstaendiges Kolostoma und einen blind verschlossenen distalen Rektum- oder Kolonstumpf.',
      'What defines a Hartmann procedure?',
      'End colostomy with a blind rectal stump',
      '["End colostomy with a blind rectal stump","Ileoanal pouch after total colectomy","Duodenojejunostomy after Whipple procedure","Fundoplication around the distal esophagus"]'::jsonb,
      'A Hartmann procedure typically consists of resection of the affected colon segment, creation of an end colostomy, and closure of the distal rectal or colonic stump.'
    )
),
upsert_questions as (
  insert into public.questions (
    slug,
    category,
    question,
    correct_answer,
    options,
    explanation
  )
  select
    slug,
    category,
    question_de,
    correct_de,
    options_de,
    explanation_de
  from question_rows
  on conflict (slug) do update
    set category = excluded.category,
        question = excluded.question,
        correct_answer = excluded.correct_answer,
        options = excluded.options,
        explanation = excluded.explanation,
        updated_at = now()
  returning id, slug
)
insert into public.question_translations (
  question_id,
  language,
  question,
  options,
  correct_answer,
  explanation
)
select
  upsert_questions.id,
  'en',
  question_rows.question_en,
  question_rows.options_en,
  question_rows.correct_en,
  question_rows.explanation_en
from upsert_questions
join question_rows
  on question_rows.slug = upsert_questions.slug
on conflict (question_id, language) do update
  set question = excluded.question,
      options = excluded.options,
      correct_answer = excluded.correct_answer,
      explanation = excluded.explanation,
      updated_at = now();
